### ISSUE TITLE
[4.1][Bug] Backpack does not pick default save action from config.

### ISSUE THREAD

**Issue by GregaUNK** [Laravel-Backpack/CRUD#3100] opened 2020-08-04 10:39 UTC
# Bug report

### What I did

In crud.php I set defaultSaveAction to "save_and_edit",

### What I expected to happen

Default action should be save and edit. 

### What happened

Each day the default action is set to save and back. 

### What I've already tried to fix it

I checked if I maybe have any modified scripts of this button, but havent found them. Dont have any other idea what to try. Its not working even with default CRUD generated controller.

I tried to delete config cache.

Each day when you manually select Save and edit, it works till the end of the day. Next day you will have default action "Save and back".

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.1 (cli) (built: Dec 18 2019 14:46:18) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.21.0@3ccdb116524de408fdc00715b6f06a1031ddace9

### BACKPACK VERSION:
4.1.15@6c751de946a9c8511dd32eb7bfa3ca6a568849f5

**Comment by pxpm** [comment] 2020-08-05 09:38
Hello @GregaUNK thanks for the report.

Indeed I could reproduce your issue.

First of all, let me tell you that when you change the save action with the crud button, it will save your option in session for future requests, that's the reason why the option you choosed is lost when session is cleared.

To make it persistent you should add to the crud.php config the default action you want for ALL you cruds, or simply define for each crud what save action you would like first. 

If this is the only place where you want `save_and_edit` to be default you could add to that crud: `$this->crud->orderSaveAction('save_and_edit', 1)` That will make the `save_and_edit` be the default only for that crud, or you could setup `$this->crud->setOperationSetting('defaultSaveAction', 'save_and_edit')`

About the default in config `crud.php` it was not beeing picked by Crud because of an error in the higher order precedence. I'v just submited a PR to fix it. #3104 

Could you give it a try a let us know in the PR if it fixed it for you? Don't forget to clear the cache: `php artisan config:clear`

Best,
Pedro

**Comment by tabacitu** [comment] 2020-08-05 13:18
Fixed by #3104

**Closed** 2020-08-05 13:17 UTC
Labels: Bug
