### ISSUE TITLE
Authentication Section I can't hide the URL 

### ISSUE THREAD

**Issue by mikdanjey** [Laravel-Backpack/CRUD#4817] opened 2022-12-05 13:43 UTC
# Bug report

### What happened

Authentication Section I can't hide the URL

even normal user can access  below URLs.

/user
/role
/permission

### Is it a bug in the latest version of Backpack?

Yes

### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.42.2@607d7867c93706eae20e28e46679f8a66e2a23ec

### BACKPACK VERSION:
5.4.10@050b288caf2f60c79313f2b0b7d4fefd25177f3f

**Comment by pxpm** [comment] 2022-12-05 15:04
Hey @mikdanjey thanks for the report.

I was not able to reproduce your issue: 
![image](https://user-images.githubusercontent.com/7188159/205669285-a87d2505-4599-4a16-8899-ed220c221977.png)

And when I go to `admin/role` I get redirected to login page if I am not authenticated. 

It must be the way you are setting up the routes, you are probably missing the backpack middleware.

Check how they are setup inside `PermissionManager` package: https://github.com/Laravel-Backpack/PermissionManager/blob/main/src/routes/backpack/permissionmanager.php

I am going to close this, I don't think there is any bug here, rather some problem in the implementation. Please feel free to continue the conversation if needed and I will help you the best I can. 

Wish you all the best 🎅

**Closed by pxpm** 2022-12-05 15:04 UTC
Labels: triage

**Comment by mikdanjey** [comment] 2022-12-06 13:11
Hello, @pxpm,

You though wrong, I think you are not understand my bug report.

**Comment by pxpm** [comment] 2022-12-06 16:23
Haa sorry my bad @mikdanjey I misunderstood your question.

One thing that I always do is to only have the `ListOperation` in the roles/permissions cruds. That way the routes for `CreateOperation` update etc are not even registered as I don't plan to ever edit any of them via interface. 

Denying access works, but some user with access can change a role name or permission or something and break your code that rely on those role names etc to work. 

Sorry again if I didn't understood the question at first. 

Cheers

**Comment by mikdanjey** [comment] 2022-12-06 17:22
Please check my below screenshot for list of users.

I want to hide the normal users, This Authentication should visible only on Super-Admin.

I have checked your complete documentation & your source code. it seems your side is not providing the hide the Authentication module.

- admin/user

![bug-1](https://user-images.githubusercontent.com/17296759/205978739-e7a17436-21b9-4cca-a030-65bdc99c1aa1.png)

![bug-2](https://user-images.githubusercontent.com/17296759/205979208-267ec3f2-1094-4912-9d14-a6622563934d.png)

Please give me a fix here.

**Comment by pxpm** [comment] 2022-12-06 17:30
To customize the sidebar you should go ahead to `resources/views/vendor/backpack/base/inc/sidebar_content`.

You can use something like:
```php
@if(backpack_user()->hasRole('super-admin')
.... show the menu here only if user is super-admin
@endif
```

Cheers

**Comment by mikdanjey** [comment] 2022-12-07 06:21
I did this complete code already in side panel. This was hiding only in side panel. but not able to remove _/admin/user_ - while browsing with direct URL.

How to reproduce my steps: == Consider this code is applied in Side panel with proper roles & permissions.

- Login with normal User
- You can't see Authentication menu in side panel. == Which is Correct
- Browse direct URL _/admin/user_ == You can see the users, this is very big issue.

```
@if (backpack_user()->hasRole('super-admin'))
<li class="nav-item nav-dropdown">
    <a class="nav-link nav-dropdown-toggle" href="#"><i class="nav-icon la la-users"></i> Authentication</a>
    <ul class="nav-dropdown-items">
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('user') }}"><i class="nav-icon la la-user"></i> <span>Users</span></a></li>
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('role') }}"><i class="nav-icon la la-id-badge"></i> <span>Roles</span></a></li>
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('permission') }}"><i class="nav-icon la la-key"></i> <span>Permissions</span></a></li>
    </ul>
</li>
@endif
```

**Comment by pxpm** [comment] 2022-12-07 09:48
Hey @mikdanjey 

To avoid the urls beeing accessible you can use what you already described, in your UserCrudController, in the `setup()` method, you can add:

```php
public function setup()
{
if(!backpack_user()->hasRole('super-admin')) {
$this->crud->denyAccess(['list', 'create', 'update', 'show']);
}
}
```

If you don't want the routes to be registered at all you need to conditional load the OperationTraits.
