### ISSUE TITLE
[Bug] relationship field: Column not found: 1054 Unknown column

### ISSUE THREAD

**Issue by mbanna-smart** [Laravel-Backpack/CRUD#2933] opened 2020-06-13 11:20 UTC
# Bug report

### What I did

$this->crud->addField(
            [
               'type' => "relationship",
              'name' => 'category',
            ],
        );

### What I expected to happen

Success create or update

### What happened

column not found: 1054 Unknown column 'category' in 'field list'

### What I've already tried to fix it

'name'      => 'category_id', 
 'entity'    => 'category',

### Backpack, Laravel, PHP, DB version

"php": "^7.2.5",
"backpack/crud": "4.1.*",

When I run ```php artisan backpack:version``` the output is:
PHP 7.4.1 (cli) (built: Dec 17 2019 19:24:02) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.13.0@6fa69bfbd57744a5bbec5538ce483919b3fd625f

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f

**Comment by martijnb92** [comment] 2020-06-14 08:48
Have you set up the correct relationship in your model?

**Comment by mbanna-smart** [comment] 2020-06-14 10:21
Yes, Off course

**Comment by pxpm** [comment] 2020-06-15 09:34
Hello @mbanna-smart 

Could you please share a more compreensive error ? Where does that error trigger ? What's your database system ?

Best,

**Comment by mbanna-smart** [comment] 2020-06-15 11:32
the field on DB: category_id
--
function on Item Model
public function category(){
        return $this->belongsTo(Category::class, 'category_id');
    }
--
Function on Category Model
public function items(){
        return $this->hasMany(Item::class);
    }
--
ItemCrudController
setupCreateOperation
[
   'type' => "relationship",
  'name' => 'category', 
   'ajax' => true,
 'inline_create' => true, 
]
--
When I create or update I get the database error
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category' in 'field list' (SQL: update `items` set `category` = 2, `items`.`updated_at` = 2020-06-15 11:31:07 where `id` = 1)

I think the field must send to db (category_id) not (category)

**Comment by tabacitu** [comment] 2020-06-22 12:51
@mbanna-smart still not sure what the issue is. Could you please post screenshots of your ENTIRE CrudController, and entire error page (the stack)? That might help debug the issue.

**Comment by mbanna-smart** [comment] 2020-06-24 07:18
@tabacitu 
I made a workaround solution:
I overwrite update() frunction to solve the problem, I think my code will help you to understand the problem

    protected function setupCreateOperation()
    {
        $this->crud->setValidation(ItemRequest::class);
        $this->crud->addFields([
            'name','code',
            [
                'type' => "relationship",
                'name' => 'category', // the method on your model that defines the relationship
                'ajax' => false,
                'inline_create' => true, // assumes the URL will be "/admin/category/inline/create"
                'wrapper' => ['class' => 'form-group col-md-6 required'],
            ],

        ]);
        
    }

public function update()
    {
        $request = $this->crud->getRequest();

        if(!$request->input('category')){
            \Alert::error('category is required')->flash();
            return Redirect::back();
        }
        if ($request->input('category')) {
            $category_id = $request->input('category');
            $request->request->remove('category');
            $request->request->set('category_id',$category_id);
            $this->crud->addField([
                'name'=>'category_id',
                'value'=>$category_id
            ]);
           
        }

        $response = $this->traitUpdate($request);
        return $response;

    }

**Comment by JacoboDominguez** [comment] 2020-07-21 11:48
Hi, similar error for me.
It seems that when using relationships as
 [
            'type' => "relationship",
            'name' => 'category', // the method on your model that defines the relationship
]
, the post for create includes the value 'category', instead of the related category_id, so if nothing is done in the laravel side it will give you an error as you cannot use a relation name as a colunm value.
In my case I use as name the _id value:
 [
            'type' => "relationship",
            'name' => 'category_id', // the method on your model that defines the relationship
],
and it works, but it seems looking at the docs that we should use the relation method not the _id value so this might be a bug?

**Comment by JacoboDominguez** [comment] 2020-07-21 12:27
I found this use of 'relationship' in the demo but it seems is using the _id field also instead of the relation method name as stated in the docs:
https://github.com/Laravel-Backpack/demo/blob/bc31a5f6f51e83b1082b74a4fa76cd12d9988243/app/Http/Controllers/Admin/FluentMonsterCrudController.php#L283
This issue might be also related: #3058

**Comment by pxpm** [comment] 2020-07-21 13:11
We use it in the regular monsters: https://github.com/Laravel-Backpack/demo/blob/bc31a5f6f51e83b1082b74a4fa76cd12d9988243/app/Http/Controllers/Admin/MonsterCrudController.php#L759

I will investigate this. thanks for report.

**Comment by rinodrummer** [comment] 2020-07-21 23:08
> I found this use of 'relationship' in the demo but it seems is using the _id field also instead of the relation method name as stated in the docs:
> https://github.com/Laravel-Backpack/demo/blob/bc31a5f6f51e83b1082b74a4fa76cd12d9988243/app/Http/Controllers/Admin/FluentMonsterCrudController.php#L283
> This issue might be also related: #3058

I closed the issue due to the duplication, but as you stated in the comment that preceeds the one I quoted, the solution is that the `name` property of the field must be valued as _the name of the foreign key_ (ex.: `context_id`, `category_id`).

I used the syntax implemented for [regular monsters](https://github.com/Laravel-Backpack/demo/blob/bc31a5f6f51e83b1082b74a4fa76cd12d9988243/app/Http/Controllers/Admin/MonsterCrudController.php#L759), and worked: it setted the foreign key correctly (before v4.1.14) but after the update it suddenly stopped working.

**Comment by pxpm** [comment] 2020-09-30 08:59
@mbanna-smart @rinodrummer and all the other who pitch in. 

Thank you very much for your effort explaining and debugging this issue. 

This is beeing addressed in #3199 

I am going to close this, if you happen to have a spare time or are willing to have a fix for this before we merge it we would highly appreciate any possible feedback on the PR thread. 

Wish you guys the best,
Pedro

**Closed by pxpm** 2020-09-30 08:59 UTC
Labels: Possible Bug
