### ISSUE TITLE
[Bug] $this->getColumnWithTableNamePrefixed in applySearchLogicForColumn doubles table prefix when using table prefixes

### ISSUE THREAD

**Issue by bretvanhorn** [Laravel-Backpack/CRUD#3620] opened 2021-03-18 20:36 UTC
# Bug report

### What I did

I accidentally upgraded our Backpack install from 4.1.15 to 4.1.40 when trying to debug a composer issue. Suddenly any searches on our CRUD models returned a 500 error:

`[11:36:59] LOG.error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'bpos_bpos_conditions.condition_name' in 'where clause' (SQL: select count(*) as aggregate from `bpos_conditions` where (`bpos_bpos_conditions`.`condition_name` like %dama% or `bpos_bpos_conditions`.`condition_description` like %dama%) and `bpos_conditions`.`deleted_at` is null) `

### What I expected to happen

Expected no compatibility issues since it was within our specified version spec in composer.json

### What happened

We are using table prefixes, something that was set up years ago and has been a bit of a pain at times. After some digging, I realized column names in the query were being prepended with our table prefix twice. So instead of bpos_conditions.condition_name, it would be referencing bpos_bpos_conditions.condition_name in the search query. I tracked this down to the getColumnWithTableNamePrefixed() function in /app/Library/CrudPanel/Traits/Search.php. T

### What I've already tried to fix it

Changing this method to the below seems to fix the issue:

```
public function getColumnWithTableNamePrefixed($query, $column)
    {
        return $column;
    }

```

I have not done a ton of testing yet, but I do feel like this is a bug and removing the method from Search.php is not something I am comfortable doing in a PR, simply because I don't have enough of a handle on the underlying framework to know what else it might affect. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.26-1+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Jan 13 2021 08:01:31) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.26-1+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.40@ecbe7676535d3c9121227329d62cad9978d29fee

**Comment by pxpm** [comment] 2021-03-25 12:34
Hello @bretvanhorn 

Sorry for taking time to get back to this. 

From what it seems, you are using prefixed tables, but in "model" you already define the table with the prefix ? 

Something like: 
`protected $table = 'prefix_tablename';`

From my understanding, and I could be wrong, when you setup `prefix` in your database connection, your table name should not contain the prefix ?

Let me know,
Pedro

**Comment by mgralikowski** [comment] 2021-03-27 20:30
Hi,

after upgrade library to 4.1.32 our admin panel stopped working, because where we're using db prefix (globally, not per model).
The same problem with double prefix: `prefix_prefix_column`.

**Comment by promatik** [comment] 2021-03-29 11:14
Hi @mgralikowski!
I was now able to reproduce the error 🙌 I'm on it.

**Comment by pxpm** [comment] 2021-03-29 11:24
Hello @mgralikowski and @bretvanhorn 

I'v just submitted PR #3633 to fix this issue. 

Let's move the conversation over there, it should be merged very soon.

Thanks for your patience and contribution on the resolution! 

Best,
Pedro

**Closed by pxpm** 2021-03-29 11:24 UTC
Labels: triage

**Comment by pxpm** [comment] 2021-03-29 11:25
WHAAT! So soooorry @promatik 

My fault on here 👎 

Check #3633

**Comment by promatik** [comment] 2021-03-29 11:27
No problem @pxpm I should have taken a look at this earlier 😅
