### ISSUE TITLE
how set addColumn type => select, with option value="1" not value="name"

### ISSUE THREAD

**Issue by zwibowo** [Laravel-Backpack/CRUD#1411] opened 2018-05-17 04:29 UTC
### What I've already tried to fix it:

$this->crud->addColumn([
            // 1-n relationship
            'label'     => "Unit",
            'type'      => "select",
            'name'      => 'measurement_id',
            'entity'    => 'measurement',
            'attribute' => "name",
            'model'     => "App\Models\Measurement",
        ]);

```
html result <option value="Name">Name</option>

i want set option value by id, <option value="1">Name</option>
```

**Comment by AbbyJanke** [comment] 2018-05-18 22:08
Hi, I am a little confused if you are trying to add a Column or a Field. A column select wouldn't have a `<option value="valueType"></option> it would just be `<td>Value</td>` so I am assuming what you are actually looking for is the addField in which your code should look something like this:

```php
$this->crud->addField([
'label' => "Unit",
'type' => "select",
'name' => 'measurement_id',
'entity' => 'measurement',
'attribute' => "name",
'model' => "App\Models\Measurement",
]);
```

The code for the select Field type contains the following:
```php
@foreach ($field['model']::all() as $connected_entity_entry)
    @if(old($field['name']) == $connected_entity_entry->getKey() || (is_null(old($field['name'])) && isset($field['value']) && $field['value'] == $connected_entity_entry->getKey()))
        <option value="{{ $connected_entity_entry->getKey() }}" selected>{{ $connected_entity_entry->{$field['attribute']} }}</option>
    @else
         <option value="{{ $connected_entity_entry->getKey() }}">{{ $connected_entity_entry->{$field['attribute']} }}</option>
    @endif
@endforeach
```

which you can see the value automatically takes the database `id`  and inserts it as the value and whatever you set as the attribute to be displayed.

**Comment by tabacitu** [comment] 2018-06-04 07:56
Completely agree with @AbbyJanke - unclear. Plus, looks like a support request not a bug. Letting you guys continue the talk, but closing the issue - spring cleaning :-) Cheers!

**Closed by tabacitu** 2018-06-04 07:56 UTC
Labels: triage
