### ISSUE TITLE
Need some help after installation on Laravel project

### ISSUE THREAD

**Issue by mogoit** [Laravel-Backpack/CRUD#2886] opened 2020-05-30 02:21 UTC
Hello,

I ve just installed Backpack on my Laravel project which is in version 7 and I don't understand why I can't access to admin area.

**Configuration**

PHP 7.4
Nginx web server

**Problem**

All of urls except "/" (my homepage) give me a 404 error 

Someone has already seen something like that ?

Thanks.

**Comment by tabacitu** [comment] 2020-06-01 09:17
The default Backpack installation places your admin panel at `your-project/admin` - try to open that up. If that triggers a 404 error it probably means you haven't actually finished installing Backpack - most likely you just did composer require, with no ```php artisan backpack:install```. 

Please make sure you've followed all steps here - https://backpackforlaravel.com/docs/4.1/installation - it should work fine, hundreds of people use this installation process every day.

If it does not, please provide more information about what you've done, like screenshots of the command line when installing, screenshots of what you're getting, things like that.

I'm going to close this as I'm pretty sure it's user fault, not a bug.
Cheers!

**Closed by tabacitu** 2020-06-01 09:17 UTC
Labels: triage

**Comment by mogoit** [comment] 2020-06-01 16:31
Hey @tabacitu,

Thanks for your help, but it's seems there is a problem with "no fresh" Laravel projects...

I followed the installation tutorial and I also tried to reinstall Backpack but I still have the same problem.

However, during the installation there is no problem as you can see with these following screenshots...

First step (install with composer)
![image](https://user-images.githubusercontent.com/8600312/83429542-79fb7a00-a434-11ea-8265-2bc89b5f7448.png)

Next step (backpack install)
![image](https://user-images.githubusercontent.com/8600312/83429642-9e575680-a434-11ea-91f8-1fc3ee789d52.png)

After these steps, access to http://my-project/admin give me this 404 (and on any anothers URL also...)
![image](https://user-images.githubusercontent.com/8600312/83429762-d1014f00-a434-11ea-983d-4734436ef89e.png)

I tried to create a testing URL (/test, without Backpack dependancy) in my app too, and I still have the 404 error, i'm discourageous.

Thanks.

**Comment by mogoit** [comment] 2020-06-01 16:53
Thank you for taking time for me @tabacitu, 

I have **clean the Laravel bootstrap cache** and now it's work fine, all routes are available.

**Comment by tabacitu** [comment] 2020-06-04 04:49
Thanks for sharing your solution @mogoit - I'm sure it'll helps someone someday 😄
