### ISSUE TITLE
Error with afterField()

### ISSUE THREAD

**Issue by danielfaulknor** [Laravel-Backpack/CRUD#532] opened 2017-03-11 06:10 UTC
**(A) what you did**
Tried to order fields:
```
        $this->crud->addField([
            'name' => 'title',
            'wrapperAttributes' => [
                'class' => 'col-md-4'
                ],
        ]);
        $this->crud->addField([
            'name' => 'barcode',
            'wrapperAttributes' => [
                'class' => 'col-md-4'
                ],
        ])->afterField('title');
```
**(B) what you expected to happen**
Put the barcode field directly after the title field
**(C) what happened**
Error: A non-numeric value encountered
**(D) what have you already tried to fix it?**
Googling. Lots of googling.

**Comment by tabacitu** [comment] 2017-03-11 06:14
:-)) sorry you're having issues. Just tried it and seems to work for me in a similar use case.

Could you please paste the whole error? Might help figure out what went wrong.

Cheers!

**Comment by danielfaulknor** [comment] 2017-03-11 06:35
> ErrorException in Fields.php line 80:
> A non-numeric value encountered
> in Fields.php line 80
> at HandleExceptions->handleError(2, 'A non-numeric value encountered', '/home/vagrant/Code/GeekGearGovernor/vendor/backpack/crud/src/PanelTraits/Fields.php', 80, array('target_field' => 'title', 'value' => array('name' => 'title', 'wrapperAttributes' => array('class' => 'col-md-4'), 'label' => 'Title', 'type' => 'text'), 'field' => 'title')) in Fields.php line 80
> at CrudPanel->afterField('title') in AssetCrudController.php line 60
> at AssetCrudController->setUp() in CrudController.php line 39
> at CrudController->Backpack\CRUD\app\Http\Controllers\{closure}(object(Request), object(Closure)) in Pipeline.php line 131
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Admin.php line 29
> at Admin->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SubstituteBindings.php line 41
> at SubstituteBindings->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
> at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
> at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
> at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
> at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
> at Pipeline->then(object(Closure)) in Router.php line 561
> at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 520
> at Router->dispatchToRoute(object(Request)) in Router.php line 498
> at Router->dispatch(object(Request)) in Kernel.php line 174
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 30
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
> at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
> at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ValidatePostSize.php line 27
> at ValidatePostSize->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
> at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
> at Pipeline->then(object(Closure)) in Kernel.php line 149
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
> at Kernel->handle(object(Request)) in index.php line 53

**Comment by danielfaulknor** [comment] 2017-03-11 06:36
Code is here https://github.com/danielfaulknor/GeekGearGovernor/blob/master/app/Http/Controllers/Admin/AssetCrudController.php

**Comment by MarcosBL** [comment] 2017-03-14 21:10
I can't find the afterField() call in the sample offered

As a workaround, after fiddling with afterField() calls myself, I ended with a much simpler solution: I reordered the fields in MySQL itself, using PHPMyAdmin, and **BOOM, order fixed** !

![image](https://cloud.githubusercontent.com/assets/389801/23922383/6bb09f0a-0902-11e7-91a6-007ddb90d9fa.png)

Just drag & drop, save and try it yourself:

![image](https://cloud.githubusercontent.com/assets/389801/23922416/90279df2-0902-11e7-9bcb-630cc53c6aff.png)

As a side note, maybe you could be interested in Snipe-IT , it's Open Source, Laravel based, and pretty mature:

- Project: https://github.com/snipe/snipe-it
- Website: https://snipeitapp.com/
- Demo: https://snipeitapp.com/demo

**Comment by danielfaulknor** [comment] 2017-03-15 23:21
It's in this commit - https://github.com/danielfaulknor/GeekGearGovernor/blob/c861719dde584cee3336f7c316ae12d442e64058/app/Http/Controllers/Admin/AssetCrudController.php

Thanks for the tip on rearranging the columns in SQL, I hadn't thought of that.

I had looked at Snipe-IT but it's actually a bit too mature (complex) for what I need

**Comment by MarcosBL** [comment] 2017-03-16 09:59
So sorry, still can't find the afterField() call myself :O

**Comment by tabacitu** [comment] 2017-04-10 17:31
Hi guys,

Never used ```afterField()``` and ```beforeField()``` myself. Does this PR https://github.com/Laravel-Backpack/CRUD/pull/472/files fix the issue for you?

Thanks, cheers!

**Comment by alexiswbr** [comment] 2017-04-13 08:12
Well in fact it just a new PHP 7 restriction ([take a look here](http://stackoverflow.com/a/42044413/4628406))

With a int cast of the `$field` value the problem is gone for me.

```
foreach ($this->create_fields as $field => $value) {
	if ($value['name'] == $target_field) {
		array_splice($this->create_fields, (int) $field + 1, 0, [$field => array_pop($this->create_fields)]);
		break;
	}
}
foreach ($this->update_fields as $field => $value) {
	if ($value['name'] == $target_field) {
		array_splice($this->update_fields, (int) $field + 1, 0, [$field => array_pop($this->update_fields)]);
		break;
	}
}
```

**Comment by tabacitu** [comment] 2017-05-31 15:46
Hi guys,

Just pushed the fix for this - for PHP 7 but also PHP 5.x.

It's on the ```dev``` branch - if you guys want to use it, just require that branch in your composer.json. If anything goes awry, please let me know. Otherwise it will be merged into ```master``` in a few days, after people get to test it a little bit.

Cheers!

**Closed by tabacitu** 2017-05-31 15:46 UTC
Labels: bug
