### ISSUE TITLE
[Bug] [4.1] Undefined variable: redirectUrl

### ISSUE THREAD

**Issue by lothindil** [Laravel-Backpack/CRUD#3324] opened 2020-11-12 16:02 UTC
I tried to override the function update of crud, like the documentation says here : https://backpackforlaravel.com/docs/4.1/crud-operation-update#callbacks

I use in fact repeatable to manage a many-to-many relationship with pivot, but also for some other computed things. I solved all issues about my specific situation. But, when the code call the function updateTraits() (to manage rest of fields), I have this error : 

 ErrorException (E_NOTICE)
Undefined variable: redirectUrl

For sure, edit vendor file is impossible (not include the git of the project).

`public function update()
    {   $request=$this->crud->getRequest();
        $qc=new QuotationController();
        $q=$qc->findQuotationById($request->quotation_id,"full");
        
        $q->email->address=$request->email["address"];
        $q->email->save();
        
        if($q->insurance<Insurance::minCovered($q->volume))
        {
            $q->insurance=Insurance::minCovered($q->volume);
        }
        
        /*gestion des tables répétables*/
        $isArray=json_decode($request->itemsSelling);
        $tmp=array();
        foreach($q->itemsSelling as $is)
        {
            $tmp[$is->item_selling_id]=$is->quantity;
        }
        $inQuotation=$tmp;

        foreach($isArray as $is)
        {
            if(array_key_exists($is->item_selling_id,$inQuotation))
            {
                if($is->quantity<="0")
                {
                    $q->itemsSelling()->detach($is->item_selling_id);
                }
                elseif($is->quantity!="")
                {
                    $q->itemsSelling()->updateExistingPivot($is->item_selling_id,  ["quantity"=>$is->quantity]);
                }
            }
            elseif($is->quantity!=""&&$is->quantity>"0")
            {
                $q->itemsSelling()->save(ItemSelling::findOrFail($is->item_selling_id), ['quantity' => $is->quantity]);
            }
        }
        $this->crud->getRequest()->request->remove('email');
        $this->crud->getRequest()->request->remove('itemsSelling');
        $this->crud->getRequest()->request->remove('calculatorItems');
        
        $response = $this->traitUpdate();
        // do something after save
        return $response;
    }`

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.2-3+0~20190208150725.31+stretch~1.gbp0912bd (cli) (built: Feb  8 2019 15:07:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2-3+0~20190208150725.31+stretch~1.gbp0912bd, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v6.18.43@7a6043b9049a93a6388d6ab6ac50dad28600d227

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877

**Comment by pxpm** [comment] 2020-11-13 11:09
Hello @lothindil 

Can you tell me what line of your code throws the error ? Maybe share the full error stack.

Is when you init the controller by hand ? `$q=$qc->findQuotationById($request->quotation_id,"full");` ?

Best,
Pedro

**Comment by lothindil** [comment] 2020-11-13 14:20
here : 
$response = $this->traitUpdate();

**Comment by pxpm** [comment] 2020-11-16 10:58
Thanks for response @lothindil 

Could I ask you one last favor ? It would help alot in debug.

Could you please do:

```php
$actions = $this->crud->getVisibleSaveActions();
dd($this->crud->getCurrentSaveAction($actions));
```

and let me know the results ? Is this a new install or an update ? 

Best,
Pedro

**Comment by pxpm** [comment] 2020-12-01 11:42
I am closing this due to inactivity. 

If the problem persists feel free to re-open. 

Best,
Pedro

**Comment by LemarinelNet** [comment] 2020-12-02 14:08
Got this error too...

It seems that in Traits/SaveActions.php, line 354, there is a reference to $redirectUrl, which could be undefined, if it has not been initialized before (ie method redirect is not callable)
Shouldn't this variable  be initialized first with a default value !?

**Comment by pxpm** [comment] 2020-12-02 14:20
@LemarinelNet I am not sure it relates with your method not beeing callable. You can redirect a save action to a static url like `https://google.com`.

I suspect from an overwritten create/update function that does not call the `$this->crud->setSaveAction()`, could it be @LemarinelNet  ?

Would you mind sharing some code to help here if you can ? I would really appreciate it. 

Thanks for reporting it,

Pedro

**Comment by LemarinelNet** [comment] 2020-12-02 14:32
Sure I would like to help  !!!
I just pinned a part of my problem...
Here's what's the context : I planned to do a "edit in a new tab" feature on a crud : a button link would open "customer/123/edit?custom_action=close" in a new tab. 
In my code, I display the "save and close" action only if the custom_action request is equal to close.
It works until here, it does display the button... But when I dd the $actions variable in SaveActions (line 335),  when saving, the "save_and_close" is not there anymore :)

So... because the save_and_close action is not there anymore, it can't be used to initialize the redirect url !

**Comment by pxpm** [comment] 2021-01-07 13:10
@LemarinelNet Sorry for late reply.

From my understanding what is happening is that you only setup the `save_and_close` if `custom_action` equals `close`.

In you first request you have it in the url, but when you save a new request is initiated, and that request does not have the `custom_action` close in the request so it does not setup the save actions.

My advice would be to add an hidden input to the form to sent the `custom_action` again so crud setup the button.

```php
CRUD::field('custom_action')->type('hidden')->value('close');
```

Let me know if I am in the right path here. 

Best,
Pedro

**Comment by pxpm** [comment] 2021-09-08 09:16
@LemarinelNet and @lothindil hope to find you guys well, and you figured out what was the problem. 

I think it's time to move on this issue, so I gave it a try once again and I am still not able to reproduce your issue. Or it's fixed 🤞 , or we are doing something different.

I've followed https://backpackforlaravel.com/docs/4.1/crud-operation-update#callbacks

> ProductCrudController.php

```php
use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation { update as traitUpdate; }

 protected function setupCreateOperation()
    {
        // setup fields

        $this->crud->removeAllSaveActions();

        $this->crud->addSaveAction([
            'name' => 'save_action_one',
            'redirect' => function($crud, $request, $itemId) {
                return $crud->route;
            }, // what's the redirect URL, where the user will be taken after saving?
        
            // OPTIONAL:
            'button_text' => 'create', // override text appearing on the button
            // You can also provide translatable texts, for example:
            // 'button_text' => trans('backpack::crud.save_action_one'),
            'visible' => function($crud) {
                return true;
            }, // customize when this save action is visible for the current operation
            'referrer_url' => function($crud, $request, $itemId) {
                return $crud->route;
            }, // override http_referrer_url
            'order' => 1, // change the order save actions are in
        ]);
    }

protected function setupUpdateOperation()
    {
        // setup fields

        $this->crud->removeAllSaveActions();

        $this->crud->addSaveAction([
            'name' => 'save_action_one',
            'redirect' => function($crud, $request, $itemId) {
                return $crud->route;
            }, // what's the redirect URL, where the user will be taken after saving?
        
            // OPTIONAL:
            'button_text' => 'update', // override text appearing on the button
            // You can also provide translatable texts, for example:
            // 'button_text' => trans('backpack::crud.save_action_one'),
            'visible' => function($crud) {
                return true;
            }, // customize when this save action is visible for the current operation
            'referrer_url' => function($crud, $request, $itemId) {
                return $crud->route;
            }, // override http_referrer_url
            'order' => 1, // change the order save actions are in
        ]);
    }

    public function update()
    {
        $response = $this->traitUpdate();
        // do something after save
        return $response;
    }
```

![vsRCO25uXx](https://user-images.githubusercontent.com/7188159/132481045-079646ff-db84-4acd-9281-05deb0671197.gif)

I am going to close this once again, but please if anyone have this issue again, comment bellow and provide maximum details so we can reproduce it and re-open if needed. 

Best,
Pedro

**Closed by pxpm** 2021-09-08 09:16 UTC
Labels: needs-more-info, triage
