### ISSUE TITLE
checkbox not render in the label(header) for bluck action

### ISSUE THREAD

**Issue by yatin13490** [Laravel-Backpack/CRUD#2364] opened 2020-01-09 06:08 UTC
![screenshot-haggadot sr-2020 01 09-11_38_58](https://user-images.githubusercontent.com/6308981/72042486-b0452b00-32d4-11ea-9dbf-4d766b3c0427.png)
# Bug report
I have used the checkbox with the list for bulk action, but it prints the HTML instead of rendering the checkbox in the header section of the datatable

### Backpack, Laravel, PHP, DB version
"php": ">=7.1.3",
        "backpack/base": "^0.9.0",
        "backpack/crud": "^3.4.0",
 "laravel/framework": "5.7.*",

**Comment by pxpm** [comment] 2020-01-09 13:37
Hello @yatin13490 

I am afraid that you are using a very old backpack version. If not 4.X the minimum stable I would advise you is 3.6.

Bare in mind that not using the latest versions you are missing great features and a lot of bug fixes.

I am closing this as we are not supporting 3.4 anymore. If you need any help to upgrade you software version go ahead: [upgrading documentation](https://backpackforlaravel.com/docs/4.0/upgrade-guide)

Note that due to big versions difference it might take some work. 

Best,
Pedro

**Closed by pxpm** 2020-01-09 13:37 UTC
Labels: triage

**Comment by tabacitu** [comment] 2020-01-20 08:11
Yup, what @pxpm said :-) I can confirm your issue has been fixed in 3.6 - so upgrading to it should fix it for you. If you can't do that, you can manually change you ```list.blade.php``` file to output the columns using ```{!! !!}``` instead of ```{{ }}```. But the more you delay the upgrade the more difficult it will get. Hope it helps. Cheers!
