### ISSUE TITLE
[Bug] Repeatable values not filled when open edit form (backpack pro)

### ISSUE THREAD

**Issue by HeriDCLXVI** [Laravel-Backpack/CRUD#4604] opened 2022-08-19 05:54 UTC
# Bug report

### What I did

Open edit form with repeatable

### What I expected to happen

![image](https://user-images.githubusercontent.com/21857693/185552374-0aa30b3e-5bc2-46ae-a006-8ae1d04ef46d.png)
Repeatable values is filled

### What happened

![image](https://user-images.githubusercontent.com/21857693/185552326-3c221e94-3b26-4033-9c01-483173e87b3d.png)
Repeatable values is blank

### What I've already tried to fix it

![image](https://user-images.githubusercontent.com/21857693/185551931-d6842fef-f271-4b0f-a348-e889f55458b5.png)
Removing this piece of code in resources/views/fields/inc/repeatable_row.blade.php

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.25.1@e8af8c2212e3717757ea7f459a655a2e9e771109

### BACKPACK VERSION:
5.3.4@ca7f97e3c644e35f134596281192dd6628ab449a

**Comment by pxpm** [comment] 2022-08-19 08:55
Hello @HeriDCLXVI 
Can you share with me your repeatable definition ? Is that a relation with pivot fields or are you storing in the same table in a text column ? 

I tried to reproduce your issue but I was not able to:
```php
[   // Textarea
                'name'  => 'textarea',
                'label' => 'Textarea'.backpack_free_badge(),
                'type'  => 'repeatable',
                'min_rows' => 1,
                'subfields' => [
                    [
                        'name' => 'testing',
                        'type' => 'select_from_array',
                        'options' => [
                            'a','b','c'
                        ],
                    ],
                    [
                        'name' => 'jsdfhj',
                        'type' => 'text',
                    ],
                ],
                'tab'   => 'Simple',
            ],
```
![image](https://user-images.githubusercontent.com/7188159/185582885-a7c94057-0e1e-4f0b-9354-75ee159ef537.png)

I have tried casting to `array` and `json` in the model and they both work. 

Do you get some javascript error on the edit page ? It seems that if there is some error repeatable migth not initialize correctly. 

Let me know,
Cheers

**Comment by HeriDCLXVI** [comment] 2022-08-19 09:24
Hello @pxpm ,

Below is my repeatable code, i stored the repeatable values in another table called `purchase_order_details`
I don't have any error on my edit page

Note : im using backpack/pro v1.2.2

```
[
    'label' => 'Item(s)',
    'name' => 'items',
    'type' => 'repeatable',
    'new_item_label' => 'Item',
    'pivot' => true,
    'min_rows' => 1,
    'subfields' => [
        [
            'label' => 'ID',
            'name' => 'id',
            'type' => 'hidden',
        ],
        [
            'label' => 'Purchase Request',
            'name' => 'purchase_request_id',
            'type' => 'select2_from_ajax',
            'model' => PurchaseRequest::class,
            'attribute' => 'code_purpose',
            'data_source' => url('/po/list/fetch/pr'),
            'placeholder' => 'Select Purchase Request',
            'include_all_form_fields' => true,
            'minimum_input_length' => 0,
            'method' => 'POST',
            'wrapper' => [
                'class' => 'form-group col-md-6 col-xs-12',
            ],
            'attributes' => [
                'onchange' => 'changePr(this)',
            ],
        ],
        [
            'label' => 'Item',
            'name' => 'purchase_request_detail_id',
            'type' => 'select2_from_ajax_repeatable',
            'model' => PurchaseRequestDetail::class,
            'attribute' => 'budget_name',
            'data_source' => url('/po/list/fetch/prdetail'),
            'placeholder' => 'Select Purchase Request Detail',
            'include_all_form_fields' => true,
            'minimum_input_length' => 0,
            'method' => 'POST',
            'wrapper' => [
                'class' => 'form-group col-md-6 col-xs-12',
            ],
            'attributes' => [
                'onchange' => 'changeItem(this)',
            ],
        ],
        [
            'label' => 'Quantity',
            'name' => 'quantity',
            'type' => 'number',
            'wrapper' => [
                'class' => 'form-group col-md-4 col-xs-12',
            ],
            'attributes' => [
                'onchange' => 'updateTotal(this)',
            ],
        ],
        [
            'label' => 'Price',
            'name' => 'price',
            'type' => 'currency',
            'prefix' => 'Rp',
            'wrapper' => [
                'class' => 'form-group col-md-4 col-xs-12',
            ],
            'attributes' => [
                'onchange' => 'updateTotal(this)',
            ],
        ],
        [
            'label' => 'Total Price',
            'name' => 'total_price',
            'type' => 'currency',
            'prefix' => 'Rp. ',
            'wrapper' => [
                'class' => 'form-group col-md-4 col-xs-12',
            ],
            'attributes' => [
                'readonly' => 'readonly',
            ],
        ],
        [
            'label' => 'Description',
            'name' => 'description',
            'type' => 'textarea',
            'wrapper' => [
                'class' => 'form-group col-md-12 col-xs-12',
            ],
            'attributes' => [
                'rows' => 2,
                'cols' => 2,
                'maxlength' => config('saint.max_char'),
            ],
        ],
    ],
],
```

**Comment by HeriDCLXVI** [comment] 2022-08-19 10:09
Hello @pxpm ,

after testing around, i have found the problem,
it is because i override the `items` values in `edit` function
![image](https://user-images.githubusercontent.com/21857693/185594583-546ab943-e642-48c4-b2c2-e993c8bb88a1.png)

Below is `itemValues`
![image](https://user-images.githubusercontent.com/21857693/185594906-7925716e-a53e-4bc7-98b8-e26be24e17d3.png)

A solution that worked is by adding `->toArray()`
![image](https://user-images.githubusercontent.com/21857693/185595219-bae2beed-8d3e-4740-9417-5fea71b367f4.png)


Previously the code without the `toArray()` worked, but now it is not working because of this `Cast translatable object to array`,
i tried changing `$row = (array) $row;` to `$row = $row->toArray();` and it worked.
could you help to explain why this is implemented?, if this is needed, maybe you can convert the object into array instead of cast the object into array
![image](https://user-images.githubusercontent.com/21857693/185595516-da6ab088-6f3b-4855-a9c9-49bc9fd08e84.png)

Thank you

**Comment by pxpm** [comment] 2022-08-19 12:13
Hello @HeriDCLXVI thanks for the explanation, very helpfull 🙏 

The reason we don't call `->toArray()` it's because that's a `Collection` method that is not present in every php object but the collection is a php object itself.

I think it's reasonable that repeatable work with laravel collections too (not only array or php plain objects). 

I've submitted a PR to PRO repo that should cover both scenarios, I've used:
```php
if (is_object($row)) {
    $row = collect($row)->toArray();
}
```

Want to test from your side and let me know if it works in your scenario too ? 

Cheers

**Comment by HeriDCLXVI** [comment] 2022-08-20 01:10
Hello @pxpm , thanks for the explanation

i tested on my side and it is working too
![image](https://user-images.githubusercontent.com/21857693/185723511-e519639b-a671-4f14-b557-944fb614c174.png)
![image](https://user-images.githubusercontent.com/21857693/185723526-63336501-f4c7-43e0-bb94-88e3dc0c20dc.png)

**Comment by pxpm** [comment] 2022-08-23 12:36
Hello @HeriDCLXVI 

The fix had been merged in PRO repo so I am closing this. Please notice that it's not tagged yet, @tabacitu should do it shortly after we merge one/two more PR's that are 99% ready. 

Thanks for the report and the patience helping me to fix this! 🙏 

Cheers

**Closed by pxpm** 2022-08-23 12:36 UTC
Labels: Minor Bug
