### ISSUE TITLE
[Bug] Wrong first column height

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#5267] opened 2023-08-04 19:35 UTC
# Bug report

### What I did
Just upgraded from the 5.x to 6.x and carefully switched to the Tabler theme.

### What I expected to happen
The table columns should be working as before.

### What happened
The leftmost column should have the same height of the other columns.

The HTML of my columns is:
```html
// column 1
<div>
    <span class="ms-0 fw-bold fs-3" title="Printer #1">Printer #1</span>
    <div>23%</div>
</div>
```
```html
// column 2
<div>
    <div class="ms-0 fw-bold fs-3" title="Milano">Milano</div>
    <span class="badge bg-azure m-0 mb-1 text-uppercase">etichette totali: 0</span>
</div>
```
```html
// column 3
<div>
    <div>
        <span class="badge bg-orange m-0 mb-1 text-uppercase">assegnato: 0</span>
    </div>
    <div>
        <span class="badge bg-yellow m-0 mb-1 text-uppercase">in stampa: 0</span>
    </div>
    <div>
        <span class="badge bg-green m-0 mb-1 text-uppercase">stampato: 0</span>
    </div>
</div>
```

![image](https://github.com/Laravel-Backpack/theme-tabler/assets/12816305/0ddb0c89-aff5-42f7-8358-8b8601db8193)

### What I've already tried to fix it

Removing the display: flex from the first td. 
I know this is not a definitive solution since it might break something else.

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
backpack/basset: 1.1.1
backpack/crud: 6.1.5
backpack/generators: v4.0.2
backpack/pro: 2.0.10
backpack/theme-tabler: 1.0.8 (carefully cleaned the basset cache)
```

**Comment by tabacitu** [comment] 2023-08-09 09:21
Hmmm I've just looked at all CRUDs in our demo - https://demo.backpackforlaravel.com/admin/article - and can't find any one where the first column is broken @EmanueleCoppola .

![CleanShot 2023-08-09 at 12 19 43](https://github.com/Laravel-Backpack/CRUD/assets/1032474/e9cc0681-d354-4ba3-8923-2937b6115290)

From what I can see... those are _custom columns_ you have there, right? So the problem (and the solution) should be in your custom code, right? It's not Backpack adding the flex in the first column, it's your custom column?

Let us know if you think I'm mistaken here. I'm wrong at least once a day 😉

Cheers!

**Comment by EmanueleCoppola** [comment] 2023-08-09 09:51
The issue I'm having seems to be related with [this](https://github.com/Laravel-Backpack/CRUD/blob/0e8cda5e5ea5e4e503a5a967fd617b9bdaa4118e/src/resources/assets/css/common.css#L158) line of code.

What occurs is that, in cases where a custom column exceeds the height of others, all cells adopt the regular table behavior, aligning with the taller column, except for the first cell, which remains smaller (probably because of it's display property).

I didn't encounter this issue in the v5 release, but the problem emerged after the v6 update.

**Comment by karandatwani92** [comment] 2023-08-10 15:22
Hey @tabacitu I just tried what he meant here.

## I tested this on v5 & v6(all themes)
I got the same output on all v6 themes, so **it's not related to the themes**.
In v5 same thing was doing fine.
Then I had a doubt, is it related to bulk action checkboxes? No, it's not.

## What difference is observed on v5 vs v6 output.
### V5:
**When we put content which occupies height in any column. All columns are centred✅**

![Screenshot 2023-08-10 at 8 30 42 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/15a5b3cb-d2d3-491b-b947-f263c05a6320)
#### V6:
- **When we put content which occupies height in any column, All columns are centred except the first column❌**
- **When we put content which occupies height in the first column. The column's height doesn't stretch as expected. ❌**

![Screenshot 2023-08-10 at 8 31 03 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/37a7429e-b677-4891-9fe6-6a73ba0ee700)

## Conclusion
### YES, It's related to the v6 CRUD LIST view.

## Solution
Looking for it. @pxpm do you have any idea?

**Comment by pxpm** [comment] 2023-08-11 08:52
@karandatwani92 I recall we had this issue before (in v5), I searched a bit around and were able to find it: https://github.com/Laravel-Backpack/CRUD/issues/4746

Maybe we need the same solution promatik came up in that issue ? 

Cheers

**Comment by karandatwani92** [comment] 2023-08-11 12:25
Found: the issue is in `src/resources/assets/css/common.css`. Don't know which element exactly but I'm about to find it.

**Comment by karandatwani92** [comment] 2023-08-11 12:46
PR submited #5275 🎉

Thanks @EmanueleCoppola for the help.🙌

**Comment by pxpm** [comment] 2023-08-11 13:17
I've just merged the fix into main branch. I will tag a new version in a few moments with some other fixes we are working on 🙏 

Thanks @EmanueleCoppola

**Closed by pxpm** 2023-08-11 13:17 UTC
Labels: Bug, Priority: MUST, Size: XS
