### ISSUE TITLE
Error calling $this->crud->update(...)

### ISSUE THREAD

**Issue by AndresOchoaS** [Laravel-Backpack/CRUD#799] opened 2017-07-21 19:38 UTC
Hello everyone,

I want to update the `images` field of my `products` table every time I upload an image with dropzone.

I have the following error when I try to execute the method `$this->crud->update(...)`

> (1/1) FatalThrowableError
> 
> Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::update() must be of the type array, object given, called in ...\vendor\backpack\crud\src\PanelTraits\Update.php on line 33

My code is:
```
public function handleDropzoneUpload(UpdateRequest $request)
{
    $id = $request->get('id');
    $disk = "uploads";
    $destination_path = "products/galleries";
    $file = $request->file('file');

    try {
        $image = \Image::make($file);
        $filename = md5($file->getClientOriginalName() . time()) . '.jpg';
        $path = $destination_path . '/' . $filename;
        \Storage::disk($disk)->put($path, $image->stream());

        $product = $this->crud->getEntry($id);
        $images = $product->images;

        array_push($images, $path);

        $request->request->set('images', $images);
        $this->crud->update($id, $request);

        return response()->json(['success' => true, 'filename' => $path]);
    } catch (\Exception $e) {
        return empty ($image) ?
            response('Not a valid image type', 412) :
            response($e, 412);
    }
}
```

It does not seem possible for an object to arrive instead of an array in the following code in the `src/PanelTraits/Update.php` file:
```
// ommit the n-n relationships when updating the eloquent item
$nn_relationships = array_pluck($this->getRelationFieldsWithPivot('update'), 'name');
$data = array_except($data, $nn_relationships);
$updated = $item->update($data);
```

The line `$updated = $item->update($data);` is the [33](https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/Update.php#L33) that shows the error.

Some help?

**Comment by lloy0076** [comment] 2017-07-22 10:23
You probably want something like:

```
$this->crud->update($id, $request->all());
```

See the comment from https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/FakeFields.php:

```
    /**

     * Refactor the request array to something that can be passed to the model's create or update function.

     * The resulting array will only include the fields that are stored in the database and their values,

     * plus the '_token' and 'redirect_after_save' variables.

     *

     * @param Request $request - everything that was sent from the form, usually \Request::all()

     * @param string  $form    - create/update - to determine what fields should be compacted

     *

     * @return array

     */
```

**Comment by lloy0076** [comment] 2017-07-22 10:23
Try:

```
$this->crud->update($id, $request->all());
```

**Comment by tabacitu** [comment] 2017-08-04 11:48
Hi guys. 

Cleaning up the issues so we can start adding some new features. This looks like more of [a StackOverflow question](stackoverflow.com/questions/tagged/backpack-for-laravel) to me (support question, not a bug in the core product), so I'll close it. 

Cheers!

**Closed by tabacitu** 2017-08-04 11:48 UTC
Labels: question
