### ISSUE TITLE
How to load a 'list' crud view with a filter enabled

### ISSUE THREAD

**Issue by luizmanoelf** [Laravel-Backpack/CRUD#1154] opened 2017-12-13 08:09 UTC
I need to load a list crud view for a subset of the data, which can be retrieved through a filter.

This has been asked here before (issue #435). @tabacitu suggested that one could use the link you get when enter the page and activate the filters by copying the GET parameters. 

I tried that but then I get the raw data not the view. Am I missing something simple?

Using Backpack 3.3.1.

**Comment by AurelDragut** [comment] 2017-12-13 08:13
you make a new list/index function where you can add any clauses that help obtaining the list that you want

**Comment by luizmanoelf** [comment] 2017-12-14 19:05
Hi @AurelDragut, thanks for the answer. 

I am not sure how to implement your solution. 
If I create a new index function, the add Clause doesn' t get applied. For example, I have a column called 'status' that can have the value 'agendado'.
I tried the following
public function myIndex()
    {
        $this->crud->hasAccessOrFail('list');
        $this->crud->addClause('where','status','agendado');
        $this->data['crud'] = $this->crud;
        $this->data['title'] = ucfirst($this->crud->entity_name_plural);
        return view($this->crud->getListView(), $this->data);
    }
I shows the list view with all row, i.e. the addClause has no effect.

If I use the same  $this->crud->addClause('where','status','agendado'); in the setup of the controller, I will the filtered rows, so I tried to check for the path of the request and apply the addClause there, like this:
if ($this->crud->request->path() == "admin/procedimento/myindex") {
           $this->crud->addClause('where','status','agendado');
      }
But now I don't get the filtered results...

**Comment by AurelDragut** [comment] 2017-12-14 19:11
Weird, it should work. i will do some tests and i will get back to this.

**Comment by tabacitu** [comment] 2017-12-18 08:29
Hi guys - more of a StackOverflow question so I'll close this (we only keep bugs in Github, helps with our sanity).

@luizmanoelf - my 2 cents: still recommend the procedure i recommended back then. Still works for me - take a look: https://cl.ly/053e2M213Y04

**Closed by tabacitu** 2017-12-18 08:29 UTC

**Comment by chriscalip** [comment] 2018-01-10 02:54
@AurelDragut @luizmanoelf 
I think this is a bug; I was able to reproduce this bug. Luiz, do you have a stackoverflow link?

**Comment by chriscalip** [comment] 2018-01-10 21:40
@tabacitu Seeking guidance whether to create a new issue or just continue with status quo.
I have reproducible way to illustrate error.

Step 1.  Provision a site of an instance of https://github.com/Laravel-Backpack/demo

Step 2.  Make sure laravel/tinker installed and activated.

Step 3.  Refer to gist link tinker.log of https://gist.github.com/chriscalip/6a1adf01c7bc6c5b532b490a1c8a8c12
`
vagrant@homestead:~/code/b1$ php artisan tinker
Psy Shell v0.8.17 (PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> use Backpack\CRUD\CrudPanel;
>>> $crud = app()->make(CrudPanel::class);
>>> $crud->setModel('Backpack\NewsCRUD\app\Models\Article');
=> null
>>> count($crud->getEntries());
=> 2062
>>> $crud->addClause('where', 'status', '=', 'PUBLISHED');
=> Illuminate\Database\Eloquent\Builder {#1075}
>>> count($crud->getEntries());
=> 1071
>>> $crud->query->toSql();
=> "select * from `articles` where `status` = ?"
>>> exit
Exit:  Goodbye.
vagrant@homestead:~/code/
`
Unit Test shows that CrudPanel query addClause works!

Step 4.a) Refer to gist link ArticleCrudController.php  of https://gist.github.com/chriscalip/6a1adf01c7bc6c5b532b490a1c8a8c12 and update vendor/backpack/newscrud/src/app/Http/Controllers/Admin/ArticleCrudController.php with gist.
Step 4.b) go to link /admin/article
Step 4.c) storage/logs/XXX.log shows that `$this->crud->query->toSql();` no longer was inline with query override done at method setup.
![admin-article-screenshot](https://user-images.githubusercontent.com/479454/34796851-86fe00e2-f61c-11e7-8a0e-1d6150702bad.png)

**Comment by chriscalip** [comment] 2018-01-10 21:45
![admin-article-workaround](https://user-images.githubusercontent.com/479454/34797141-12071bba-f61d-11e7-8d2d-0069baa05dc1.png)

Attached is a screenshot illustration demo of workaround solution.. the idea is to update the `$this->crud->query` by  adding `search` method and adding your query update there.
Source Code: 
https://gist.github.com/chriscalip/8ce5c898e090336116bebb42fb095c94

**Comment by tabacitu** [comment] 2018-01-11 10:50
Hi @chriscalip ,

First - let me know if I understand your problem correctly. You're saying that **AFTER a filter is enabled** (say... ```status = PUBLISHED```), **if you use the DataTables search, the search ignores the filter?**

If so, what Backpack\CRUD version are you using? You can find out by taking a look at the latest version specified in your ```vendor/backpack/crud/changelog.md```. You might be due for an update. If you're using the latest demo, this is very weird, because it seems to work fine for me in the latest version: https://cl.ly/1a353r1L2s0B

Cheers!

**Comment by chriscalip** [comment] 2018-01-11 21:51
@tabacitu 

It was weird indeed. I found the trouble. It was a setRoute issue. Thanks for response.

**Comment by luizmanoelf** [comment] 2018-01-12 16:03
Hi @chriscalip and @tabacitu 

My original question was how to load a filter by default. @tabacitu's solution does work. The only thing to keep in mind is that you don't use the exact link that the application submits when activating the filter. For example, in a simple application with two columns: name, publisher and a publisher filter, activating the filter generates a post request to
http://localhost:8000/admin/hero/search?publisher=1
the same result can be obtained by a GET request to
http://localhost:8000/admin/hero?publisher=1
So that solves my original problem.

But there was the issue of using the $this->addClause inside of a list or index function. This doesn't seem to work at all. I don't know if it is a bug or if the addClause function is only supposed to be used in the SetUp function. 
So
adding 
$this->crud->addClause('where', 'publisher_id', 1); 
to SetUp works fine, but of course not what I want to do.
But something like
  public function myindex()
    {
        $this->crud->addClause('where', 'publisher_id', 1);
        return parent::index();
    } 
Doesn't really filter the results.

Source Code here: https://gist.github.com/luizmanoelf/ff845b3ae3b5eb3f4589adb905371f94

Thanks for the help!

**Comment by tabacitu** [comment] 2018-02-21 16:18
@luizmanoelf indeed, ```addClause()``` is only meant to be used in the ```setup()``` method. It's mainly used to make sure the ```search()``` method returns the results after applying that clause.

**Comment by juniorgarcia** [comment] 2018-10-24 01:29
Indeed, a friend of mine came with a situation like that but, instead, he wanted to filter a list using a custom route like:

```php
// routes/backpack/custom.php
Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin')],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
    Route::get('/bills/paid 'Bills@paid');
}); // this should be the absolute last line of this file

// BillCrudController.php
public function paid()
{
  $this->crud->addClause('wherePaid', 1);
  return parent::index();
}
```

Although this does not filter the listing inside that route's view, a dump of `$this->crud->query->get()->toArray()` above the `addClause` shows the correct result.

It's like the filtering is made on the backend, but not on the frontend.
I've looked a little bit through the source code but didn't find anything that can cause that.

**Comment by jrbecart** [comment] 2019-02-21 17:06
Hello,

Please find a potential workaround / solution...
This allow you to use dynamic clause from url parameter. For me it's helpfull, so I can redirect from another Crud with a button link.

I think [#307](https://github.com/Laravel-Backpack/CRUD/issues/307) is the same kind of issue.

Update to your need:
```
// in YourCrudController 
public function setup()
{
  ...
  if (!empty(\Route::current()->parameter('personid'))) {
    $this->crud->setRoute(config('backpack.base.route_prefix') . '/access/' . \Route::current()->parameter('personid') . '/showlist');  
  }
  else {
    $this->crud->setRoute(config('backpack.base.route_prefix') . '/access');  
  }
  $person_id = \Route::current()->parameter('personid');
  if (!empty($person_id)) {
    $this->crud->addClause('where', 'person_id', '=', $person_id);
  }
  ...
}

// in your Custom Backpack Routes (custom.php)
...
    Route::get('access/{personid}/{id}', 'YourCrudController@show');
    Route::get('access/{personid}/{id}/edit', 'YourCrudController@edit');
    // Other needed route...
    CRUD::resource('access/{personid}', 'YourCrudController');
...
```
Anyone, let me know if it was helpful or if it fully works.
