### ISSUE TITLE
[BUG] Show Button With Translation Occuer an Error In `ListOperation`

### ISSUE THREAD

**Issue by EGYWEB-Mohamed** [Laravel-Backpack/CRUD#4940] opened 2023-02-25 04:24 UTC
# Bug report

### What I did

Added a `SpatieTranslatable` to the model and configured it as usual as shown below.
![image](https://user-images.githubusercontent.com/23424932/221335393-ed588153-91e5-4e83-b680-6efde489a8b9.png)

### What I expected to happen

See Show Button In `ListOperation` with the Dropdown menu for available languages.

### What happened

`ListOperation` does not load properly I've checked the network tab to see the request and I find it returns a mix of HTML with Json which is incorrect 
![image](https://user-images.githubusercontent.com/23424932/221335493-0f94b93f-7cdc-4ab4-afad-d40276d6057e.png)

### What I've already tried to fix it

I published the show button and tried to snipe the problem and the result is that I remove this section 
![image](https://user-images.githubusercontent.com/23424932/221336026-4fbdf9d4-7cea-4d6e-aca2-3053b36512c7.png)
it works as expected
![image](https://user-images.githubusercontent.com/23424932/221336562-e4c6feca-45f8-4494-a97d-0b5f4063ea6c.png)

I know it's a Very Weird bug and maybe it's not clear to anyone so I shot a video for it

https://user-images.githubusercontent.com/23424932/221337191-9679bc3d-9d66-4756-a012-334231a3c2ea.mp4

### Is it a bug in the latest version of Backpack?
Yes.

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 16 2022 12:46:39) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v12.0.5, Copyright (c) 2002-2022, by ionCube Ltd.

### LARAVEL VERSION:
v9.52.4@9239128cfb4d22afefb64060dfecf53e82987267

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.5.0
backpack/devtools: 1.3.2
backpack/editable-columns: 2.1.1
backpack/filemanager: 2.0.0
backpack/generators: 3.3.14
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.0

**Comment by EGYWEB-Mohamed** [comment] 2023-02-25 04:37
I figured out the problem 🎉 but I don't know if it is still a bug or not!
I had a custom button at the beginning of `ListOperation` 
```php
$this->crud->addButtonFromView('line','series_videos','series_videos','beginning');
```
the `series_videos` view had this logic

```html
<a href="{{ url($crud->route.'/'.$entry->getKey().'/video') }}" class="btn btn-sm btn-warning text-capitalize"><i class="la la-video"></i> @lang('Videos') @endlang</a>
```
Phpstorm was close `@lang` tag I don't know why so when I removed `@endlang` it back to work again

**Comment by tabacitu** [comment] 2023-03-05 17:34
Wooow that's weird one indeed. No idea why that was happening, I was just about to suggest parts you might have custom code that interferes with it (buttons, overridden methods etc) but I would NOT have thought of `@endlang` 😅

Since it's working fine in our demo - https://demo.backpackforlaravel.com/admin/product - I'm going to close this as "user error", not a bug.

Glad you figured it out @EGYWEB-Mohamed !

**Closed by tabacitu** 2023-03-05 17:34 UTC
Labels: triage
