### ISSUE TITLE
[Bug] Tabs feature creates duplicate assets

### ISSUE THREAD

**Issue by MarcosBL** [Laravel-Backpack/CRUD#509] opened 2017-02-28 00:46 UTC
Maybe related to #461 Tabs feature creates a new asset for every Tab present, despite the use of **checkIfFieldIsFirstOfItsType** both in the included fields and new ones.

For example, this code:

* generates 4 calls to **simplemde.min.css** and 4 to **simplemde.min.css** if you use 4 fields in 4 tabs
* 2 calls of each if you only use 2 tabs
* and only 1 call to each if you insert them all in the same tab

### Definition

````php
$this->crud->addField([ 'label' => "Text 1", 'type' => 'simplemde', 'name' => 'intro', 'tab' => 'Texts 1' ], 'both');
$this->crud->addField([ 'label' => "Text 2", 'type' => 'simplemde', 'name' => 'intro', 'tab' => 'Texts 2' ], 'both');
````

### Field template assets

````php
@if ($crud->checkIfFieldIsFirstOfItsType($field, $fields))
    {{-- FIELD CSS - will be loaded in the after_styles section --}}
    @push('crud_fields_styles')
        <link rel="stylesheet" href="{{ asset('js/simplemde/simplemde.min.css') }}">
    @endpush
    {{-- FIELD JS - will be loaded in the after_scripts section --}}
    @push('crud_fields_scripts')
        <script src="{{ asset('js/simplemde/simplemde.min.js') }}"></script>
    @endpush
@endif
````

### Result

````html
<link href="http://www.acedis.dev/vendor/backpack/summernote/summernote.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="http://www.acedis.dev/js/simplemde/simplemde.min.css">
<link rel="stylesheet" href="http://www.acedis.dev/js/simplemde/simplemde.min.css">

<link rel="stylesheet" href="http://www.acedis.dev/vendor/adminlte/plugins/datepicker/datepicker3.css">

....

<script src="http://www.acedis.dev/js/simplemde/simplemde.min.js"></script>
<script src="http://www.acedis.dev/js/simplemde/simplemde.min.js"></script>

....

````

**Comment by MarcosBL** [comment] 2017-03-09 03:15
After testing the patch at #461 for the Tabs/Queries problem, it doesn't fix this

**Comment by tabacitu** [comment] 2017-03-13 09:34
Damn. On it, thanks for reporting it.

Cheers!

**Comment by Spodnet** [comment] 2017-04-21 07:50
This appears to effect tinymce, I would presume anything that calls checkIfFieldIsFirstOfItsType would have the same problem.

I can see the issue is the fields_array is only passing in the current tab fields, rather than all the fields.

However this looks to be inefficient, in reality you should just be passing in the type of the field, and then keep a list of types that have already been used on the page.

In CrudPanel.php:

`
public $fields_types_shown = []; // Define the fields shown in the page to stop duplicate resources
`

Then in Fields.php

```
    public function checkIfFieldIsFirstOfItsType($type)
    {
        if (in_array($type, $this->fields_types_shown)) {
            return false;
        } else {
            $this->fields_types_shown[] = $type;
            return true;
        }
    }
```

And in the views:

`
@if ($crud->checkIfFieldIsFirstOfItsType($field['type']))
`

**Comment by scottjs** [comment] 2017-04-26 12:31
Hey,

Any updates for this bug? I've just built a crud panel with 112 form fields split across 9 tabs and I've just started noticing this bug now.

Wondering if there's a quick win hack or helper function I can put in place for the time being otherwise I'm going to be in a bit of bother.

**Comment by b8ne** [comment] 2017-05-01 07:03
This is a little bit hacky, but should do the trick until the underlying problem is fixed
```
...
<?php
    if (isset($field['tab'])) {
        $fields = $crud->create_fields;
    }
?>
@if ($crud->checkIfFieldIsFirstOfItsType($field, $fields))
...
```

**Comment by tabacitu** [comment] 2017-05-31 14:57
Hi guys,

Just pushed the fix on the ```dev``` branch, so it will be publicly available in a few days, after more testing. 

If you guys want to check it out and confirm, just use the ```dev``` branch in your project - that would be great. Otherwise, you can [manually make these modifs](https://github.com/Laravel-Backpack/CRUD/commit/84710a11481277bc3393ecdafac777127df7df1d) in your project files.

Cheers!

**Comment by robsimpkins** [comment] 2017-07-25 04:57
Has this fixed been removed from v3.2.13 with [this commit](https://github.com/Laravel-Backpack/CRUD/commit/2553d222ba92ec644cd01943bccf9746b36a81c7)?

**Comment by robsimpkins** [comment] 2017-07-25 05:56
Similar to @b8ne, I ended up overriding the `$fields`.

    @php

    if ($crud->tabsEnabled) {
        $fields = $entry->exists ? $crud->update_fields : $crud->create_fields;
    }

    @endphp

    @if ($crud->checkIfFieldIsFirstOfItsType($field, $fields)) ...

**Comment by indra1** [comment] 2018-02-07 15:43
@tumf87  any updates on the issue? I see it's assigned to you

**Comment by lloy0076** [comment] 2018-02-09 03:10
@tumf87 @tabacitu Please re-open if necessary.

**Comment by PaulLawton227** [comment] 2018-10-15 10:45
It does look as if this fix (on src/resources/views/inc/show_fields.blade.php) got reverted back in this commit:  
https://github.com/Laravel-Backpack/CRUD/commit/e22194e1b9d358ea8c037303e2423c45816c2fd1#diff-b67841600e27daa9eecc81ba6826f81b

**Closed** 2018-11-09 15:37 UTC
Labels: bug

**Comment by tabacitu** [comment] 2018-11-09 15:39
Hi guys,

So sorry - did not expect this to be a real issue. Several of my tests did not confirm it, but now I have tested again and have confirmed the assets are loaded twice. Maybe I was using the fixed version when testing, I don’t know…

Just pushed a 100% fix for this in this PR - https://github.com/Laravel-Backpack/CRUD/pull/1689

Already merged it into ```master```, will be available with ```composer update``` later today, after I bundle it with a few more non-breaking changes.

Cheers!
