### ISSUE TITLE
[3.6][Bug] CSS issue - tbody td is wider then thead td when relations are used

### ISSUE THREAD

**Issue by sheriffmarley** [Laravel-Backpack/CRUD#1849] opened 2019-04-02 21:37 UTC
# Bug report

### What I did:
I noticed that in the table the `tbody > td` width is screwed up if I use relations. eg. 
```php
$this->crud->addColumn([
            'name' => 'user.name',
            'label' => 'User',
            'type' => 'text'
        ]);
```

### What I expected to happen:
The width of the `tbody > td` should match the width of `table > th > td`

### What happened:
It's not aligned. See: https://s17.directupload.net/images/190402/j39728ou.jpg The width of the `tbody > td` is greater than the width of the `thead > td`

### What I've already tried to fix it:
The issue is in the file `list.css` at line ~188
This rule is causing the issue. I removed it and it was correctly displayed 
```css
#crudTable thead>tr>th, table.dataTable thead>tr>td {
	padding-right: 30px;
}
```
 
### Backpack, Laravel, PHP, DB version:
"backpack/crud": "^3.5",
JS/CSS Related issue, i gues sno php and db version are needed

**Comment by tabacitu** [comment] 2019-08-17 16:08
Hi @sheriffmarley , 

Thanks for bringing this up. **Are you getting the same problem after the upgrade to 3.6?** 

I just tested it with 3.6 and it looks good for me - ```th>td``` and ```tr>td``` are aligned:
<img width="674" alt="Screenshot 2019-08-17 at 19 05 04" src="https://user-images.githubusercontent.com/1032474/63214546-119c1000-c122-11e9-912a-9949f7b32210.png">

In this case I've used:
```php
            [
               'label'     => 'Relationship',
               'type'      => 'text',
               'name'      => 'category.name',
            ],
```

Thanks!

PS. I'll close the issue for now since I couldn't reproduce it. I'll gladly reopen it if it's still occurring.

**Closed by tabacitu** 2019-08-17 16:08 UTC
Labels: triage
