### ISSUE TITLE
[Bug] 'validationRules' => 'required' no longer effective on Repeatable

### ISSUE THREAD

**Issue by jfelixoptimiumnc** [Laravel-Backpack/CRUD#4686] opened 2022-09-27 21:26 UTC
Hi all,

In my memories, I'm quite sure it used to be effective... but not anymore.

Thanks for your help and time.

Jerome

### PHP VERSION:
PHP 8.1.8 (cli) (built: Jul  5 2022 23:04:29) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.32.0@aae3b59f82434176546c9dd10804adda16da5278

### BACKPACK VERSION:
5.3.12@883ff76f74bb4cdb70559990026b1130db5234f6

**Comment by pxpm** [comment] 2022-09-29 11:40
Hello @jfelixoptimiumnc thanks for the report.

Unfortunatelly I cannot reproduce your issue. 

I've tried it with:

```
[
                'name'      => 'wish',
                'label'     => 'HasOne (1-1) <small>+ subfields</small>'.backpack_new_badge(),
                'subfields' => [
                    [
                        'name' => 'country',
                    ],
                    [
                        'name' => 'body',
                    ],
                    [
                        'name' => 'universes',
                    ],
                ],
                'wrapper' => [
                    'class' => 'form-group col-md-4',
                ],
                'tab'   => 'Relationship',
                'validationRules' => 'required' // here I added the validation
            ],
```

![image](https://user-images.githubusercontent.com/7188159/193021441-a2c3d38d-c93b-4fda-83ee-57d705b642a2.png)

I also tried adding in the FormRequest and it worked, so I guess it's something on your end, maybe the wrong field name ? 
I am going to close this, please re-open if I am wrong, I've been wrong alot of times in the past 🙃 
Just make sure to include some code examples so that I can reproduce the issue if needed.

Cheers

**Closed by pxpm** 2022-09-29 11:40 UTC
Labels: triage

**Comment by jfelixoptimiumnc** [comment] 2022-09-29 21:50
Hi Pedro,

Thank you for your test and time.

Here is the code. The point is to make a field in a repeatable item required.

Again, I'm 95% sure it used to work...

       $this->crud->addFields([
            [   // repeatable
                'name'  => 'some_field',
                'label' => 'Some field',
                'type'  => 'repeatable',              
                'fields' => [
                    [
                        'name'    => 'date',
                        'type'    => 'date_picker',
                        'label'   => 'Date',
                    ],
                    [
                        'name'    => 'value',
                        'type'    => 'number',
                        'label'   => 'A value',
                        **'validationRules' => 'required',**  
                    ],
                ],
            ],        

        ]);

        **$this->crud->setValidation([]);** 

Best

**Comment by pxpm** [comment] 2022-09-30 10:27
Hello @jfelixoptimiumnc 

I am still unable to reproduce your issue. 

```php
[
                'name'      => 'wish',
                'label'     => 'HasOne (1-1) <small>+ subfields</small>'.backpack_new_badge(),
                'subfields' => [
                    [
                        'name' => 'country',
                    ],
                    [
                        'name' => 'body',
                        'validationRules' => 'required',
                        'validationMessages' => [
                            'required' => 'i am a required sub field'
                        ]
                    ],
                    [
                        'name' => 'universes',
                    ],
                ],
                'wrapper' => [
                    'class' => 'form-group col-md-4',
                ],
                'tab'   => 'Relationship',
            ]
```

![image](https://user-images.githubusercontent.com/7188159/193249218-06821c7d-c623-4bf2-afda-132d962fce5e.png)

I tried adding also with `$this->crud->setValidation()` and it worked: `$this->crud->setValidation(['wish.*.country' => 'required'], ['wish.*.country' => ['required' => 'country is also required']]);`

![image](https://user-images.githubusercontent.com/7188159/193250375-7b81b8cc-18c3-4678-80b4-7e26a4600ef5.png)

Let me know if I am missing something here. Cheers

**Comment by jfelixoptimiumnc** [comment] 2022-10-03 02:50
Hi Pedro,

Thx again for your test and feedback.

I guess you are using the "relationship" field type. Mine is a "Repeatable".

Could this be the difference?

Best,

Jerome

**Comment by pxpm** [comment] 2022-10-03 08:20
It shouldn't make a difference, since relationship uses repeatable under the hood, I will give it a test with  pure repeatable and get back to you. :+1:
