### ISSUE TITLE
Strange visual issue

### ISSUE THREAD

**Issue by JaspervRijbroek** [Laravel-Backpack/CRUD#2348] opened 2020-01-03 15:10 UTC
# Bug report

### What I did

Installed backpack on an existing install of Laravel 6.2,
after the installation the login goes without issues but opon navigating to another panel I recieve strange styling with visual issues.

### What I expected to happen

That the panels work without issues.

### What happened

After login and navigation to the dashboard I receive a different styling than on a panel.

### What I've already tried to fix it

- Cleared all the caches (server & browser)
- Reinstall Backpack

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```markdown
### PHP VERSION:
PHP 7.2.23 (cli) (built: Oct 17 2019 15:56:53) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
Do not run Composer as root/super user! See https://getcomposer.org/root for details

laravel/framework                     v6.9.0             The Laravel Framework.

### BACKPACK VERSION:
Do not run Composer as root/super user! See https://getcomposer.org/root for details

backpack/base                         1.1.13             Laravel Backpack's base package, which offers adminauthentication and a blank admin panel using AdminLTE
backpack/crud                         4.0.31             Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5              Generate files for laravel projects
```

![Screenshot 2020-01-03 at 16 10 54](https://user-images.githubusercontent.com/1225017/71730906-b1450b00-2e43-11ea-9183-6d325623c0d5.png)
![Screenshot 2020-01-03 at 16 11 04](https://user-images.githubusercontent.com/1225017/71730908-b1450b00-2e43-11ea-8abe-8bea56a158f2.png)

**Comment by pxpm** [comment] 2020-01-04 13:25
Hello @JaspervRijbroek 

I think the problem is related to have `backpack/base` installed. In v4.* base is not needed anymore. Remove it from your composer and run a `composer update`.

I am going to close this issue, if you think I might be wrong please re-open it. 

Best,
Pedro

**Closed by pxpm** 2020-01-04 13:25 UTC
Labels: triage
