### ISSUE TITLE
[Bug] Radio buttons do not work correctly

### ISSUE THREAD

**Issue by NikitaMakovey** [Laravel-Backpack/CRUD#3019] opened 2020-07-09 06:43 UTC
# Bug report

### What I did

```
'name' => 'some_boolean_var',
'type' => 'radio',
'options' => [
    0 => 'Something...',
    1 => 'Something else...',
],
'inline' => true,
'label' => 'Some label',
'tab' => 'Some tab',
```

### What I expected to happen

![image](https://user-images.githubusercontent.com/43372486/87005831-fedf6d80-c202-11ea-9b03-4ad4d6df106b.png)

### What happened

![image](https://user-images.githubusercontent.com/43372486/87005871-0e5eb680-c203-11ea-9896-e4939c0ee944.png)

### What I've already tried to fix it

```
'default' => 0,
```

### Backpack, Laravel, PHP, DB version

- Backpack 4.1
- Laravel 7+
- PHP 7.4
- PostgreSQL 12+

**Comment by tabacitu** [comment] 2020-07-09 06:46
Hmm I'm not sure I understand @NikitaMakovey . What's the problem you're raising? 
That the first item doesn't get selected automatically?

**Comment by NikitaMakovey** [comment] 2020-07-09 06:48
@tabacitu, I noticed that this variable is **NULL**, no matter what choice was made. 
And yes - default value is ignored.

**Comment by tabacitu** [comment] 2020-07-09 07:11
Hmm... @NikitaMakovey I just tested this and it worked well for me. This:
```php
            [
                'name'    => 'radio', // the name of the db column
                'label'   => 'Status (radio)', // the input label
                'type'    => 'radio',
                'options' => [ // the key will be stored in the db, the value will be shown as label;
                    0 => 'Draft',
                    1 => 'Published',
                    2 => 'Other',
                ],
                // optional
                'inline' => true, // show the radios all on the same line?
                'tab'    => 'Simple',
                'default'     => 0,
            ],
```

Got me this:
![Screenshot 2020-07-09 at 10 08 55](https://user-images.githubusercontent.com/1032474/87008301-3979e380-c1cc-11ea-87cf-e15bba9a2407.png)

Which is what I expected. Indeed, by default nothing is selected, but if I set a default that one will be selected by default.

So it seems to work in the latest Backpack. Maybe a `composer update`? Maybe you have some JS errors on page that prevent the default selecting from happening? Any JS errors in your Chrome Developer Tools?

**Comment by tabacitu** [comment] 2020-07-09 07:14
Closing the issue for now, since I couldn't replicate it. We'll reopen if it proves to indeed be a bug. Feel free to post here to debug the issue even if it's closed - I'll try to help.

**Comment by NikitaMakovey** [comment] 2020-07-09 07:20
@tabacitu, JS errors are not observed, I don't use Chrome Developer Toolsin work. 

If I **previously** selected a value equal to **0 (false)**, then after I save the record and go back to editing, _the values ​​will be empty_, by default is **NULL**. If you add `default = 0`, then another bug appears that allows you to select several options (that is, _0 and 1_).

**Comment by tabacitu** [comment] 2020-07-09 08:00
Hmm... that's weird @NikitaMakovey - this doesn't happen for me:

![2020-07-09 10 54 36](https://user-images.githubusercontent.com/1032474/87013056-c45ddc80-c1d2-11ea-877a-a444ee0f6b99.gif)

**Please try it yourself in [our online demo](https://demo.backpackforlaravel.com/admin/monster) too - if it works fine there then the problem is not browser-related, it's something to do with your custom code. Have you included any custom field types in that CrudController, any custom JS?**

You really _should_ use Chrome Developer Tools, or some alternative like Firebug if that's still a thing. Without something like that you can't tell if there's any JS errors on page, preventing this from working.

**Comment by NikitaMakovey** [comment] 2020-07-09 08:11
My pull request that solved the problem: [Laravel-Backpack/CRUD/pull/3021](https://github.com/Laravel-Backpack/CRUD/pull/3021)

**Comment by lucidlive** [comment] 2020-07-15 14:41
I experienced the same issue. However, I quickly realized that my field values (0 and 1) were being cast by Laravel as Boolean (false and true). If I removed the casting then it worked as expected and the "default" parameter was not needed.

**Comment by tabacitu** [comment] 2020-07-16 03:36
Wow that's interesting, thanks for pitching in @lucidlive .

@NikitaMakovey - any chance you had this attribute casted as `boolean` inside your Model?

**Comment by nbolender** [comment] 2020-07-16 21:18
@tabacitu I am experiencing this as well, where the field is cast as boolean. My workaround for now is to create a new accessor/mutator with a different field name which does not cast the value (since I use the casted value elsewhere in my application).

The problem is that the value is being set in a hidden input, then being compared in jQuery to set the checked status. The result is the value is `''` instead of `0` or `false`, and thus does not match the given options.

Is there a reason a hidden input is used, instead of setting the value directly on the radio, and setting the checked attribute right away?

**Comment by lucidlive** [comment] 2020-07-16 23:24
@nbolender Maybe just use the "boolean" field type instead of a radio?

**Comment by lucidlive** [comment] 2020-07-20 12:49
> I don't think we _have_ a boolean field type @lucidlive . We do have a `toggle` field type through a first-party add-on: https://github.com/DigitallyHappy/toggle-field-for-backpack maybe that's what you were referring to.

Hey @tabacitu, I'm referring to this: https://backpackforlaravel.com/docs/4.1/crud-columns#boolean

**Comment by nbolender** [comment] 2020-07-21 22:21
Yes it does appear to fix it for me.

**Comment by mgralikowski** [comment] 2020-09-03 22:18
```
// Model
protected $casts = ['confirmed' => 'boolean'];

// Backpack
$this->crud->addField([
    'name'    => 'admin',
    'label'      => 'Is super admin?',
    'type'      => 'radio',
    'options' => [0 => 'No', 1 => 'YES!'], // [false => 'No', true => 'YES!'] in reality 
    'default'  => false,
]);
```

I prefer radio type instead of checkbox because is more readable so it would be nice to fix it.

**Comment by pxpm** [comment] 2020-11-09 13:18
Hello @NikitaMakovey @mgralikowski @nbolender @lucidlive 

Thanks for your reports, it really helped to get down to the bottom issue and apparently I was able to fix it in #3317 

Would you mind giving it a go and let us know if it fixed for you ?

I am going to close this so we keep any further discussion on this issue in the PR thread #3317 

Best,
Pedro

**Closed by pxpm** 2020-11-09 13:18 UTC
Labels: Possible Bug

**Comment by MeerKatDev** [comment] 2021-11-17 17:45
doesn't seem to work, I can select multiple options at the same time, and the value sent is always null.

**Comment by tabacitu** [comment] 2021-11-18 06:56
@MeerKatDev , the checkboxes don't have a `name` attribute because they're there just as an interface. The value is actually stored in a hidden input above, using JavaScript:
<img width="1438" alt="Screenshot 2021-11-18 at 08 51 43" src="https://user-images.githubusercontent.com/1032474/142366733-da7da9a5-c7e1-4736-879a-01f3f82eaa78.png">

I just tested this in our demo and it worked for me - the value was passed to PHP and saved. So it does work in the standard scenario - but you might have stumbled into a niche use case where we have a bug, who knows. Let's see.

1) Do you have any JS errors onpage, that could prevent this from working? 
2) If not, please give extra info here - your addField statement, if that attribute is cast, if you've overwritten the saving process in any way.

**Comment by kiddtang** [comment] 2022-05-23 16:09
Just another scenario I just encountered...
If you have any script to reset the `value` of the form `input`, it will clear the value of the `radio` options too!
meaning that all your options have `null` in `value`, so the hidden field will always be `null` too!
double-check your `value` of all options of the radio input.
