### ISSUE TITLE
Nested routes and resources

### ISSUE THREAD

**Issue by jsiebach** [Laravel-Backpack/CRUD#252] opened 2016-11-22 14:43 UTC
Thanks for the great library! I posted earlier about how to integrate this with laravel-5-boilerplate, but I'm now considering rebuilding my project with backpack!

I've tried a couple of methods to nest resources that haven't been successful.  I am trying to achieve a system where I can have URLs like this: `/account/1/contact`

This would be the CRUD index view of all the contacts tied to that particular account.  I have achieved this so far using two separate resources, `/account` and `/contact`, which use n-n relationships.  I also have filters on the `/contact` that allow me to specify an account to show.  

Is there a way to write my routes in such a way that I can limit the scope of the nested resource to only show those attached to the first?

**Comment by tabacitu** [comment] 2016-11-29 14:20
In short, yes, you can use the ```$this->crud->addClause()``` method, which allows you to modify the query. You'll find a few examples [here, under Advanced Queries](https://laravel-backpack.readme.io/docs/crud-full-api#section-usage-level-2-often).

Also, here's a [tutorial on how to achieve nested resources in Backpack\CRUD](https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud). Seems to me like you've already done 90% of that, you only need to add the query constraint.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by jsiebach** [comment] 2016-11-29 14:25
Thank you very much @tabacitu - I was very close, I was trying to use `account/{account}/contact` instead of dropping in the actual param.

**Comment by tabacitu** [comment] 2016-11-29 14:27
;-)

**Comment by jsiebach** [comment] 2016-12-01 11:01
Hey @tabacitu!  I ran into an issue with this setup I wanted to point out.  This works great for displaying nested resources, but fails when you try to hit any of the other routes on the controller (delete, showDetailsRow, edit).  All of these controller methods only take one parameter for `$id`, but Laravel tries to pass them two because the route has two variables.  It ends up passing the ID of the parent entity to the function.  Example:

Route `/account/2/contact/6/details`would call to `AccountContactsCrudController@showDetailsRow` which accepts 1 parameter `$id` which should be 6, but instead is 2.  The details returned are for the Contact entity with id 2.  This also happens for delete or edit methods.

Since the `AccountContactCrudController` extends from `ContactCrudController`, you can't edit the method signature to take a second variable (and wouldn't want to manually overwrite all those methods anyway)

**Comment by M0H3N** [comment] 2016-12-20 08:21
@jsiebach 
Hi .... can you solve this issue .... I have the same problem now and no idea about that

**Comment by tabacitu** [comment] 2016-12-21 09:30
@jsiebach  - damn, you're right. 

@M0H3N how about this for a fix - in the parent we overwrite all methods that don't work, and just call the child method, with the right parameter. This works for the tutorial example ("post" is the child entity - "user posts"):

```php
class UserPostCrudController extends PostCrudController {

    public function show($id)
    {
        return parent::show($this->request->post); 
    }
}
```

That should be a fix for you until we can find a long-term fix for this.

**Comment by tabacitu** [comment] 2016-12-21 09:40
Here's all of them at this date:
```php
    public function show($id)
    {
        return parent::show($this->request->post);
    }

    public function listRevisions($id)
    {
        return parent::listRevisions($this->request->post);
    }

    public function restoreRevision($id)
    {
        return parent::restoreRevision($this->request->post);
    }

    public function showDetailsRow($id)
    {
        return parent::showDetailsRow($this->request->post);
    }
```

**Comment by jrpub** [comment] 2017-05-26 09:12
Same issue. Waiting for a patch, I implemented the workaround through a Trait in the needed controllers.

**My current controller, broken:**
```
class ItemFieldCrudController extends CrudController
{
    public function setup()
    {
        $project_id = \Route::current()->parameter('project_id');
        $this->crud->setRoute(config('backpack.base.route_prefix') .'/'.$project_id. '/itemfield');
        $this->crud->addClause('where', 'project_id', '=', $project_id);
```
This is the lines that break the edit, delete, and other operations in Backpack as the "project_id" will be viewed as the parameter to edit, delete etc.

**Workaround**:

In the controller:
` use Traits\NestedRouteBadParameterBug;
`

And the Trait:

```
namespace App\Http\Controllers\Admin\Traits;

trait NestedRouteBadParameterBug
{
    public function getLastParameter()
    {
        $params = \Route::current()->parameters();
        $lastparam =  array_values($params)[count($params)-1];
        return $lastparam;
    }

    public function edit($id)
    {
        return parent::edit($this->getLastParameter());
    }

    public function view($id)
    {
        return parent::view($this->getLastParameter());
    }

    public function destroy($id)
    {
        return parent::destroy($this->getLastParameter());
    }

    // All the relevant functions of CrudController.php can be added.
}
```
Hope it will be patched soon!

**Comment by tarmo1979** [comment] 2017-12-03 15:52
@jrpub I see the issue is closed, but the problem still seems to exists?
Thank You @jrpub for the trait, You saved my day :)

**Comment by jrpub** [comment] 2018-04-14 16:59
Yes, the issue still exists. Too bad! 

See #307 also, where the question left by @tabacitu stayed without any answer :-)

**Comment by tabacitu** [comment] 2018-04-17 08:08
@jrpub , thanks a lot for your solution! 

I've just implemented an official patch here: https://github.com/Laravel-Backpack/CRUD/pull/1339 , which I'll be merging after a bit more feedback & testing. Let me know what you think, and if it's a good fix for you guys. Cheers!

**Closed by tabacitu** 2018-04-17 08:08 UTC
Labels: triage
