### ISSUE TITLE
[Bug] $entry not usable with addButtonFromModelFunction()

### ISSUE THREAD

**Issue by flip-9** [Laravel-Backpack/CRUD#3128] opened 2020-08-18 01:00 UTC
# Bug report

### What I did

Setup the Custom Button example based on documentation
`$this->crud->addButtonFromModelFunction('line', 'open_google', 'openGoogle', 'beginning');`

Added the openGoogle method to my Model
`public function openGoogle($crud = false)
    {
        return '<a class="btn btn-sm btn-link" target="_blank" href="http://google.com?q=' . urlencode($this) . '" data-toggle="tooltip" title="Just a demo custom button."><i class="fa fa-search"></i> ' . $entry->getKey() . ' it</a>';
    }`

### What I expected to happen

I tried using the $entry variable as documentation suggests. 

### What happened

addButtonFromModelFunction() doesn't seem to pass $entry on an inline button.
addButtonFromView does.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### LARAVEL VERSION:
v7.25.0@fdf3d4a40447eb286ba3820768306cae64bcc0b3

### BACKPACK VERSION:
4.1.17@952ba942c7ff8b41fc2409d3c3cfef68dd48bf18

**Comment by tabacitu** [comment] 2020-08-18 11:59
Indeed @flip-9 , if you're using the `addButtonFromModel()` method you won't have `$entry` inside your method, but that's just because you're inside the model, so you already have `$this`. You should be able to replace `$entry->id` with `$this->id` and it'll work without a hitch. See an [example here in our demo](https://github.com/Laravel-Backpack/demo/blob/master/app/Models/Monster.php#L46).

Looks like we have a problem in our docs - could you please point me to where you've read the above, so we can fix it?

Cheers!

**Comment by tabacitu** [comment] 2020-08-18 12:00
I'll close this in the meantime, since it's not a bug _per se_.

**Closed by tabacitu** 2020-08-18 12:00 UTC
Labels: triage

**Comment by flip-9** [comment] 2020-08-18 14:38
Hey @tabacitu . Thanks for the details and example!
As a real real beginner to both Laravel and Backpack, this section in docs made it a bit confusing:
https://backpackforlaravel.com/docs/4.1/crud-buttons#creating-a-custom-button

Maybe it could be noted that $entry really isn't relevant when dealing inside the model already? I'm sure for 90% of the more experienced devs it makes perfect sense already and I'm just missing basics, so maybe unnecessary.

**Comment by tabacitu** [comment] 2020-08-18 15:12
Got it, thanks! I've added a note there, hope it helps reduce the confusion: https://github.com/Laravel-Backpack/docs/commit/5995daa3159922968c87e359b476689be0cf62bd
