### ISSUE TITLE
Can't install the demo "Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by avifatal** [Laravel-Backpack/CRUD#381] opened 2017-01-22 08:55 UTC
Hi,
I did the tutorials from here: https://laravel-backpack.readme.io/docs/demo
and when running the composer I get:

```
Problem 1
    - Installation request for cviebrock/eloquent-sluggable 4.1.2 -> satisfiable by cviebrock/eloquent-sluggable[4.1.2].
    - cviebrock/eloquent-sluggable 4.1.2 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/annotations v1.3.0 -> satisfiable by doctrine/annotations[v1.3.0].
    - doctrine/annotations v1.3.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 3
    - Installation request for laravel/framework v5.3.24 -> satisfiable by laravel/framework[v5.3.24].
    - laravel/framework v5.3.24 requires php >=5.6.4 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 4
    - Installation request for laravelcollective/html v5.3.0 -> satisfiable by laravelcollective/html[v5.3.0].
    - laravelcollective/html v5.3.0 requires php >=5.6.4 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 5
    - laravel/framework v5.3.24 requires php >=5.6.4 -> your PHP version (5.5.9) does not satisfy that requirement.
    - laracasts/generators 1.1.3 requires illuminate/support ~5.0 -> satisfiable by laravel/framework[v5.3.24].
    - Installation request for laracasts/generators 1.1.3 -> satisfiable by laracasts/generators
```[1.1.3].

Thanks

**Comment by OwenMelbz** [comment] 2017-01-22 09:16
My first tip would be to read the error 😉It tells you exactly what the problem is.

As this is not a backpack related issue I'll close it to keep things tidy

**Closed by OwenMelbz** 2017-01-22 09:16 UTC

**Comment by tabacitu** [comment] 2017-01-22 09:32
Hi @avifatal ,

Seems like you're running an old PHP version. Laravel needs PHP 5.6.4 or higher. 

My recommendation is to go straight to PHP 7, since all previous versions are now considered deprecated. Plus, there's a big speed boost in PHP 7.

Cheers!
