### ISSUE TITLE
[Bug] Mongo Db Connection 

### ISSUE THREAD

**Issue by eudovic** [Laravel-Backpack/CRUD#5553] opened 2024-07-06 12:19 UTC
# Bug report

### What I did
I am using MongoDB connection as part of the CQRS architecture in a Backpack project. Everything seems to be working fine except for the DevTools Create Model view, which is now broken.
![image](https://github.com/Laravel-Backpack/CRUD/assets/31167386/99089456-6366-4bbb-9cfa-43890e7e3d1e)

??

### What I expected to happen
I expected to be able to create new MySQL models.
??

### What happened
The view is now broken.
??

### What I've already tried to fix it
I haven't attempted any fixes yet.
??

### Is it a bug in the latest version of Backpack?
Yes
After I run ```composer update backpack/crud``` the bug... is it still there?
Yes. After running composer update backpack/crud, the bug is still present.

### Backpack, Laravel, PHP, DB version
Back pack 6 , laravel 10 , PHP 8.1, DB mysql and mongo

When I run ```php artisan backpack:version``` the output is:
backpack/activity-log: 2.0.4
backpack/basset: 1.3.4
backpack/crud: 6.7.17
backpack/devtools: 3.1.5
backpack/editable-columns: 3.0.9
backpack/generators: v4.0.5
backpack/logmanager: v5.0.2
backpack/pagemanager: 3.3.0
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.4
backpack/theme-tabler: 1.2.10

**Comment by pxpm** [comment] 2024-07-08 09:04
Hello @eudovic thanks for the report. 

Can you confirm if that happens every time, or when you add some specific column type or perform some specific action ? 

Can you tell me the minimum steps to reproduce this issue ? 

Thanks in advance. 

Cheers

**Comment by eudovic** [comment] 2024-07-08 10:04
The error occurs when trying to open the page for creating new models, that
is, it is not even possible to start configuring a new one.  About the
steps to reproduce.  Here I just used the laravel/mongodb library and
created new models using mongo dB, this way I had two different databases
in the project.  MySQL and mongodb.  This way made the page break.




Em seg., 8 de jul. de 2024 06:05, Pedro Martins ***@***.***>
escreveu:

**Comment by eudovic** [comment] 2024-07-10 00:48
Tried Now changing the default connection, but same trouble
[image: image.png]

Em seg., 8 de jul. de 2024 às 07:11, Pedro Martins ***@***.***>
escreveu:

**Comment by eudovic** [comment] 2024-07-23 20:12
Hi, how are you doing?
Do you have any news about that?
Is there anything you want me to do help you debug?
Tks!

Em ter., 9 de jul. de 2024 às 21:47, Emerson Udovic ***@***.***>
escreveu:

**Comment by pxpm** [comment] 2024-07-24 08:38
Hey @eudovic sorry I missed your previous message. 

If the same error persist after you changed the default db, it's because either the configs didn't take effect (maybe cache?), or that the mongo db implementation completely takes over, because in the error your can see it's trying to call some Mongo class. 

If you can reproduce this using a rdbms with sql I can try to help you a little more. Or if the error is related with sql classes. If it's related with mongo classes I am totally un-ware of how to fix it, just like I said previously, probably using a project with just mysql, or even sqlite, create there the stuff and move over the files. 

Sorry I can't be much more help here. Let me know how it goes 🙏

**Comment by eudovic** [comment] 2024-07-24 10:27
Don't worry!
I Will try to fix and I Will let you know If I have sucesso doing that.
Thank you so much

Em qua., 24 de jul. de 2024 05:38, Pedro Martins ***@***.***>
escreveu:

**Comment by pxpm** [comment] 2024-07-24 11:55
Sure, thanks @eudovic 

Let me know your findings, maybe we can work something out to provide that support in-house 👍 

Closing this, but I am subscribed to notifications 👍 

Cheers

**Closed by pxpm** 2024-07-24 11:55 UTC
Labels: triage
