### ISSUE TITLE
[Bug] Remove filter button does not hide when select2 filters are cleared.

### ISSUE THREAD

**Issue by martijnb92** [Laravel-Backpack/CRUD#3367] opened 2020-12-01 13:18 UTC
# Bug report

### What I did

- Open https://demo.backpackforlaravel.com/admin/monster
- Select an item from the select2_multiple/select2/select2_ajax filter
- Clear the item by pressing the small x

### What I expected to happen

The "Remove filters" button should disappear.

### What happened

The "Remove filters" button does not disappear

### What I've already tried to fix it

This happens with multiple select2 filter types, small javascript problem
The current script checks if the filter is active and if it is, an .active class is added to the filter
If it's no longer active, the .active class is removed. 

The "Remove filter" button which has been created by activating the filter will never be removed.

Solution is easy, select2_multiple filter with the fix:

```javascript
// mark this filter as active in the navbar-filters
if (URI(new_url).hasQuery(filterName, true)) {
	$("li[filter-key="+filter_key+"]").removeClass('active').addClass('active');
}
else
{
	$("li[filter-key="+filter_key+"]").removeClass("active");
	$("li[filter-key="+filter_key+"]").find('.dropdown-menu').removeClass("show");
	
	// THE FIX: check if there any other filters are still active, if not trigger filter:clear.
	if(!URI(new_url).search()){
		$(".navbar-filters li[filter-name]").trigger('filter:clear');
	}
}
```
I can create a PR if needed.

### BACKPACK VERSION:
4.1.27

**Comment by promatik** [comment] 2020-12-01 22:47
Hi @martijnb92!
Thank you once again for reporting this issue, just confirmed it on demo.

If you have the time and want to be credited for the solution, since you've already provided it, we will gladly welcome your PR 😁
It's ok if you don't have the time, I'll pick this within this week.

Thank you 🙌

**Comment by martijnb92** [comment] 2020-12-03 10:23
Just created a PR https://github.com/Laravel-Backpack/CRUD/pull/3371

**Comment by promatik** [comment] 2020-12-03 22:18
Thank you @martijnb92 🎉
I'll close this in favor of #3371

**Closed by promatik** 2020-12-03 22:18 UTC
Labels: Minor Bug, Priority: SHOULD
