### ISSUE TITLE
Image Compression

### ISSUE THREAD

**Issue by emaikongebm** [Laravel-Backpack/CRUD#2490] opened 2020-02-28 04:08 UTC
Is there any way for Backpack For Laravel to compress the image that i uploaded?

Say that I have a 300 kilobytes size of an image, is there any way that I compress the uploaded image to only 3 kilobytes without using other image compression library?

**Comment by t-prod** [comment] 2020-02-28 15:41
Hi,

I try to do that to but you should use Intervention Image to do this in the upload function from your CRUD Controller. As I know, there's no backpack way for this.

Regards

**Comment by tabacitu** [comment] 2020-02-28 17:10
![https://media.giphy.com/media/3orieMxI2f5075NFJe/giphy.gif](https://media.giphy.com/media/3orieMxI2f5075NFJe/giphy.gif)

Compressing images is out of scope for Backpack, I'm afraid. 

As @t-prod said, you already have [Intervention Image](http://image.intervention.io/api/resize) if you've installed Backpack, and it can help with resizing images. But for compressing, Intervention can only do it with quality loss, as far as I know. 

If you're looking for lossless compression, I don't know any good solutions to recommend, that would do it automatically for you, for free. I know there are paid services that do this though. And I know ImageOptim, TinyPNG and stuff like that can do it manually. But honestly I haven't done automatic image compression in a while, so I can't help there. Would love to hear your solution if you find something you like, please post back here so we all can learn from your research. I'll close the issue though, since this is not a bug.

Sorry I couldn't be of more help.
Cheers!

**Closed by tabacitu** 2020-02-28 17:10 UTC
Labels: triage
