### ISSUE TITLE
[Bug] Json field casted as array and treated as "fake column", with an "id" field inside the array, overwrites the main entry id inside setupUpdateOperation

### ISSUE THREAD

**Issue by skpr-repo** [Laravel-Backpack/CRUD#5133] opened 2023-06-20 13:51 UTC
# Bug report

### What I did

Well, first and foremost, sorry for the long title :-)

This is the problem, somehow connected to this one (https://github.com/Laravel-Backpack/CRUD/issues/5073)

I have a json field _shipping_data_ casted as array. The field was also listed as **fake column** inside the model (the reason was explained inside the issue linked before).

```
protected $fakeColumns = [
    'shipping_data',
];
```

The json field is a list of fields:

{ "id": 22428, "city": "Milan", "name": "Abc", ... }

When I call `CRUD::getCurrentEntry()->id`

inside the setupUpdateOperation() I get the id of the fake field _shipping_data_ instead of the $entry id.

### What I've already tried to fix it

Removing the _shipping_data_ field from the list of fake_columns solves the problem. 

It took quite a while to find the error...

### Is it a bug in the latest version of Backpack?

yes

After I run ```composer update backpack/crud``` the bug is still there

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP 8.1.7 (cli) (built: Jun 10 2022 12:22:48) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.52.9@c512ece7b1ee393eac5893f37cb2b029a5413b97

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.6.1
backpack/devtools: 1.3.5
backpack/editable-columns: 2.1.4
backpack/filemanager: 2.0.1
backpack/generators: 3.3.16
backpack/logmanager: v4.0.10
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.6
backpack/revise-operation: 1.0.12
backpack/settings: 3.0.16

**Comment by promatik** [comment] 2023-08-27 22:37
Hi @skpr-repo, sorry for the long delay, we've been over v6 and I finally get the time to look at your report 👌

So, first I was able to reproduce your issue, but later I understood the usage of `fakeColumn` is wrong here, I'll explain;

FakeColumns are meant to store multiple fields that do not have a proper column for it, so they're grouped together in a fake column.
But, these are *extra* fields, this is not meant to save an object with shipping information, like yours `{"id": 22428, "city": "Milan", "name": "Abc"}`.

This shipping information can be all on a column, casted as an object or array, but **it is not** a fake column, you don't even need it to be fake, just casted 👌

If you can't change your code (not recommended) you can always use `CRUD::getCurrentEntryId()` to get the entry ID and if you need the entry model object, without the fakes, you can do `CRUD::getEntry(CRUD::getCurrentEntryId())`.
Again, not recommended, but it works because it's not loading the fakes.

Let me know if you were able to solve your issue, I'll close this one for now 🙌

**Closed by promatik** 2023-08-27 22:37 UTC
Labels: triage
