### ISSUE TITLE
[4.1][Bug] Fix relationship to work inside repeatable with dependencies attribute

### ISSUE THREAD

**Issue by Freezon** [Laravel-Backpack/CRUD#3218] opened 2020-09-22 07:39 UTC
A dependency relationship field is not reset when the dependent field changes.
Also, when requesting via "fetch", the data of the repeated field is not sent.

**Comment by pxpm** [comment] 2020-09-30 08:52
Hello @Freezon 

Thanks for the report. We have two issues to discuss here, so the first one about the dependant fields:

```js
for (var i=0; i < $dependencies.length; i++) {
                $dependency = $dependencies[i];
                $('input[name='+$dependency+'], select[name='+$dependency+'], checkbox[name='+$dependency+'], radio[name='+$dependency+'], textarea[name='+$dependency+']').change(function () {
                    element.val(null).trigger("change");
                });

            }
``` 

The above code is the one responsible for reseting the parent element. In repeatable fields the attribute `name` is stripped from the input, so this bit of code would never find it. 

For repeatable elements this could be a little bit tricky because you could have one or more inputs with the same `input-repeatable-name`. So even if we add the search for the `input-repeatable-name` it might find two or more inputs with the same name and reset them all.

We need a way to reset the specific input in a specific repeatable row. 

One solution could be to add an `repetable-row="x"` to every repeatable row so we can search by a combination of `input-repeatable-name` with `repeatable-row` to match a specific element. 

@tabacitu your toughts on this ?

About the second problem could you clarify ? You have a select with ajax and use `'include_all_form_fields'` and repeatable field is not sent ? 

Best,
Pedro

**Comment by pxpm** [comment] 2020-10-01 08:47
Doing an issue checkup I found that we already have this issue open. See #2865 

I am closing the other in favor of this one because here I think I have a better explanation of the problem and a "could be" solution.

**Comment by pxpm** [comment] 2020-10-22 11:44
I'v just submitted a PR that would bring the dependant functionality to repeatable fields. 

Please checkout #3275 .

I am going to close this so we keep any discussion in the PR thread. 

Wish you the best,
Pedro

**Closed by pxpm** 2020-10-22 11:44 UTC

**Comment by o15a3d4l11s2** [comment] 2021-01-04 09:48
I could not find any information regarding the second issue. I have a field of type `select2_from_ajax` with `include_all_form_fields` inside a `repeatable`, but when I execute the fetch, I get only the parent (the repeatable field) as part of the form data with null. Is there any solution for this?

**Comment by pxpm** [comment] 2021-01-04 10:29
I think I got it now, thanks. Let me investigate and I will get back to you .

**Comment by pxpm** [comment] 2021-01-04 14:45
Hello @o15a3d4l11s2 

I'v just submited PR #3439 that should fix this issue. 

If you happen to have time and test it, please leave your review in the PR thread. 

Thanks for raising this to our attention. 

Best,
Pedro

**Comment by o15a3d4l11s2** [comment] 2021-01-05 08:18
I have tested and confirmed the fix in the PR.

Slightly off-topic: @pxpm, do you have any idea how I can identify the exact index of the repeatable select2?
I have created a question on StackOverflow: https://stackoverflow.com/questions/65575235/laravel-backpack-identify-the-exact-repeatable-field-index

**Comment by pxpm** [comment] 2021-01-05 13:58
@o15a3d4l11s2 that's something we need to workout somehow.

I think by adding a `repeatable_row_trigger` to the request, with the number of the row where something (by something I mean ajax request, validation errors), this second we are aware of. 

For the second one I think the solution would lie around writting custom validators for repeatable fields.

The first one, the problem you described I am tempted to add an hidden input that will pass along the `repeatable container` and the `repeatable row` that triggered that request. 

I will open an issue for that specific case (ajax requests) to see if we can come up with a solution we all agree on. 

Best,
Pedro

**Comment by o15a3d4l11s2** [comment] 2021-01-05 14:21
@pxpm I am not sure if I understood you completely. To use the idea you provided - how can I send some extra information to `fetchXXXXXX()` so that I can identify the element that triggered it? If I am able to identify it, then I can look for the hidden field that has the same information and then implement my custom fetch login. For the fetch I am following https://backpackforlaravel.com/docs/4.1/crud-operation-fetch. It seems like I should create my custom `repeatable` and `select2_from_ajax` fields to achieve this? Or maybe better, I don't really need the whole form data, but just the repeatable row data to implement my logic. In this case I might be able to create only a custom `select2_from_ajax` with option similar to `include_all_form_fields`, that includes only the data of the fields that are siblings of my select2 field.

@tabacitu, can you think of a smart solution of this? Is this something that might be needed by other people also? If so I might be able to help with it
