### ISSUE TITLE
Using Accessor in relationship attribute need to declare $appends

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#5309] opened 2023-09-01 09:18 UTC
I'm not  sure it this is a bug, but I think in previous versions you didn't need to declare $appends for the use of an accessor in a relation to work, but it seems that now you need to, although the documentation doesn't mention it.

This is my field in the controller:

```
 CRUD::addField([ 
            'type' => "relationship",
            'name' => 'employee', // the method on your model that defines the relationship
            'ajax' => true,
            'label'       => "Empleado",
            'attribute'   => "full_name",
        ]);
```

My accessor
```
protected function fullName(): Attribute
    {
        return Attribute::make(
            get: fn (mixed $value, array $attributes) => $attributes['name'].' '.$attributes['lastName'],
        );
    }
```

If I test the accessor:

```
 $empl=Employee::find(200);
    dd($empl->full_name);
```
return the full name as I expected.

But the relationship field doesn't show the accessor returned data  until I declare $appends in the model

```
 protected $appends = ['full_name'];
```

My versions are:

### PHP VERSION:
PHP 8.1.22 (cli) (built: Aug 14 2023 05:32:33) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.22, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

### LARAVEL VERSION:
10.21.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.0
backpack/crud: 6.2.0
backpack/devtools: 2.0.3
backpack/editable-columns: 3.0.2
backpack/generators: v4.0.2
backpack/logmanager: v5.0.0
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.2.0
backpack/theme-tabler: 1.1.0

**Comment by tabacitu** [comment] 2023-09-01 10:36
Hi @miquelangeld ,

Needing to declare `$appends` is not a Backpack thing, it's a Laravel thing. I can confirm it was always needed.

The reason`$appends` isn't documented in the relationship field is that... we've never thought of using the `relationship` field on an accessor. It's meant to be used on a relationship method. That's the way it'll work best, and the way it's documented - point it to your _relationship method_. I have no idea what problems you might run into using it on something else... but... yeah if that works for you, nice! 😀 

Closing this, as it's not a bug.
Cheers!

**Closed by tabacitu** 2023-09-01 10:36 UTC
Labels: triage

**Comment by tabacitu** [comment] 2023-09-04 10:53
> It is the other way round I'm using an accessor in a relationship field in order to show a full name in the combo.

OOooooh. Ok 😀 That should be fine then 😀 Pfiew!
