### ISSUE TITLE
Select column not working ?

### ISSUE THREAD

**Issue by alexstudle** [Laravel-Backpack/CRUD#584] opened 2017-04-02 19:29 UTC
Hi,
first of all thank you for this amazing tool, I love it :) !

I'm having a problem with the Columntype "select". As soon as I add a select-column in my controller, I get an Error 500 

The input works perfectly but I can't figure out, why the column returns such an error.
I followed the exemple provided in your documentation. Here is my code:

My input field (works fine)

> $this->crud->addField([
>             'name'  => 'recipe_type_id',
>             'label' => 'Type',
>             'type'  => 'select2',
>             'entity' => 'recipe_type',
>             'attribute' => 'name',
>             'model' => Recipe_type::class,
>             'wrapperAttributes' => [
>                 'class' => 'form-group col-md-4'
>             ]
>         ]);

My column (doesn't work..)

> $this->crud->addColumn([
> 		    'name'  => 'recipe_type_id',
> 		    'label' => 'Type',
> 		    'type'  => 'select',
> 		    'entity' => 'recipe_type',
> 		    'attribute' => 'name',
> 		    'model' => Recipe_type::class
> 	    ]);

Any idea how I could solve this ?
Thank you for your help !

Alex

**Comment by tabacitu** [comment] 2017-04-03 05:43
Hi @alexstudle ,

Sounds like a misconfigured column. Could you please also post the Model? 
1. What strikes me at first is using the underline - models are usually RecipeType, not recipe_type.
2. One the model you're currently editing, do you have the recipe_type relationship defined?

Cheers!

PS. Gonna close this issue, as it's definitely not a bug in the software. But reply here and we'll try to help.

**Closed by tabacitu** 2017-04-03 05:43 UTC

**Comment by alexstudle** [comment] 2017-04-03 07:01
Hi,

In fact I think the "_" was part of the Problem... My model was named "Recipe_type" and same for Controller, Requests etc..

I renamed them in "RecipeType" and now it works fine ! So I should respect the convensions properly ;)

Thank you for your help :) !

Cheers,
Alex

**Comment by tabacitu** [comment] 2017-04-03 07:12
Glad it worked out. Cheers!
