### ISSUE TITLE
How to make the routes ?

### ISSUE THREAD

**Issue by sudargits** [Laravel-Backpack/CRUD#559] opened 2017-03-18 15:45 UTC
ok, i spent 4 hours and gave up.

how do you set the routes after you run `backpack:crud` ?

the steps i took 
`$ php artisan backpack:crud pelayanan`

then, in `routes/web.php` i put these at the bottom
`Route::group([
    'prefix' => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['admin'],
    'namespace' => 'Admin'
], function() {
    Route::resource('pelayanan', 'Admin\PelayananCrudController');
});`

but when i tried to open `localhost/myapp/public/admin/pelayanan` it gives error 500.

any idea why ? any help is appreciated.
thanks

**Comment by OwenMelbz** [comment] 2017-03-18 16:26
Do you know how to use laravel first?

Have you watched laracasts?

If the answer is no to either of them, watch the free laracasts which teaches you how.

I'll close this now as github issues is for software bugs not support. If you checkout the readme and guidelines it tells you to ask for support on stackoverflow

**Closed by OwenMelbz** 2017-03-18 16:26 UTC

**Comment by sudargits** [comment] 2017-03-18 16:58
yes, i;m currently using laravel 4 for an ongoing project.
yes, i've watched laracast.

i just followed the backpack's instructions,
i can make new routes with Route::get, post, put, etc.

it's just the CRUD routes that i confused. it didn't work. what did i missed ? can you point it out ?

**Comment by tabacitu** [comment] 2017-04-03 17:07
Hi @sudargits ,

I noticed you said you used ```Route::resource('pelayanan', 'Admin\PelayananCrudController'); ```, but you should have used ```CRUD::resource('pelayanan', 'Admin\PelayananCrudController'); ```. That might have been your problem.

Anyway, I've just checked and this is definitely not a bug. Please post support questions on StackOverflow, using the backpack-for-laravel and laravel tags. Keeping GitHub only for bugs and features helps us develop faster.

Cheers!
