### ISSUE TITLE
[Bug] [v6] Slow check all rows on new themes Core UI v4 and Tabler

### ISSUE THREAD

**Issue by preBit** [Laravel-Backpack/CRUD#5266] opened 2023-08-04 08:37 UTC
# Bug report

### What I did

Went to: [Backpack Demo Product page](https://demo.backpackforlaravel.com/admin/product) and changed counter from "10" "All" for testing purposes.

### What I expected to happen

When check all rows is clicked in the new themes based on bootstrap 5 (Core UI v4 and Tabler) to be as speedy as it was on old Core UI v2 theme. This all on Backpack v6 demo.

### What happened

On new themes Core UI v4 and Tabler, which are based on bootstrap 5, for some reason check all is much slower than old Core UI v2 theme based on bootstrap 4 all on Backpack v6. 

On the Core UI v2 theme check all rows is instant and on both new themes (Core UI v4 and Tabler) is like 10 time slower. And to notice the lag in the demo if you click multiple times check all rows on Core UI v2 theme you can actually do that, but on both of the new themes there is a noticeable lag.

In practice this is noticeable a little on 25 rows, on 50 rows is maybe a 1-2 sec but on 100 is like 5 or more seconds to check all rows.

This is old Core UI v2 theme on Backpack v6:
![Screenshot 2023-08-04 at 09 36 47](https://github.com/Laravel-Backpack/CRUD/assets/598483/09adb8f5-b2a5-482e-b02d-c916237eebac)

This is new Core UI v4 theme on Backpack v6:
![Screenshot 2023-08-04 at 09 39 04](https://github.com/Laravel-Backpack/CRUD/assets/598483/f8838f1f-f8d1-4905-9ac6-927b55431836)

Purely subjective, but it seems to me that datatables rendering performance is much better on Core UI v2. Is it bootstrap or something else...hmmmm...i don't know...

**Comment by karandatwani92** [comment] 2023-08-04 10:04
Hey @preBit 
Thanks for putting it in our notice.
we'll find the cause and try to come up with a solution.

Good day

**Comment by tabacitu** [comment] 2024-06-04 06:09
Just checked (pun intended) and this is no longer the case. Checking 100 rows is just as fast in Tabler and CoreUIv4 as it is in CoreUIv2. So let's close this. Thanks for opening the issue @preBit . Sometimes we get lucky and issues solve themselves 😅

**Closed by tabacitu** 2024-06-04 06:09 UTC
Labels: Priority: COULD, enhancement, Size: XS
