### ISSUE TITLE
[Bug] Demo Alerts show up without styling after alerts PR got merged 

### ISSUE THREAD

**Issue by promatik** [Laravel-Backpack/CRUD#3540] opened 2021-02-19 00:15 UTC
# Bug report

@martijnb92 just report on https://github.com/Laravel-Backpack/CRUD/pull/3079, that PR introduced a bug.

![image](https://user-images.githubusercontent.com/1838187/108438541-5d63d400-7247-11eb-8ac2-15e182c7ebb7.png)

Noty alerts are not working.
It's also not working on [online demo](https://demo.backpackforlaravel.com/admin/monster/create#miscellaneous).

**Comment by promatik** [comment] 2021-02-19 00:22
@pxpm I spent some time around this, and I cannot reproduce this on my local environment.

I have demo and crud up to date, and Noty is working as not expected 🤦‍♂️

Can you please help me debugging this?

---
Things I've discovered already;
- if you run the `Noty.overrideDefaults(...` on the console, it starts working, as expected...
```js
Noty.overrideDefaults({
    layout: 'topRight',
    theme: 'backstrap',
    timeout: 2500,
    closeWith: ['click', 'button'],
});
```

Apparently this code haven't run because that alert on demo have the default `mint` theme ...

My best guess right now, is for the `DOMContentLoaded` event, on the #3079 PR you've moved that Noty override inside the `DOMContentLoaded`, it should work, but I don't know, I can't see why this is not working ...

**Comment by promatik** [comment] 2021-02-19 00:28
@martijnb92 did you experienced this issue on your local environment or only on demo?

**Comment by martijnb92** [comment] 2021-02-19 09:40
Can confirm moving the `overrideDefaults()` outside of the event listener solves the styling issue.

Did some testing, appears to be a timing issue. In some cases the `DOMContentLoaded` event if fired before the event listener is created, preventing all notifications from being shown.
https://stackoverflow.com/questions/39993676/code-inside-domcontentloaded-event-not-working

Another example: when I press save on the account page, a notification should be shown. But it doesn't
https://demo.backpackforlaravel.com/admin/edit-account-info

**Comment by pxpm** [comment] 2021-02-19 11:14
Hello @promatik and @martijnb92 

I can't reproduce it in local either. My guess is that is has to do something with css, I will have another look. 

About the `DOMContentLoad` it's seems the accepted solution is to wrap it in another condition:

```javascript
if (document.readyState !== 'loading') init()
else document.addEventListener('DOMContentLoaded', init);

function init();
```

Since you can reproduce the error, could you check if this fixes it @martijnb92 ?

Best,
Pedro

**Comment by pxpm** [comment] 2021-02-19 11:39
On a new demo install I could not reproduce the error. So a `php artisan vendor:publish --force --tag=public` should fix ? 

But this is a BC in this case. We should ask @tabacitu to revert this commit in this scenario.

**Comment by martijnb92** [comment] 2021-02-19 12:02
Found the issue!

Backpack demo and my site are both using cloudflare.
We both have _Rocket Loader_ enabled.

Rocket Loader does some JavaScript optimizations, and in this case it prevents the `DOMContentLoad` event.

The only thing that needs to be fixed is moving the `overrideDefaults()` outside of `DOMContentLoad`.
This fixes on demand notifications (such as the Youtube video ID validation), by setting the `backstrap` theme instead of `mint`.

Alerts **will not work** on sites with Rocket Loader enabled, in the current situation.

From the Rocket Loader page:
_Rocket Loader prioritises your website's content (text, images, fonts etc) by deferring the loading of all of your JavaScript until after rendering._ 
This breaks `DOMContentLoad`
https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-

``` javascript
<script type="text/javascript">
    // This is intentionaly run after dom loads so this way we can avoid showing duplicate alerts
    // when the user is beeing redirected by persistent table, that happens before this event triggers.
    Noty.overrideDefaults({
            layout: 'topRight',
            theme: 'backstrap',
            timeout: 2500,
            closeWith: ['click', 'button'],
        });
    window.addEventListener('DOMContentLoaded', function() {
        // get alerts from the alert bag
        var $alerts_from_php = JSON.parse('@json(\Alert::getMessages())');

        // get the alerts from the localstorage
        var $alerts_from_localstorage = JSON.parse(localStorage.getItem('backpack_alerts')) ?? {};

        // merge both php alerts and localstorage alerts
        Object.entries($alerts_from_php).forEach(([type, messages]) => {
            if(typeof $alerts_from_localstorage[type] !== 'undefined') {
                $alerts_from_localstorage[type].push(...messages);
            } else {
                $alerts_from_localstorage[type] = messages;
            }
        });

        for (var type in $alerts_from_localstorage) {
            let messages = new Set($alerts_from_localstorage[type]);
            messages.forEach(text => new Noty({type, text}).show());
        }

        // in the end, remove backpack alerts from localStorage
        localStorage.removeItem('backpack_alerts');
    });
</script>
```

**Comment by pxpm** [comment] 2021-02-19 12:49
You rock @martijnb92 ! Thanks for such a good explanation and debugging!  

I think there is no issue having the `overrideDefaults` outside of the event. @promatik ?

Since you found it, would you mind sending a PR with it ? This is just a `congratulations`, so you would show up as a contributor, I appreciate all the time you already spent here, if you don't have the time for it just let me know a I create the PR. You can imagine that if this is the solution, is a no brainer :) The muscle job was done by research and debug. Excelent work!

Best,
Pedro

**Comment by martijnb92** [comment] 2021-02-19 13:16
I'm currently unable to create a PR, happy to help!

What about changing `DOMContentLoaded` to `document.onreadystatechange`?
That should solve to Rocket Loader issue on the demo site.

``` javascript
// alternative to DOMContentLoaded event
document.onreadystatechange = function () {
  if (document.readyState == "interactive") {
    initApplication();
  }
}
```

**Comment by martijnb92** [comment] 2021-02-19 13:36
Confirmed working with and without Rocket Loader enabled:

``` javascript
<script type="text/javascript">
    // This is intentionaly run after dom loads so this way we can avoid showing duplicate alerts
    // when the user is beeing redirected by persistent table, that happens before this event triggers.
	Noty.overrideDefaults({
		layout: 'topRight',
		theme: 'backstrap',
		timeout: 2500,
		closeWith: ['click', 'button'],
	});
		
	document.onreadystatechange = function () {
	  if (document.readyState == "interactive") {
        // get alerts from the alert bag
        var $alerts_from_php = JSON.parse('@json(\Alert::getMessages())');

        // get the alerts from the localstorage
        var $alerts_from_localstorage = JSON.parse(localStorage.getItem('backpack_alerts')) ?? {};

        // merge both php alerts and localstorage alerts
        Object.entries($alerts_from_php).forEach(([type, messages]) => {
            if(typeof $alerts_from_localstorage[type] !== 'undefined') {
                $alerts_from_localstorage[type].push(...messages);
            } else {
                $alerts_from_localstorage[type] = messages;
            }
        });

        for (var type in $alerts_from_localstorage) {
            let messages = new Set($alerts_from_localstorage[type]);
            messages.forEach(text => new Noty({type, text}).show());
        }

        // in the end, remove backpack alerts from localStorage
        localStorage.removeItem('backpack_alerts');
	  }
	}
</script>
```

**Comment by promatik** [comment] 2021-02-19 15:26
Perfect @martijnb92 🙌
I would never guess CloudFlare could cause `DOMContentLoaded` event to not be fired.

@pxpm I think we don't even need the `DOMContentLoaded` listener.
After reading the code, I think nothing needs to be done after DOM is ready, I tested and it's working without that.

Do you think we may need that in any scenario?

**Comment by martijnb92** [comment] 2021-02-19 21:21
> @pxpm I think we don't even need the `DOMContentLoaded` listener.
> After reading the code, I think nothing needs to be done after DOM is ready, I tested and it's working without that.
> 
> Do you think we may need that in any scenario?

I'm also curious is there a specific reason for using `DOMContentLoaded`?

**Comment by pxpm** [comment] 2021-02-20 13:49
The reason is that waiting for `DOMContentLoad` will wait for the datatables script to run before handling the alerts. That way, we can be redirected without showing alerts.

**Comment by tabacitu** [comment] 2021-02-21 08:44
Hey guys - pretty nasty, thanks for raising the issue @martijnb92 . Tagging this issue as URGENT, since I know A LOT of people put their projects behind CloudFlare (us included).

Can confirm the problem happens [in our online demo](https://demo.backpackforlaravel.com/admin/article) - just click on the Clone button:
![2021-02-21 10 32 09](https://user-images.githubusercontent.com/1032474/108619828-184ec600-7430-11eb-92bd-83b7eb87704c.gif)

-----

1) @pxpm is the ListOperation the only one that needs the notifications to be triggered on `DOMContentLoaded`? 

2) Do you see any problems in changing it to `document.readyState == "interactive"` like @martijnb92 suggested [here](https://github.com/Laravel-Backpack/CRUD/issues/3540#issuecomment-782079595)?

**Comment by promatik** [comment] 2021-02-21 17:12
Hi @tabacitu!
I see a problem on using that code. We are not going to be able to use it again if we ever need. To avoid a future problem I suggest on adding a `onDomReady` Helper. I'll submit a PR with it.

**Comment by promatik** [comment] 2021-02-21 18:17
Guys just submitted what I think it's the best solution for this; https://github.com/Laravel-Backpack/CRUD/pull/3546
Let me know what you think.

**Comment by tabacitu** [comment] 2021-02-22 19:50
Just merged https://github.com/Laravel-Backpack/CRUD/pull/3551 which fixes this using @martijnb92 's suggestion above. 
Thanks again for the help @martijnb92 🙏 Super grateful.

**Closed by tabacitu** 2021-02-22 19:50 UTC
Labels: Bug, Priority: MUST, urgent
