### ISSUE TITLE
Translation / Validation messages missing at login?

### ISSUE THREAD

**Issue by nikolai-nikolajevic** [Laravel-Backpack/CRUD#4745] opened 2022-10-27 10:03 UTC
Hey guys.

When I'm trying to login and leave the inputs empty I get the error 'validation.required'
![backpack-validation-required](https://user-images.githubusercontent.com/37556958/198255351-5f8ff1ff-adcc-4932-bc57-728340eb56e2.png)

And if my login fails I get the message 'auth.failed'
![backpack-auth-failed](https://user-images.githubusercontent.com/37556958/198255527-8b375bf4-a69d-44e0-b064-fe22d41a4c7c.png)

Where can I change or set this translation for these keys?

**Comment by pxpm** [comment] 2022-10-31 11:27
Hello @nikolai-nikolajevic 

I am sorry but I could not reproduce your issue: 

![image](https://user-images.githubusercontent.com/7188159/198997060-7ca3ebc1-98d3-4ec1-b14c-b902b2b703b8.png)

What's your Backpack software version ? You can check it out with: `php artisan backpack:version`. 

You can find those translations inside `auth.php` lang file: 

![image](https://user-images.githubusercontent.com/7188159/198997450-e719dc05-6278-4ea3-ad67-a3df397bda4e.png)

I will be closing this as I don't think there is any bug here. Please feel free to continue the discussion if needed and provide me more details so that I can help you. 

Cheers

**Closed by pxpm** 2022-10-31 11:27 UTC

**Comment by nikolai-nikolajevic** [comment] 2022-11-02 12:06
You're right. That was my mistake 😇 

I overrite the base.php translations in `resources/lang/vendor/backpack/de/base.php` so laravel looked in the folder `resources/lang` for core translations. But there was nothing…

Now it's working with this structure

![grafik](https://user-images.githubusercontent.com/37556958/199485594-e675fa0e-29da-4188-afda-8e88bf7a2926.png)

**Comment by Mte90** [comment] 2025-01-22 13:54
I have the same issue, in config/backpack/crud.php in locales just italian as language and the rest of the app is localized.

On Login I have `auth.failed` and also on profile editing some alerts like this.
