### ISSUE TITLE
Remove underscores from field labels by default

### ISSUE THREAD

**Issue by slickorange** [Laravel-Backpack/CRUD#685] opened 2017-05-19 10:11 UTC
Is it possible to set the default formatting for field labels to title case?
I have many simple text fields in my models, most which names consist of two words. It feels like a lot of unnecessary work to call addField for each of these fields just to remove the underscore from the label.

**Comment by lloy0076** [comment] 2017-05-19 10:17
@tabacitu - seems to be a duplicate of https://github.com/Laravel-Backpack/CRUD/issues/642

@slickorange - maybe see the converstaion in the above linked issue?

**Comment by slickorange** [comment] 2017-05-19 10:32
Sorry, I missed that one.
Thanks!

For now I just hacked the setFromDb() method to do:
`'label'      => ucwords(str_replace('_', ' ',$field)),`

Would be nice if this could be na option.

**Closed** 2017-06-01 04:13 UTC
