### ISSUE TITLE
[Bug] removeColumn() doesn't work in setupShowOperation()

### ISSUE THREAD

**Issue by leocharrua** [Laravel-Backpack/CRUD#3108] opened 2020-08-09 13:22 UTC
# Bug report

$this->crud->removeColumn('name') don't work in setupShowOperation()

### What I did

In the modelCRUDController add the setupShowOperation method to select the columns to show in the show action:

'''
 use \Backpack\CRUD\app\Http\Controllers\Operations\ShowOperation;

 protected function setupShowOperation()
    {        
        $this->crud->removeColumn('name');
    }

'''

### What I expected to happen

The column "name" should not appear in action view.

### What happened

The "name" column is still displayed.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.3 (cli) (built: Mar  6 2019 21:53:23) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v7.22.4@30e851a2b3a2af73fba0b7f4fa22b04260db98e7

### BACKPACK VERSION:
4.1.16@4c2264f8dd52381aa891136edb61e8d4083a033d

**Comment by tabacitu** [comment] 2020-08-19 14:12
Hi @leocharrua ,

You've found a skeleton in our closet 👀 ☠️ 

Indeed, in order to keep backwards-compatibility, we've chosen to keep an old behaviour for the Show operation that... is not intuitive at all. I hope with Backpack 4.2 (due in a few months) we'll finally be changing this. I've just created PR https://github.com/Laravel-Backpack/CRUD/pull/3132 to fix this, but unfortunately, because it's a breaking change, we can't merge it right now, we have to wait for the next version (sep-oct 2020).

Let me explain what's happening:
- you'd expect `setupShowOperation()` to be run after anything that the operation itself has set up; that's what's _intuitive_;
- but it doesn't happen that way, unfortunately `setFromDb()` is called inside the `show()` method, after `setupShowOperation()` from userland has already been run;
- that means that even if you remove a column in your `setupShowOperation()`, that will be overwritten when `show()` gets called, and the column is added back;

To avoid crappy behaviour _right now_, I recommend you run something like this inside your `setupShowOperation()`:

```php
    protected function setupShowOperation()
    {
        // no longer set up columns automatically for all db columns
        $this->crud->set('show.setFromDb', false);

        // Option 1: add whatever columns you were using in the List operation
        $this->setupListOperation();

        // Option 2: 
        $this->crud->setFromDb(); // run setFromDb() yourself
        $this->crud->removeColumn('slug'); // remove the columns you don't need
    }
```

Hope the comments above explain it properly - let me know if they don't. You'll notice the same trick is shown inside the [Show Operation docs](https://backpackforlaravel.com/docs/4.1/crud-operation-show#how-to-use), though it wasn't well explained - I've now added a few more comments, hope they help.

Even though the issue is still present, I'm going to close it, because I want to continue the conversation inside PR https://github.com/Laravel-Backpack/CRUD/pull/3132. If you have the time, please also give feedback on _the real fix_, in PR https://github.com/Laravel-Backpack/CRUD/pull/3132 - I'd really appreciate your thoughts on this.

Cheers!

**Closed by tabacitu** 2020-08-19 14:12 UTC
Labels: triage
