### ISSUE TITLE
godday upload base64 image with backpack laravel ,Request Entity Too Large

### ISSUE THREAD

**Issue by abdallahmaali** [Laravel-Backpack/CRUD#1444] opened 2018-06-05 20:11 UTC
I'm  sorry to post this here but i'm really need  help, i asked same question on stackoverflow but no body helped me 

im  useing  image_base64 upload  for images with crop it's working fine on locally but  i have shared host  on godday, but when trying to upload image size no more than 4Mg   i get this error "413 Request Entity Too Large error"

this is my question on stackoverflow 
[stackoverflow question link ](https://stackoverflow.com/questions/50707814/godday-upload-base64-image-with-backpack-laravel-request-entity-too-large)

anyboday face this problem ? 

thanks in advance

**Comment by AbbyJanke** [comment] 2018-06-05 21:24
Hello @abdallahmaali the issue is with your web host. Most hosting company have a 'max_size' for uploading files for shared hosting packages and is commonly about 2mb sometimes even less. You will have to reach out to your provider to see if they can upgrade that or what plans they may have that will allow you to have a larger size.

Closing as this is not a backpack issue, but feel free to reply and I can try to help as best I can.

**Closed by AbbyJanke** 2018-06-05 21:24 UTC
Labels: triage

**Comment by o15a3d4l11s2** [comment] 2021-06-21 19:40
I know this is an old issue and partially it is related to the hosting and PHP/Apache/nginx, but I just faced the same and it made me wonder if there is a way to work around this? I am having `repeatable` with images inside and it hits the limit for request with `ModSecurity: Request body no files data length is larger than the configured limit `.

**Comment by tabacitu** [comment] 2021-06-22 05:35
Hey @o15a3d4l11s2 - I don't think so, no. Unfortunately... it's a problem at the server level, so there's nothing we can do in PHP to work around it... 🤷‍♂️ If the server says "no", it's a "no" 😅 And this is a big NO, it applies to all requests, so we can't think of a different request type or method to use... No way around it in my opinion...

**Comment by o15a3d4l11s2** [comment] 2021-06-22 08:50
Thanks for the fast response, @tabacitu. I know it is a hard limitation.

In my specific case the limitation is a POST with a big json encoded data with the images inside as base64. So what I was trying to ask is if you think there is any other way to send the images data (as binary data?), rather than part of the json data. At the moment ModSecurity interprets the request as a "request with no files", that's why the data length limit is usually much lower.

**Comment by tabacitu** [comment] 2021-06-23 07:22
Mnope... I have no quick solution for you, sorry 😅  I'm afraid the only way to _reliably_ achieve that would be to use an AJAX uploader like dropzone, which sends the images to the server before the request, and then in the request it only sends the image path.

But then again, if you use something like that, you'll need a cleanup mechanism, to delete images that people uploaded but then didn't actually use.
