### ISSUE TITLE
Revision not working

### ISSUE THREAD

**Issue by boudgeau** [Laravel-Backpack/CRUD#2432] opened 2020-02-06 17:15 UTC
# Bug report

### What I did
installed a revision as instructed in [https://backpackforlaravel.com/docs/4.0/crud-operation-revisions](url)
modified both article's controller and models as instructed
??

### What I expected to happen
to be able to see changes on the article 
??

### What happened
nothing shown
??

### What I've already tried to fix it
composer update
detect errors via debugbar
??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.8 (cli) (built: Jul 30 2019 12:44:06) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.14.0   The Laravel Framework.

### BACKPACK VERSION:
backpack/backupmanager                2.0.3     Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                         4.0.38    Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.6     Generate files for laravel projects
backpack/menucrud                     2.0.2     An admin panel for menu items, using Backpack\CRUD on Laravel 6.
backpack/newscrud                     3.0.1     An admin panel for news with categories and tags, using Backpack\CRUD on Laravel 5.
backpack/pagemanager                  2.0.5     Create admin panels for presentation websites on Laravel, using page templates and Backpack\CRUD.
backpack/permissionmanager            5.0.6     Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/settings                     3.0.2     Application settings interface for Laravel 5 using Backpack CRUD.

**Comment by pxpm** [comment] 2020-02-07 11:03
Hello @boudgeau 

Could you please share some more info what errors are you getting ? When you do Y happens X but should happen Z! It would help us alot on debugging. 

Best,
Pedro

**Comment by boudgeau** [comment] 2020-02-08 00:04
> Hello @boudgeau
> 
> Could you please share some more info what errors are you getting ? When you do Y happens X but should happen Z! It would help us alot on debugging.
> 
> Best,
> Pedro

Actually i do not get any type of error, even in the debugbar, even db fields are not been filled, seems the package is not been initiated for some reason!! any idea?
Thanks for the help

**Comment by tabacitu** [comment] 2020-02-08 16:13
Hi @boudgeau I've just double-checked, and Revisions seem to work well in my projects, and in [the online demo](https://demo.backpackforlaravel.com/admin/icon/3/revisions).

Are you sure you've followed [all the steps here](https://backpackforlaravel.com/docs/4.0/crud-operation-revisions#how-to-use)? It sounds to me like your Model might be missing the RevisionableTrait (missing step 2).

**Comment by boudgeau** [comment] 2020-02-09 09:42
> Hi @boudgeau I've just double-checked, and Revisions seem to work well in my projects, and in [the online demo](https://demo.backpackforlaravel.com/admin/icon/3/revisions).
> 
> Are you sure you've followed [all the steps here](https://backpackforlaravel.com/docs/4.0/crud-operation-revisions#how-to-use)? It sounds to me like your Model might be missing the RevisionableTrait (missing step 2).

i've double checked and did everything exactly as explained in the steps but i think the issue is with the model in app folder not extending the article model in newscrud package, i simply copied the models from newscrud package to controller and model folder in main app directory. any idea where did i go wrong!?

**Comment by tabacitu** [comment] 2020-02-09 10:23
Oh ok. Well then my next guess is that either:
1. The Controller doesn't use the ```App\Models\Article```, but ```Backpack\..\Article```;
2. The route doesn't point to your ```App\Http\Controllers\Admin\ArticleCrudController``` but to ```Backpack\..\ArticleCrudController```;

Start from the top, ```php artisan route:list```:
- which controller does the route point to?
- in the controller, which model is used?
- in that model, is the Revisionable trait used?

**Comment by tabacitu** [comment] 2020-02-09 10:24
Closing this since it's not a bug. But continue the conversation if you don't figure it out.

**Closed** 2020-02-09 10:24 UTC
Labels: Ask-It-On-Stack-Overflow, question
