### ISSUE TITLE
[Bug] select2 filter disappears upon clicking

### ISSUE THREAD

**Issue by MeerKatDev** [Laravel-Backpack/CRUD#3791] opened 2021-07-15 09:58 UTC
# Bug report

### What I did
I added a filter to a CrudController

### What I expected to happen

the select2 to open and stay visible

### What happened

a select appeared (not select2) upon clicking on the filter, then I click on the select, the select2 appears for some milliseconds and then everything closes.

### What I've already tried to fix it

I tried to simplify the select2 so that it doesn't contain other code but a static array( like in the docs)

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

```bash
$ composer update backpack/crud                                                                                                   
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
$ php artisan backpack:version                                                                                                    
### PHP VERSION:
PHP 7.4.19 (cli) (built: May 13 2021 06:28:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.49.2@d9b43ee080b4d51344b2e578aa667f85040471a2

### BACKPACK VERSION:
4.1.48@53bc6028f445f9b2ecfb8893283f6b6087539353
```

**Comment by tabacitu** [comment] 2021-07-27 05:19
Hmmm that's weird, thanks @MeerKatDev . 

Does the bug happen to you [in our online demo](https://demo.backpackforlaravel.com/admin/monster) too? If so, what browser are you using? Any console errors there?

**Comment by steeveci** [comment] 2021-09-17 09:36
I have the same issue. Select2 disappear when you try to click on it after some milliseconds.

**Comment by tabacitu** [comment] 2021-09-17 10:13
Thanks for telling us @steeveci . Reopening!

**Any chance you can record your screen doing that?** I'm hoping that will provide more information to us, so we can reproduce it and fix it. Bonus points if you can have Chrome Developer Tools open on the Console tab, when you record... maybe there's an error there providing some insight...

**Comment by pxpm** [comment] 2021-09-20 13:51
Can't reproduce this. I am sorry. 

Please, pretty please, can you post your filter definition ? Also, if it's worth, the model you are filtering by ? Also .. do you guys get any error in console ?

Did you tried in a new install ? It could (and probably is) assets not updated ? Any chance you guys can run `php artisan vendor:publish --provider=\"Backpack\\CRUD\\BackpackServiceProvider\" --tag=public --force ` ? (Note: the `--force` will overwritte all backpack assets in public folder)

Note: I am using latest chrome, latest BP and PHP 7.4.

**Comment by tabacitu** [comment] 2021-09-20 16:33
@promatik any chance you can reproduce this?

**Comment by promatik** [comment] 2021-09-22 12:57
I tried to reproduce it, with no success 😕
I tried on an new project, with new assets (Backpack 4.1.53 – new assets), and on an old project (Backpack 4.1.53 – old assets), I also tried to configure the filter a little bit, but `select2` filter is not that much configurable ...

**Comment by tabacitu** [comment] 2021-10-04 10:10
@MeerKatDev sorry - since we weren't able to reproduce this, we're going to close it for now. If you can do it again and figure out what we can do to also get it, please reply here and we'll happily reopen. Some bugs are just tricky that way... 😔 You know how it is.

Cheers!

**Comment by Priyank-laraveldev** [comment] 2022-03-11 14:37
yes it happens  as you can see in image .. my genre filter is not displaying values on filter click
![image](https://user-images.githubusercontent.com/97592992/157888153-af1b8d75-e4ad-4567-92be-b7503e96b6c2.png)

**Comment by Priyank-laraveldev** [comment] 2022-03-11 14:38
when i click on select_2 the dropdown appears for milliseconds and disappears.. does not give time for user to select

**Comment by pxpm** [comment] 2022-03-14 10:05
Hello @Priyank-laraveldev can you let me know you backpack and laravel version ? You can get them by running: `php artisan backpack:version`

**Comment by tabacitu** [comment] 2022-08-03 07:35
@Priyank-laraveldev if you can reproduce in a video, or provide more information like the version of Backpack used, like Pedro asked above, please do so. It'll help us determine where/when/how the problem occurs. Until then, I'm going to close this issue as I can't reproduce it in the latest version of Backpack. Let us know please, and we'll reopen 🙏 Thanks!

**Closed by tabacitu** 2022-08-03 07:35 UTC
Labels: Bug, could not reproduce
