### ISSUE TITLE
Stop calling yourselves "Open Source" with such a restrictive license

### ISSUE THREAD

**Issue by hackel** [Laravel-Backpack/CRUD#853] opened 2017-08-15 15:16 UTC
Your [License](https://github.com/Laravel-Backpack/CRUD/blob/master/LICENSE.md) is literally garbage.  You should be ashamed of yourselves.  I'm deeply offended that you are trying to trick potential customers into believing you are truly an Open Source project.  In case you need some education on the matter, Open Source is a movement.  It does not mean simply making your source code available on Github.  Here is the definition: https://opensource.org/osd

Key points:
* The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale.
* The license must allow modifications and derived works, and must allow them to be distributed under the same terms as the license of the original software.
* The license must explicitly permit distribution of software built from modified source code.
* The rights attached to the program must apply to all to whom the program is redistributed without the need for execution of an additional license by those parties.

Please remove any and all "open source" verbiage from your website, documentation, and any other materials.  You are selling PROPRIETARY software, period.  Even users who are licensed to use the product for free do not have the Freedom to use the software as they wish.  This is unacceptable.

Remember, Open Source is not about *money*, it's about *Freedom*.  Please try to show some small bit of respect for your potential customers.

**Comment by lloy0076** [comment] 2017-08-15 21:02
I'd invite you to discuss which parts of the license, documentation or code indicates that any parts of Backpack are "open source" in accordance with the definition you have posted.

**Comment by ConnorVG** [comment] 2017-08-15 21:18
I think it's abundantly clear that this is a paid-for package, @hackel. The only issue I have with this, *obviously* paid-for package, is that the pricing isn't very consistent depending on where you're looking.

https://laravel-news.com/laravel-backpack = 19 USD
https://backpackforlaravel.com/pricing = 39 EUR
https://laravel-backpack.readme.io/docs = 39 USD

**Comment by OwenMelbz** [comment] 2017-08-16 08:03
You can be picky with definitions but......

Yes its open source, because the source is open, everybody can see, anybody can modify/redistribute there is no enforcing. You can completely ignore the pricing if you really wanted.

It's not released under an open source license, thus your point does not really stand. Its like me slagging off Barack Obama for his presidency, yet he's not even the current president sooo is irrelevant. 

---

If however, you find somewhere on the documentation etc that the pricing/license has been *missed* or *forgotten* or *incorrect* then please feel free to point it out, and it will be corrected.

As this is clearly a toxic post and not a bug with the package - I will close the issue, this does not mean you cannot keep discussing it - however we just find its easier for users looking for answers to their problems when its not clogged up with misc content.

**Closed by OwenMelbz** 2017-08-16 08:03 UTC

**Comment by tabacitu** [comment] 2017-08-16 09:16
Hi guys,

@ConnorVG yup, you're right, thank you. Just went through all README files and documentation and changed them to the current price of 39 EUR/project. Can't do anything about the laravel-news article and other external mentions, though, but I'm sure people will check the pricing page before purchasing - they _have_ to. Plus, prices change all the time, we can't keep changing prices on external websites. Thanks for the heads-up - changed everywhere I could!

@lloy0076 , @OwenMelbz , thank you :-)

@hackel this is a controversial topic - whether open-source requires being free - and obviously it's still a hot one, where one side won't admit the other makes any sense. Like tabs vs spaces, I think the only good thing the debate does is that it lets people vent out some anger, like you did. So I won't give you reasons I don't agree - I'm sure it won't do any good. But **I'd really hate for Backpack's license to cause anybody any bad feelings.** **I see it's made you angry and I apologise for it. It was definitely not our intention. This is exactly the reason why we removed all "open-source" mentions from the docs, github and website when Backpack became paid** - as a necessary step to keep this project alive. I thought we had removed all of them, but I just checked and there was one leftover on the pricing page. That's it. Nothing in github, nothing in the license, nothing in the docs. I fail to see how that one mention angered you so much and made you think we're trying to "trick" people. But I get angry easily too, sometimes, so I'm really not the one to judge. **I've just removed that one isolated mention too - I hope this shows you that we're good people and our intention isn't to trick anybody. Keep in mind we're doing this _even if_ we don't agree with you.** We just want everybody to make good use of the software we spent thousands of hours creating. Let's stay away from unproductive disputes like this one.

I hope this reply, correction and sign of good faith brings peace to this topic. If you find any other official mentions of it being "open-source" please let us know and we'll eliminate them. But if you want to continue being part of this community (or any community), **please stop sending toxic messages like this. You could have said the same thing without offending people.** There's no reason we should put up with negative people like you. Please show respect to your fellow human beings.

Keep in mind _open-source_ is just a word. If all your anger was directed at the fact that we've used one word incorrectly _from your point of view_, I should point out that you seem to be doing the same thing, _from my point of view_:

> Your License is **literally** garbage.

Is it really?... :-)

![giphy](https://user-images.githubusercontent.com/1032474/29356046-a346111e-827b-11e7-8bde-760a68bd5bef.gif)
