### ISSUE TITLE
file not found nestedSortable/jquery.mjs.nestedSortable2.js

### ISSUE THREAD

**Issue by developerpratika** [Laravel-Backpack/CRUD#565] opened 2017-03-22 06:39 UTC
i am getting this path 
`http://genxopto.dev/vendor/backpack/nestedSortable/jquery.mjs.nestedSortable2.js`
it should be 
`http://genxopto.dev/public/vendor/backpack/nestedSortable/jquery.mjs.nestedSortable2.js`
 any body suggest me how to change this

**Comment by OwenMelbz** [comment] 2017-03-22 08:02
What makes you think it should be that?

Just publish and edit the template as you normally would for editing anything else.

As this is not a bug and a support request I'll close it to keep place tider

**Closed by OwenMelbz** 2017-03-22 08:02 UTC

**Comment by developerpratika** [comment] 2017-03-22 08:28
ok thanks

**Comment by tabacitu** [comment] 2017-03-30 12:28
Hi @developerpratika ,

I think you have your server improperly configured. It's best practice to declare your project's root as ```genxopto.dev/public```, not ```genxopto.dev```, as this will:
- prevent "public" from showing up in the URLs;
- prevent bad people from taking a peek at your PHP classes;

Hope it helps. Cheers!

**Comment by developerpratika** [comment] 2017-03-30 12:45
ya you are right thanks for you suggestion :)
can you tell me
 **how to prevent "public" from showing up in the URLs**

**Comment by tabacitu** [comment] 2017-04-03 06:06
It depends on your server software: apache/nginx. Plenty of answers on StackOverflow about that. [Here's one](https://stackoverflow.com/questions/28364496/laravel-5-remove-public-from-url). If that doesn't work, search google for "Laravel prevent public from URL". Cheers!
