### ISSUE TITLE
Column Values not Escaped

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/CRUD#534] opened 2017-03-11 19:03 UTC
Examing all the files in:

*  https://github.com/Laravel-Backpack/CRUD/tree/master/src/resources/views/columns

None of them attempt to escape any HTML.

Thus, if a customer model function returns something like "David Lloyd <lloy0076@adam.com.au>" the last bit is lost.

In fact I wrote a custom function that did the following:

```
function breakMe() {
  return "</table>";
}
```

And the view broke so badly that no laravel logs were even created (i.e. it took laravel out BEFORE the logger could log what, if anything, was wrong).

I assume this is not the expected behaviour.

To pick on https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/columns/model_function.blade.php, its code is:

```
{{-- custom return value --}}
<td>
	<?php
        echo $entry->{$column['function_name']}();
    ?>
</td>
```

I also verified that I could run Javascript (eep) like this:

```
 40     public function getUpperCaseEmail() {
 41         $email = $this->email;
 42
 43         return "<script>window.alert('hi');</script>";
 44     }
```

(and then have a column like so)

```
$this->crud->addColumn([ 
  'label' => 'break me', 
  'type' => 'model_function',
  'function_name' => 'getUpperCaseEmail']
);
```

**Comment by lloy0076** [comment] 2017-03-11 19:07
I think, at a minimum, the documentation probably SHOULD warn users that this is the case; I'd go further, though, and HTML escape the whole lot.

**Comment by MarcosBL** [comment] 2017-03-14 21:01
I can understand the frustration of finding this after much testing... but I really think it's the right way of doing it: after all, we are coders, we are supposed to work with "pure/raw" data, and show it as we want.

As a workaround, you can just create `/resources/views/columns/model_function.blade.php` in your project, and just fill it with something like this:

````php
{{-- custom return value --}}
<td>
	{{ $entry->{$column['function_name']}(); }}
    ?>
</td>
````

**Comment by lloy0076** [comment] 2017-03-14 21:27
I published the whole lot and escaped everything (which works fine for me).

My main concern is that:

- It's not documented;
- It's not necessarily secure by default.

Or to put this another way: I'd prefer to wonder why `<script>window.alert('hello');</script>` appeared escaped (i.e. in the actual output) rather than discover by accident that things aren't escaped by default.

In fact, having a look through the view files in `views/columns` *do* validate and some of them *do not*.

One could argue that they should all _at least_ be consistent :)

**Comment by jsiebach** [comment] 2017-03-14 23:44
I would've had to over-write almost all of the column types if they escaped by default.  I think in any application anywhere, the developer is responsible for escaping inputs or at least displaying them safely... this would be a huge pain to have by default in my opinion.  I think a mention in the documentation could be useful though!

**Comment by lloy0076** [comment] 2017-03-14 23:45
@jsiebach - you have a good point and some consistency would be useful too (as some of them DO and some of them DON'T) :)

**Comment by jsiebach** [comment] 2017-03-14 23:47
You may even consider a pull request - if the developers weigh in and think this would be useful - that adds a parameter to all of the columns.  Something like `"html" => "false"` that would automatically escape things instead of just printing.

**Comment by lloy0076** [comment] 2017-03-15 00:28
@jsiebach - that's a good idea; I have a few things to do at the moment but will put a suggestion up within 48 hours; I'm thinking:

- Make such a parameter available (globally, locally, per controller?);
- Standardise the way the escaping is done.

(Some of the escaping is done like:

```
<?php
$displayValue='some value'
?>
{{ $displayValue }}
```

...whilst others are:

```
<?php
echo $the_value; # which would be echo htmlspecialchars($the_value) at minimum to escape
?>
```

I'm tempted to go with the first so one can make all escaping "Blade's" problem :)

**Comment by tabacitu** [comment] 2017-03-15 06:39
Hi guys,

Thanks for mentioning this, @lloy0076 , and thank you everyone for voicing your opinions. After all, a thing like this would affect us all. 

I have to agree with @MarcosBL and @jsiebach on this one, because:
- personally, I am using the fact that they're unescaped in a bunch of places - returning spans with a certain color, or bolded text, or link to an email, small things like that that make the Admin's life easier; so for me... "It's not a bug, it's a feature" :-)
- I think that this kind of security matter should be treated before storing in the db, not when displaying; I don't know what your use case is, but I strongly recommend you use Requests to filter out any potentially dangerous scripts from getting to your db; always better to cut the problem at the root, I say; this would also solve the problem for anywhere else you show those values;
- considering 
  - what column types are unescaped (```model_function```, ```model_function_attribute```, ```select```, ```select_multiple```) - they're either model functions (that require coding) or very very simple columns, usually string/varchar, that don't actually fit long scripts;
  - that filtering should have happened already before storing in the DB
  - that this is an admin panel, so we should trust our users to a certain degree 
 
  I think the risk is minimal.

But it must have been frustrating for you to find out by yourself and see it's not mentioned anywhere. I'm sorry for that, and I do agree it should be mentioned in the docs. I've just updated them - I don't want anyone else to share your pain. I'm not that good at writing public docs, sorry for that.

I'll close the issue because it's closed from my point of view. But please reply to convince me otherwise if you think I'm wrong. It's been known to happen :-)

Cheers!

**Closed by tabacitu** 2017-03-15 06:39 UTC
