### ISSUE TITLE
Is there any way I can add an argument to addField?

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#743] opened 2017-06-14 01:47 UTC
I have this in my model.

```
    public function center_room($center_id)
    {
        // return rooms which belongs to the center
        return Room::where('center_id', $center_id)->get();
    }

```

And I want to use it in addField, but I am not sure how to add an argument. 

            $this->crud->addField([
                'name' => 'room_id',
                'label' => 'Room ID',
                'type' => 'select2',
                'entity' => 'center_room',
                'attribute' => 'name',
                'center_id' => $this->user->center_id,
                'model' => 'App\Models\Room'
            ])->beforeField('title');

**Comment by lloy0076** [comment] 2017-06-14 13:27
Not without fiddling with the code a little.

You could probably put the `center_id` into the session and then extract it from the session though...

**Comment by tabacitu** [comment] 2017-06-15 13:55
Hi @shinokada , 

If you pass ```center_id``` to addField() like that, it will be available in ```select2.blade.php``` as ```$field->center_id```. You can overwrite the select2 field to take advantage of that, or maybe create a different field type for this particular purpose. Say... ```select2_room```.

Hope it helps. Cheers!

PS. This is not a bug, nor a proposal, so I'll close the issue.

**Closed by tabacitu** 2017-06-15 13:55 UTC
