### ISSUE TITLE
[Bug] relationship field with ajax when editing does not allow searching

### ISSUE THREAD

**Issue by DanielKimmich** [Laravel-Backpack/CRUD#3032] opened 2020-07-15 00:56 UTC
# Bug report
I am using the "relationship" field inside a "repeatable" field, with the "ajax" functionality set to true. The problem I have is that when editing the data, the search cannot be entered, but the option to select comes out. That does not happen when a new items is added.

### What I did
My code
```
                [   'name'  => 'data8',
                    'label' => trans('contact.address.division'),
                    'type'  => 'relationship',
                    'wrapper' => ['class' => 'form-group col-md-6'],
                    'attributes' => ['id' => 'address_division'],
                    'model' => 'App\Models\WorldDivision', // foreign key model
                    'entity'    => 'addresses',
                    'attribute' => 'name',
                    'ajax' => true,
                    'multiple' => false,
                    'data_source'  => url($this->crud->route.'/fetch/division'),
                    'dependencies'  => ['data10'], //this select2 is reset to null
                    'minimum_input_length' => 0, // minimum before querying results
                    'default' => Config::get('settings.contact_division'),
                    'include_all_form_fields'  => false,
                ],

```
### What I expected to happen
Attachment screenshot:
In add items:
![image](https://user-images.githubusercontent.com/44840413/87490646-90444a80-c61c-11ea-96fa-d82a1433a81f.png)

In existing modify:
![image](https://user-images.githubusercontent.com/44840413/87490671-a3571a80-c61c-11ea-9f63-89a5e5226b6c.png)

### PHP VERSION:
PHP 7.4.7 (cli) (built: Jun  9 2020 13:36:15) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.20.0@682ea946bc136aa686d5a64940ab3d4a24d5a613

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323

**Comment by pxpm** [comment] 2020-07-17 12:59
Hello @DanielKimmich 

I am afraid I was not able to reproduce your issue. 

What I did:

- Added a repeatable field with a relationship field inside.
```php
[    // Relationship
                'label'     => 'Relationship',
                'type'      => 'relationship',
                'name'      => 'products',
                'entity'    => 'products',
                'tab'       => 'Relationships',
                'ajax'      => true,
                'multiple' => false,
                'minimum_input_length' => 0,
                'data_source'       => backpack_url('monster/fetch/product'),
            ],
```

![Screenshot_13](https://user-images.githubusercontent.com/7188159/87788694-b09b2180-c835-11ea-9964-ff01fb476ee5.png)

Anything more I should be looking at? 

Best,
Pedro

**Comment by DanielKimmich** [comment] 2020-07-17 15:04
Thank you very much, I found the problem.
When you define "'attributes' => ['id' => 'address_division'],", the search option is removed and passed to a select.
I leave to you the analysis if that corresponds to a bug or not.

For now, I'm deleting the attribute.
Regards,

**Comment by pxpm** [comment] 2020-07-20 08:58
Indeed @DanielKimmich . `ID's` does not play well with repeatable. I suggest you to use some other `data-attribute` to store anything extra you need in field. 

Going to close this. 

Thanks, Pedro

**Closed by pxpm** 2020-07-20 08:58 UTC
Labels: needs-more-info
