### ISSUE TITLE
Undefined array key "attribute"

### ISSUE THREAD

**Issue by AlexKomMsk** [Laravel-Backpack/CRUD#4885] opened 2023-01-06 14:52 UTC
I'm getting an error when adding a relation field id (belongsTo relation). I add 
`CRUD::field('exchange_id');`
to setupCreateOperation
I open the resource editing page and get an error:
**Undefined array key "attribute" (View: vendor\backpack\crud\src\resources\views\crud\fields\select.blade.php)**
This field in migration
`$table->foreignIdFor(Exchange::class)->constrained()->cascadeOnDelete();`
### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.27@e1afe088b4ca613fb96dc57e6d8dbcb8cc2c6b49

### BACKPACK VERSION:
5.4.12@6ff47ed84735c672cf08c763c633419beea8e392

**Comment by pxpm** [comment] 2023-01-08 18:51
Hello @AlexKomMsk thanks for the report.

Unfortunately I was not able to reproduce your issue. 

This is my relation and field
```php
// model
public function user()
    {
        return $this->belongsTo(\App\User::class);
    }
// crud controller
CRUD::field('user_id');
```

And the generated field: (you can see it by doing: `dd(CRUD::fields())` after the field definition)
```php
"user_id" => [
    "name" => "user_id"
    "entity" => "user"
    "label" => "User"
    "relation_type" => "BelongsTo"
    "model" => "App\User"
    "attribute" => "name"
    "multiple" => false
    "pivot" => false
    "type" => "select"
  ]
```

![image](https://user-images.githubusercontent.com/7188159/211213059-859ed32b-db09-4f90-812a-023a459961f8.png)

The problem that I think may be happening is the relation definition. In my example, since I didn't provide the second parameter of `belongsTo()` relation, Laravel assumes my column name is `user_id`, inferred from the relation name. 

In case you have a `public function exchange() { ...->belongsTo('smt'); }` it will assume the column name in database to be `exchange_id`. 

If you have `entity => false` is probable that this code: https://github.com/Laravel-Backpack/CRUD/blob/f77c74c1d6ae8b0dedf825f74c6c1aea84ba1992/src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php#L133 is not returning the proper `entity` for you.

Let me know how it goes.

Cheers

**Comment by AlexKomMsk** [comment] 2023-01-12 20:42
Hello @pxpm.

When I do dd(CRUD::fields()) I don't see the attribute key like you do. Here is my output
```
   "exchange_id" => array:8 [▼
     "name" => "exchange_id"
     "entity" => "exchange"
     "label" => "exchange"
     "relation_type" => "BelongsTo"
     "model" => "App\Models\Exchange"
     "multiple" => false
     "pivot" => false
     "type" => "select"
   ]
```

My relation in the RatingEchange model is written like this

```
     public function exchange(): BelongsTo
     {
         return $this->belongsTo(Exchange::class);
     }
```

The RatingEchange model has fields
```
id
exchange_id
```

**Comment by pxpm** [comment] 2023-01-13 02:11
Hey @AlexKomMsk thanks for the reply. 

The attribute should be defined here: 
https://github.com/Laravel-Backpack/CRUD/blob/146a08082ebf3ad2f88df3e18c9735ad57ff19e5/src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php#L182

Can you add some `dump()` and `dd()` there to see where we are missing you, and why attribute is not set ? 

Cheers

**Comment by pxpm** [comment] 2023-01-20 01:28
Closing this, thanks for the report 🙏 

Please feel free to continue the conversation, we can re-open if needed 👍 

Cheers

**Closed by pxpm** 2023-01-20 01:28 UTC
Labels: triage

**Comment by AlexKomMsk** [comment] 2023-01-29 12:00
dd return
array:5 [▼
  "name" => "exchange_id"
  "entity" => "exchange"
  "label" => "Exchange"
  "relation_type" => "BelongsTo"
  "model" => "App\Models\Exchange"
]
