### ISSUE TITLE
[4.0.9] Header and Sidebar UI Bug

### ISSUE THREAD

**Issue by drionix** [Laravel-Backpack/CRUD#2153] opened 2019-10-13 13:35 UTC
# Bug report

### What I did

Test Backpack in responsive mode (mobile screen) and scroll down while sidebar is opened.

### What I expected to happen

Header and sidebar position is fixed

### What happened

Sidebar is fixed, while header scrolled out of view

This is before scroll down
![Cap1](https://user-images.githubusercontent.com/14888588/66716478-4a8df380-edf8-11e9-85f2-a158250014f4.JPG)

This is after scroll down
![Cap2](https://user-images.githubusercontent.com/14888588/66716479-4d88e400-edf8-11e9-9a3e-39d4862c6522.JPG)

There are 2 weird UI in the image, 1 in the header section (losing header nav), and 1 below the sidebar (sidebar is not stretched to the bottom)

### What I've already tried to fix it

Add `.header-fixed` to 'body_class' in `config/backpack/base.php` after inspecting the bundle.css, specifically this part:

```
@media (max-width: 991.98px)
body:not(.header_fixed) .app-header {
    position: relative;
}
```
and this part
```
@media (max-width: 991.98px)
.app-header {
    position: fixed;
    z-index: 1020;
    width: 100%;
    text-align: center;
    background-color: #fff;
}
```
However, it is not working

### Backpack, Laravel, PHP, DB version
Backpack 4.0.9
Laravel 6.2
PHP 7.2

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment] 2019-12-02 11:04
Hello @drionix 

Thanks for reporting it. Sorry for late response :|

I think this is already fixed, i could NOT reproduce it and i recall something was merged related to this stuff.

Please if the problem persists for you make sure you have the last version, clear caches a re-open if needed. I am wrong sometimes :+1: 

Best,
Pedro

**Closed by pxpm** 2019-12-02 11:04 UTC
Labels: triage
