### ISSUE TITLE
[Bug] Inline create "Add" button doesn't show

### ISSUE THREAD

**Issue by wahyunurarizky** [Laravel-Backpack/CRUD#4248] opened 2022-03-04 04:14 UTC
# Bug report

### What I did

I'm using backpack pro and try to make field with type relationship and also inline create

### What I expected to happen

it should be show me a modal and button for inline create

### What happened

it does'nt showed up

### What I've already tried to fix it

I already try to figured it in blade

### Is it a bug in the latest version of Backpack?
yes

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### LARAVEL VERSION:
v9.1.0@ca7ddd4782f120ae50569d04eb9e40e52f67a9d9

### BACKPACK VERSION:
5.0.9@d995de2026b6fcb1b13b469f371c929c29d1c1cc

**Comment by ikblmul** [comment] 2022-03-04 04:19
i have same problem too with backpack\pro.

my add button not appear in relationships fields

**Comment by tabacitu** [comment] 2022-03-04 07:52
Hey guys,

I just checked and I see it's working in [our online demo](https://demo.backpackforlaravel.com/admin/monster/create#relationship) - so I'm pretty sure it's not a bug, but misconfiguration. 

To help you out, please post your addField statement. Also, make sure you've used [the InlineCreate operation](https://backpackforlaravel.com/docs/5.x/crud-operation-inline-create#about-1) on the correct Controller (the one being created in the modal).

Cheers!

**Comment by pxpm** [comment] 2022-03-04 15:56
@ikblmul and @wahyunurarizky thanks for the report.

I've just tested this myself and it's working fine, so I guess is some implementation issue or you guys found some bug that slipped us. 

Anyway I am going to close this, feel free to do as @tabacitu suggested and post your field definition etc so we can better help you guys. 

This is closed but we receive notifications, so feel free to keep the discussion going. Otherwise you can reach out in https://gitter.im/BackpackForLaravel/Lobby there are other devs there and people usually help each other! 👍 

Cheers

**Closed by pxpm** 2022-03-04 15:56 UTC
Labels: triage

**Comment by stryfe200fps** [comment] 2022-04-08 11:25
#Models

```
class Video extends Model
{
 public function tags()
    {
       return $this->hasMany(Tag::class);
    }
}
```

```
class Tag extends Model
{
    public function video()
    {
        return $this->belongsTo(Video::class);
    }
}
```

#Controllers

```
class VideoCrudController extends CrudController
{
   CRUD::addField([
            'type' => 'relationship',
            'name' => 'tags',
            'ajax' => true,
            'inline_create' => true 
        ]);
}
```

```
class TagCrudController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\CreateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\InlineCreateOperation;
}

```
#Migrations

```
      Schema::create('tags', function (Blueprint $table) {
            $table->id();
            $table->foreignId('video_id');
            $table->string('name');
        });

```

```
   Schema::create('videos', function (Blueprint $table) {
            $table->id();
            $table->string('name');
        });
```


Is my configuration correct? I tried it using many to many and it works, I'm wondering why 1-N relationship is not working. I just started using this package and it's really amazing.

**Comment by pxpm** [comment] 2022-04-08 14:25
@stryfe200fps that relationship (HasMany) have some caveats, for it to use the `inline_create`, the connected key needs to be nullable, otherwise Backpack can't create the related model. https://backpackforlaravel.com/docs/5.x/crud-how-to#hasmany-1-n-relationship

Anyway the best way to inline-create an HasMany is using the relationship with `subfields` also described in the link I shared.

Cheers

**Comment by dauvray** [comment] 2023-07-31 13:04
Hello, I have the same issue.
But when i change at line 344 in fetch_or_create.blade.php

$modal.modal('show');

Adding 'show' make it working.
