### ISSUE TITLE
[Bug] browse_multiple contents lost on validation failure related to other fields

### ISSUE THREAD

**Issue by tibbsa** [Laravel-Backpack/CRUD#4123] opened 2022-01-25 19:12 UTC
# Bug report

### What I did

Created a CRUD form which contains a series of fields including, for example, ```title``` and ```attachments```.

```title``` is a text field, and is required.
```attachments``` is a browse_multiple field, and has no validation rules specified whatsoever. 

(The ```attachments``` field may or may not contain any selections on any given create or update operation, i.e. it is entirely optional at all phases.)

### What I expected to happen

After submitting the form, if ```title``` validation failed, the contents of the ```browse_mutliple``` field would be unchanged.

### What happened

When validation fails on ```title```, the form reloads without any of the contents of the existing ```browse_mutliple``` field. The attached items are lost whenever a validation error occurs on another field.

### What I've already tried to fix it

I've looked at the various existing issues regarding validation of multiple upload fields (including #4073/#4080 and #3781), but these seem to slightly miss the mark in that I'm not trying to validate the ```browse_multiple``` field.  But perhaps they point to the source of some issues re: whether or not 'unchanged' fields get re-POSTed.

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
PHP 7.4.3 (cli) (built: Nov 25 2021 23:16:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v8.78.1@16359b5ebafba6579b397d7505b082a6d1bb2e31

### BACKPACK VERSION:
4.1.63@c3a09d64090cc15c51df7898889d763aaa335260
```

**Comment by pxpm** [comment] 2022-01-26 11:38
Hello @tibbsa 

I think that is problem with our `old()` mechanism that is fixed in 4.2 already but it's totally a breaking change for 4.1. 

In 4.2 I cannot reproduce your issue: https://recordit.co/3XRtFnWTlP but I could in 4.1.

So, I will leave this open until I got some time to look at this field and try to fix it in a non-breaking way in 4.1, in the meanwhile if you are going to fix this yourself and are willing to send a PR for it, we would really appreciate. 

Sorry can't be more help at this moment.

Best,
Pedro

**Comment by pxpm** [comment] 2022-02-08 15:51
Hey @tibbsa good news.

We launched today Backpack v5 that has this fix as I mentioned. Check out the [upgrade guide](https://backpackforlaravel.com/docs/5.x/upgrade-guide)

There are some breaking changes, but it should not take much time to upgrade. 

I will be closing this issue, let me know if you have some trouble upgrading. 

Wish you the best,
Pedro

**Closed by pxpm** 2022-02-08 15:51 UTC
Labels: Minor Bug

**Comment by tibbsa** [comment] 2022-02-08 17:54
@pxpm: Upgrading will be a little trickier with half the project now in a closed source repo, which I can't as easily clone it to develop the local patches needed. In my case, #3480 is a blocking issue for screen reader accessibility, and so now those label issues span both backpack/crud and backpack/pro.... But I will see what can be done.

**Comment by pxpm** [comment] 2022-02-08 18:13
Hey @tibbsa that label issue is on the roadmap to be addressed. We take acessibility very consciouly here. It just need a little tinkering on how to implement, because `label for` is supposed to have a matching ID, so we need to think in a way to assure we don't have duplicate id's even if inside repeatable fields, or inside inline modals etc. Maybe we need to resort to random id's or something alike to guarantee uniqueness in all those scenarios.

Now that we launched we have more time to work on this "minor" issues. We will be working in some of the most requested features as per the pool @tabacitu created and some others we see fit. 

I get the trouble you are in, I will talk @tabacitu about this to see what kind of priority he thinks this should be given, maybe he thinks this is more important than I do, don't get me wrong, I get the importance of it, but also think there are other things more important left to do. But if @tabacitu thinks different he's usually rigth about it, so ... lets see. 

About the fix for this in 4.1 I don't think it will ever happen, it was one of the big breaking changes from 4.1 -> v5.

Sorry can't be more help here for the moment.

Pedro

**Comment by tibbsa** [comment] 2022-02-08 18:27
If I understand, it's not possible to 'git clone' backpack/pro now, is it? I could "fix" it for my current use case -- we are not using ```repeatable```'s -- but tracking upstream and re-applying that branch when backpack/pro upgrades come along is the trick.

**Comment by pxpm** [comment] 2022-02-08 18:37
Indeed not, but if you have the licence purchased and have some special need regarding that, please shout an email to @tabacitu explaining your situation, he migth be able to work something out until we fix that label issue. 

hello@backpackforlaravel.com

Cheers
