### ISSUE TITLE
[Bug] Auth routes without an email are breaking route:list command

### ISSUE THREAD

**Issue by danilopolani** [Laravel-Backpack/CRUD#3256] opened 2020-10-10 18:11 UTC
# Bug report

### What I did
Setup Backpack on a project where Users have no email field and `setup_auth_routes => true`.

### What I expected to happen
The `php artisan route:list` should work properly.

### What happened
The `php artisan route:list` command returns an error because the Users have no email field, but Backpack registers the `reset-password` routes that use the following snippet in the construct (`Http\Controllers\Auth\ResetPasswordController.php`):

```php
if (! backpack_users_have_email()) {
    abort(501, trans('backpack::base.no_email_column'));
}
```

This is the source of the error.

**TL;DR**  

You can't run `php artisan route:list` if you have no `email` field but `auth_routes => true`.

### What I've already tried to fix it
I got it working by disabling `setup_auth_routes` and manually registering this inside `routes/backpack/custom.php` before everything else:

```php
Route::group([
  'namespace'  => 'Backpack\CRUD\app\Http\Controllers',
  'middleware' => config('backpack.base.web_middleware', 'web'),
  'prefix'     => config('backpack.base.route_prefix'),
], function () {
  Route::get('login', 'Auth\LoginController@showLoginForm')->name('backpack.auth.login');
  Route::post('login', 'Auth\LoginController@login');
  Route::get('logout', 'Auth\LoginController@logout')->name('backpack.auth.logout');
  Route::post('logout', 'Auth\LoginController@logout');
});
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.11 (cli) (built: Oct  1 2020 20:11:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.9.0@8a6bf870bcfa1597e514a9c7ee6df44db98abb54

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877
```

**Comment by pxpm** [comment] 2020-10-11 09:52
Hello @danilopolani,

I think that is expected to fail if you are using backpack auth without an email column, the auth was built to have an email column.

You can also configure what column backpack uses for authentication in `config/backpack/base.php` setup `'authentication_column' => 'email',` 

I am going to close this as I think it's not a bug, but feel free to re-open in case I am wrong. 

Best,
Pedro

**Closed by pxpm** 2020-10-11 09:52 UTC
Labels: triage

**Comment by danilopolani** [comment] 2020-10-11 11:07
Ehy @pxpm ,
I already have `'authentication_column' => 'username'` and, in fact, the reset password links do not appear anywhere, but the routes are still registered and this is causing the error when running `php artisan route:link` (due to the middleware aborting), but the whole app is just working fine.

Yesterday I [submitted a PR to solve this](https://github.com/Laravel-Backpack/CRUD/pull/3257), an easy solution that does not break any logic and let just everything else work as expected, please consider it.

If you don't like that solution there should be at least a disclaimer in [this docs page (Login with username instead of email)](https://backpackforlaravel.com/docs/4.1/base-how-to#login-with-username-instead-of-email) to inform users to disable `auth_routes` if not using `email` field and manually copy'n'paste them in their `custom.php` file.  
I don't really like this 2° solution because it's "over engineered" and it could be annoying for the user to register something manually that already exists.

Let me know what you think :)

**Comment by pxpm** [comment] 2020-10-12 08:56
Hello @danilopolani 

I think now I agree with you. I just don't agree with the proposed solution. 

I will let you know my thoughts on the PR thread. 

Best,
Pedro
