### ISSUE TITLE
True / false type accessor is lost after using related model in button

### ISSUE THREAD

**Issue by timbertens** [Laravel-Backpack/CRUD#1898] opened 2019-06-02 12:00 UTC
# Bug report
Very weird and I'm not 100% sure this is a bug or that I'm doing something terribly wrong.

### What I did:
In a custom 'line' button there are some actions defined.  The availability of the actions are sometimes depending on counts or the existence of attributes.  Some of those attributes are database columns, some are accessors (that work fine). Some of these attributes are eg. text and some are booleans.  
After accessing the attribute on a related model, the boolean attributes are for some reason lost on $entry

```
        #invoice = {{$entry->number_of_invoices}}<br/>
        eligible for rollback? => {{$entry->is_eligible_for_roll_back}}
       
        @if($entry->instance->invoice_delivery_to_accountant_type_id)
          <li><a href="#" data-toggle="modal" data-target="#deliver-to-accountant-{{ $entry->id }}">Deliver all to accountant... <span 
            class="badge @if($entry->last_delivered_to_accountant_at) label-success @else label-warning @endif"
            @if($entry->last_delivered_to_accountant_at) title="Last delivered to accountant at {{$entry->last_delivered_to_accountant_at->isoFormat(Config::get('backpack.base.default_datetime_format'))}}"  @endif
            >{{$entry->invoices()->count()}}</span></a></li> 
        @else 
          <li class="disabled"><a href="#">Deliver all to accountant...</a></li>
        @endif 

        #invoice = {{$entry->number_of_invoices}}<br/>
        eligible for rollback? => {{$entry->is_eligible_for_roll_back}} 
``` 

{{$entry->number_of_invoices}} = returns a number using an accessor
{{$entry->is_eligible_for_roll_back}}  = return a boolean using an accessor

### What I expected to happen:
Both {{$entry->number_of_invoices}}  and {{$entry->is_eligible_for_roll_back}}  should be the same before and after the conditional

### What happened:
{{$entry->number_of_invoices}} is the same value before and after but {{$entry->is_eligible_for_roll_back}} has lost it value after the conditional

### What I've already tried to fix it:
when using an eg $entry->created_at instead of $entry->instance->invoice_delivery_to_accountant_type_id (which is of course functionally not correct anymore) both values before and after the conditional remain the same

#### PHP VERSION:
PHP 7.3.1-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jan 13 2019 10:19:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.24.3~linux-x64-non_zts73, https://blackfire.io, by Blackfire

#### BACKPACK PACKAGES VERSION:
backpack/base                           1.1.4              
backpack/crud                           3.6.21             
backpack/generators                     1.2.7              
eduardoarandah/backpacklogviewer        1.0.5.1            
laravel/framework                       v5.8.19            

#### MYSQL VERSION:
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

**Comment by pxpm** [comment] 2019-06-03 10:28
could you try setting them to temp variables on top? like `$is_elegible_for_rollback ={{$entry->is_eligible_for_roll_back}}` ?

**Comment by timbertens** [comment] 2019-06-03 12:28
yes, I expected it to work and it did when I tested
Question remains of course, why does the original version happen?

**Comment by timbertens** [comment] 2019-06-12 09:27
Anybody else any input on this? Still not sure if it is a backpack issue or not..

**Comment by pxpm** [comment] 2019-06-12 11:30
do you have those acessors on laravel model $appends ?

**Comment by timbertens** [comment] 2019-06-12 12:36
yes, they are

**Comment by pxpm** [comment] 2019-06-12 13:00
i'm not sure, but i think it might be because your model is beeing "re-builted" when you load some relational data, like $model->instance or $model->invoices() and somehow the acessors get lost ?

It's indeed very strange that some accessors work and others don't. 

If you have time, and want to try to debug this, try loading the entry with the relationships you need, and instead of $entry->xxx use $entry['xxx'], e.g: `$entry['instance']->field_you_would_like_to_get`

I think this might solve your problem.

**Comment by timbertens** [comment] 2019-06-19 10:33
thanks for your reply,  I cannot however get your suggestion to work.  The requested accessor (is_elegible_for_rollback) in the base model itself (bill_run) not a related one ...

When I output the full $entry variable at that point in the button, the property is_elegible_for_rollback has changed to false.  Outputting it earlier in the button that same property is true.  Of course that is just a confirmation of the same problem.

I can fix it easily by assigning that value to a local $is_elegible_for_rollback variable, and use that variable going onwards, but I don't want ... Maybe @tabacitu needs to have a look a this?

**Comment by tabacitu** [comment] 2019-06-21 07:17
@timbertens the way you present it it's indeed very weird. But maybe the problem is not with the accessor, but with the _blade echoing_? If ```$entry->is_eligible_for_roll_back``` is a boolean, using ```{!! !!}``` or ```{{ }}``` alone to output its value is NOT intuitive.

Because:
- ```{{ false }}``` and ```{!! false !!}``` - will output nothing
- ```{{ true }}``` and ```{!! true !!}```- will output ```1```

Since I see you're outputting the ```{{ $entry->is_eligible_for_roll_back }}``` I think that may be the root cause. So **maybe something like ```{{ (false) ? 'true' : 'false' }}``` will fix it for you?**

Does the problem occur if you do
```diff
        #invoice = {{$entry->number_of_invoices}}<br/>
-        eligible for rollback? => {{$entry->is_eligible_for_roll_back}}
+        eligible for rollback? => {{ ($entry->is_eligible_for_roll_back) ? 'true' : 'false' }}
       
        @if($entry->instance->invoice_delivery_to_accountant_type_id)
          <li><a href="#" data-toggle="modal" data-target="#deliver-to-accountant-{{ $entry->id }}">Deliver all to accountant... <span 
            class="badge @if($entry->last_delivered_to_accountant_at) label-success @else label-warning @endif"
            @if($entry->last_delivered_to_accountant_at) title="Last delivered to accountant at {{$entry->last_delivered_to_accountant_at->isoFormat(Config::get('backpack.base.default_datetime_format'))}}"  @endif
            >{{$entry->invoices()->count()}}</span></a></li> 
        @else 
          <li class="disabled"><a href="#">Deliver all to accountant...</a></li>
        @endif 

        #invoice = {{$entry->number_of_invoices}}<br/>
-        eligible for rollback? => {{$entry->is_eligible_for_roll_back}} 
+        eligible for rollback? => {{ ($entry->is_eligible_for_roll_back) ? 'true' : 'false' }}
```

Or maybe doing a ```dd()``` at the end so we're sure that's not the cause?

Cheers!

**Comment by timbertens** [comment] 2019-06-21 08:03
Thanks for your response! 
I'm afraid it is not an issue with the output in blade itself, when looking at the $entry object before and after the condition this is its contents

**BEFORE** 

`{"id":652,"started_at":"2019-05-21 17:16:19","completed_at":"2019-05-21 17:16:24","created_at":"2019-05-21 17:16:19","updated_at":"2019-05-21 17:55:16","instance_id":4,"imported_id":null,"last_downloaded_for_print_at":null,"last_delivered_by_email_at":null,"last_delivered_to_accountant_at":null,"failed_at":null,"roll_back_started_at":null,"roll_back_completed_at":null,"invoice_date":"2019-05-20T22:00:00.000000Z","number_of_invoices":6,"is_rolled_back":false,"is_latest_non_rolled_back":true,"is_eligible_for_roll_back":true}`


**AFTER** 

`{"id":652,"started_at":"2019-05-21 17:16:19","completed_at":"2019-05-21 17:16:24","created_at":"2019-05-21 17:16:19","updated_at":"2019-05-21 17:55:16","instance_id":4,"imported_id":null,"last_downloaded_for_print_at":null,"last_delivered_by_email_at":null,"last_delivered_to_accountant_at":null,"failed_at":null,"roll_back_started_at":null,"roll_back_completed_at":null,"invoice_date":"2019-05-20T22:00:00.000000Z","number_of_invoices":6,"is_rolled_back":false,"is_latest_non_rolled_back":false,"is_eligible_for_roll_back":false,"instance":{"id":4,"name":"Bene.be bvba","address_1":"Oswald Ponettestraat 56","address_2":null,"postcode":"9600","city":"Ronse","country_id":56,"vat":"BE0543443389","phone":null,"fax":null,"email":"info@bene.be","website":"www.bene.be","logo_path":"instance_logos\/7415d317fddbc48a9e12e6b918d8d374.jpg","currency_id":1,"created_at":null,"updated_at":"2019-05-21 ....`

Apart from the fact that afterwards it contains the related objects now, it also has a different boolean value for 
- "is_latest_non_rolled_back" -> before it is true, afterwards it is false 
- "is_eligible_for_roll_back" -> before it is true, afterwards it is false

"number_of_invoices" that is also an accessor still holds 6 (which is correct)

**Comment by tabacitu** [comment] 2019-06-24 05:53
Wow. Very weird indeed then. I can't see anything inside the conditional that would change the value. Maybe an accessor does ```$this->is_eligilble_for_rollback = false``` by mistake? I think your only two options would be to:

A) use temp variables like @pxpm suggested [here](https://github.com/Laravel-Backpack/CRUD/issues/1898#issuecomment-498202529)

B) delete everything inside the if conditional, see if that fixes it; if so, introduce everything one-by-one, see when the value gets modified - might be inside an accessor;

Sorry I can't be of more help.

PS. I can confirm it's not a Backpack-related bug, so I'll close this issue. Feel free to keep the conversation going, though.

**Closed by tabacitu** 2019-06-24 05:53 UTC
Labels: triage

**Comment by timbertens** [comment] 2019-06-29 12:39
Thanks for the answer and yep, it's no Backpack issue nor an Laravel one, it's me.  Who else :-)
The accessor `$this->is_eligilble_for_rollback` uses another accessor to determine its value and that one had an error.  

I was comparing objects like this 
```
        if ($this == ($this->nonRolledBack()->latest()->first()) {
            return true;
        } else {
            return false;
        }
```

This worked fine, until I loaded the relation 'instance' in that button.  

Changing the code to

```
        if ($this->is($this->nonRolledBack()->latest()->first())) {
            return true;
        } else {
            return false;
        }
```
now works fine in all situations 

A bit more patience and the page below helped to solve the issue. 
https://stackoverflow.com/questions/54152701/eloquent-orm-why-does-laravel-not-think-these-two-objects-are-the-same
