### ISSUE TITLE
[Bug] Pass 'save_actions' operation setting to the 'array_filter' without validation on 'null'

### ISSUE THREAD

**Issue by mialex** [Laravel-Backpack/CRUD#3321] opened 2020-11-11 08:14 UTC
# Bug report

### What I did

I have a custom action in my controller that uses **update** operation. In this case, I don't use `\Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation` in my controller as it's a completely custom action

### What I expected to happen

I expect to open the edit page where I can do my custom things.

### What happened

I get an error in the next trait `\Backpack\CRUD\app\Library\CrudPanel\Traits\SaveActions`:

```
array_filter() expects parameter 1 to be array, null given
./vendor/backpack/crud/src/app/Library/CrudPanel/Traits/SaveActions.php (line 52)
```

This happens due to the missed validation in this method:

```
    public function getSaveActionByOrder($order)
    {
        return array_filter($this->getOperationSetting('save_actions'), function ($arr) use ($order) {
            return $arr['order'] == $order;
        });
    }
```
In the rest of places of this trait there is  the next logic, shic is correct:

```
$this->getOperationSetting('save_actions') ?? [];
```

But in this specific case, there is no validation if it's an array or no. That causes the error to be thrown.

Additionally, in the method `\Backpack\CRUD\app\Library\CrudPanel\Traits\SaveActions::performSaveAction` it would be also a good idea to have an array by default.

### What I've already tried to fix it

I've added default option to the config file: `backpack.crud.operations.update.save_actions` or use `$crud->setupDefaultSaveActions()`.
Also, going to investigate what has been changes as I see there are many changes under the SaveAction logic were done in the latest 4.1, as I have some customization for the save actions

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 

### LARAVEL VERSION:
v7.29.2@0fb15ae253c3a043f2c5cbf9641427a7646ea77a

### BACKPACK VERSION:
4.1.26@ae68ca24844929ac38d2e792197551e823c43570

**Comment by pxpm** [comment] 2020-11-11 12:42
Hey @mialex 

Could you provide me your method code ? I think I don't fully understand what you mean by `... i have a custom action that uses update operation but I am not using UpdateOperation` ? 

Best,
Pedro

**Comment by mialex** [comment] 2020-11-12 07:50
When I set up the rote, I define it with the **update** operation: `Route::post('update-list', ['uses' => "...", 'operation' => 'update',]))`
In the controller, I don't use `\Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation` trait. I use there only `\Backpack\CRUD\app\Http\Controllers\Operations\ListOperation` trait.

I described the issue just to show the error, I don't ask why my code does not work, it's working and I solved my case. I just wanted to point you to the issue I found with the `array_filter`. The value is not type-casted before it's passed. In other places where you get the same setting `$this->getOperationSetting('save_actions')` there is validation for the type  `$this->getOperationSetting('save_actions') ?? [];`. In the case I've described, there is no such validation and it's possible when `$this->getOperationSetting('save_actions')` returns `null` instead of an array and then `null` is passed to the `array_filter` function. To fix that it's possible just to replace it with the `$this->getOperationSetting('save_actions') ?? [];`, also would be great to replace it in the `\Backpack\CRUD\app\Library\CrudPanel\Traits\SaveActions::performSaveActio` method

**Comment by pxpm** [comment] 2020-11-12 14:16
Thanks for clarification @mialex 

I asked because we had a similar issue (the same error) related with the order you setup operations in crud. 

The reason why we didn't validate input there is because the solution of casting to array does not seem to be the optimal solution, and we didn't find a better yet. 
When the function that requires save actions is called there should be save actions in crud, otherwise why would call save actions when not using them ?

Imagine the case that I described before, get exactly the same error and the problem is the order of the Operations, to make things worse it happened in InlineCreateOperation, if it was casted it simply didn't work and no errors at all. 

In you scenario it seems the error is triggered because you didn't setup any of the operations that uses save actions (create/update), but perform a call to a crud function that uses save actions.

I think in your scenario it could be solved by **using** update operation, and override the update method, it seems is what you are trying to achieve. 

```php
use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation { update as traitUpdate; }

public function update()
{
    // check update function in the operation and do the overrides you need.
  
}

```

Please note that by using update operation we call `$this->crud->setupDefaultSaveActions();` in operation setup. This setup the crud default save actions so the `performSaveAction` could be called. 

You can edit those actions: https://backpackforlaravel.com/docs/4.1/crud-save-actions#save-actions-api

Can you tell me why you didn't setup the update operation  and are using save functionality in that crud ? Just trying to figure out in what kind of scenarios that error could be triggered so we can have a better solution if needed.

Best,
Pedro

**Comment by pxpm** [comment] 2020-11-18 11:52
Going to close this, but still would like to know in what scenarios people migth have your use case, if you come by and have time, please let me know, it will help us improving Backpack in the future.

**Closed** 2020-11-18 14:28 UTC
Labels: triage
