### ISSUE TITLE
Target folder "#" not found. BackPack Elfinder

### ISSUE THREAD

**Issue by grupaoem** [Laravel-Backpack/CRUD#858] opened 2017-08-16 13:58 UTC
Hi I have problem with upload files...

![image](https://user-images.githubusercontent.com/3195513/29366967-b43cdf0a-829b-11e7-84d7-bb2b4ac48209.png)

In console i have error
![image](https://user-images.githubusercontent.com/3195513/29361877-bf1b5fd0-8289-11e7-8a46-f912cbf1ef48.png)

**Comment by lloy0076** [comment] 2017-08-19 00:58
I'm going to close this as a dumplicate of #389 - if it is actually not a duplicate of that, please add more comments here (otherwise, please review that issue and see if anything there is helpful).

**Closed by lloy0076** 2017-08-19 00:58 UTC
Labels: bug, duplicate
