### ISSUE TITLE
High memory consumption on lang files

### ISSUE THREAD

**Issue by fauzie** [Laravel-Backpack/CRUD#2191] opened 2019-11-02 14:30 UTC
# Bug report

### What I did

- Laravel clean install with new install backpack crud via composer
- change default global language from config path `app.locale` to `id` and `app.faker_locale` to `id_ID`
- change available locale config on `config/backpack/crud.php` to only `en` and `id`
- copy `vendor/backpack/crud/src/resources/lang/en/crud.php` to `resources/lang/vendor/backpack/id/crud.php`
- `artisan view:clear`
- access admin area after logging in

### What I expected to happen

- Display nomal backpack admin area panel

### What happened

- HTTP error 500
- Check on php log:
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in <my_laravel_path>/vendor/backpack/crud/src/resources/lang/id/crud.php on line 13
```

### What I've already tried to fix it

Remove code at `vendor/backpack/crud/src/resources/lang/id/crud.php`:
```
if (file_exists(__DIR__.'/../../../../../crud/src/resources/lang/'.basename(__DIR__).'/'.basename(__FILE__))) {
    return include __DIR__.'/../../../../../crud/src/resources/lang/'.basename(__DIR__).'/'.basename(__FILE__);
}
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.2.24 (cli) (built: Oct 24 2019 07:39:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.3.0     The Laravel Framework.

### BACKPACK VERSION:
backpack/backupmanager                2.0.0      Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                         4.0.9      Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.4      Generate files for laravel projects
backpack/logmanager                   3.0.0      An interface to preview, download and delete Laravel log files.
backpack/pagemanager                  2.0.1      Create admin panels for presentation websites on Laravel, using page templates and Backpack\CRUD.
backpack/settings                     3.0.0      Application settings interface for Laravel 5 using Backpack CRUD.
```

**Comment by pxpm** [comment] 2019-11-19 16:07
Hello @fauzie 

Thanks for reporting in. :)

I think this is not a bug. My assumption (and can be incorrect) is that you copied the wrong lang file.

In the header of that file should be an header along this lines:

```
// --------------------------------------------------------
// This is only a pointer file, not an actual language file
// --------------------------------------------------------
//
// If you've copied this file to your /resources/lang/vendor/backpack/
// folder, please delete it, it's no use there. You need to copy/publish the
// actual language file, from the package.

// If a langfile with the same name exists in the package, load that one
```

It means you should copy for example the english crud translation (`crud.php`) file into your `resources/lang/id/` and edit that file and not the file you copied.

I am going to close this, if you still think this is a bug feel free to continue the discussion or re-open if need :)

Best,
Pedro

**Closed** 2019-11-19 16:07 UTC
Labels: triage

**Comment by yanuardev** [comment] 2019-12-12 16:15
hi @pxpm ,
I think it's a bug, this file (`vendor/backpack/crud/src/resources/lang/id/crud.php`) check if this very own file is exists which obviously exists and load itself then make an infinite loop. CMIIW.

I simply change `app.locale` from `en` to `id` without copy this file and experience the same error. Any locale that use this pointer does the same thing.

I also tried your suggestion by copy `crud.php` from `en` to my `resources/lang/id/` but not working, same error.
