### ISSUE TITLE
[Bug] Installation through composer fails - likely due to big package size

### ISSUE THREAD

**Issue by Saif-XI-Coderz** [Laravel-Backpack/CRUD#3842] opened 2021-09-27 10:32 UTC
# Bug report

### What I did

`composer install` or `composer update` or `composer require`.

### What I expected to happen

Should install/update backpack/crud library.

### What happened

Installation stuck for very long time on (for e.g.) `Downloading backpack/crud (4.1.54)`, then it fails.
It says it tried to download from dist but failed then tries to download from source but fails again.
I fail to understand why download from dist is failing in the first place.
![image](https://user-images.githubusercontent.com/7271727/134889170-d65811fb-5b7d-4407-bcc8-c97137e34f67.png)

### What I've already tried to fix it

I've followed instructions in the other similar issues:
- Cleared cache and tried again: `composer clearcache`.
- Preferred source: `composer require backpack/crud --prefer-source`
- I've also installed an arbitrary php package to see if the problem is with composer or my internet connection, but no error occurred there.
- I also tried to install backpack in an empty directory `composer require "backpack/crud"`, all other libraries/dependencies gets installed but still fails on installing backpack/crud with same error as above. :(

### Software Versions
Laravel v8.32.1
Composer 2.0.10
PHP 7.3.11
git 2.30.1.windows.1

Thanks, any help much appreciated. xD

**Comment by pxpm** [comment] 2021-09-27 14:07
Hello @Saif-XI-Coderz !

I am sorry but I am unable to reproduce your issue. Could it be a temporary issue ? 

I've just tried with both `--prefer-source` and normal and both worked just fine. 

I think if it was in backpack side probably more people would already complained so I guess is something in your setup. 

Can you try increasing your PHP `max_execution_time` ini setting ? Don't forget to restart your webserver after changing PHP config. 

Let me know,
Pedro

**Comment by tabacitu** [comment] 2021-09-28 08:46
> Personally I've a hunch that it's due to backpack's huge filesize (~36MB) and/or some incompatibility with composer's (or php's) default configs, evidenced by the fact that other php packages were being successfully installed on the same machine.

Might be. Since that's the  only thing that's different - all other packages get served by Packagist & Github too. 

We plan to eliminate the CSS & JS dependencies from the package in the next version. That'll make it <1 MB so hopefully nobody's going to get this kind of issue 🤞

I'm going to close this issue since you found a solution, and it'll get fixed as a sideffect of the next version changes - we have 3-4 issues about that already.

Thanks for posting about this @Saif-XI-Coderz .
Cheers!

**Closed by tabacitu** 2021-09-28 08:46 UTC
Labels: can't reproduce

**Comment by karandatwani92** [comment] 2022-08-31 10:59
@tabacitu 
I'm facing same issue from three-four days, delaying everything. I'm trying the above fix but it's not appropriate as it keeps one waiting for so long.
This issue is particularly happening to CRUD package only. Other Backpack Packages are downloading smoothly.

**Comment by tabacitu** [comment] 2022-08-31 12:48
> I'm trying the above fix but it's not appropriate as it keeps one waiting for so long.

Hmm... what do you mean, Karan? Can you rephrase please?
