### ISSUE TITLE
Cant access elfinder after fresh install

### ISSUE THREAD

**Issue by reeslo** [Laravel-Backpack/CRUD#191] opened 2016-10-19 18:41 UTC
Laravel return only an 404 error, I do all steps.

**Comment by reeslo** [comment] 2016-10-20 07:31
`config('elfinder.route.prefix')` return `/elfinder`

but elfinder.php configuration has :
``` php

    'route' => [
        'prefix'     => config('backpack.base.route_prefix').'/elfinder',
        'middleware' => ['web', 'auth'], //Set to null to disable middleware filter
    ],
```

**Comment by tabacitu** [comment] 2016-10-21 13:36
Hi @reeslo ,

I've just installed a fresh copy to test it and it works perfectly for me. 
(1) Are you sure you've followed all the installation steps?
(2) Did you install the demo project or manually the Base and CRUD packages?
(3) Do you mean elfinder is not working inside ckeditor/etc or stand-alone, at ```http://project-name/admin/elfinder```?

Cheers!

**Comment by reeslo** [comment] 2016-10-21 15:11
I've installed too time with composer after base package.

For the two installations elfinder.route.prefix dont return the complete route Idk why the backpack.base.route_prefix are not parsed in the config file. I set admin path manually. I am at work monday if you want more investigations :)

**Comment by reeslo** [comment] 2016-10-21 15:13
for the steps I do all listed like readme.io base, crud, ..., ...

**Comment by reeslo** [comment] 2016-10-21 15:18
sorry for multiple messages. The issue was the route not reconized

**Comment by tabacitu** [comment] 2016-10-21 22:30
What about your base config file, then, in ```app/config/backpack/base.php```? It should contain something like:

```php

    /*
    |--------------------------------------------------------------------------
    | Routing
    |--------------------------------------------------------------------------
    */

    // The prefix used in all base routes (the 'admin' in admin/dashboard)
    'route_prefix' => 'admin',

    // Set this to false if you would like to use your own AuthController and PasswordController
    // (you then need to setup your auth routes manually in your routes.php file)
    'setup_auth_routes' => true,

    // Set this to false if you would like to skip adding the dashboard routes
    // (you then need to overwrite the login route on your AuthController)
    'setup_dashboard_routes' => true,

    /*
    |--------------------------------------------------------------------------
    | User Model
    |--------------------------------------------------------------------------
    */

    // Fully qualified namespace of the User model
    'user_model_fqn' => '\App\User',
```

I'm more interested in the ```route_prefix``` variable. If it's not valid, a 404 error might be shown when trying to access elfinder.

**Comment by tabacitu** [comment] 2016-10-21 22:46
Or if you changed the value in the config file, take a look at ```sidebar.blade.php``` - it may contain the link to the elfinder section using the ```url('admin/elfinder')``` instead of the correct ```url(config('backpack.base.route_prefix', 'admin') . '/elfinder')```. This mistake was in an old documentation file, you might have used that.

**Comment by reeslo** [comment] 2016-10-22 06:27
I've changed the route_prefix value, I have noted difference for adding url in blade template I use url(config(....).'elfinder'). I look monday at work if I Can drop you more informations

**Comment by reeslo** [comment] 2016-10-22 13:04
I re-do same steps with a fresh laravel install same issue, 

I've screenrecorded to show you, config/elfinder.php does not add the config('backpack.base.route_prefix') value.
https://framadrop.org/r/0lSy-_rIR9#ijQCjROnp/AxdaVkPN3VZKF0k5imoJYYf6cU8gGHdoI=

I can access to elfinder http://localhost/public/elfinder like in screenshot
![forget](https://cloud.githubusercontent.com/assets/2724844/19619452/2e0d97f8-9868-11e6-9f79-7efda6143c5a.png)

**Comment by tabacitu** [comment] 2016-10-23 13:34
This is very very weird. Just tried it again, changed the admin prefix and it _does_ work for me. And I used exactly your settings. [Video here](https://infinit.io/_/WDHKbUn). So the problem in your case seems that elfinder does not register the modification you made to the elfinder config file.

Question: if you edit something else in config/elfinder.php, does the modification register?

**Comment by reeslo** [comment] 2016-10-23 14:06
yes it work if I set manually the prefix in config/elfinder.php

**Comment by reeslo** [comment] 2016-10-28 17:31
I was looking to find why..
Its very strange elfinder.php can't read backpack.base but other config file too test/test.php.
I copy the forlder to backpack2 and this work... 
![image](https://cloud.githubusercontent.com/assets/2724844/19815714/70aca622-9d44-11e6-9550-12ac687f224d.png)

```php
dd(\Config::all());
```
![capture d ecran 2016-10-28 a 19 27 38-fullpage](https://cloud.githubusercontent.com/assets/2724844/19815806/d4869d2e-9d44-11e6-9d8e-504148561de5.png)


I changed all permission files to 777 for test, same ! 
```
php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies

```

**Comment by tabacitu** [comment] 2016-10-30 16:46
This is weird. Are the Backpack service providers loaded at the END of your ```config/app.php```'s providers array? After everything else? Here are mine:

```php
/*
         * Backpack Service Providers...
         */
        Backpack\Base\BaseServiceProvider::class,
        Backpack\CRUD\CrudServiceProvider::class,
        Backpack\NewsCRUD\NewsCRUDServiceProvider::class,
        Backpack\LangFileManager\LangFileManagerServiceProvider::class,
        Spatie\Backup\BackupServiceProvider::class,
        Backpack\BackupManager\BackupManagerServiceProvider::class,
        Backpack\LogManager\LogManagerServiceProvider::class,
        Backpack\Settings\SettingsServiceProvider::class,
        Backpack\PageManager\PageManagerServiceProvider::class,
        Backpack\PermissionManager\PermissionManagerServiceProvider::class,
        Backpack\MenuCRUD\MenuCRUDServiceProvider::class,
        Backpack\LangFileManager\LangFileManagerServiceProvider::class,
```

**Comment by reeslo** [comment] 2016-10-31 13:16
:(
```php
'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,

        /*
         * Package Service Providers...
         */


        /*
        * Backpack Service Providers...
        */
        Backpack\Base\BaseServiceProvider::class,
        Backpack\CRUD\CrudServiceProvider::class,


        //

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

    ],
```

**Comment by tabacitu** [comment] 2016-11-09 06:59
Hi @reeslo , figured this out yet?

Cheers!

**Comment by reeslo** [comment] 2016-11-09 11:28
Hi, sorry I don't understand :x

**Comment by zschuessler** [comment] 2016-11-22 22:40
Simple solution is to update the `CrudServiceProvider.php` file on the `register` method to set the configuration dynamically:

```php
public function register()
{
    \Config::set(
        'elfinder.route.prefix',
        \Config::get('backpack.base.route_prefix') . '/elfinder'
    );
```

(I'm open to suggestions on if this is the best place, architecturally, to override the elfinder config.)

**Why This Works**

In Laravel 4 it appears it was once possible to access variables in the configuration files. This is no longer the case in Laravel 5, by design. Configuration files are loaded too early in the bootstrapping process to access the configuration of another config file (properly, anyway).

The new solution is to either use `.env` files (which doesn't apply here) , to set dynamic values in your service provider (as I did above), or to use middleware.

On a last note, I hard-coded the "elfinder" path as suffix to the dynamic path. You might want to instead use the default path the elfinder library uses (which is just `/elfinder`)

**Comment by OwenMelbz** [comment] 2016-12-04 18:53
as @zschuessler has provided a workaround, I'll close this off now, feel free to further discuss, its been added to the list over https://github.com/Laravel-Backpack/CRUD/issues/285 for future reference

**Closed by OwenMelbz** 2016-12-04 18:53 UTC

**Comment by tabacitu** [comment] 2016-12-05 11:09
@zschuessler , I tried again and again and I wasn't able to replicate this issue. The config value gets registered for me. I think we'll implement a solution blindly in this case, because I want you guys to stop having this issue. 

1. Wouldn't your solution overwrite the default config value, if that did get set? I'm think we should wrap it in an if statement:
```php
        // map the elfinder prefix
        if (!\Config::get('elfinder.route.prefix')) {
            \Config::set('elfinder.route.prefix', \Config::get('backpack.base.route_prefix') . '/elfinder');
        }
```
Can you please confirm this solution fixes it for you, in CrudServiceProvider::register()?

2. Can you please give me more details about your system, so I can try to match it entirely, one last time? 
- Laravel version
- Backpack\Base version
- Backpack\CRUD version
- Operating System
- PHP version
- Apache\Nginx version

Thank a lot, cheers!

**Comment by zschuessler** [comment] 2016-12-05 16:33
@tabacitu #1 - correct on overriding the config, posted that for an example. Sorry for confusion!

#2 - Sure:

```
Larvel: 5.3.*
Backpack\Base: dev-master
Backpack\CRUD: dev-master
OS: LinuxMint 17
PHP: 7.0.8
Apache: 1.4.8 (Ubuntu)
```

**Comment by tabacitu** [comment] 2016-12-13 16:10
Ok, just pushed an update that should fix it, using the method above. A ```composer update``` should fix it for you guys. If not, please let me know. Cheers!

**Comment by kakoos** [comment] 2016-12-28 20:59
Hi everyone,
I am novice in laravel but looks like i have the same problem
I installed all Backpack packages step by step, some of them works fine 
but for some of them i have problem (i think root problem)
so i can't access:
/admin/log
/admin/backup    
/admin/elfinder (this route i can acces with tsis url /elfinder#elf_l1_Lw)
https://nimbus.everhelper.me/client/notes/share/703857/q80o8otdug7lmoaf810h

Operation sistem: Linux mint 18
PHP 7.0.14-2+deb.sury.org~xenial+1 (cli) ( NTS )
Laravel 5.3

Thanks.
