### ISSUE TITLE
[Bug] checklist_dependency possible bug

### ISSUE THREAD

**Issue by skatsaounis** [Laravel-Backpack/CRUD#525] opened 2017-03-08 10:53 UTC
Hello Cristian,

I am opening the issue here because I think it has to do with checklist_dependency field. The problem occurs when creating a user, while using PermissionManager.

Description:
Admin wants to create a user and give him specific role. On submitting the request, if for any reason form validation fails, there is a problem with checklist_dependency. Ticked role stays ticked but its permissions get unticked. Furthermore, if admin fixes the error (e.g. password matching) without change ticks on roles, the user is created in database without any role assigned to him. (Role was ticked from previous form submission though).

The exact same scenario works perfect when updating an existing user.

Once again thank you for your time and effort on this awesome package.

Kind regards,
Stamatis

**Comment by eddilou** [comment] 2017-06-07 05:22
The question is still open #712

**Comment by lloy0076** [comment] 2017-06-07 12:54
Successfully reproduced as described in https://github.com/Laravel-Backpack/CRUD/issues/525#issue-212701405.

This isn't the same issue as https://github.com/Laravel-Backpack/CRUD/issues/712.

**Comment by tabacitu** [comment] 2017-09-04 09:51
Hi @skatsaounis ,

I see #712 has been closed so I'll close this one too. Please correct me if I'm wrong.

Cheers!

**Comment by tabacitu** [comment] 2017-09-04 09:53
Oups, I see it's not the same issue. Opening it again :-)

@skatsaounis , thanks a lot for the clear bug report. 
@lloy0076 thanks a lot for confirming you can reproduce the issue, it helps a lot.

@mariusconstantin2503 do you think you can work on a PR to fix this?

**Comment by ziming** [comment] 2019-11-17 12:46
I see it is labelled a bug in 3.6. Does this mean this is not a bug in 4.0?

**Comment by pxpm** [comment] 2019-11-17 13:07
@ziming not sure, just got here from your notification :) 

Please if you test it leave here the your findings. :+1: 

Best,
Pedro

**Comment by awgklist** [comment] 2020-02-21 19:47
In regards to v3.6 and the checklist_dependency.blade.php template:

From what I can tell,
The primary & secondary fields which are setup via javascript are not re-populated when the page re-loads (i.e. when the page fails validation). It's only on a javascript change event that then those hidden fields are setup. I'm guessing that the "old" fields aren't rendered to the page given the check for `isset($field['value'])` that surrounds them.

For a workaround you can manually re-trigger the change event on the primary checkboxes to re-populate those hidden fields. Either on page load -or- prior to submission.

e.g.
`$('.checklist_dependency .primary_list:checked').trigger('change');`

Hopefully that makes sense and helps.

**Comment by pxpm** [comment] 2020-10-28 11:33
I think this might be related with #1816 that is going to be addressed in 4.2, with PR #3054 

So I am postponing this to 4.2, so that when we merge that fix we hopefully fix this issue too.

**Comment by tabacitu** [comment] 2022-01-11 05:38
Hey guys. I've just merged Pedro's https://github.com/Laravel-Backpack/CRUD/pull/4057 which fixes this in 4.2. Sorry it took us so long to do it.

Cheers!

**Closed by tabacitu** 2022-01-11 05:38 UTC
Labels: Priority: MUST, Priority: SHOULD
