### ISSUE TITLE
Error 404 on edit rows

### ISSUE THREAD

**Issue by lvar** [Laravel-Backpack/CRUD#1466] opened 2018-06-20 20:38 UTC
I'm actually inserting data without problems on my DB...but when I try to edit one row and save the changes... it throws me this error...

"No query results for model [model's name]"

 I already try to fix that with => protected $primaryKey = 'id'; 
But still getting the same error ....any help ? 

The specific crud route looks like => /admin/titulares/2 and before I press the save button like /admin/titulares/2/edit

**Comment by tabacitu** [comment] 2018-06-21 06:05
Hi @lvar ,

Just tested a newly generated CRUD and it seems to work fine. So not a bug, must be something you did. So I'll close the issue.

Either way, please copy-paste your route, controller, model and request - maybe I can help you track down the problem.

Cheers!

**Closed by tabacitu** 2018-06-21 06:05 UTC
Labels: triage

**Comment by lvar** [comment] 2018-06-21 22:35
any help ? :( ....still no find solution

**Comment by tabacitu** [comment] 2018-06-22 05:07
@lvar - I don't see anything in your classes that could generate this problem. I'm pretty sure it's 
- your custom ```edit.blade.php``` file
- or 
- the ```TitularesCrudController::store()``` method, if you've overwritten that
- your custom CrudController, if you've overwritten that

If that isn't it, I suggest you start from the route and go down the chain with ```dd()``` to see where it fails. Sorry I couldn't be of more help - definitely something in your project that breaks this.

Cheers!

**Comment by lvar** [comment] 2018-06-22 13:17
mmmmm...this is weird...follow the example I give you, I'm just have 2 function on my Titular Controller.

        `public function store(StoreRequest $request)
        {
            // your additional operations before save here
           $redirect_location = parent::storeCrud($request);
           // your additional operations after save here
           // use $this->data['entry'] or $this->crud->entry
           return $redirect_location;
         }

    public function update(UpdateRequest $request)
    {
        
        // your additional operations before save here
        $redirect_location = parent::updateCrud($request);
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }`


and about my edit.blade it's just:

         `@extends('backpack::layout')

          @section('header')
	    <section class="content-header">
	     <h1>
	      {{ trans('backpack::crud.edit') }} <span>{{ $crud->entity_name }}</span>
	    </h1>
	   <ol class="breadcrumb">
	    <li><a href="{{ url(config('backpack.base.route_prefix'),'dashboard') }}">{{ 
               trans('backpack::crud.admin') }}</a></li>
	    <li><a href="{{ url($crud->route) }}" class="text-capitalize">{{ $crud->entity_name_plural }}</a> 
            </li>
	    <li class="active">{{ trans('backpack::crud.edit') }}</li>
	  </ol>
	</section>
       @endsection

      @section('content')
       <div class="row">
	<div class="col-md-8 col-md-offset-2">
		
		@if ($crud->hasAccess('list'))
			<a href="{{ url($crud->route) }}"><i class="fa fa-angle-double-left"></i> {{ trans('backpack::crud.back_to_all') }} <span>{{ $crud->entity_name_plural }}</span></a><br><br>
		@endif

		@include('crud::inc.grouped_errors')

		  {!! Form::open(array('url' => $crud->route.'/'.$entry->getKey(), 'method' => 'put', 'files'=>$crud->hasUploadFields('update', $entry->getKey()))) !!}
		  <div class="box">
		    <div class="box-header with-border">
		    	@if ($crud->model->translationEnabled())
			    	
					<div class="btn-group pull-right">
					  <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					    {{trans('backpack::crud.language')}}: {{ $crud->model->getAvailableLocales()[$crud->request->input('locale')?$crud->request->input('locale'):App::getLocale()] }} <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu">
					  	@foreach ($crud->model->getAvailableLocales() as $key => $locale)
						  	<li><a href="{{ url($crud->route.'/'.$entry->getKey().'/edit') }}?locale={{ $key }}">{{ $locale }}</a></li>
					  	@endforeach
					  </ul>
					</div>
					<h3 class="box-title" style="line-height: 30px;">{{ trans('backpack::crud.edit') }}</h3>
				@else
					<h3 class="box-title">{{ trans('backpack::crud.edit') }}</h3>
				@endif
		    </div>
		    <div class="box-body row">
		      
		      @if(view()->exists('vendor.backpack.crud.form_content'))
		      	@include('vendor.backpack.crud.form_content', ['fields' => $fields, 'action' => 'edit'])
		      @else
		      	@include('crud::form_content', ['fields' => $fields, 'action' => 'edit'])
		      @endif
		    </div>

            <div class="box-footer">

                @include('crud::inc.form_save_buttons')

		    </div>
		  </div>
		  {!! Form::close() !!}
	</div>
       </div>
       @endsection
`
I have been stock by  days already with this problem :/

**Comment by tabacitu** [comment] 2018-06-23 04:45
Hmmm.. I really don't see anything here that could trigger that kind of error. And you're right, it's especially weird since Create works but Update doesn't...

Two ways to debug this further:
- Strip your CrudController of everything but one text field, see if it works that way, and if it does gradually add the other stuff to see what it is that broke it.
- Start from the route and go down the chain with ```dd()``` to see where it fails.

**Comment by lvar** [comment] 2018-06-25 13:43
@tabacitu Hi again...I follow your suggest...With the first one nothing happens, still fail. And using dd() to debug..at this point (update function on my controller), it's printing all fine:

        `public function update(UpdateRequest $request)
        {
          dd($request);
        return parent::updateCrud();
          }`

So the problem is being generated by the crud updateCrud function inside vendor folder ?...I use dd() at the first line of this method and print null...

      `public function updateCrud(UpdateRequest $request = null)
       {
         dd($request);
        $this->crud->hasAccessOrFail('update');

        // fallback to global request instance
        if (is_null($request)) {
            $request = \Request::instance();
        }

        // replace empty values with NULL, so that it will work with MySQL strict mode on
        foreach ($request->input() as $key => $value) {
            if (empty($value) && $value !== '0') {
                $request->request->set($key, null);
            }
        }

        // update the row in the db
        $item = $this->crud->update($request->get($this->crud->model->getKeyName()),
                            $request->except('save_action', '_token', '_method'));
        $this->data['entry'] = $this->crud->entry = $item;

        // show a success message
        \Alert::success(trans('backpack::crud.update_success'))->flash();

        // save the redirect choice for next time
        $this->setSaveAction();

        return $this->performSaveAction($item->getKey());
    }`

**Comment by tabacitu** [comment] 2018-06-26 05:58
@lvar that's not that bad. You can fix it by passing the ```$request``` as parameter. See if that fixes it for you. But I don't think it will. You can see the next chunk of code checks if the request is null and if it is it re-generates the Request.

Go further down the code with dd().

**Comment by lvar** [comment] 2018-06-26 14:00
@tabacitu I print this sentence 

`$request->get($this->crud->model->getKeyName())`

 And It's throwing 'Null'....And use a dd() after this sentence:

`$item = $this->crud->update($request->get($this->crud->model->getKeyName()),
                            $request->except('save_action', '_token', '_method'));`

And it shows the 404 Error so this is the point when the code fail...Any idea ? Thanks for your time.

**Comment by tabacitu** [comment] 2018-06-27 06:44
Hmm... are you sure you had the ```id``` column in your DB, and on your model?

**Comment by adriandmitroca** [comment] 2018-08-10 13:01
I've encountered the same issue. Turned out, I had a field that had incorrectly name equal to `id` that broken default Backpack behavior that resulted with no `id` value on edit request.
