### ISSUE TITLE
backup manager backup does not work

### ISSUE THREAD

**Issue by marcoz2102** [Laravel-Backpack/CRUD#2578] opened 2020-03-19 15:07 UTC
# Bug report

### What I did
I can't backup administrative side of backpack inside backupmanager.
I from the following error in the logs:
[2020-03-19 15:36:16] local.ERROR: Backpack \ BackupManager - backup process failed because The dump process failed with exitcode 1: General error: "" mysqldump "" is not recognized as an internal or external command
I had the same error even when I was backing up from the command line
php artisan backup: run.

### What I expected to happen

I solved it by creating the environment variable in windows and by entering the mysql path 'dump_command_path' => 'd: \ xampp \ mysql \ bin',
in d: \ xampp \ htdocs \ foo \ config \ backup.php

### What happened

I expected that by putting it the same path in
d: \ xampp \ htdocs \ pippo \ vendor \ backpack \ backupmanager \ src \ config \, clicking on the button create a new backup would also work on the administrative side but it was not so

### What I've already tried to fix it

??

### PHP VERSION:
PHP 7.4.3 
mysql  Ver 15.1 Distrib 10.4.11-MariaDB

### LARAVEL VERSION:
v6.18.1@367c2c8dfdfe83cb2ddbc029c0222174098d093a

### BACKPACK VERSION:
4.0.54@e1ff2e96f70229c2ffafdb03b468bec9fcd74c70

When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment] 2020-03-19 16:57
This package is just a quick interface for triggering https://github.com/spatie/laravel-backup and downloading/deleting the backups it makes. If that package is not installed correctly, or you don't have mysqldump installed, it will indeed not work. I recommend you take a closer look at [their docs](https://docs.spatie.be/laravel-backup) - and google the error. There must be other people with the same local configuration of you not knowing where mysqldump is. Try googling "xampp mysqldump location" or stuff like that. I don't have access to a Windows machine so I wouldn't know where to help you debug it, sorry.

I'm pretty sure this is a server/app configuration issue, not a bug with BackupManager, so I'm going to close this.

Cheers!

**Closed by tabacitu** 2020-03-19 16:57 UTC
Labels: triage
