### ISSUE TITLE
[Bug] Multi column order doesn't work

### ISSUE THREAD

**Issue by pcipov** [Laravel-Backpack/CRUD#3424] opened 2020-12-29 10:10 UTC
# Bug report

When I click on column header, it orders the column (and changes the icon). It's ok.
Then I push SHIFT and click on another column header, it changes the icon, but doesn't order the column.
This should be multi column function, but doesn't work.
The same case is when I insert this code to setupListOperation method:

        $request = $this->crud->getRequest();
        if (!$request->has('order')) {
            $request->merge(['order' => [
                ['column' => '0', 'dir' => 'desc',],
                ['column' => '1', 'dir' => 'asc',],
            ]]);
        }

It orders only first column from array.
Please, can you repair it? Thanks.

### What I did

I tried everything.

### What I expected to happen

Multi column ordering.

### What happened

Orders only first selected column.

### What I've already tried to fix it

Nothing.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

**Comment by pxpm** [comment] 2020-12-30 11:26
Hello @pcipov 

Thanks for raising this issue. I can confirm that the subsequent orders were ignored by our code. I considered this a bug, so I expect it to be fixed soon.

I'v submitted the PR #3428 to address this issue, it should be reviwed by @promatik or @tabacitu before beeing merged into master. 

You can test the code in the PR overwritting the `search()` function in your controller. 

`use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation { search as traitSearch; }` 

and then define the search function in your controller:

```php
public function search() {
//copy here the complete search() function from PR you can find here: https://github.com/Laravel-Backpack/CRUD/blob/multiple-order-columns/src/app/Http/Controllers/Operations/ListOperation.php
}
```
If you have time and are willing to do so, we highly appreciate if you provide feedback on PR #3428 

Anyway thank you very much for reporting it, I would never had knew about it because that Datatables functionality was unknown to me. 

Wish you the best,
Pedro

**Closed** 2020-12-30 11:27 UTC
Labels: Bug
