### ISSUE TITLE
the create and edit function does not work after updating to 5 version

### ISSUE THREAD

**Issue by Bekzhan99** [Laravel-Backpack/CRUD#4214] opened 2022-02-18 12:06 UTC
# Bug report

### What I did

I updated the backup from 4.1 to 5 with the code "composer update"

### What happened

![image](https://user-images.githubusercontent.com/47516570/154679931-ddc42124-9292-48a2-b0ae-a4ebf3890796.png)

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment] 2022-02-18 12:26
Hey @Bekzhan99 ,

Looks like you forgot to require `backpack/pro`. If you upgrade from 4.1 to 5.0 you most likely need that too. 

Please [follow our upgrade guide](https://backpackforlaravel.com/docs/5.x/upgrade-guide) when upgrading, don't just do a `composer update` - that's not enough. You should also [read the v5 release notes](https://backpackforlaravel.com/docs/5.x/release-notes) if you don't know what backpack/pro is.

We're working on better error messages - this should read something like "_The select2_from_ajax field cannot be found_. This is most likely because you have not installed backpack/pro._". There's an issue for that somewhere, so I'm going to close this, since it's not a bug.

Cheers!

**Closed by tabacitu** 2022-02-18 12:26 UTC
Labels: triage

**Comment by Bekzhan99** [comment] 2022-02-22 05:08
@tabacitu  backpack/pro paid?
