### ISSUE TITLE
[Bug] v1.12.1 of datatable shows 2 loader on datatable ajax loading

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#4832] opened 2022-12-12 11:49 UTC
# Bug report

### What I did

Nothing, simply initialized a new project
Then did a 'vendor:publish'
Then did a 'npm install'

### What happened

When datatable is loading, the spinner added from backpack datatablelogic js code is ADDED to the loader of datatable

### What I've already tried to fix it

Manually downgraded datatable

See  vendor\backpack\crud\src\public\packages\datatables.net\js\jquery.dataTables.js 
function _fnFeatureHtmlProcessing

The new version has

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.8 (cli) (built: Jul  5 2022 23:04:29) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.42.2@607d7867c93706eae20e28e46679f8a66e2a23ec

### BACKPACK VERSION:
5.4.11@ffbadcdb6478822646600b2cd763490caa927155

**Comment by pxpm** [comment] 2022-12-17 12:33
I will be closing this, as the problem is the same as #4831 that is still open.

**Closed by pxpm** 2022-12-17 12:33 UTC
Labels: triage

**Comment by realtebo** [comment] 2022-12-17 14:00
It a issue due to same problem. But it is a different issue. I think it should be left open because the solution to other issues is not automatically resolving this issue too.



Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
