### ISSUE TITLE
[Bug] JS Arrow functions don't work in old browsers, we should rewrite to regular anonymous functions

### ISSUE THREAD

**Issue by DanielKimmich** [Laravel-Backpack/CRUD#3661] opened 2021-04-09 17:00 UTC
# Bug report
For all crud it does not show the list, this happens to me with internet explorer. For chrome it works.

### What I did
jQuery.Deferred exception: 'crud' is not defined ReferenceError: 'crud' is not defined
   at Anonymous function (http://crudcontact.telecom.int/admin/contactfamily:1086:7)
   at c (http://crudcontact.telecom.int/packages/backpack/base/js/bundle.js?v=4.1.41@44770347b918e42c052d0a138c24535b43e32472:2:31065)
   at Anonymous function (http://crudcontact.telecom.int/packages/backpack/base/js/bundle.js?v=4.1.41@44770347b918e42c052d0a138c24535b43e32472:2:31375) undefined

### What happened 
![image](https://user-images.githubusercontent.com/44840413/114215914-93b2fb00-993c-11eb-8cce-078afc2a05b5.png)

### What I've already tried to fix it

php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force

C:\laragon\www\crudContact (master)
λ php artisan config:clear
Configuration cache cleared!

C:\laragon\www\crudContact (master)
λ php artisan view:clear
Compiled views cleared!

C:\laragon\www\crudContact (master)
λ php artisan cache:clear
Application cache cleared!

### PHP VERSION:                                                           
PHP 7.4.7 (cli) (built: Jun  9 2020 13:36:15) ( ZTS Visual C++ 2017 x64 )  
Copyright (c) The PHP Group                                                
Zend Engine v3.4.0, Copyright (c) Zend Technologies                        
                                                                           
### LARAVEL VERSION:                                                       
v8.36.2@0debd8ad6b5aa1f61ccc73910adf049af4ca0444                           
                                                                           
### BACKPACK VERSION:                                                      
4.1.41@44770347b918e42c052d0a138c24535b43e32472

**Comment by pxpm** [comment] 2021-04-15 14:54
Hello @DanielKimmich 

Unfortunatelly IE does not support Javascript arrow functions. IE is a discontinued browser, the new Edge from microsoft support arrow functions, as like chrome, firefox etc. https://caniuse.com/arrow-functions

I don't think IE will ever support arrow functions .

@tabacitu is this something we should "care" ? I mean, either use a polyfill or remove arrow function in favor of old syntax to support IE ? From caniuse it's seems the browser is almost dead, but I am thinking about old intra-stations or air-gapped machines that probably still run XP orso!

Let me know,
Pedro

**Comment by DanielKimmich** [comment] 2021-04-15 17:52
This I have tried in several browsers that give me the error:
Microsoft Edge 41.16299.1004.0
FireFox Quantum 59.0.2 (32-bit)

If it works for me in:
Google Chrome 85.0.4183.121 (Official Build) (32-bit)

Thanks for viewing the topic.

**Comment by tabacitu** [comment] 2021-04-16 05:34
@DanielKimmich - I don't have Firefox 57.0 to test (it was launched March 2018), but it just worked for me in the latest Firefox Quantum (87.0, 64-bit, launched March 2021). So I guess the problem is still _old browsers_ vs _new browsers_.

@pxpm I think it won't hurt us to rewrite it to a regular anonymous function instead of array function - it's easy to do. If this adds support for old browsers, yeah let's do it. Old browser support is not necessarily _needed_, but yeah... you never know what computers admin use, so it's a load off the developer's mind.

Anywhere else in Backpack you've found this problem with arrow functions @DanielKimmich ?

**Comment by DanielKimmich** [comment] 2021-04-16 14:03
@tabacitu It is also crashing when editing has a column of the type "repeatable", shows the fields at the end, and does not load the data.

**Comment by pxpm** [comment] 2021-04-16 16:08
This might be a little bit more than just the one I tracked. 

https://github.com/Laravel-Backpack/CRUD/blob/e786bf4fd294304a5e35bb7f98bacd714c11bd45/src/resources/views/crud/fields/video.blade.php#L187

https://github.com/Laravel-Backpack/CRUD/blob/e786bf4fd294304a5e35bb7f98bacd714c11bd45/src/resources/views/crud/fields/select2_from_ajax_multiple.blade.php#L166

https://github.com/Laravel-Backpack/CRUD/blob/e786bf4fd294304a5e35bb7f98bacd714c11bd45/src/resources/views/crud/fields/select2_from_ajax.blade.php#L193

https://github.com/Laravel-Backpack/CRUD/blob/e786bf4fd294304a5e35bb7f98bacd714c11bd45/src/resources/views/crud/fields/image.blade.php#L241

https://github.com/Laravel-Backpack/CRUD/blob/4d05f98a1878f8cfff91ee7e98fc47d2bfc9a270/src/resources/views/crud/fields/repeatable.blade.php#L225

https://github.com/Laravel-Backpack/CRUD/blob/4d05f98a1878f8cfff91ee7e98fc47d2bfc9a270/src/resources/views/crud/fields/relationship/fetch_or_create.blade.php#L235

https://github.com/Laravel-Backpack/CRUD/blob/4d05f98a1878f8cfff91ee7e98fc47d2bfc9a270/src/resources/views/base/inc/sidebar.blade.php#L47

This was just some that popup in my IE experiment, it could be more hidden that were not used in my tests.

**Comment by pxpm** [comment] 2021-04-16 19:47
Hello @DanielKimmich 

I'v just pushed https://github.com/Laravel-Backpack/CRUD/pull/3671 with what I think would clean up incompatible IE errors.

If you have time, and are willing give it a try. 

I will be closing this as the PR addresses the issues mentioned here. 

Thanks for the report,
Pedro

**Closed by pxpm** 2021-04-16 19:47 UTC
Labels: dependent, triage
