### ISSUE TITLE
[Bug] summernote-classes plugin doesn't work

### ISSUE THREAD

**Issue by gaellepierlot** [Laravel-Backpack/CRUD#3760] opened 2021-06-22 07:28 UTC
# Bug report

### What I did

I added a [summernote-classes](https://github.com/DiemenDesign/summernote-classes) plugin in summernote.blade.php

### What I expected to happen

Align text with css classes of summernote-classes

### What happened

It doesn't work, apparently the css classes are removed before saving.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is still there

### PHP VERSION:
PHP 7.4.19 (cli) (built: May 12 2021 21:21:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.27.0@a6680d98f9dadaa363aa7d5218517a08706cee64

### BACKPACK VERSION:
4.1.47@b2325eedd661adb75c23683aa6ee1d291b3578e7

**Comment by pxpm** [comment] 2021-07-03 10:43
Hello @gaellepierlot 

Sorry but I can't be much help here. I can try to give it a better look but It would require that you provide your `summernote.blade.php` and your field definition in the controller so I can try to reproduce it. 

Also I don't think Backpack removes anything from the editor, we just save what is in the textarea. 

I am closing this for now, please re-open if needed or feel free to continue the discussion. If the problem is something we can fix I am willing to give it a try. 

Best,
Pedro

**Closed by pxpm** 2021-07-03 10:43 UTC
Labels: triage

**Comment by tabacitu** [comment] 2021-07-05 10:16
Ha! I didn't know about that Summernote plug, it's pretty cool. 

I agree with @pxpm here - I'm afraid there's not much we can do to help here @gaellepierlot . Since it's custom code you're working with here, we have no idea what might be going wrong. If you figure it out though, please consider leaving your tips / solution / code / something as a reply here, I'm sure it'll help someone someday do the same thing (maybe even you 😅).

Sorry we can't be of more help. Cheers!
