### ISSUE TITLE
Search on joined tables results in 'clause is ambiguous' when tables have similar fieldnames (eg id) that can be searched on

### ISSUE THREAD

**Issue by timbertens** [Laravel-Backpack/CRUD#3396] opened 2020-12-12 08:18 UTC
# Bug report

### What I did
I have a list view with multiple columns and where one field 'Account' refers to a related model.  Not important for this issue, but just to be complete the 'name' attribute in that model is a custom attribute that shows different fields based on the account type (individual or company), hence the custom orderLogic and searchLogic parts to accommodate order and search for these concatenated fields. 

        $this->crud->setColumns(['id', 'account', 'offer_date', 'offer_due_date',
            'customer_reference', 'status']);

        $this->crud->setColumnDetails('account', 
        [
            'label' => 'Account',
            'type' => 'select',
            'attribute' => 'name',
            'wrapper' => [
                'href' => function($crud, $column, $entry, $related_key) {
                    return backpack_url('account/' . ($related_key ?? $entry->id) . '/show');
                }
            ],
            'entity' => 'account',
            'orderable' => true,
            'orderLogic' => function ($query, $column, $columnDirection)  {
    
                    $query = $query 
                    ->leftJoin('accounts', 'accounts.id', '=', 'offers.account_id')
                    ->orderByRaw('CONCAT_WS("", accounts.company_name,accounts.first_name,
                            accounts.last_name) ' . $columnDirection)->select('offers.*');
                    return $query;

            },
            'searchLogic' => function($query, $column, $searchTerm)  {

                    $query->orWhereHas('account', function ($q) use ($column, $searchTerm) {
                        $q->where('accounts.first_name', 'like', '%'.$searchTerm.'%');
                        $q->orWhere('accounts.last_name', 'like', '%'.$searchTerm.'%');
                        $q->orWhere('accounts.company_name', 'like', '%'.$searchTerm.'%');
                    });
 
            },
        ]);

### What I expected to happen

I expected it to just work and to be able to search and sort the different fields in the list view

### What happened

When combining a search with a sort, I hit an error: Column 'id' in where clause is ambiguous because of this SQL that is constructed

```
select offers.* from offers left join accounts on accounts.id = offers.account_id where (id like %TestSearch% or 
exists (select * from accounts where offers.account_id = accounts.id and (accounts.first_name like %TestSearch%
 or accounts.last_name like %TestSearch% or accounts.company_name like %TestSearch%) and 
accounts.instance_id = 4) or customer_reference like %TestSearch%) and offers.instance_id = 4 order by 
CONCAT_WS("", accounts.company_name,accounts.first_name, accounts.last_name) desc, offers.id DESC limit 10
```

This comment also refers to the same problem, I believe, https://github.com/Laravel-Backpack/CRUD/issues/2908#issuecomment-638243587

### What I've already tried to fix it

This can be solved by adding custom searchLogic to the 'id' field like this

```
'searchLogic' => function ($query, $column, $searchTerm) {
                    $query->orWhere('offers.id', 'like', '%' . $searchTerm . '%');
                }
```

Being lazy as I am (and because I have similar issues on other list views) I believe it would be better if where clauses are always using the tablename.fieldname notation or am I missing something? 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.18.1@31747193c26ba0a9cb7929a912895d3cdefd10cf

### BACKPACK VERSION:
4.1.28@011e818304b3ebac28b673c1c91018590bdceb12

**Comment by pxpm** [comment] 2020-12-14 11:42
Hello @timbertens 

Thanks for such a well described issue report. 

Indeed, backpack checks if there is some order in primary key (your case id). But if there is not, we apply the order with the table prefixed: 

```php
 if (! $hasOrderByPrimaryKey) {
            $this->crud->orderByWithPrefix($this->crud->model->getKeyName(), 'DESC');
        }

 public function orderByWithPrefix($column_name, $column_direction = 'ASC')
    {
        if ($this->driverIsSql()) {
            return $this->query->orderByRaw($this->model->getTableWithPrefix().'.'.$column_name.' '.$column_direction);
        }

        return $this->query->orderBy($column_name, $column_direction);
    }
```

The problem you referenced is because we previously only used: `$this->query->orderBy($column_name, $column_direction);` and we added the `orderByRaw` to fix that issue. 

Can you please post the `expected` SQL query so I can try do debug it down the line ?

Thanks,
Pedro

**Comment by timbertens** [comment] 2020-12-14 12:30
sure, this is what is expected (it seems that I deleted a few non relevant quotes for this issue to many)

```
select offers.* from offers left join accounts on accounts.id = offers.account_id where (offers.id like '%TestSearch%' or 
exists (select * from accounts where offers.account_id = accounts.id and (accounts.first_name like '%TestSearch%'
 or accounts.last_name like '%TestSearch%' or accounts.company_name like '%TestSearch%') and 
accounts.instance_id = 4) or customer_reference like '%TestSearch%') and offers.instance_id = 4 order by 
CONCAT_WS("", accounts.company_name,accounts.first_name, accounts.last_name) desc, offers.id DESC limit 10
```
_(change on first line => id becomes offers.id)_

Not a problem in my case, but if in general tablename.fieldname is used then it should be 

```
select offers.* from offers left join accounts on accounts.id = offers.account_id where (offers.id like '%TestSearch%' or 
exists (select * from accounts where offers.account_id = accounts.id and (accounts.first_name like '%TestSearch%'
 or accounts.last_name like '%TestSearch%' or accounts.company_name like '%TestSearch%') and 
accounts.instance_id = 4) or offers.customer_reference like '%TestSearch%') and offers.instance_id = 4 order by 
CONCAT_WS("", accounts.company_name,accounts.first_name, accounts.last_name) desc, offers.id DESC limit 10
```
_(change on second last line customer_reference become offers.customer_reference)_

**Comment by pxpm** [comment] 2020-12-14 12:47
Hello again @timbertens and thanks I think I got it now. 

Could you do me a last favor and check if this solution fixes the problem? If you can, go to `vendor\backpack\crud\src\app\Library\CrudPanel\Traits\Search.php` and replace from line `64` to `95` with this code:

```php
       if ($column['tableColumn']) {
            switch ($columnType) {
                case 'email':
                case 'text':
                case 'textarea':
                    $query->orWhere($query->getModel()->getTableWithPrefix().'.'.$column['name'], 'like', '%'.$searchTerm.'%');
                    break;

                case 'date':
                case 'datetime':
                    $validator = Validator::make(['value' => $searchTerm], ['value' => 'date']);

                    if ($validator->fails()) {
                        break;
                    }

                    $query->orWhereDate($query->getModel()->getTableWithPrefix().'.'.$column['name'], Carbon::parse($searchTerm));
                    break;

                case 'select':
                case 'select_multiple':
                    $query->orWhereHas($column['entity'], function ($q) use ($column, $searchTerm) {
                        $q->where($q->getModel()->getTableWithPrefix().'.'.$column['attribute'], 'like', '%'.$searchTerm.'%');
                    });
                    break;

                default:
                    return;
                    break;
            }
        }
    }
```

If it fixes you are free to submit a PR for it and show up as a contributor if you want/have time to. Otherwise let me know and I can create it 👍 

Thanks for all the support debbuging this issue.
 
Best,
Pedro

**Comment by timbertens** [comment] 2020-12-14 13:14
Work perfectly, thanks!  PR has been created

**Comment by pxpm** [comment] 2020-12-14 13:21
Thank you very much. 🥇 

Will review the PR and close this one. 

Wish you the best,
Pedro

**Closed by pxpm** 2020-12-14 13:21 UTC
Labels: needs-more-info

**Comment by notf0und** [comment] 2023-10-18 06:40
This needs to be reopened as doesn't work when adding joins trough global scopes. To fix it:
```php
    public function orderByWithPrefix($column_name, $column_direction = 'ASC')
    {
        if ($this->query->toBase()->joins !== null) {
            return $this->query->orderByRaw($this->model->getTableWithPrefix().'.'.$column_name.' '.$column_direction);
        }

        return $this->query->orderBy($column_name, $column_direction);
    }
```

**Comment by pxpm** [comment] 2023-10-18 08:23
Hello @notf0und thanks for the report, but this issue is almost 3 years old. 

Can you please open a new issue, with a description of what's broken, and what you propose to fix it ? 

Please fill the issue template the most accurate possible so that I can reproduce the problem and fix it 🙏 

Cheers
