### ISSUE TITLE
[Bug] Column type closure return Error: Object of class Closure could not be converted to string

### ISSUE THREAD

**Issue by GarryKa** [Laravel-Backpack/CRUD#3990] opened 2021-12-06 05:00 UTC
# Bug report

### What I did

```php
 CRUD::column([
                    'name'  =>'active', 
                    'label' => 'Status',
                    'type'  => 'closure',
                    'function' => function($entry) {
                        return 'Active: ' . $entry->active;
                    }
                    ]);
```

### What I expected to happen

column Status in list "Active: 1(0) ''

### What happened

Symfony\Component\Debug\Exception\FatalThrowableError
Object of class Closure could not be converted to string 

::preg_replace
C:\OpenServer\domains\admin-laravel\vendor\backpack\crud\src\app\Library\CrudPanel\Traits\AutoSet.php:186

return trim(mb_ucfirst(str_replace('_', ' ', preg_replace('/(_id|_at|\[\])$/i', '', $value)));

### What I've already tried to fix it

strval($entry->active)

### Is it a bug in the latest version of Backpack?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 
PHP 7.4.14 (cli) (built: Jan  5 2021 15:12:29) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v6.20.41@74db641f743e65dd8f39dcb74dce68709e73711c

### BACKPACK VERSION:
4.1.61@4400187391eb5b73672c2b166a990cd737277409

**Comment by tabacitu** [comment] 2021-12-07 08:34
Hey @GarryKa ,

I notice you're using a mix of the ARRAY and the FLUENT syntaxes. You should be using one of these two:
- `CRUD::addField($array_definition_of_column)`;
- `CRUD::column($string)->label($string)->type($string);`


The parameter in `CRUD::column()` is the column NAME, not the DEFINITION. So:


If you want to use the array syntax, do:

```diff
-            \CRUD::column([
+            \CRUD::addColumn([
                'name'  =>'active',
                'label' => 'Status',
                'type'  => 'closure',
                'function' => (function ($entry) {
                    return 'Active: ' . $entry->active;
                })
            ]);
```


If you want to use the fluent syntax, do:
```php
            CRUD::column('active')->label('Status')->type('closure')->function(function ($entry) {
                return 'Active: ' . $entry->active;
            });
```

I just checked, and your code works with the changes above, so I'm going to close this issue as "not a bug".

Hope it helps.
Cheers!

**Closed by tabacitu** 2021-12-07 08:34 UTC
Labels: triage
