### ISSUE TITLE
[4.0] Cannot use xDebug - InvalidArgumentException: View [xxx] not found. (on debug, VSC)

### ISSUE THREAD

**Issue by rUriarteDev** [Laravel-Backpack/CRUD#2585] opened 2020-03-21 09:08 UTC
During the development of my project I had the problem when activating xdebug in visual studio code, and navigating through the browser in the CRUDs. In each CRUD or backpack form that was loaded, the following error appeared.
InvalidArgumentException: View [vendor.backpack.crud.xxxx.yyyyy] not found.
So I tried the backpack demo and I get the same errors when navigating between the CRUDs with the debug activated.
This is normal? Is there any way to fix it?
if I'm not debugging these errors don't appear
I already tried composer-update and the problem continues.
![image](https://user-images.githubusercontent.com/39219144/77223306-20282b00-6b3a-11ea-8699-9076ca4e1eaf.png)

**Comment by tabacitu** [comment] 2020-03-22 10:07
Hmm... not sure @rUriarteDev - I don't use xDebug myself, I use Whoops/Ignition+dd+laravel-debugbar, I find that's a good workflow for me. 

Maybe someone else who uses it can pitch in with a reason/solution. So let's leave this open. If you do find a solution, let me know. It shouldn't error though, since it _does work_ 😄

**Comment by rUriarteDev** [comment] 2020-03-28 09:55
I have updated to last PHP and Xdebug version and problem persist.
It is not a solution but it is a way to avoid concurrent exceptions. In the php.ini file set xdebug.remote_autostart = 0. And download the Xdebug helper extension, and enable or disable debug from the browser. Also configuring that way xdebug greatly improves response times when loading pages

**Comment by tabacitu** [comment] 2020-03-28 15:12
Thanks for sharing your findings @rUriarteDev ! So... **is this a Backpack problem? Or is it an XDebug configuration issue?** Are you having the same issue with other AJAX requests in debug (I assume that's part of the problem for you). If other, non-backpack, ajax requests trigger the same error... I'd close this issue.

Cheers!

**Comment by rUriarteDev** [comment] 2020-03-31 02:07
I dont think is a xDebug configuration issue, since the only views afected by this problem are those that have a backpack column or field.
What I interpret from the message is that the views of the columns and fields were not being found (in vendor??).
Do you think of something I can try to fix it?

**Comment by tabacitu** [comment] 2020-03-31 06:31
Hmm... Maybe try to go to ```Backpack\CRUD\app\Library\CrudPanel\Traits\Search::getCellViewName()``` - that's where Backpack calculates the views to use for each column. Maybe xDebug doesn't somehow run the ```view()->exists()``` or something, idk...

**Comment by juventus18** [comment] 2020-04-10 22:47
This happens because of the way the view engine looks for views. It first checks to see if you've overridden a view using your view folder, when that view is not found, an exception is thrown and handled by backpack to load its version of the view instead. So here, the exception is considered handled (unless the view engine can't find a backpack view with that name either, then it bubbles up.) The reason you are seeing this each time is because you have enabled XDebug to stop on all exceptions. You can disable this in the debug panel under the "breakpoints" section:
![image](https://user-images.githubusercontent.com/1124513/79027788-763d2c80-7b42-11ea-90b3-47672e1a9c74.png)

This behavior is expected and not a bug of backpack.

**Comment by rUriarteDev** [comment] 2020-04-11 15:28
Hi @juventus18 , I tried your solution and it worked without problems. Is there a way to exclude these kinds of exceptions only? If I check the exceptions box and not "always", keep throwing this. Thank you very much for the solution anyway

**Comment by tabacitu** [comment] 2020-04-13 07:48
This looks like an explanation & solution @juventus18 - thanks a lot! 
This means I can close the issue then, since there's a solution for it.

**[Solution here](https://github.com/Laravel-Backpack/CRUD/issues/2585#issuecomment-612252095)**

**Closed by tabacitu** 2020-04-13 07:48 UTC
Labels: Bug, Priority: COULD

**Comment by juventus18** [comment] 2020-04-13 19:10
@rUriarteDev I'm not exactly sure I understand what you're asking, but I'll take a stab at an explanation anyway...

You're probably thinking "If I don't have this checkbox, how will I know if my application has generated an exception?" and the simple answer is, it generally just wont matter.... exceptions happen all the time in programming. As long as the exceptions are gracefully handled, you rarely need to know they even happened at all. In the case where code does not handle an exception, you will still get the exception output on the page as normal like this: 
![image](https://user-images.githubusercontent.com/1124513/79151647-a6bdda00-7d7f-11ea-91fe-be29dc65384d.png)

Then you can just set breakpoints around it.
