### ISSUE TITLE
Translatable fake fields getTranslation() must be type string

### ISSUE THREAD

**Issue by hocklai8** [Laravel-Backpack/CRUD#1732] opened 2018-11-27 14:07 UTC
# Bug report
Fake fields with translatable field gets this error 

> "Return value of App\Models\Page::getTranslation() must be of the type string, array returned."

### What I did:
Quite similar to my previous issue #1633 case as example 
**app\Http\Controllers\Admin\PageCrudController.php**
```php
    public function setup()
    {
        $this->crud->setModel('App\Models\Page');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/page');
        $this->crud->setEntityNameStrings('page', 'pages');

        // COLUMNS
        $this->crud->addColumn([
            'name' => 'title',
            'label' => 'Title',
        ]);
        $this->crud->addColumn([
            'name' => 'status',
            'label' => 'Published',
        ]);

        // Fields
        $this->crud->addField([
            'name' => 'title',
            'type' => 'text',
            'label' => 'Title'
        ]);
        $this->crud->addField([
            'name' => 'slug',
            'label' => 'Slug (URL)',
            'type' => 'text',
            'hint' => 'Will be automatically generated from your title, if left empty.',
            // 'disabled' => 'disabled'
        ]);
        $this->crud->addField([
            'name' => 'description',
            'label' => 'Meta Description',
            'type' => 'text',
            'fake' => true,
            'store_in' => 'meta',
        ]);
        $this->crud->addField([
            'name' => 'keywords',
            'label' => 'Meta Keywords',
            'type' => 'text',
            'fake' => true,
            'store_in' => 'meta',
        ]);
        $this->crud->addField([
            'name' => 'content',
            'label' => 'Content',
            'type' => 'ckeditor',
        ]);

        // add asterisk for fields that are required in PageStoreCrudRequest
        $this->crud->setRequiredFields(StoreRequest::class, 'create');
        $this->crud->setRequiredFields(UpdateRequest::class, 'edit');
    }
```

**app\Models\Page.php**
```php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\Sluggable;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\SluggableScopeHelpers;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations;

class Page extends Model
{
    use CrudTrait;
    use Sluggable, SluggableScopeHelpers;
    use HasTranslations;

    protected $table = 'pages';
    protected $primaryKey = 'id';
    public $timestamps = true;
    // protected $guarded = ['id'];
    protected $fillable = ['title', 'slug', 'meta', 'content', 'status'];
    protected $fakeColumns = ['meta'];
    // protected $hidden = [];
    // protected $dates = [];
    protected $translatable = ['title', 'slug', 'meta', 'content'];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'slug_or_title',
            ],
        ];
    }

    // The slug is created automatically from the "name" field if no slug exists.
    public function getSlugOrTitleAttribute()
    {
        if ($this->slug != '') {
            return $this->slug;
        }

        return $this->title;
    }
}
```

### What happened:
Saves data correctly but retrieving it in list or view gets the error above

### What I've already tried to fix it:
Seems like the upstream package spatie/laravel-translatable have updated the `getTranslation()` to return string only since v3 release (Oct 16). Since backpack already overwrites some of the upstream functions, perhaps should add this too? A quick fix might just be to overwrite and revert this function to not forced return string. @tabacitu @OliverZiegler ?

### Backpack, Laravel, PHP, DB version:
backpack/crud 3.5.3, Laravel 5.7.14, MySQL 5.7, spatie/laravel-translatable 3.0.1

**Comment by Sergiu026** [comment] 2018-11-28 10:07
Hey guys, I have the same issue, rollback to 2.2.1 version of laravel-translatable seems to fix the problem

**Comment by tabacitu** [comment] 2018-11-28 12:21
Thank you @hocklai8 ! Hmm... as far as I can tell, this new version of spatie/translatable (3.0.0) no longer allows you to make non-text attributes translatable. Which... is a big bubu.

I recommend using ```2.*``` for the time being. Will investigate further.

**Comment by tabacitu** [comment] 2018-11-28 12:56
Hi @hocklai8 ,

I've fixed the problem on our end, you can do a ```composer update``` and use the 3.x version of spatie/laravel-translatable now. I've also added a PR for them to change this in the package - https://github.com/spatie/laravel-translatable/pull/139 - not sure they'll merge it though.

Thanks, cheers!

**Comment by hocklai8** [comment] 2018-11-28 12:59
Hi @tabacitu ,
Thanks for the quick fix 👍

**Comment by iFeras93** [comment] 2021-01-31 07:50
this problem appearing again

Backpack, Laravel, PHP, DB version:
backpack/crud 4.1.31, Laravel 8.25.0, 10.4.11-MariaDB, spatie/laravel-translatable 4.6

**Comment by tabacitu** [comment] 2021-02-01 13:47
Thanks for the heads-up @iFeras93 . We'll investigate and get back to you ASAP.

**Comment by tabacitu** [comment] 2021-02-02 15:31
@iFeras93 couldn't achieve the same thing. Could you please let us know exactly _what error_ you're getting _when_?

**Comment by promatik** [comment] 2021-02-13 02:51
Hi everyone, since we can't reproduce this, let's close it for now.
@iFeras93 if you think this should be reopen please do, let us know if you have the problem persists.

**Closed by promatik** 2021-02-13 02:51 UTC
Labels: can't reproduce, triage
