### ISSUE TITLE
Pass value to ......./create/ or overide add method

### ISSUE THREAD

**Issue by inquisitive-stha** [Laravel-Backpack/CRUD#835] opened 2017-08-11 06:37 UTC
...........address?hospital_id=14

I have an address something like above in URL. what I want is I want to pass hospital_id to add form. Currently, I can pass it using a session variable. But, I don't think this is an ideal method. So, I wanted to override 'add button' by using model function. But when ever I add stact as "top" i get error like: 

`Undefined variable: entry (View: C:\wamp64\www\hamrohospital\vendor\backpack\crud\src\resources\views\inc\button_stack.blade.php) (View: C:\wamp64\www\hamrohospital\vendor\backpack\crud\src\resources\views\inc\button_stack.blade.php)`

**Comment by OliverZiegler** [comment] 2017-08-11 15:06
When you add your button to the top there is no `$entry` available.
The `$entry` variable is only available in the table, and so only for buttons in the table rows, (`line`-stack)

**Comment by inquisitive-stha** [comment] 2017-08-11 15:10
So, how can i add button at top??? I didn't get what you are trying to explain?

**Comment by OliverZiegler** [comment] 2017-08-11 15:13
Please give me some more info so I can better understand your issue and give you more precise feedback. 
Please provide:
* your button code of `C:\wamp64\www\hamrohospital\vendor\backpack\crud\src\resources\views\inc\button_stack.blade.php`

**Comment by inquisitive-stha** [comment] 2017-08-11 15:57
![test](https://user-images.githubusercontent.com/16288854/29221217-a70dea3e-7edd-11e7-8059-c126bca2fc60.png)

How to add button at that "add department" button position with a custom link on that button.

**Comment by lloy0076** [comment] 2017-08-11 18:36
https://laravel-backpack.readme.io/docs/crud-buttons#section-buttons-stacks

Do the docs explain what you want to do?

**Comment by OliverZiegler** [comment] 2017-08-11 21:36
It seems like you are trying to have some kind of dependent or sub controller as you want to create a department which belongs to some hospital...

Check out (this)[https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud] blog post as this could solve your problem I think.

**Comment by inquisitive-stha** [comment] 2017-08-12 03:07
In controller,

`$this->crud->addButtonFromModelFunction('top', 'open_google', 'openGoogle', 'beginning'); // add a button whose HTML is returned by a method in the CRUD model`

In Model,

```
public function openGoogle($crud = false)
    {
        return '<a class="btn btn-xs btn-default" target="_blank" href="http://google.com?q='.urlencode($this->text).'" data-toggle="tooltip" title="Just a demo custom button."><i class="fa fa-search"></i> Google it</a>';
    }
```
error: ` Cannot redeclare App\Models\Address::openGoogle()`

**Comment by lloy0076** [comment] 2017-08-16 02:02
@inquisitive-stha - usually that's because ... there is already such a function but if the probem were that obvious I suppose you'd have fixed it already.

That said, there may be some other obscure reason why you can't redeclare it - is it possible that it's complaining about the `$crud = false` argument?

**Comment by inquisitive-stha** [comment] 2017-08-16 05:43
Tried by removing $crud = false and making $crud = true also. But, both generate the same error.

**Comment by tabacitu** [comment] 2017-09-04 12:16
Hi guys. Keep talking, but I'll close this issue as it's not a bug, it's more of a stackoverflow question. Cheers!

**Closed by tabacitu** 2017-09-04 12:16 UTC
Labels: question
