### ISSUE TITLE
[Bug] translatable model not showing correct language translations in edit form

### ISSUE THREAD

**Issue by kartomantas** [Laravel-Backpack/CRUD#4344] opened 2022-04-29 16:20 UTC
# Bug report

### What I did

Tried to use HasTranslations trait on my MenuItem model in order to be able to use translations for that model

### What I expected to happen

To be able to translate my models in different languages

### What happened

Every language edit form shows same current values (of default language). Save operation works - for example, I can change values and it shows different in in database, but backpack edit form still shows values from default language for every language.

### What I've already tried to fix it

Tried to override/extend these methods:
vendor/backpack/crud/src/app/Http/Controllers/Operations/UpdateOperation.php -> edit
vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Update.php -> getModelAttributeValue
But the final result gets ugly and/or with a lot of repetitive code. I believe the issue is 80 line of Update.php -> getModelAttributeValue:

`return $model->{$field['name']};`

it takes default value of the model (default locale) whereas instead it should take translated value for corresponding locale that's in request (_locale)

quick fix in UpdateOperation.php -> edit:

```
app()->setLocale(request()->input('_locale') ?? app()->getLocale());
$this->crud->setOperationSetting('fields', $this->crud->getUpdateFields());
app()->setLocale(config('app.locale'));
```

### Is it a bug in the latest version of Backpack? - yes

After I run ```composer update backpack/crud``` the bug... is it still there? - yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.0.6 (cli) (built: May  4 2021 23:31:45) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.9.0@4d5a07640891b772188d7737348886a0222737d8

### BACKPACK VERSION:
5.0.14@1e355c4c046a34423a1a3e3150120245a4bfd8e9
```

**Comment by guleswine** [comment] 2022-05-03 14:23
hi, i think that same problem, right? 
https://github.com/Laravel-Backpack/CRUD/issues/4326

add 'hydrate' method works for you?

**Comment by pxpm** [comment] 2022-05-03 14:50
@kartomantas I don't think it's the same issue as @guleswine mentioned, but in 5.0.15 https://github.com/Laravel-Backpack/CRUD/pull/4313 was added to try to fix this. 

Can you update your backpack version to the latest to check if it's fixed ? 

Cheers

**Comment by guleswine** [comment] 2022-05-04 14:13
@pxpm hi, i check  5.0.15 fix, but problem still here, only add hydrate method works for me https://github.com/Laravel-Backpack/CRUD/issues/4326

**Comment by pxpm** [comment] 2022-05-04 16:11
Hello @guleswine 

`hydrate` from my understanding is just a fancy word for `set attributes`, so hydrate is the name given to the operation where attributes are set in the model, if you call `find` or any other method it will eventually `hidrate` the model with the values it gets from the database. 

Wouldn't the problem be fixed by https://github.com/Laravel-Backpack/CRUD/pull/4267 ? Or you are having a specific problem when manual calling `hydrate` on the model ?

What I think is that if we use `hydrate` we can probably remove all other methods, since I think all of them will call hydrate somewhere in their lifecycle.

**Comment by guleswine** [comment] 2022-05-04 16:28
@pxpm  no, I don't call this method manually.

Unfortunately this PR #4267 does not help with this problem, the language in the interface does not switch

**Comment by pxpm** [comment] 2022-05-04 20:07
It's just too late here now, I just finished other thing I was working on, I will have a look tomorrow on this 👍 

Cheers

**Comment by pxpm** [comment] 2022-05-05 09:54
So, I can confirm that this specific issue (not the @guleswine one) is fixed by #4267 

https://recordit.co/3sC5FycPs0

I will leave this open until we merge the PR. 

Will have a look on your issue now @guleswine ! Will get back to you with news.

**Comment by pxpm** [comment] 2022-05-05 09:54
So, I can confirm that this specific issue (not the @guleswine one) is fixed by #4267 

https://recordit.co/3sC5FycPs0

I will leave this open until we merge the PR. 

Will have a look on your issue now @guleswine ! Will get back to you with news.

**Comment by tabacitu** [comment] 2022-05-26 05:54
Ouch! Looks like we badly misinterpreted this @guleswine , sorry it took so long to realise this! I now understand that:
- You're NOT talking about us pro-populated empty fields with the default language;
- You're talking about a BUG here; that after you edit a translated entity (eg. Italian) you do not see the Italian strings, but the English ones; so it's broken;

We're working on it! Thank you so much, and sorry we misinterpreted this 🙏

**Comment by guleswine** [comment] 2022-05-26 06:27
@tabacitu  hi this is not my topic, I closed (https://github.com/Laravel-Backpack/CRUD/issues/4326) mine when I saw the fix from @pxpm  https://github.com/Laravel-Backpack/CRUD/pull/4267

and I'm already using two of his PRs (very important to me), so it's still hard for me to update to new versions 😀(second https://github.com/Laravel-Backpack/CRUD/pull/4359)

but yes, in the current topic the problem is that the language does not change

**Closed** 2022-05-26 12:06 UTC
Labels: Bug, URGENT, Priority: MUST, Has Fix

**Comment by kartomantas** [comment] 2022-06-25 17:42
> Ouch! Looks like we badly misinterpreted this @guleswine , sorry it took so long to realise this! I now understand that:
> 
> * You're NOT talking about us pro-populated empty fields with the default language;
> * You're talking about a BUG here; that after you edit a translated entity (eg. Italian) you do not see the Italian strings, but the English ones; so it's broken;
> 
> We're working on it right now! Thank you so much, and sorry we misinterpreted this 🙏

Yes, that's exactly what I was talking about. Seems to be working now, thanks!
