### ISSUE TITLE
[Bug] table layout in show with too long string value

### ISSUE THREAD

**Issue by tree1891** [Laravel-Backpack/CRUD#3174] opened 2020-09-02 02:08 UTC
When long string value exists, show page's table layout is broken.
![image](https://user-images.githubusercontent.com/1282201/91924010-4adef800-ed04-11ea-8e31-508e0d47ce2c.png)

**Comment by pxpm** [comment] 2020-09-02 09:29
I am sorry @tree1891 I could not even know what is happening in here. 

Could you post a SS with a `small string` so it shows up correctly and I can compare with that one you provided ? 

From what it seems it shrinks the `header/title` columns ?

Best,
Pedro

**Comment by tree1891** [comment] 2020-09-02 14:07
This is result with limit length.
![image](https://user-images.githubusercontent.com/1282201/91994078-bf4b8280-ed68-11ea-9ab3-009deb7dd8aa.png)

**Comment by pxpm** [comment] 2020-09-04 20:59
Thank you @tree1891 , I am going to have a look at it in a few ... !

Best,
Pedro

**Comment by pxpm** [comment] 2020-09-07 14:12
@tree1891 

I am trying to reproduce your issue but I am unable to. 

Table explands verticaly and does not shrink the column names. 

Are you sure you are using the latest BP version with latest CSS/JS assets? 

This is what happens to my table when using a very long text:

![Screenshot_17](https://user-images.githubusercontent.com/7188159/92396110-5d9a6800-f11c-11ea-8268-39ffb1803f23.png)

Best,
Pedro

**Comment by tree1891** [comment] 2020-09-07 14:48
It seems cause of asia font.
![image](https://user-images.githubusercontent.com/1282201/92399048-39f71200-f15c-11ea-831e-1d683b24b5f2.png)

**Comment by pxpm** [comment] 2020-09-07 14:50
Sorry for that :| It must be annoying. 

Do you happen to know any solution for this ?

**Comment by tree1891** [comment] 2020-09-07 14:52
no, just limit length.

**Comment by tree1891** [comment] 2020-09-07 14:58
Would you like to check with 'トレーニング説明文' label and value?

**Comment by pxpm** [comment] 2020-09-07 15:05
Just did, here is the result:

![Screenshot_18](https://user-images.githubusercontent.com/7188159/92400412-ce914e00-f123-11ea-9a7d-9e73426246f6.png)

They don't shrink but it breaks on column breakpoint. 

Best,
Pedro

**Comment by tree1891** [comment] 2020-09-07 15:06
You can make long string by repeat 'トレーニング説明文'

**Comment by pxpm** [comment] 2020-09-07 15:16
![Screenshot_19](https://user-images.githubusercontent.com/7188159/92401404-7e1af000-f125-11ea-8cff-4f6f243edbc5.png)

**Comment by tree1891** [comment] 2020-09-07 15:20
Maybe it may depend on other label.

**Comment by tabacitu** [comment] 2020-10-15 14:13
Sorry @tree1891 since we weren't able to reproduce this, I'm going to close it for now. To be super-clear, this might still be a bug. But since
- we were not able to reproduce it 
- we have no idea what it's about

I'm going to close it, until you or someone else brings more information about it, so we can replicate & fix it.

I know it come off as dismissive - I assure you it's not. But we can't fix what we can't replicate. We will gladly reopen the issue when there's more information, enough so we can take this further towards a fix.

Cheers!

**Closed by tabacitu** 2020-10-15 14:13 UTC
Labels: Possible Bug, triage
