### ISSUE TITLE
[Bug] select2_from_ajax doesn't ever call the function to fetch data

### ISSUE THREAD

**Issue by lakridserne** [Laravel-Backpack/CRUD#4610] opened 2022-08-22 08:51 UTC
# Bug report
It seems that select2_from_ajax never calls the function to fetch data to the dropdown.

### What I did
After upgrading Backpack from version 3.6 to 5 (PRO), we have noticed that select2_from_ajax doesn't work. From debugging, it is apparent that the function `bpFieldInitSelect2FromAjaxElement()` is never called, and therefore there are never any data returned from any API endpoints.

We had this configuration:
`$this->crud->addField([
            'label'                => 'Mærke',
            'name'                 => 'brand_id',
            'type'                 => 'select2_from_ajax',
            'entity'               => 'brand',
            'attribute'            => 'name',
            'model'                => Brand::class,
            'data_source'          => url('api/brands/all'),
            'placeholder'          => 'Select a car brand',
            'minimum_input_length' => 0,
            'method'               => 'POST',
            'attributes'           => $this->disabledAttributes(),
            'tab'                  => self::TAB_1,
]);`

### What I expected to happen
I expected it would call the function and thereby the API endpoint.

### What happened
The API endpoint was never called.

### What I've already tried to fix it
I don't believe it's a thing I should fix since it's a bug in Laravel Backpack.

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 25 2022 08:13:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v9.19.0@bbce25bd823133f6a5a724f2d62680b711f1d0df

### BACKPACK VERSION:
5.1.2@a15f93a784e8d130f5ea5c3341fb7bca1f3c25e3

**Comment by pxpm** [comment] 2022-08-22 09:14
Hello @lakridserne 

Can you update to the latest Backpack version ? I am not sure that the version is the problem, I don't recall we doing big changes there, but who knows.

From my side I could not reproduce it:
![image](https://user-images.githubusercontent.com/7188159/185884599-2eea8819-ea94-48ad-987f-b8d72fa9fcf8.png)

Some other javascript errors popping up on console ? 

3.6 to 5 is quite a change, my bet for the error here would be some file you have overriden in your 3.6 project that needs to be update to 5 ... well I guess ALOT of files will need to be upgraded since you didn't updated 3.6>4>4.1>5.

The init function should be called on:
https://github.com/Laravel-Backpack/CRUD/blob/2d91f788c42504a04a5737af452207d6fece72ff/src/resources/views/crud/form_content.blade.php#L31

Those init functions need to be defined on field attributes too.

![image](https://user-images.githubusercontent.com/7188159/185885343-5f53c792-6d8f-48d7-908d-36deab8b7c94.png)

Let me know,

Cheers

**Comment by lakridserne** [comment] 2022-08-22 12:53
Hi @pxpm (and others)

Thanks for your reply.

Even though I tried running Backpack 5.3.4, it doesn't work still.

There are no Javascript errors at all.

There are no overrides for this particular file, and if I do console.log() directly in the vendor folder, I can see that it reaches the javascript part, but never touches the function itself.

You can see a screenshot of the HTML here:
![image](https://user-images.githubusercontent.com/419298/185925429-a84ae4eb-d1e4-4cef-ae11-207d1b78f620.png)

It seems I can't grab a screenshot with the dropdown open, but it only shows the value in the database, it does not have any other values at all. If I look at the API endpoint manually, I can get the data just fine.

**Comment by pxpm** [comment] 2022-08-23 10:21
Hey @lakridserne no issues, we are missing something here, let's try to figure out where. Can you `console.log(functionName)` in:
https://github.com/Laravel-Backpack/CRUD/blob/2d91f788c42504a04a5737af452207d6fece72ff/src/resources/views/crud/form_content.blade.php#L41

And also a console.log() in `select2_from_ajax.blade.php` field in the `function bpFieldInitSelect2FromAjaxElement()` function ? 

Cheers

**Comment by lakridserne** [comment] 2022-08-23 11:35
I put `console.log()` in both places. None of them put anything in the console unfortunately.

![image](https://user-images.githubusercontent.com/419298/186147934-afabf663-a10c-4791-ae59-e6906b78d2d0.png)

I also still don't have other options than the currently selected.

**Comment by pxpm** [comment] 2022-08-23 12:37
Does a `console.log()` reaches here: 
https://github.com/Laravel-Backpack/CRUD/blob/2d91f788c42504a04a5737af452207d6fece72ff/src/resources/views/crud/form_content.blade.php#L99 

What about before the input loop, does it reach:
https://github.com/Laravel-Backpack/CRUD/blob/2d91f788c42504a04a5737af452207d6fece72ff/src/resources/views/crud/form_content.blade.php#L38

 If your `console.log('functionName')` does not yield any result I guess NONE of your fields that need JS are beeing initialized, can you add any other field that uses the init function? (It could be any select2, or a repeatable, or color, some field that has the `init-function`. 

Maybe it's worth to see the `source of the page` and try to search if you can find the code we are talking about here, to make sure crud is including the correct files. 

I see you are using Firefox, may it be a browser compatibility issue ? Do you have a Chrome instance you can test on ? 

Cheers

**Comment by lakridserne** [comment] 2022-08-23 13:35
It seems it doesn't include the correct files - from having inspected the source and trying the things mentioned.

It has been tested in Chrome, and also on Windows machines instead of Linux along with Mac.

**Comment by pxpm** [comment] 2022-08-23 15:29
I am highly suspecting that is some misconfiguration from the upgrade process. 
Are you able to reproduce the issue in a new project ?

**Comment by lakridserne** [comment] 2022-08-24 10:51
@pxpm I can see that it definitely calls the JavaScript in a new clean project, so I think you are correct that it's something to do with the upgrade. However, I folllowed the upgrade guide completely, so a little help with figuring out what could possibly lead to it would be much appreciated.

**Comment by pxpm** [comment] 2022-08-24 20:33
Hey @lakridserne thank you for coming back with news. 
I've been trying it from the start, trying to help you the best I can. And I will continue as long as my ideas don't end, I don't quite remember everything that we changed since 3.6, sorry 😔

In the same project, a crud with only the select from ajax, still don't work? I am trying to figure out if it is some other field causing the issue. 

In case of positive answer, can you tell me what Backpack files you have overriden in your resources folder, if any?

Cheers

**Comment by lakridserne** [comment] 2022-08-25 14:54
@pxpm I'll start with the 2nd question since I think you are hitting it right on there. I suspect somewhere in there, that the problem lies. Unfortunately quite a few of the fields in the project have been overriden. However it might be that I just had published them for some reason, because I can see that I published them 4 months ago.

I have a list for you here:
- boolean
- checkbox
- checklist
- checklist_dependency
- checklist_grouped
- color
- custom_html
- date
- datetime
- email
- enum
- hidden
- month
- number
- password
- radio
- range
- select
- select_from_array
- select_grouped
- select_multiple
- select_page_template
- summernote
- text
- textarea
- time
- upload
- upload_multiple
- url
- user_checklist_dependency
- view
- week

I tried publishing the pro assets as well so it had a folder under `resources/views/vendor/backpack/pro` with fields. However, that didn't solve the problem.

It does not work in a crud with only a single select field.

**Comment by pxpm** [comment] 2022-08-25 15:03
Thank you, we will get there ;)

If it does not work without any other fields, the problem is not on the fields you have overriden we can forget about those for now.

What other files from Backpack you have overriden ? Like `form_content.blade.php` layouts etc, the "outter" files without beeing the fields/columns? 
As you said before, it is probably not including the correct `form_content` file, since in that file lives the script that call the init function on fields.

Did you published backpack assets when upgrading with `php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public` ? IF so, **make sure you do a backup** of the `/public` folder and try the same command adding the `--force` option as it will override previous assets. 

Let me know how it goes.

Cheers

**Comment by lakridserne** [comment] 2022-08-26 08:55
@pxpm I tried publishing all backpack assets with force as you suggested with the command above. When I tried that, it did not work unfortunately.

I tried clearing caches and building again, so it's not that.

**Comment by pxpm** [comment] 2022-08-29 08:26
Maybe you are binding you own `CrudPanel` class in the ServiceProvider and have some overriden functions ? 

When you cleared caches, you cleared config too? `php artisan config:clear` and also the views with `php artisan view:clear`? 

Can you post me the contents of the `form_content.blade.php` that is loaded ? 

Cheers

**Comment by lakridserne** [comment] 2022-08-31 10:11
@pxpm 
Sorry for the wait.

I think you are correct.

        // Fix backpack filter bug.
        $this->app->booting(function () {
            $loader = AliasLoader::getInstance();
            $loader->alias('Backpack\CRUD\PanelTraits\Filters', \App\Vendor\Backpack\CRUD\PanelTraits\Filters::class);
        });

I did run the above commands.

Here is the content of form_content.blade.php:

<input type="hidden" name="_http_referrer" value={{ session('referrer_url_override') ?? old('_http_referrer') ?? \URL::previous() ?? url($crud->route) }}>

{{-- See if we're using tabs --}}
@if ($crud->tabsEnabled() && count($crud->getTabs()))
    @include('crud::inc.show_tabbed_fields')
    <input type="hidden" name="_current_tab" value="{{ Str::slug($crud->getTabs()[0]) }}" />
@else
  <div class="card">
    <div class="card-body row">
      @include('crud::inc.show_fields', ['fields' => $crud->fields()])
    </div>
  </div>
@endif


{{-- Define blade stacks so css and js can be pushed from the fields to these sections. --}}

@section('after_styles')

    
    @stack('crud_fields_styles')

@endsection

@section('after_scripts')

    
    @stack('crud_fields_scripts')

    <script>
    function initializeFieldsWithJavascript(container) {
      var selector;
      if (container instanceof jQuery) {
        selector = container;
      } else {
        selector = $(container);
      }
      selector.find("[data-init-function]").not("[data-initialized=true]").each(function () {
        var element = $(this);
        var functionName = element.data('init-function');

        if (typeof window[functionName] === "function") {
          window[functionName](element);

          // mark the element as initialized, so that its function is never called again
          element.attr('data-initialized', 'true');
        }
      });
    }

    jQuery('document').ready(function($){

      // trigger the javascript for all fields that have their js defined in a separate method
      initializeFieldsWithJavascript('form');

      // Retrieves the current form data
      function getFormData() {
        return new URLSearchParams(new FormData(document.querySelector("main form"))).toString();
      }

      // Prevents unloading of page if form data was changed
      function preventUnload(event) {
        if (initData !== getFormData()) {
          // Cancel the event as stated by the standard.
          event.preventDefault();
          // Older browsers supported custom message
          event.returnValue = '';
        }
      }

      @if($crud->getOperationSetting('warnBeforeLeaving'))
      const initData = getFormData();
      window.addEventListener('beforeunload', preventUnload);
      @endif

      // Save button has multiple actions: save and exit, save and edit, save and new
      var saveActions = $('#saveActions'),
      crudForm        = saveActions.parents('form'),
      saveActionField = $('[name="_save_action"]');

      saveActions.on('click', '.dropdown-menu a', function(){
          var saveAction = $(this).data('value');
          saveActionField.val( saveAction );
          crudForm.submit();
      });

      // Ctrl+S and Cmd+S trigger Save button click
      $(document).keydown(function(e) {
          if ((e.which == '115' || e.which == '83' ) && (e.ctrlKey || e.metaKey))
          {
              e.preventDefault();
              $("button[type=submit]").trigger('click');
              return false;
          }
          return true;
      });

      // prevent duplicate entries on double-clicking the submit form
      crudForm.submit(function (event) {
        window.removeEventListener('beforeunload', preventUnload);
        $("button[type=submit]").prop('disabled', true);
      });

      // Place the focus on the first element in the form
      @if( $crud->getAutoFocusOnFirstField() )
        @php
          $focusField = Arr::first($fields, function($field) {
              return isset($field['auto_focus']) && $field['auto_focus'] == true;
          });
        @endphp

        @if ($focusField)
          @php
            $focusFieldName = isset($focusField['value']) && is_iterable($focusField['value']) ? $focusField['name'] . '[]' : $focusField['name'];
          @endphp
          window.focusField = $('[name="{{ $focusFieldName }}"]').eq(0),
        @else
          var focusField = $('form').find('input, textarea, select').not('[type="hidden"]').eq(0),
        @endif

        fieldOffset = focusField.offset().top,
        scrollTolerance = $(window).height() / 2;

        focusField.trigger('focus');

        if( fieldOffset > scrollTolerance ){
            $('html, body').animate({scrollTop: (fieldOffset - 30)});
        }
      @endif

      // Add inline errors to the DOM
      @if ($crud->inlineErrorsEnabled() && $errors->any())

        window.errors = {!! json_encode($errors->messages()) !!};

        $.each(errors, function(property, messages){

            var normalizedProperty = property.split('.').map(function(item, index){
                    return index === 0 ? item : '['+item+']';
                }).join('');

            var field = $('[name="' + normalizedProperty + '[]"]').length ?
                        $('[name="' + normalizedProperty + '[]"]') :
                        $('[name="' + normalizedProperty + '"]'),
                        container = field.parents('.form-group');
            
            // iterate the inputs to add invalid classes to fields and red text to the field container.
            container.children('input, textarea, select').each(function() {
                let containerField = $(this);
                // add the invalida class to the field.
                containerField.addClass('is-invalid');
                // get field container
                let container = containerField.parent('.form-group');
                
                // if container is a repeatable group we don't want to add red text to the whole group,
                // we only want to add it to the fields that have errors inside that repeatable.
                if(!container.hasClass('repeatable-group')){
                  container.addClass('text-danger');
                }
            });
            
            $.each(messages, function(key, msg){
                // highlight the input that errored
                var row = $('<div class="invalid-feedback d-block">' + msg + '</div>');
                row.appendTo(container);

                // highlight its parent tab
                @if ($crud->tabsEnabled())
                var tab_id = $(container).closest('[role="tabpanel"]').attr('id');
                $("#form_tabs [aria-controls="+tab_id+"]").addClass('text-danger');
                @endif
            });
        });

      @endif

      $("a[data-toggle='tab']").click(function(){
          currentTabName = $(this).attr('tab_name');
          $("input[name='_current_tab']").val(currentTabName);
      });

      if (window.location.hash) {
          $("input[name='_current_tab']").val(window.location.hash.substr(1));
      }

      });
    </script>
@endsection

**Comment by pxpm** [comment] 2022-08-31 14:25
If you `console.log()` inside this function:
```javascript
function initializeFieldsWithJavascript(container) {
console.log('here');
}
```
You don't get the log ?

It's called rigth after: 
```javscript
jQuery('document').ready(function($){

  // trigger the javascript for all fields that have their js defined in a separate method
  initializeFieldsWithJavascript('form');
```

**Comment by lakridserne** [comment] 2022-09-01 20:49
I think I gave you the wrong form_content.blade.php. I found one in the folder for the specific admin page in resources/views that has the below content:

`<input type="hidden" name="http_referrer" value={{ old('http_referrer') ?? \URL::previous() ?? url($crud->route) }}>

@if ($crud->model->translationEnabled())
<input type="hidden" name="locale" value={{ $crud->request->input('locale')?$crud->request->input('locale'):App::getLocale() }}>
@endif

{{-- See if we're using tabs --}}
@if ($crud->tabsEnabled() && count($crud->getTabs()))
    @include('admin.cars.show_tabbed_fields')
    <input type="hidden" name="current_tab" value="{{ Str::slug($crud->getTabs()[0], "") }}" />
@else
    <div class="box col-md-12 padding-10 p-t-20">
    @include('crud::inc.show_fields', ['fields' => $fields])
    </div>
@endif

{{-- Define blade stacks so css and js can be pushed from the fields to these sections. --}}

@section('after_styles')
    <link rel="stylesheet" href="{{ asset('vendor/backpack/crud/css/crud.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/backpack/crud/css/form.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/backpack/crud/css/'.$action.'.css') }}">

    
    @stack('crud_fields_styles')
    <style>
        .select2-container--bootstrap .select2-selection--single {
            padding: 8px 24px 6px 12px;
        }
    </style>
@endsection

@section('after_scripts')
    <script src="{{ asset('vendor/backpack/crud/js/crud.js') }}"></script>
    <script src="{{ asset('vendor/backpack/crud/js/form.js') }}"></script>
    <script src="{{ asset('vendor/backpack/crud/js/'.$action.'.js') }}"></script>

    
    @stack('crud_fields_scripts')

    <script>
    jQuery('document').ready(function($){

      // Save button has multiple actions: save and exit, save and edit, save and new
      var saveActions = $('#saveActions'),
      crudForm        = saveActions.parents('form'),
      saveActionField = $('[name="save_action"]');

      saveActions.on('click', '.dropdown-menu a', function(){
          var saveAction = $(this).data('value');
          saveActionField.val( saveAction );
          crudForm.submit();
      });

      // Ctrl+S and Cmd+S trigger Save button click
      $(document).keydown(function(e) {
          if ((e.which == '115' || e.which == '83' ) && (e.ctrlKey || e.metaKey))
          {
              e.preventDefault();
              // alert("Ctrl-s pressed");
              $("button[type=submit]").trigger('click');
              return false;
          }
          return true;
      });

      // prevent duplicate entries on double-clicking the submit form
      crudForm.submit(function (event) {
        $("button[type=submit]").prop('disabled', true);
      });

      // Place the focus on the first element in the form
      @if( $crud->getAutoFocusOnFirstField() )
        @php
          $focusField = Arr::first($fields, function($field) {
              return isset($field['auto_focus']) && $field['auto_focus'] == true;
          });
        @endphp

        @if ($focusField)
        @php
        $focusFieldName = !is_iterable($focusField['value']) ? $focusField['name'] : ($focusField['name'] . '[]');
        @endphp
          window.focusField = $('[name="{{ $focusFieldName }}"]').eq(0),
        @else
          var focusField = $('form').find('input, textarea, select').not('[type="hidden"]').eq(0),
        @endif

        fieldOffset = focusField.offset().top,
        scrollTolerance = $(window).height() / 2;

        focusField.trigger('focus');

        if( fieldOffset > scrollTolerance ){
            $('html, body').animate({scrollTop: (fieldOffset - 30)});
        }
      @endif

      // Add inline errors to the DOM
      @if ($crud->inlineErrorsEnabled() && $errors->any())

        window.errors = {!! json_encode($errors->messages()) !!};
        // console.error(window.errors);

        $.each(errors, function(property, messages){

            var normalizedProperty = property.split('.').map(function(item, index){
                    return index === 0 ? item : '['+item+']';
                }).join('');

            var field = $('[name="' + normalizedProperty + '[]"]').length ?
                        $('[name="' + normalizedProperty + '[]"]') :
                        $('[name="' + normalizedProperty + '"]'),
                        container = field.parents('.form-group');

            container.addClass('has-error');

            $.each(messages, function(key, msg){
                // highlight the input that errored
                var row = $('<div class="help-block">' + msg + '</div>');
                row.appendTo(container);

                // highlight its parent tab
                @if ($crud->tabsEnabled())
                var tab_id = $(container).parent().attr('id');
                $("#form_tabs [aria-controls="+tab_id+"]").addClass('text-red');
                @endif
            });
        });

      @endif

      $("a[data-toggle='tab']").click(function(){
          currentTabName = $(this).attr('tab_name');
          $("input[name='current_tab']").val(currentTabName);
      });

    });

    </script>
@endsection
`

**Comment by pxpm** [comment] 2022-09-02 08:00
There you are, you need to update that file or use the one in the package. 
I dunno why you overriden it, so if you still need the overriden code it would be probably better to identify it first, start from a clean form content from the package and merge your changes there.
I say that because that file is so old without the scripts that there are more things missing I am sure.
Let me know how it goes,
Cheers

**Comment by pxpm** [comment] 2022-09-02 09:55
I am going to close this @lakridserne as this is not a bug per-se.

Please keep the discussion going if you need my help with something, I still receive the notifications. 

Cheers

**Closed by pxpm** 2022-09-02 09:55 UTC
Labels: Wait Response

**Comment by lakridserne** [comment] 2022-09-02 14:06
Seems to work! Thank you so much
