### ISSUE TITLE
[Bug] Field fluent syntax doesn't work with relations?

### ISSUE THREAD

**Issue by ale1981** [Laravel-Backpack/CRUD#3971] opened 2021-12-01 15:24 UTC
# Bug report

### What I did

CrudController

This doesn't work...
```
            $this->crud->field('userDefined.test')
                ->type('boolean')                
                ->label('Test')
                ->entity('userDefined')
                ->attribute('test')
                ->model('App\Models\userDefined');
```

This does work...

```
            $this->crud->addField([
                'name' => 'userDefined.test',
                'type' => 'boolean',
                'label' => 'Test',
                'entity' => 'userDefined',
                'attribute' => 'test',
                'model' => 'App\Models\userDefined',
            ]);
```

### What I expected to happen

The field type and label to be as defined.

### What happened

The field type gets set to text and the label gets set to the field name.

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

Yes, running latest version.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.26 (cli) (built: Nov 22 2021 09:48:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.73.2@0e1c63315eeaee5920552ff042bd820bb4014533

### BACKPACK VERSION:
4.1.60@bec5cfa11f0cd0712c79256748acf5850080c0ee

**Comment by pxpm** [comment] 2021-12-02 14:48
Hello @ale1981 thanks for the contribution. 

I guess the `userDefined` is an `HasOne` relation. 

I could replicate your issue and found out that the problem is that we parse the `dot.notation` field names into `dot[notation]` names, and when using fluent syntax after changing the names the subsquent `->type()` etc calls would not find the field in the array of fields because it would check `userDefined.test` against `userDefined[test]`. 

I came up with https://github.com/Laravel-Backpack/CRUD/pull/3981 that aims to solve this problem by only changing field names at the time they are displayed in HTML. 

I am going to close this so we keep any discussion in this regard in the PR thread. 

Once again, thank you very much for the report. 

Pedro

**Closed by pxpm** 2021-12-02 14:48 UTC
Labels: triage, Possible Bug

**Comment by tabacitu** [comment] 2021-12-03 13:15
Thanks a lot for letting us know @ale1981 🙏  I had no idea this was happening.

Please take note that the fixing this will most likely be considered a small breaking change, so we'll only launch it in 4.2 (due in about 3 weeks). Until then, please use the array syntax for this particular use case.

Please let us know if you find any other inconsistencies like this 🙏
Cheers!

**Comment by ale1981** [comment] 2021-12-03 15:53
No problem, glad to help.
