### ISSUE TITLE
[4.0][Bug]Div class being generated for each input when wrapperAttributes on non tabbed field when tab is being used in any field.

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2145] opened 2019-10-11 13:31 UTC
```
 $this->crud->addFields([
            [
                'name' => 'no_processo',
                'label' => "Numero do Processo",
                'type' => 'number',
                'wrapperAttributes' => [
                    'class' => 'form-group col-md-6',

                ],
            ],
            [
                'name' => 'no_processo_ant',
                'label' => "Numero do Processo Anterior",
                'type' => 'number',
                'wrapperAttributes' => [
                    'class' => 'form-group col-md-6',


                ],
            ],
        ]);

```
I'm trying to place 2 inputs in the same column, but in html code it creates a div for each input which it does not make this possible. How can I place the inputs in the same div?

**Comment by jsvini** [comment] 2019-10-11 18:19
@samuk190  I don't think that is possible to remove the div, because is part of the field template:

https://github.com/Laravel-Backpack/CRUD/blob/4.0.7/src/resources/views/crud/fields/number.blade.php#L2

Can you explain why do you need to put both fields in the same column?

**Comment by johnpuddephatt** [comment] 2019-10-11 19:21
looking at the comment and screenshot here #192 I think they might mean same row?

**Comment by samuk190** [comment] 2019-10-12 00:34
> @samuk190 I don't think that is possible to remove the div, because is part of the field template:
> 
> https://github.com/Laravel-Backpack/CRUD/blob/4.0.7/src/resources/views/crud/fields/number.blade.php#L2
> 
> Can you explain why do you need to put both fields in the same column?

Sorry I think I didnt explained well. 

when I'm using form-group col-md-6 the space should split into 2 columns and fit another field that have the same form-group col-md-6 attribute.

It does not work.

however it works if:
I place it on ANY tab eg:
```
   'name' => 'no_processo_ant',
                'label' => "Numero do Processo Anterior",
                'type' => 'number',
                 'tab' => 'test',
                'wrapperAttributes' => [
                    'class' => 'form-group col-md-6',
                

```
I'm not sure why the behaviour is different

**Comment by samuk190** [comment] 2019-10-12 00:38
> looking at the comment and screenshot here #192 I think they might mean same row?

Yes, I'm not being able to put two fields in the same row if I dont use 'tab' attribute on addfield

**Comment by tabacitu** [comment] 2019-10-12 06:10
@samuk190 that's weird - it worked for me, both with tabs and without, and it works inside the PageManager package without tabs:
![Screenshot 2019-10-12 at 09 05 54](https://user-images.githubusercontent.com/1032474/66695944-e96b0080-eccf-11e9-8f01-ccc95fa63be4.png)

```php
        $this->crud->addField([
            'name' => 'template',
            'label' => trans('backpack::pagemanager.template'),
            'type' => 'select_page_template',
            'view_namespace'  => 'pagemanager::fields',
            'options' => $this->getTemplatesArray(),
            'value' => $template,
            'allows_null' => false,
            'wrapperAttributes' => [
                'class' => 'form-group col-md-6',
            ],
        ]);
        $this->crud->addField([
            'name' => 'name',
            'label' => trans('backpack::pagemanager.page_name'),
            'type' => 'text',
            'wrapperAttributes' => [
                'class' => 'form-group col-md-6',
            ],
            // 'disabled' => 'disabled'
        ]);
```

So it should work. Please try:
- running a ```php artisan view:clear```
- running a ```composer update``` to make sure you have the latest Backpack version

Other than that... not sure what to recommend.

**Comment by samuk190** [comment] 2019-10-12 13:18
> @samuk190 that's weird - it worked for me, both with tabs and without, and it works inside the PageManager package without tabs:
> ![Screenshot 2019-10-12 at 09 05 54](https://user-images.githubusercontent.com/1032474/66695944-e96b0080-eccf-11e9-8f01-ccc95fa63be4.png)
> 
> ```
>         $this->crud->addField([
>             'name' => 'template',
>             'label' => trans('backpack::pagemanager.template'),
>             'type' => 'select_page_template',
>             'view_namespace'  => 'pagemanager::fields',
>             'options' => $this->getTemplatesArray(),
>             'value' => $template,
>             'allows_null' => false,
>             'wrapperAttributes' => [
>                 'class' => 'form-group col-md-6',
>             ],
>         ]);
>         $this->crud->addField([
>             'name' => 'name',
>             'label' => trans('backpack::pagemanager.page_name'),
>             'type' => 'text',
>             'wrapperAttributes' => [
>                 'class' => 'form-group col-md-6',
>             ],
>             // 'disabled' => 'disabled'
>         ]);
> ```
> 
> So it should work. Please try:
> 
> * running a `php artisan view:clear`
> * running a `composer update` to make sure you have the latest Backpack version
> 
> Other than that... not sure what to recommend.

Thanks for your answer, I guess the problem is I was using backpack base which cause some conflicts

**Comment by samuk190** [comment] 2019-10-14 12:31
> @samuk190 that's weird - it worked for me, both with tabs and without, and it works inside the PageManager package without tabs:
> ![Screenshot 2019-10-12 at 09 05 54](https://user-images.githubusercontent.com/1032474/66695944-e96b0080-eccf-11e9-8f01-ccc95fa63be4.png)
> 
> ```
>         $this->crud->addField([
>             'name' => 'template',
>             'label' => trans('backpack::pagemanager.template'),
>             'type' => 'select_page_template',
>             'view_namespace'  => 'pagemanager::fields',
>             'options' => $this->getTemplatesArray(),
>             'value' => $template,
>             'allows_null' => false,
>             'wrapperAttributes' => [
>                 'class' => 'form-group col-md-6',
>             ],
>         ]);
>         $this->crud->addField([
>             'name' => 'name',
>             'label' => trans('backpack::pagemanager.page_name'),
>             'type' => 'text',
>             'wrapperAttributes' => [
>                 'class' => 'form-group col-md-6',
>             ],
>             // 'disabled' => 'disabled'
>         ]);
> ```
> 
> So it should work. Please try:
> 
> * running a `php artisan view:clear`
> * running a `composer update` to make sure you have the latest Backpack version
> 
> Other than that... not sure what to recommend.

I removed the override views folder and still same problem, strange... what files could modify the behaviour of the field?

**Comment by samuk190** [comment] 2019-10-14 12:35
> > @samuk190 that's weird - it worked for me, both with tabs and without, and it works inside the PageManager package without tabs:
> > ![Screenshot 2019-10-12 at 09 05 54](https://user-images.githubusercontent.com/1032474/66695944-e96b0080-eccf-11e9-8f01-ccc95fa63be4.png)
> > ```
> >         $this->crud->addField([
> >             'name' => 'template',
> >             'label' => trans('backpack::pagemanager.template'),
> >             'type' => 'select_page_template',
> >             'view_namespace'  => 'pagemanager::fields',
> >             'options' => $this->getTemplatesArray(),
> >             'value' => $template,
> >             'allows_null' => false,
> >             'wrapperAttributes' => [
> >                 'class' => 'form-group col-md-6',
> >             ],
> >         ]);
> >         $this->crud->addField([
> >             'name' => 'name',
> >             'label' => trans('backpack::pagemanager.page_name'),
> >             'type' => 'text',
> >             'wrapperAttributes' => [
> >                 'class' => 'form-group col-md-6',
> >             ],
> >             // 'disabled' => 'disabled'
> >         ]);
> > ```
> > 
> > 
> > So it should work. Please try:
> > 
> > * running a `php artisan view:clear`
> > * running a `composer update` to make sure you have the latest Backpack version
> > 
> > Other than that... not sure what to recommend.
> 
> I removed the override views folder and still same problem, strange... what files could modify the behaviour of the field?

I tested with a different controller it works lol so I think I need to recreate everything :(

**Comment by samuk190** [comment] 2019-10-14 13:07
@tabacitu Ok I DISCOVERED THE BUG! If you add any Field Table into the view it will cause the wrapper atribute to not work on OTHER FIELDS! Try yourself my code
 ```
 $this->crud->addField([
            'name' => 'template',
            'label' => trans('backpack::pagemanager.template'),
            'type' => 'select_page_template',
            'view_namespace'  => 'pagemanager::fields',
            'options' => $this->getTemplatesArray(),
            'value' => $template,
            'allows_null' => false,
            'wrapperAttributes' => [
                'class' => 'form-group col-md-6',
            ],
        ]);
        $this->crud->addField([
            'name' => 'name',
            'label' => trans('backpack::pagemanager.page_name'),
            'type' => 'text',
            'wrapperAttributes' => [
                'class' => 'form-group col-md-6',
            ],
            // 'disabled' => 'disabled'
        ]);


  $this->crud->addField(
            [ // Table
                'name' => 'lawyers_intern',
                'label' => 'Advogados Internos',
                'type' => 'table',
                'tab' => 'Advogados Internos',
                'entity_singular' => '', // used on the "Add X" button
                'columns' => [
                    'titular' => 'Advogado Titular',
                    'advogado' => 'Nome do Advogado',

                ],
                'max' => 10, // maximum rows allowed in the table
                'min' => 0, // minimum rows allowed in the table
            ]
        );
```

**Comment by pxpm** [comment] 2019-11-12 14:18
Hello guys. 

Thanks for bringing this up to our atention. 

Indeed I have confirmed an odd behaviour as i described in my review of #2181 

I will be closing this issue as there is already a PR to fix it, any further conversation should be moved there. 

Thanks again @samuk190 for bring this up @johnpuddephatt  and @jsvini for your help and @DiyanDesigns for the PR.

Best,
Pedro

**Closed by pxpm** 2019-11-12 14:18 UTC
Labels: triage
