### ISSUE TITLE
[3.6][Bug] Details row stays in the table after the item is deleted

### ISSUE THREAD

**Issue by st3r30t1p** [Laravel-Backpack/CRUD#1541] opened 2018-07-13 08:48 UTC
If you open the details row in the list and after deleting the row, the details do not disappear as a row

**Comment by tabacitu** [comment] 2018-07-13 09:15
![screen recording 2018-07-13 at 12 14 pm](https://user-images.githubusercontent.com/1032474/42683584-5cb739d8-8696-11e8-97b9-7b021d26bdb5.gif)


Confirmed! Thank you for reporting this @st3r30t1p !

**Comment by tabacitu** [comment] 2019-08-20 07:22
The issue has been fixed since July 21st 2018, thanks to @promatik 's PR. Closing. 
Thanks for reporting this @st3r30t1p , and fixing it @promatik !

**Closed by tabacitu** 2019-08-20 07:22 UTC
Labels: bug, good first issue, non breaking change
