### ISSUE TITLE
[Bug] Column visibility display bug with responsive table

### ISSUE THREAD

**Issue by jrbecart** [Laravel-Backpack/CRUD#3539] opened 2021-02-18 20:06 UTC
# Bug report

### What I did

Open the monster demo: https://demo.backpackforlaravel.com/admin/monster
Hide all column but keep one "Text" (for example)
![image](https://user-images.githubusercontent.com/11264667/108414739-94f85f00-71fa-11eb-847b-fd72759ed075.png)

Do search, for example "Minus"
![image](https://user-images.githubusercontent.com/11264667/108414800-a6416b80-71fa-11eb-85ae-7e6fdb8f7867.png)

Show (select) columns until "Number"
![image](https://user-images.githubusercontent.com/11264667/108414677-83af5280-71fa-11eb-9de6-e24dddfd94e8.png)

### What I expected to happen

Display all possible columns, then add ... in the first column

### What happened

Display all possible columns, then add ... in the first column, then add the "Number" column values under the "Actions" columns header 
![image](https://user-images.githubusercontent.com/11264667/108414921-cbce7500-71fa-11eb-937b-3d8de496d870.png)

### What I've already tried to fix it

Tried to see where can be the bug with backpack and datatables.net with no luck :(

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.23 (cli) (built: Oct 13 2020 10:38:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.23, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v7.29.3@93f6d565a07045baa0e4b941ae1f733cd5984d65

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7

**Comment by pxpm** [comment] 2021-02-19 11:55
Hello @jrbecart thanks for the report. 

![image](https://user-images.githubusercontent.com/7188159/108500966-79e42880-72a8-11eb-85ba-83091bd205f8.png)

I can confirm the error, I don't necessarily need to go into `Number` column, it depends on viewport size. Nor also have anything in search.

What seems that is happening is that if the `column` is empty the responsive plugin hides it but if it has some value like `-`, the responsive plugin don't hide it.

This part is very tricky, I think it's what I dislike more in CRUD atm, is the datatable dependency. We have other errors related to it. We have plans to move away from it, but until then it's such a pain to maintain. 

I will have a deeper look to try to figure out why are columns not beeing hidden.

Best,
Pedro

**Comment by jrbecart** [comment] 2021-02-19 16:51
Thank you for your help, you put me in the right direction.
I was looking in the button plugin (for column visibility) but you are right it's in the responsive one.

If you update the responsive plugin it seems to fix it!

```html
  <script type="text/javascript" src="//cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.js"></script>
  <script type="text/javascript" src="//cdn.datatables.net/responsive/2.2.7/js/responsive.bootstrap4.min.js"></script>
```

**Comment by promatik** [comment] 2021-03-01 00:30
@jrbecart I can confirm the update on that libs solves the problem.
Tomorrow I'll talk with @tabacitu about this 👌

**Comment by pxpm** [comment] 2021-03-04 11:51
Hello guys.

Just to let you know that I tested this too with the updated version and it seems to be fixed. FYI we are using v2.2.5

I'v just created PR https://github.com/Laravel-Backpack/CRUD/pull/3589 to update versions.

Let me know,
Pedro

**Comment by promatik** [comment] 2021-03-04 23:55
Hi @jrbecart, this issue is now being addressed, and **it will probably be fixed on the next release**.

Once this is merged, note that since this fix requires new assets you'll probably need to publish them on your project with the command;
```php
php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --force
```

Also note the flag `--force` will force the replace of your existing assets, thus any change you've done to any of those files.

I'll close this issue for now, you can follow the progress on this on #3594.
Thank you once again for the help you gave by providing the fix for the issue 🙌

**Closed by promatik** 2021-03-04 23:55 UTC
Labels: Bug
