### ISSUE TITLE
[Bug] Image field cannot be used with big sized image

### ISSUE THREAD

**Issue by mahasadhu** [Laravel-Backpack/CRUD#3457] opened 2021-01-11 13:35 UTC
# Bug report

### What I did

I made a crud controller using `image` field. Here's the image field's declaration:
```
CRUD::field('featured_image')
            ->type('image')
            ->label('Featured Image')
            ->crop(true)
            ->aspect_ratio(1.96)
            ->disk('public');
```

### What I expected to happen

Image cropped and uploaded as usual

### What happened

for some reason when I use images with big size or big resolution, it returns error 404 method not found for `POST /admin/{entity}/{primary_key}`

![image](https://user-images.githubusercontent.com/13914485/104188643-8036e780-5454-11eb-889b-3919ee7d9b40.png)

![image](https://user-images.githubusercontent.com/13914485/104188831-ce4beb00-5454-11eb-932a-b2da859137af.png)

![image](https://user-images.githubusercontent.com/13914485/104188906-e58ad880-5454-11eb-8b41-0242ebeb5da6.png)

### What I've already tried to fix it

- resize the image to small resolution (around 700-800px width) so backpack won't return 404 error. (always works)
- convert the image to .jpg (sometimes still return 404 error, intermittent)

And also, this is error is not showing in my local machine. So this is either because of server error, connection (images took some time to upload to server, unlike in localhost), or the particular image problem

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

# Local:

### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.19.0@f5f331cee60f1bbe672503b7eb9ba5b22b2ceacb

### BACKPACK VERSION:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

# Server:

### PHP VERSION:
PHP 7.4.13 (cli) (built: Nov 25 2020 21:00:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.19.0@f5f331cee60f1bbe672503b7eb9ba5b22b2ceacb

### BACKPACK VERSION:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

**Comment by mahasadhu** [comment] 2021-01-11 13:37
I haven't got free time to inspect this, I'll add some more information later if I've found something useful

**Comment by promatik** [comment] 2021-01-20 20:40
Hi @mahasadhu!
The error looks like to be a server limitation, I tried to reproduce the error, first I tried to upload an image with 39Mb, 8000x5350px, and it worked nice (JPG and PNG).

Since this field works by generating the base64 of the image, it has a huge impact on server memory and post max size.
So by scale down any of those php variables `post_max_size` and `memory_limit` on `php.ini` **I was able to blow up the server.**

Can you please make sure your server has high values on this settings and tell us the results?

**Comment by mahasadhu** [comment] 2021-01-21 03:13
hi @promatik 

Yes I've tried to change the `post_max_size` , `upload_max_filesize` and `memory_limit` on `php.ini` to like 1GB but no luck.

Other thing that I've tried is to change the intervention driver from `gd` to `Imagick`, but still no luck. But thanks to this issue I have to learn to install `Imagick` to the server, and now it feels quicker when resizing / compressing images 🤣 

The main problem is, why does the backpack / laravel returns error `404` instead of like the server saying "oops, can't do dat" with `500`ish error code.
It's like as if something is not initialized properly, most probably the routes (CMIIW). 
Or maybe somewhere in the code there is a wild `abort(404)` code waiting to jump on us

But then again I'm sorry I can't provide more information regarding this issue yet.

**Comment by mahasadhu** [comment] 2021-01-21 03:13
Oh! And sometimes (highly less frequent), the error is `419` session expired, but when I refresh the page the session is still there.

Sorry I forgot to mention earlier

**Comment by promatik** [comment] 2021-01-24 01:28
@mahasadhu don't know if you use it or not, maybe laravel debugbar can help out a lot debugging this problem.
You can grab the specific past request that's returning 404 and analise everything on it.
Take a look at this sample;

https://user-images.githubusercontent.com/1838187/105618791-36021e80-5de3-11eb-81cc-5fba207af8cd.mp4

**Comment by mahasadhu** [comment] 2021-01-24 05:47
@promatik Ah of course! why haven't I think of this 🤦‍♂️ 

I used to use debugbar, but iirc it has some problems to the chart widget? So I haven't use debugbar for quite a while.

I will try it this week and I'll report you my findings, if any, hopefully

Thanks!

**Comment by pxpm** [comment] 2021-01-24 12:11
Hello @mahasadhu 

The debugbar bug with charts had already been fixed: https://github.com/Laravel-Backpack/CRUD/pull/3266

Best,
Pedro

**Comment by mahasadhu** [comment] 2021-01-25 01:52
Ah I see! Thank you for the info @pxpm

**Comment by promatik** [comment] 2021-02-03 23:40
@mahasadhu I'm going to close this issue for now, if you find out more about this please share with us 🙌
And if this is indeed a problem with backpack, we reopen the issue ✌

**Closed by promatik** 2021-02-03 23:40 UTC
Labels: needs-more-info, triage

**Comment by mahasadhu** [comment] 2021-02-04 03:47
Sorry I haven't got any time to test thoroughly, thanks @promatik will reopen again when I got new info about this

**Comment by mahasadhu** [comment] 2021-02-10 07:59
hi @promatik 

sorry I was quite busy last week, today I've just got time to install laravel debugbar to staging environment in server

And I found something. For some reason, when that error happened, laravel do not use the backpack routes (custom.php). Instead it loads the frontend routes (web.php file).
![image](https://user-images.githubusercontent.com/13914485/107479748-8389d400-6bb6-11eb-9bd1-6adf9049675b.png)

Here's the code in the web.php for the catch all route `PageController`

```
Route::get('{page}/{subs?}', ['uses' => '\App\Http\Controllers\Frontend\PageController@index'])
    ->where(['page' => '^(((?=(?!admin))(?=(?!\/)).))*$', 'subs' => '.*']);
```

So basically laravel was trying to find the `manage` slug from the frontend's `PageController` class, which is undefined.

--------------------------------------------------------------

**HOWEVER**, when I tried to comment out the `{page}/{subs?}` route, the error changed to 405

![image](https://user-images.githubusercontent.com/13914485/107480572-c304f000-6bb7-11eb-9199-6ba3c2d8feb8.png)

This is so strange, which part of the code redirects me to that unknown URL with GET method ?

It is only happening in the web server, I still cannot reproduce it in my local machine, even though I'm using the same big-sized image

server configuration:
php memory limit 512
post max size 256
upload max size 256

**Comment by mahasadhu** [comment] 2021-02-10 08:36
I found this in the rendered `/edit` page in backpack

![image](https://user-images.githubusercontent.com/13914485/107484632-aa97d400-6bbd-11eb-9207-6f93e65bbf0a.png)

And in the network tab, 

![image](https://user-images.githubusercontent.com/13914485/107484855-f9456e00-6bbd-11eb-911a-6b6a5872b005.png)

Is that how backpack actually is telling the form method here? 
Or am I missing something?

**Comment by mahasadhu** [comment] 2021-02-23 03:24
@promatik I found it!!

The problem was in PHP's `apcu` and `opcache` extension!

When I disabled those two extensions, the big image uploads normally

Additionally, in some shared hosting provider sometimes they use ModSecurity (https://modsecurity.org/). That also needs to be disabled in order the image fields to work.

What do you think about this @promatik ?

I'll report later when I found another conflicting things with Backpack

**Comment by promatik** [comment] 2021-02-23 10:34
Hi @mahasadhu!
Great, glad you found it 🙌

I searched for it and makes some sense to be the root cause of the problem, both [`apcu`](https://www.php.net/manual/en/intro.apcu.php), [`opcache`](https://www.php.net/manual/en/intro.opcache.php) are cache systems.
> _APCu is an in-memory key-value store for PHP. Keys are of type string and values can be any PHP variables. APCu only supports userland caching of variables._

> _OPcache improves PHP performance by storing precompiled script bytecode in shared memory, thereby removing the need for PHP to load and parse scripts on each request._

Since it's a cache system, the images are probably crossing that storage and for being so big it occupies a lot of space on RAM, and that explain the irregularity of situation, some times it breaks other it don't because the amount of available RAM on the machine also varies.

I'm not sure if it makes sense to add this to docs, because it's a rare problem, if anyone has it they may reach this post and find your answer 🙌
But I'll let @tabacitu decide on that.

Thank you for the time you spent on this @mahasadhu 🎉

**Comment by mahasadhu** [comment] 2021-02-24 02:38
No problem @promatik 🤝 
Yea it could be, since the `image` field send the image as base64 string (CMIIW).

Understood, if you need me to update the issue title so it can be more easily searched, just tell me.

I've also tried to find how to disable those extensions programmatically, but so far no success 😅 
I'll post later if I got any ways to work around it.

Thank you!

**Comment by promatik** [comment] 2021-02-24 19:42
@mahasadhu end up creating the PR, thinking about it twice, it may help some 😅
https://github.com/Laravel-Backpack/docs/pull/239

**Comment by ShaungBhone** [comment] 2021-12-06 16:09
Hello, I have the same issues. But I using docker. So where am I find apcu through Docker?

> PHP version
PHP 8.1.0 (cli) (built: Nov 25 2021 20:22:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans
