### ISSUE TITLE
OutOfBoundsException  : Required package "backpack/crud" is not installed: cannot detect its version

### ISSUE THREAD

**Issue by itelmenko** [Laravel-Backpack/CRUD#2146] opened 2019-10-11 17:46 UTC
# Bug report

### What I did

Using this manual  https://backpackforlaravel.com/docs/4.0/installation 
Try to install

```
➜  myproject git:(master) composer require backpack/crud:"4.0.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 10 installs, 0 updates, 1 removal
  - Removing laravel/ui (v1.1.1)
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing venturecraft/revisionable (1.32.0): Downloading (100%)         
  - Installing prologue/alerts (0.4.5): Downloading (100%)         
  - Installing laravel/helpers (v1.1.1): Downloading (100%)         
  - Installing intervention/image (2.5.0): Downloading (100%)         
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/dbal (v2.9.2): Loading from cache
  - Installing creativeorange/gravatar (v1.0.13): Downloading (100%)         
  - Installing backpack/crud (4.0.8): Downloading (100%)         
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   OutOfBoundsException  : Required package "backpack/crud" is not installed: cannot detect its version

  at /home/igor/projects/myproject/vendor/ocramius/package-versions/src/PackageVersions/Versions.php:145
    141|         if (isset(self::VERSIONS[$packageName])) {
    142|             return self::VERSIONS[$packageName];
    143|         }
    144| 
  > 145|         throw new \OutOfBoundsException(
    146|             'Required package "' . $packageName . '" is not installed: cannot detect its version'
    147|         );
    148|     }
    149| }

  Exception trace:

  1   PackageVersions\Versions::getVersion("backpack/crud")
      /home/igor/projects/myproject/vendor/backpack/crud/src/config/backpack/base.php:145

  2   require("/home/igor/projects/myproject/vendor/backpack/crud/src/config/backpack/base.php")
      /home/igor/projects/myproject/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:63

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

```

### What I expected to happen

Correct installation

### What happened

Error ` OutOfBoundsException  : Required package "backpack/crud" is not installed: cannot detect its version`

### Backpack, Laravel, PHP, DB version

backpack/crud (4.0.8), Laravel v6.2.0, PHP 7.2.19, MySQL 5.7.27

When I run ```php artisan backpack:version``` the output is:

```
  OutOfBoundsException  : Required package "backpack/crud" is not installed: cannot detect its version

  at /home/igor/projects/statgui/vendor/ocramius/package-versions/src/PackageVersions/Versions.php:144
    140|         if (isset(self::VERSIONS[$packageName])) {
    141|             return self::VERSIONS[$packageName];
    142|         }
    143| 
  > 144|         throw new \OutOfBoundsException(
    145|             'Required package "' . $packageName . '" is not installed: cannot detect its version'
    146|         );
    147|     }
    148| }

  Exception trace:

  1   PackageVersions\Versions::getVersion("backpack/crud")
      /home/igor/projects/statgui/vendor/backpack/crud/src/config/backpack/base.php:145

  2   require("/home/igor/projects/statgui/vendor/backpack/crud/src/config/backpack/base.php")
      /home/igor/projects/statgui/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:63

  Please use the argument -v to see more details.
```

**Comment by itelmenko** [comment] 2019-10-11 18:10
I have tried to remove the vendor folder and do `composer install`.
Look like it works now

```
php artisan backpack:version     
### PHP VERSION:
PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.2.0     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.8      Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
```

**Comment by tabacitu** [comment] 2019-10-12 05:18
Hi @itelmenko ,

This is very weird: ```ocramius/package-versions``` which checks for package version is required by ```backpack/crud```. So there's NO WAY that ```ocramius/package-versions``` can be installed, and ```backpack/crud``` NOT be installed. Very weird. I couldn't get the same thing myself, always worked for me:
![Screenshot 2019-10-12 at 08 17 28](https://user-images.githubusercontent.com/1032474/66695311-cee15900-ecc8-11e9-9520-ec60ca02900b.png)


I'm glad you found a solution to this - I'll close the issue since I can't reproduce it, but I'll keep my eye on this thread, in case anybody else runs into the same problem. Thanks for reporting this!

**If this happened to you too, please reply here to let us know.**

Cheers!

**Closed by tabacitu** 2019-10-12 05:18 UTC
Labels: triage

**Comment by mobielbekeken-jan** [comment] 2021-06-10 07:02
i just updated laravel ( 6 to 8) and backpack from 4.0 to 4.1 and got a similar error, if this aint the right issue i will make a new one. Here is my error log:

```
[2021-06-10 08:59:17] local.ERROR: Package "backpack/crud" is not installed {"exception":"[object] (OutOfBoundsException(code: 0): Package \"backpack/crud\" is not installed at /MASKED/other/import/vendor/composer/InstalledVersions.php:159)
[stacktrace]
#0 //MASKED//vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(191): Composer\\InstalledVersions::getPrettyVersion('backpack/crud')
#1 //MASKED//config/backpack/base.php(168): PackageVersions\\Versions::getVersion('backpack/crud')
```
