### ISSUE TITLE
[4.0]Change Status in Save Data Button "Save and New" to "Save and Back"

### ISSUE THREAD

**Issue by Ramaniks** [Laravel-Backpack/CRUD#2147] opened 2019-10-11 22:31 UTC
# Bug report or not

### What I did

Save Actions not save status with "save_and_new" and after change to "save_and_back". Just stay "save_and_new". Add data and click "Save and Back" works.

### What I expected to happen

Change the button status to "Save and New", save data and open another form, add data, save with "Save and Back" load the list of the data. In the case two line.

### What happened

I create new project Laravel, add backpack/crud and execute this command:
php artisan make:migration:schema create_tags_table --model=0 --schema="name:string:unique"
php artisan migrate
php artisan backpack:crud tag

And to access the link http://myproject.test/admin/tag, click to create a new Tag and write tag text a change button to "save_and_new", add another text and change to "save_and_back". Show the message for indicator of the change but opened the form to add another tag, and another, another...

### What I've already tried to fix it

I didn't try anything

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
[### PHP VERSION:]
PHP 7.2.11 (cli) (built: Oct 10 2018 02:04:07) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

[### LARAVEL VERSION:]
laravel/framework                     v6.2.0     The Laravel Framework.

[### BACKPACK VERSION:]
backpack/crud                         4.0.8      Quickly build an admin interfaces using Laravel 6, CoreUI, Boos...
backpack/generators                   2.0.4      Generate files for laravel projects
backpack/permissionmanager            5.0.1      Users and permissions management interface for Laravel 5 using ...

**Comment by pxpm** [comment] 2019-11-14 12:23
Hello @Ramaniks ,

Sorry for late reply, it has been busy times. 

If i understood your problem it's not a bug indeed. It's the way CRUD works.

`Save and Back` allways return you to the page you were previously like the name says. If you went from a `create page` to `another create page`, the `back route` will be your **first** create page.

It's planned however the ability to allow developers to change the save actions in this PR #658 

I will get into that PR when time allows, meanwhile you can give your thoughts on the matter in the PR thread. 

I will be closing this, issue. If you think i might be wrong please re-open it :)

Best,
Pedro

**Closed by pxpm** 2019-11-14 12:23 UTC
Labels: question

**Comment by ssimo3lsuhsc** [comment] 2020-01-27 16:18
There should be no "Save and Back." There should be two options: "Save and List" or "Save and Preview." "Save and List" should be the default when the user logs in.

**Comment by pxpm** [comment] 2020-01-27 16:25
Hello @ssimo3lsuhsc ! We are working on a way of making save actions configurable. Have a look if you need the code asap, i think it's bug free, but give it a try and feedback if possible :) #2356

Also you can change default save action in crud config file. Have a look: https://github.com/Laravel-Backpack/CRUD/blob/745c0869e48ed14592a0fa85f716ea6a2e30bca4/src/config/backpack/crud.php#L77

Best,
Pedro
