### ISSUE TITLE
[Bug] spinner asset on tables

### ISSUE THREAD

**Issue by malek77z** [Laravel-Backpack/CRUD#5185] opened 2023-07-05 15:04 UTC
# Bug report

On the list page table loading, the spinner is broken.
The source of this is how the processing image is loaded in datatables_logic.blade.php line 237

```
              "processing":     "<img src='{{ asset('storage/basset/vendor/backpack/crud/src/resources/assets/img/spinner.svg') }}' alt='{{ trans('backpack::crud.processing') }}'>",

```

Note, line 16 seems to be trying to load or store the same asset:

```
  @basset(base_path('vendor/backpack/crud/src/resources/assets/img/spinner.svg'))
```
though basset, but its not showing up anywhere.

### What I did

This should be seen on any list page, although hard to see as data loads in soon after.

### What I expected to happen

spinner to show

### What happened

Spinner does not show and has broken image instead. Also confirmed no basset file was created

### What I've already tried to fix it

I'm just changing to my version datatables_logic.blade.php for now, so there is a work around

**Comment by tabacitu** [comment] 2023-07-11 09:44
Hi @malek77z ,

That is odd. It seems to be working for me, both on local and in our online demo:

![CleanShot 2023-07-11 at 10 42 24](https://github.com/Laravel-Backpack/CRUD/assets/1032474/48b6a8ab-d273-4823-8d98-6ac79996e590)

(1) Are you having the same problem in our online demo too? https://demo.backpackforlaravel.com/admin/article

(2) Are you seeing any JS errors in your Chrome DevTools?

(3) How about after a `php artisan basset:fresh`? Still having this problem?

Cheers!

**Comment by tabacitu** [comment] 2023-07-20 07:42
Sorry @malek77z since I couldn't reproduce this problem, I'm going to close this issue. If you're still having this problem, please reply with answers to the 4 questions above and I'm happy to take another look.

Cheers!

**Closed by tabacitu** 2023-07-20 07:42 UTC
Labels: triage

**Comment by tungfinblox** [comment] 2024-04-08 23:14
Hello!

On my local this is what happened
![image](https://github.com/Laravel-Backpack/CRUD/assets/96406390/010aa4b9-224b-434e-8111-f440c06cd0bd)
