### ISSUE TITLE
[Bug] Don't load custom routes when in console environment

### ISSUE THREAD

**Issue by susanu** [Laravel-Backpack/CRUD#5379] opened 2023-11-24 18:13 UTC
# Bug report

### What I did
I have some cruds with dependency injection in `__construct` that require the `.env` to be set up.

### What I expected to happen
When running `composer install` and `php artisan` with no `.env`, no errors should be thrown.

### What happened
An `Illuminate\Contracts\Container\BindingResolutionException` exception is thrown because the singleton doesn't have the configuration loaded.
`Unresolvable dependency resolving [Parameter #0 [ <required> string $token ]] in class App\Service`

### What I've already tried to fix it
Nothing.

You can create a new singleton in Laravel that uses some configuration from the `.env`  and try to inject it into the crud construct function.
Execute `composer install` or `php artisan` after.

### Is it a bug in the latest version of Backpack?
Yes
After I run ```composer update backpack/crud``` the bug... is it still there?
Yes
### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.2.11 (cli) (built: Oct  6 2023 09:47:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.11, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

### LARAVEL VERSION:
10.33.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.2
backpack/crud: 6.3.0
backpack/filemanager: 3.0.6
backpack/generators: v4.0.2
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.1.1
backpack/pro: 2.0.18
backpack/theme-tabler: 1.1.1
```

**Comment by pxpm** [comment] 2023-11-26 11:44
I am sorry @susanu I really didn't get the issue. 
What does the singleton has to do with setup routes in console environment ? 

Can you inject that service in any other non-crud (backpack) controller ? I don't see anything related to backpack in that error, maybe some reproduction scenario would help me here. 

Cheers

**Comment by susanu** [comment] 2023-11-27 12:20
Hi @pxpm,

I created a new repository with a simple use case.
https://github.com/susanu/backpack-singleton

Clone the repository and run `composer install`.
You will get an error.

I have 2 controllers in the example, 1 normal and 1 crud, both have the `WebService` singleton injected.
After you run `composer install`, set up the `.env` file and comment/uncomment the line with `WEB_SERVICE_TOKEN`.
A simple `./artisan` command would do the trick to see the difference.
You can also comment `Route::crud` line for the error to go away.

Let me know if you have any question.

The main idea is that no controller should be loaded in a console environment.

**Comment by pxpm** [comment] 2023-11-27 17:48
I think I got the issue, thanks for the repo and explanation, very easy to reproduce 🙏 

I am not sure wrapping it and not registering the routes would help, because then the `route:cache` wouldn't cache those routes. 

What I think we can do here is instead of creating an instance of the controller, we make the `setupRoutes` a static method and avoid initializing a controller instance. 

That would work, but since it's a public method I am not sure if we can do it without considering it a breaking change. 

I think that if we check in the provider if there is a public method in the CrudController we ran that method, otherwise we ran the static method, may make this a non-bc change.

What do you think ? 

Cheers

**Comment by pxpm** [comment] 2023-11-28 18:20
So, I've sent a little more time investigating this. 

I think the problem you mentioned specifically:  `Unresolvable dependency resolving [Parameter #0 [ <required> string $token ]] in class App\Service` is not related with Backpack, but with the fact that your service does not accept `?string` but only `string`. So when you don't have an empty string on the `.env` file it will complain. You can see the same error on your non-crud controller if you comment the service key in the env.

The difference is that Backpack throws that error earlier in the application life cycle, and that can have undesirable side-effects, I 100% agree with you. 

With that in mind I created https://github.com/Laravel-Backpack/CRUD/pull/5389 that I think it's the most future proof way of doing it, and we can push it as a non-breaking change I think. 

If you happen to give a shoot on that PR, let me know if it's working as expected for you. 

In the meanwhile I am going to close this issue so we keep any conversation regarding this on the PR thread. 

Thanks for the heads up, I've stumbled upon this issue a few years ago, and def. I didn't have the complete understanding of the issue, so I just used the `setup()` as a constructor, by injecting the services there, or getting them from the container directly.

Cheers

**Closed by pxpm** 2023-11-28 18:20 UTC
Labels: Minor Bug
