### ISSUE TITLE
After upgrading from v3.6 to v4.0 (v4.1) filters select2 and select2_ajax does not work

### ISSUE THREAD

**Issue by potocky** [Laravel-Backpack/CRUD#2811] opened 2020-05-12 11:06 UTC
# Bug report
After upgrading from v3.6 to v4.0 filters select2 and select2_ajax does not work - it only shows empty area after click on it. When click on that empty area, it shows options, but close immediately. 
This bug is present in v4.0 and v4.1 too.

### What I did
filter definition:

```php
$this->crud->addFilter([ // select2 filter
                'name' => 'id_outlay_center',
                'type' => 'select2',
                'label'=> trans('backpack::nou.outlay_center'),
            ], function() {
                return \App\Models\Codelist\OutlayCenterActive::all()->pluck('outlay_center_with_code', 'id_outlay_center')->toArray();
            }, function($value) { // if the filter is active
                $this->crud->addClause('where', 'id_outlay_center', $value);
            });
```

### What I expected to happen
Show options for select2 or line to write characters in select2_ajax filters.
??

### What happened
Show only empty area
??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.2.10 (cli) (built: Sep 13 2018 00:48:27) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.10.3@6e927e78aafd578d59c99608e7f0e23a5f7bfc5a

### BACKPACK VERSION:
4.1.3@02988a0d14b09e55949781d729060df910f0d94b

**Comment by tabacitu** [comment] 2020-05-13 06:02
Thanks for reporting this @potocky . We'll investigate ASAP. 

One question: did you follow the 4.0 upgrade guide, and only then the 4.1 upgrade guide?

**Comment by pxpm** [comment] 2020-05-13 10:08
Hum... this seems odd to me. 
We indeed have a known bug in select filters, but it's not related to not showing the entries in the list. #2772 

My guess here is that `outlay_center_with_code` is an acessor attribute and is not in `$appends` property of the model. 

In this scenario we can't do more than tell you to add it, it's your code. 

When you do `\App\Models\Codelist\OutlayCenterActive::all()` if that attribute is an acessor and not in `$appends` property it will not be in the collection of models. It's just how Laravel works. 

Let me know if I was right, I may not be, but I hope I am! :man_dancing:

**Comment by potocky** [comment] 2020-05-14 07:13
Hello, appends doesn't help with this issue. It looks like a javascript problem. When click on the empty area, it shows the select options (so the model works), but hide them on mouse button release.

**Comment by pxpm** [comment] 2020-05-29 15:13
This is somehow related with css/js or wtv, but I don't think this is a bug with filters.

Did re-publishing backpack assets, clearing the cache etc help ?

I am going to close this for now, I cannot reproduce this issue. 

If you found out a way that I could reproduce it, please let me know I will give it a go and try to debug it further. 

Wish you the best,
Pedro

**Closed by pxpm** 2020-05-29 15:13 UTC
Labels: Bug

**Comment by trip-somers** [comment] 2020-07-18 04:30
I just upgraded from 3.6 to 4.0, and I'm having a similar problem. For my select2 filter (and other select2-based filters) not a thing happens when clicked. No dropdown. No filter box. No errors.

I followed the directions for upgrading in order.

On a separate project that was created with v4.0, I am not having this problem.

**Comment by trip-somers** [comment] 2020-07-18 04:37
UPDATE: It occurred to me to look into potential Bootstrap conflicts. I was already using Bootstrap v4 in my app.js which I had set up in my `config/base.php` to be included on my admin pages. When I commented that out of my config, the select2 filters started working again.

**Comment by tabacitu** [comment] 2020-07-20 09:50
Thanks for sharing your solution @trip-somers !
