### ISSUE TITLE
problem with orderBy and enableAjaxTable

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#357] opened 2017-01-14 12:27 UTC
I would like to order by created_at my list view.
So i have add
`$this->crud->orderBy('updated_at','desc');`

I need Ajax table, so i have also
`$this->crud->enableAjaxTable();`

I've read in the doc that date and datetime columns won't be sortable anymore with enableAjaxTable :-(

Maybe this is why I have this error :

```
QueryException in Connection.php line 770:
SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select count(*) as aggregate from `personnes` order by `updated_at` desc)
```

How can I order by created_at with ajax enable ? Any way to do it ?

**Comment by deviloflaplace** [comment] 2017-01-16 16:52
Same problem here

**Comment by indra1** [comment] 2017-01-20 09:54
Hey,

This is a known issue. The issue is actually with a third party library used for the ajax datatables. If you have the time and will you can overwrite the AjaxTrait from the package as well as the CrudController and (to reflect the new AjaxTrait) or you can wait for a solution. 

What I did was overwrite the AjaxTrait and that helped fix part of the issue, but since im still using that 3rd party library(https://github.com/LiveControl/EloquentDataTable) I also still have the sort by date issue.

**Comment by karandatwani92** [comment] 2017-01-20 10:51
Same problem here and it is happening because of $this->crud->orderBy('updated_at','desc');
It is mentioned not use orderBy with Date & Datetime while using ajax
- date and datetime columns won't be sortable anymore

But the problem is orderBy is not working with any datatype. i.e; id,name, etc.

**Comment by stygiansabyss** [comment] 2017-01-24 19:58
This seems to work when adding `$this-crud->orderBy('ANY_FIELD');`.  I am trying to order on an indexed string field and getting this error.

**Comment by ChrisThompsonTLDR** [comment] 2017-01-26 01:27
I just want to throw in my two cents.  I have backpack running a fairly high-end server.  We start to see 20 second page loads with as few as 2000 records, displaying only 5 fields.

We had to completely disabled the "views" area of debugtoolbar because the site wouldn't even load.

`$this->crud->enableAjaxTable();` won't be an option for use if the sorting doesn't work.  I think our only option will be to write a custom `index` blade for the `setup` method of CRUD.

I want to see backpack succeed, but I can't pitch it to clients as it stands.

**Comment by OwenMelbz** [comment] 2017-01-26 07:53
Do you mean that you can't set the data tables default ordering?

**Comment by indra1** [comment] 2017-01-26 15:11
@OwenMelbz  When you use ajax table, the search function that retrieves the data uses this library: https://github.com/LiveControl/EloquentDataTable. The order by date actually works, but this library takes the next column when you order by date so there's where the problem comes from.

@ChrisThompsonTLDR  that's what I'm worried about as well, but as a quick solution you can overwrite the AjaxTrait in backpack inside your project and change the search function to behave normally. I will let you know when I have time to work on a solution

**Comment by OwenMelbz** [comment] 2017-01-26 15:30
@indra1 would it be worth you publishing the rewritten AjaxTrait so it can be used in a PR? as it might be quicker to get implemented? Open Source projects need community contributions as well as feedback! Too much work for any single person otherwise!

**Comment by indra1** [comment] 2017-01-26 15:35
@OwenMelbz I will post here what I did. I'm reluctant to publish it. It's a quick hack and I need to go back to it and do it properly. I can in no way do a pull request with that

**Comment by OwenMelbz** [comment] 2017-02-02 13:21
Closing this as its a known issue which needs addressing, have added it to the consolidated list.

**Closed by OwenMelbz** 2017-02-02 13:21 UTC

**Comment by lsancheztapia** [comment] 2019-06-14 15:40
`$this->crud->query->orderBy('updated_at', 'DESC');`

worked for me !
