### ISSUE TITLE
Response time for loading big amounts of data

### ISSUE THREAD

**Issue by rUriarteDev** [Laravel-Backpack/CRUD#2696] opened 2020-04-21 22:25 UTC
Good morning, I am testing my system and I just realized that in the list view if I select to see all the records, in a table that has approximately 2000 records, it is taking between 20 and 30 seconds to load the datatable.
For example i have a bulk action operation where you may need to perform operations on 2k or 3k rows.
I know that normally we do not have this number of rows on a screen, but I am struck by the high response time in 2k rows, I mean I don't think 2k is that much ...
This is normal? Is there a way to speed this up?

**Comment by tabacitu** [comment] 2020-04-22 04:32
Hi @rUriarteDev ,

It should definitely not take 20 seconds to load 2000 rows inside the List operation's table. Do you have many columns inside it? Do you have many _relationship_ columns inside it? Do you have ```model_function``` columns?  If I were you, I'd:
- take a look at the query that results from my usage using something like laravel-debugbar - the fact that it takes 20 seconds to load is a red flag, it means something is really really slow and my bet is on the database query;
- try eliminating (commenting) most columns, see how fast it loads then; if it's fast, then I'd gradually uncomment one column, see if that one is the one causing the huge delay;

Either way, that's not normal. How many entries are there in total, in that DB table?

It's the first time I hear of someone trying to use checkboxes to perform a bulk operation on 2000 entries, to be honest. I've never thought of the "checkbox"-style bulk interface to be appropriate for something like this - what's the point selecting & seeing 2000 rows - you're not going to read any of them, they're too many. But yeah, I guess you _should_ be able to do this. And it _is_ an interface you already have, so it's easy to just use the one you have instead of having to create a totally new interface, I agree with that 😄 

For your 2000 row bulk operation I recommend you:
- first fix the querying problem - it should NOT take 20 seconds to load 2000 records; I just tried it on a CRUD that has 1-n columns too (```select``` and it took 1.8 seconds - which is A LOT, but it's... still bearable to the user;
- second optimize your bulk operation code; make sure your operation performs the query you need in a reasonable amount of time; for example:
   - instead of doing a foreach, pass all the parameters you need (all rows) directly to the query; if there's a loop inside your operation, it will most likely take too long to perform on 2000+ entries;
   - if you NEED a foreach, and you see it takes a lot of time to perform (>3 seconds), I heavily recommend putting the rows in a [Queue](https://laravel.com/docs/7.x/queues) and returning a message like "_Process started. It might take a while_"; or having a [Command](https://laravel.com/docs/7.x/artisan#writing-commands) that only takes care of fewer entries at a time, then advances to the next set; you should be able to easily trigger custom bubble notifications from your bulk operation if you use [the process outlined here](https://github.com/Laravel-Backpack/CRUD/pull/2477) - check that your custom button also has similar front-end code though;

Hope it helps!

**Comment by tabacitu** [comment] 2020-04-22 05:04
Check #2697 too - I have another solution there - a button that would do stuff on the ```$query``` instead of the entries sent.

I'm going to close this because:
- the list loading slowly is most likely a problem with what columns are used and how;
- the checkbox-style bulk actions are not supposed to be used for 2000 entries like that;

If anybody else stumbles into this problem, I guess we could create a tutorial on how to create a Bulk Operation that does NOT use the checkbox buttons, but the filtered ```$query```, to know what entries it should be performed on. But it should be pretty simple to do - just use ```$query``` instead of ```request('entries')```. **Please reply to this issue if you have the same problem.**

Closing this for now. I'll gladly reopen if others think that checkbox-style bulk actions should be performed on 2000 rows. But I really think this is not the way to use this feature. In my opinion, if:
- you're showing 2000 rows and zero are actually read
- you're selecting ALL rows and zero are actually read
- you're hitting a PHP max_input_vars limit
- your bulk operation takes a long time to process

there are already 4 red flags, telling you "_this is not how you're supposed to be doing this_". I understand it's tempting to use the existing interface, instead of creating a new one for that operation. I do. But... checking 2000 rows to do something on them... that really wasn't in the cards when we implemented this feature... Let me know if you think I'm wrong - it happens pretty often 😆

**Closed by tabacitu** 2020-04-22 05:04 UTC
Labels: triage

**Comment by rUriarteDev** [comment] 2020-04-22 05:11
Hi @tabacitu thanks for your reply, i attach the debugbar query tab if that is what you mean, i dont think is that way, if i comment all select columns the result is the same(there are 3 select columns and five in total), if i comment all columns in list operation the result is the same...
Im using the bulk operation in this case because the only field updated is a boolean true/false so seems quite good to me, but could be better sure.
![image](https://user-images.githubusercontent.com/39219144/79943117-7a205700-843e-11ea-8afc-149391bd88b8.png)

**Comment by tabacitu** [comment] 2020-04-22 05:13
How many rows are there in total in the db table?

**Comment by rUriarteDev** [comment] 2020-04-22 05:19
Now there are 1464 rows in total in this table

**Comment by tabacitu** [comment] 2020-04-22 05:28
Hmmm... So the problem is NOT having millions of rows. It still suspect it's a db query problem - but I'm afraid you're the only one that can get to the bottom of it... Sorry @rUriarteDev I'm afraid this is as far I can help. When you discover what was wrong please consider posting about it here - maybe someone else with the same problem stumbles upon it and they don't go through the same frustrating process you have to.

Cheers!

**Comment by rUriarteDev** [comment] 2020-04-22 21:29
I've tried in an clean backpack install, with a tags CRUD just name and slug, and is taking around 15 seconds to load 2000 entries, im thinking is something with my local develop enviroment, im working with laragon (php7.4.4, mysql5.7.24), strange situation, I'm still investigating what the problem may be.

**Comment by rUriarteDev** [comment] 2020-04-22 22:25
Ok, start to clean up the things, if a disable xDebug extension in Laragon panel, response time down from 20 sec to 10 sec, still a lot. Maybe there is some other package or something causing this strange behavior. @tabacitu what software enviroment you use in localhost(XAMPP WAMPP etc)? maybe ill try to change that...

**Comment by rUriarteDev** [comment] 2020-04-22 23:28
Investigating in the network tab in the developer chrome tools, I found that every time the page with the 2000 entries is loaded, approximately 10MB of data are downloaded, of which much comes from a "search" process(http://pruebabp41.test/admin/tag/search?) (8.8 MB) . These 10MB make sense of the response time (10sec) considering my internet speed (12Mbps).
What do you think of that?
![image](https://user-images.githubusercontent.com/39219144/80042922-ad162980-84d6-11ea-8566-29a42b3eb93f.png)

**Comment by tabacitu** [comment] 2020-04-23 09:02
```search``` is the AJAX response. To get the rows to show inside the table, DataTables makes an AJAX call to /search/ and Backpack responds to that call with the actual rows, from inside the controller's ```search()``` method. 

It's normal for that one to be the one that takes the longest, because that's the one that actually does the querying. But it's not normal to take 10sec, or to weigh 10mb. Just tried 2000 rows, for me the response took 5.2sec and 500k. Which is not a lot in terms of weight, but maybe too much in terms of loading time. Maybe the user will be ok with waiting 5 sec in this niche use case. Maybe not. But time will vary depending on the server resources available. The problem is NOT be with the weight of the response, it's the querying.

![Screenshot 2020-04-23 at 11 57 57](https://user-images.githubusercontent.com/1032474/80080170-e93e9e00-8559-11ea-81ef-574c56bc47ef.png)


Again, tables are not meant to have 2000 rows I'm afraid @rUriarteDev . I recommend you build a different interface for what you're trying to achieve. I think your time is better spent that way, rather than trying to make such big tables work well.

Hope it helps.
Cheers!

**Comment by tabacitu** [comment] 2021-10-18 14:55
Server-side export sounds like the way to go to me too, @mamarmite , if you need 2000 rows. Nowadays, we can use PHP generators on server-side. I've been meaning to create a server-side Export operation for some time now. 

If you end up with something you like, maybe share it with us, we could take the maintenance burden if you don't want to create a Backpack addon and maintain it. Just sayin... every line of code gets us closer to having it for everyone 😅

Sorry we don't have a plug-and-play solution for you at the moment...
Cheers!

**Comment by mamarmite** [comment] 2021-12-22 23:21
I've started an operation for this purpose as describe in #3860
The development will be pushed in : https://github.com/mamarmite/export-operation until we find a way to make it as good as the backpack community would :)

**Comment by ahmadmobaraki-updivision** [comment] 2022-07-27 11:46
Hello @tabacitu ! 
This is how I'm going to implement bulk operation on thousands of rows (filtered rows not checked by checkbox); please advise if it's a good practice or not.

We have a custom bulk edit operation that shows a "Bulk edit" button in the list page, it is used to edit some specific db table fields. Basically the button is a simple blade view, when clicked, a modal form shows up with some empty input fields to bulk edit. when the user fills the inputs and submits the form, it sends an ajax request to controller action. Now to send the actual $query of the filtered results to the backend, I use `{{ $crud->query->toSql() }}` inside my js code in my blade view. So for example inside the action we receive something like this: "select * from users when name like %abc%..." a string! then we run this raw query and perform the edit operation on each of the results one by one (of course in a queue!). 

Thank you so much in advance!
