### ISSUE TITLE
clear filter button will make date_range filter drop endless loop

### ISSUE THREAD

**Issue by lucksevenl7** [Laravel-Backpack/CRUD#1073] opened 2017-10-24 07:21 UTC
clear filter button will make date_range filter drop endless loop

**Comment by lloy0076** [comment] 2017-10-26 12:39
https://gist.github.com/carlo/3402842

**Comment by tomcss** [comment] 2017-10-30 12:28
#### Issue description

Clicking the 'clear filters' button on an ajax datatable causes an endless loop in the applyDateRangeFilter function.

In the applyDateRangeFilter is the following line of code:
`    $('li[filter-name=van_tot]').trigger('filter:clear');`

'van_tot' being my filtername. This line seems to be called when there is a van_tot query parameter that doesn't hold a value. The clear filter event handler does this:

`    $('li[filter-name=van_tot]').removeClass('active');
    applyDateRangeFilter(null, null);`

Which goes back to applyDateRangeFunction and the whole cycle repeats until a StackOverflow.

I'm not sure why the applyDateRangeFunction would need to clear a trigger in the first place.

#### Steps to reproduce the issue

1. Open up an ajax datatable view
2. Add a date range filter
3. Press 'clear filters'


#### What's the expected result?

No endless loop.


#### What's the actual result?

Endless loop.

**Comment by gmatkowski** [comment] 2017-11-03 15:47
Same problem here ...

**Comment by tomcss** [comment] 2017-11-03 18:17
@lloy0076 Do we need to create a new report or can this one be re-opened?

**Comment by lucksevenl7** [comment] 2017-11-04 08:35
@tomcss  my condition same to you,tanks your description

**Comment by lucksevenl7** [comment] 2017-11-05 04:41
@lloy0076 i try again problem still exist，and new problem is click date_range filter close button will endless loop too.  
i send a PR to fix this,please check.

**Comment by tomcss** [comment] 2018-02-13 09:59
This is pretty important to me. It breaks important functionality.

**Comment by lloy0076** [comment] 2018-02-13 13:17
You've said:

```
I'm not sure why the applyDateRangeFilter would need to clear a trigger in the first place
```

I assume you actually mean "...would need to trigger a filter:clear event"?

Have you tried removing that line to see what happens?

**Comment by tabacitu** [comment] 2018-02-22 05:40
Update: The issue has since been fixed, in Nov 2017, by merging PR https://github.com/Laravel-Backpack/CRUD/pull/1092

So let's close this. @tomcss , a ```composer update``` should do it for you. Let me know if it doesn't.

Cheers!

**Closed by tabacitu** 2018-02-22 05:40 UTC
Labels: more info please
