### ISSUE TITLE
Error with enum fields if setFromDb() is used

### ISSUE THREAD

**Issue by slickorange** [Laravel-Backpack/CRUD#704] opened 2017-05-27 11:19 UTC
If setFromDb() is called for a table with an enum field, I get:

`DBALException in AbstractPlatform.php line 423:
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.`

I am using MySql.

Related: 
https://github.com/Laravel-Backpack/CRUD/issues/236

**Comment by tabacitu** [comment] 2017-05-29 14:55
Hi @slickorange ,

I can confirm the issue. Thank you for reporting, we'll get right on it.

Cheers!

**Comment by tumf87** [comment] 2017-09-24 10:47
Hi,
I've ran the AutoSet trait tests, which cover the `setFromDb()` method, and I can also confirm that when I change the testing database from an in memory SQLite to a MySQL one, I encounter the same issue.

Done some digging and it seems this is indeed a Doctrine issue, like the error suggests.

There's a [laravel issue](https://github.com/laravel/framework/issues/1186) in which you can read more about it.

In the issue discussion as well as [other places](https://stackoverflow.com/questions/42072360/laravel-5-4-migration-enum-fails-in-mysql) people suggest mapping the enum types to strings in doctrine, which will fix the error, but kinda defeats the purpose of having enum columns.

@tabacitu, I would suggest closing this issue since there's not really much to do on backpack's part.

**Comment by tabacitu** [comment] 2017-09-30 09:25
Fixed this week on ```dev``` and ```master```, thanks to @AbbyJanke 's ```setDoctrineTypesMapping()```.

Finally! :-) Cheers!

**Closed by tabacitu** 2017-09-30 09:25 UTC
Labels: bug, ready
