### ISSUE TITLE
json type throws an error when used with select

### ISSUE THREAD

**Issue by ockam** [Laravel-Backpack/CRUD#545] opened 2017-03-14 20:35 UTC
I have a table with a json field type.

When trying to access the create form, it throws an error:
```
Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
```
I have narrowed the problem to the fact that I also use a select2 field for another field: the error is triggered by the call to `$entity_model::isColumnNullable` (even though it’s a simple integer). If I comment the call in `select2.blade.php`, the error go away and both fields work correctly.

**Comment by MarcosBL** [comment] 2017-03-14 20:57
Not sure if Laravel itself manages MySQL 5.7+ field types, if that's the problem. Have you tried to set the column as MEDIUMTEXT ?

Also, look at thjis if you use https://github.com/barryvdh/laravel-ide-helper/issues/295

**Comment by ockam** [comment] 2017-03-14 21:13
Laravel 5.4 allow you to create json fields: [doc](https://laravel.com/docs/5.4/migrations#creating-columns)

I could use TEXT but I want to have the ability to query the jSON field.

**Comment by MarcosBL** [comment] 2017-03-15 00:41
Confirmed this myself with Percona fork: 5.7.17-11-log - Percona Server (GPL), Release '11', Revision 'f60191c'

Using a select2 as well, traced to `/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php` line 105, at `_getPortableTableColumnDefinition` : no "json" type there, so not sure if the problem could be DBAL itself: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php#L134

There seems to be a bit of confusion on this on DBAL community https://github.com/doctrine/dbal/pull/2653

**Comment by OwenMelbz** [comment] 2017-03-15 07:54
You guys can carry on talking, but I'll close this as it's not a backpack bug it's an issue with Doctrine 

If you search the error you'll probably find fixes

**Closed by OwenMelbz** 2017-03-15 07:54 UTC

**Comment by ewiggin** [comment] 2017-05-25 11:04
the error throwed by isColumnNullable inside the field blade template.

**Comment by ewiggin** [comment] 2017-05-25 11:05
```php 
@if ($entity_model::isColumnNullable($field['name']))
            <option value="">-</option>
        @endif
```

**Comment by tabacitu** [comment] 2017-05-29 15:44
@ockam what MySQL version were you running?

**Comment by ockam** [comment] 2017-05-29 15:46
5.7.17 (on Homestead)
