### ISSUE TITLE
[Bug]  Repeatable fields stopped calling mutators  after update.

### ISSUE THREAD

**Issue by AndresLealColon** [Laravel-Backpack/CRUD#3290] opened 2020-10-28 22:42 UTC
# Bug report

### What I did

Composer Update and updated backpack

### What I expected to happen

I was trying  install simple-qrcode for my project. Backpack was also updated. My code was working properly before update

### What happened

Repeatable fields stopped calling mutators, Accessors keep working normally

My field

                      ['name'     => 'fechasvuelos','label'    => "Vuelos",'type' => 'repeatable','tab'=> 'Vuelos',
                            'fields' => [
                                          ['name'=>'id','type'=> 'hidden',],
                                          ['name'=>'aerolinea_id','type'=> 'select2_from_ajax','entity'=>'aerolineas','attribute'=> "nombre",'data_source' => url("api/aerolinea"),'placeholder'=> "Selecciona la aerolinea",'minimum_input_length'=> 0,'wrapperAttributes'=>['class'=>'form-group col-md-12']],
                                          ['name'=>'lugar_salida_id','type'=> 'select2_from_ajax','entity'=>'aerolineas','attribute'=> "nombre",'data_source' => url("api/aeropuertos"),'placeholder'=> "Selecciona un aeropuerto",'minimum_input_length'=> 0,'wrapperAttributes'=>['class'=>'form-group col-md-4']],
                                          ['name'=>'fecha','type'=> 'date','label'=>'Fecha de salida','wrapperAttributes'=>['class' => 'form-group col-md-4'],],
                                          ['name'=>'hora_salida','type'=> 'time','wrapperAttributes'=>['class' => 'form-group col-md-4']],
                                          ['name'=>'lugar_llegada_id','type'=> 'select2_from_ajax','entity'=>'aerolineas','attribute'=> "nombre",'data_source' => url("api/aeropuertos"),'placeholder'=> "Selecciona un aeropuerto",'minimum_input_length'=> 0,'wrapperAttributes'=>['class'=>'form-group col-md-4']],
                                          ['name'=>'fecha_llegada','label'=>'Fecha de llegada','type'=> 'date','wrapperAttributes'=>['class' => 'form-group col-md-4'],],
                                          ['name'=>'hora_llegada','type'=> 'time','wrapperAttributes'=>['class' => 'form-group col-md-4']],
                                          ['name'=>'asientos','wrapperAttributes'=>['class' => 'form-group col-md-4'],],
                                          ['name'=>'numvuelo','label'=>'Número de vuelo','wrapperAttributes'=>['class' => 'form-group col-md-4'],],
                                          ['name'=>'otros_servicios','label'=>'Observaciones','wrapperAttributes'=>['class' => 'form-group col-md-4'],],
                                        ],   'new_item_label'  => 'Agregar', // customize the text of the button
                      ],

 My mutator in model, 

    public function setFechasvuelosAttribute($value){
          \Log::debug("fechas vuelo");
          $jsonre=json_decode($value);
          if(count($jsonre)<1 || empty($jsonre[0]->aerolinea_id) ||empty($this->id)){
            \Log::debug("fechas no se carga nada");
            return;
          }

          \App\Models\Fechas_vuelo::where('reserva_id', $this->id)->where('active', 1)->update(['active' => 0]);

          foreach ($jsonre as $dato) {
            \App\Models\Fechas_vuelo::updateOrCreate(['id'=>$dato->id],['aerolinea_id'=>$dato->aerolinea_id,
                'fecha'=>$dato->fecha,'lugar_salida_id'=>$dato->lugar_salida_id,'hora_salida'=>$dato->hora_salida,
                'lugar_llegada_id'=>$dato->lugar_llegada_id,'reserva_id'=>$this->id,
                'hora_llegada'=>$dato->hora_llegada,'asientos'=>$dato->asientos,'otros_servicios'=>$dato->otros_servicios,
                'numvuelo'=>$dato->numvuelo,'fecha_llegada'=>$dato->fecha_llegada,
                'active'=>1]);
          }
    }

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.19 (cli) (built: Jul  1 2020 19:31:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.28.4@de187e9200948bab6975167e480950abcd5efdac

### BACKPACK VERSION:
4.1.26@ae68ca24844929ac38d2e792197551e823c43570

**Comment by pxpm** [comment] 2020-10-29 00:02
Hello @AndresLealColon 

Is fechas_vuelos a column in your database casted as array? Or a fake column?

Best,
Pedro

**Comment by AndresLealColon** [comment] 2020-10-29 01:14
It is not an array column, it is a fake column.  Inside mutator I save data in other table related 

I already tried to set fake to the repeatable field but not working neither

'fake'     => true

All other mutators  are calling as usual. 


My accessor works normally, only mutator not calling after updating from 4.1.16 to 4.1.26

Mi accessor is this

    public function getFechasvuelosAttribute(){
      $id = $this->id;
      $vuelos =  \App\Models\Fechas_vuelo::where('reserva_id', $id)->where('active', 1)->get();
      return $vuelos;
    }

**Comment by tabacitu** [comment] 2020-10-29 17:38
Thanks for the clarification @AndresLealColon . Knowing you upgraded from 4.1.16 helps us narrow down the problem. 

@pxpm this is the second issue I see reporting this problem with `repeatable` (after https://github.com/Laravel-Backpack/CRUD/issues/3279), so please let's give it priority. Since #3279 was reported before we released 4.1.26, we can assume the problem is somewhere between 4.1.16 and 4.1.25. [This diff between the two versions](https://github.com/Laravel-Backpack/CRUD/compare/4.1.16...4.1.25) might help pinpoint the problem.

**Comment by AndresLealColon** [comment] 2020-10-29 19:24
I don't know if it is related but now I found this crazy behavior in another view controller

Only one repeatable field now is calling its mutator with info of other field after I set the other field as fake

Repeatable field

           ['name'     => 'extras','label'=> "Extras",'type' => 'repeatable','tab'=> 'Básico',
                       'fields' => [
                                   ['name'=>'extra_id','type'=> 'select2_from_ajax','attribute'=> "concepto",'entity'=>'viaje','data_source' => url("api/destinos/extras"),'placeholder'=> "Selecciona un concepto",'minimum_input_length'=> 0,'wrapperAttributes'=>['class' => 'form-group col-md-4'],],
                                   ['name'=>'monto','type'=>'number','prefix'=> "$",'attributes' => ["step" => "any"],'default'=>0,'wrapperAttributes'=>['class' => 'form-group col-md-3'],],
                                   ['name'=>'pax','type'=> 'number','wrapperAttributes'=>['class' => 'form-group col-md-3'],],
                 ],
                 'new_item_label'  => 'Agregar', // customize the text of the button
                 ],

Mutator in model (this columns is declared as array)
    public function setExtrasAttribute($value){

      if($value==null){
          $this->attributes["extras"]=null;
          return;
      }
      \Log::debug("extras------------>".json_encode($value));
      $this->attributes["extras"]=json_encode($value);
    }

If I set another random field in same controler as fake

                [
                                'type'  => 'relationship',  // HTML element which displaying transactions
                                'name'     => 'destinofs',
                                'fake'=> true,
                                'label'    => "Destino",
                                'placeholder'=> "Buscar destino",
                                'attributes' => [
                                     'required'    => 'required',
                                     'id' => 'destinoop',
                                     'OnChange' => 'getDestinos()',
                                    ],
                                'attribute' => 'nombre', // Column which user see in select box
                                  'ajax' => true,
                                'wrapperAttributes'          => ['class' => 'form-group col-md-6'],
                              ],


Now mutator is called but with data of  other field and its own data 

Look info entered 
![mutator1](https://user-images.githubusercontent.com/71194141/97622259-9a326380-19e9-11eb-97e3-8ff61b6ee0f3.PNG)

My log file return data of repeatable an other fake field

![mutator2](https://user-images.githubusercontent.com/71194141/97622272-9f8fae00-19e9-11eb-9ee1-1e60e949de2e.PNG)

**Comment by pxpm** [comment] 2020-10-30 10:27
Hello @AndresLealColon 

As i'v answered before I think there is some bad implementation here, or some edge case that are not covered .. anyway.. I vouche for the first.

@tabacitu I tested when first issue came and it fired ok, that's why no Issue was opened and I just answered it.

Give it another shot today, but this time keep my evidence: 
![Untitled_ Oct 30, 2020 10_17 AM](https://user-images.githubusercontent.com/7188159/97693866-ae359e00-1a99-11eb-9407-9fae9f917775.gif)

For your "strange" behaviour what I think that happened is that when you set a field `fake => true` and don't specify where it will be saved, Backpack assumes it's in `extras` column. Looking at naming of your fields it seems that is what is happening. 

When you use a fake field, the mutator will be fired on the `fake field` not in repeatable name, unless repeatable name is the actual column in your database that you want to save.

I am not sure I am making myself clear here, but feel free ask something, if I can help.

Best,
Pedro

**Comment by AndresLealColon** [comment] 2020-10-30 12:42
Hi again Pedro,
I downgraded Laravel from 7.28.4 to my previous one 7.23.0 and it is all working again  keeping backpack 4.1.26. I realize that #3279  and me were working with 7.28.4, so with the downgrading magic comes again,  the issue is with Laravel I suppose. 
Thanks for the support.
Best,
 Andrés

**Comment by pxpm** [comment] 2020-10-31 09:58
@AndresLealColon I am very happy that you found the culprit. 

Anyway, I am running Laravel v8.1.0 and the mutators fire here, so probably some bug between minor LV versions ? It seems strange, but it could happen. 

I am going to close this for now, if there is something more we can help, just let us know.

Best,
Pedro

**Closed by pxpm** 2020-10-31 09:58 UTC
Labels: triage

**Comment by tabacitu** [comment] 2020-11-02 15:03
Ouch! Glad you figured it out, guys. If anybody else stumbles upon this thread, because it happens to you too:
- please **let us know your current Laravel version**
- try a `composer update laravel/framework` and see if it works with the latest version (and let us know)

It'll help us a lot in figuring out the problem.

Cheers!
