### ISSUE TITLE
video type needs two fields ?

### ISSUE THREAD

**Issue by MarcBrillault** [Laravel-Backpack/CRUD#213] opened 2016-11-01 23:43 UTC
I followed the steps mentioned here : https://laravel-backpack.readme.io/docs/crud-fields#video and had an issue :
`SQLSTATE[42S22]: Column not found: 1054 Champ 'extract_link' inconnu dans field list`

It seems I have to create two fields, xxx, and xxx_link in order for the video type to work.

Is it really necessary ? The video field already contains the link, as it is stored as json.

**Comment by OwenMelbz** [comment] 2016-11-02 09:12
@MarcBrillault if your column is called "extract" you only need to add 1 field.

Not sure why you're creating 2 fields, can you share your code?

**Comment by MarcBrillault** [comment] 2016-11-02 10:50
Here is my migration code:
```
// [...]
    public function up()
    {
        Schema::create('discs', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
            $table->string('subtitle_fr')->nullable();
            $table->string('subtitle_en')->nullable();
            $table->string('publisher')->nullable();
            $table->text('text_fr')->nullable();
            $table->text('text_en')->nullable();
            $table->date('publication_date')->nullable();
            $table->string('image')->nullable();
            $table->string('extract')->nullable();

            // Sorting
            $table->integer('lft')->default(0);

            $table->timestamps();
        });
    }
```

And the code in DiscCrudController:

```
// [...]
        $this->crud->addField(
            [
                'name'  => 'extract',
                'label' => 'Extrait',
                'type'  => 'video',
            ]
        );
// [...]
```

When I do that, without adding the "extract_link" field in the migration, I have the above error.
The error disappears when I add the extract_link, and the extract field contains the full JSON, while the extract_link field only contains the full viedo url.

**Comment by OwenMelbz** [comment] 2016-11-02 16:39
The "extract" field needs to be TEXT as its more than likely longer than 255.

But I'm confirming now that all you need is

```php
$this->crud->addField(
            [
                'name'  => 'extract',
                'label' => 'Extrait',
                'type'  => 'video',
            ]
        );
```

In your model, make sure its cast as an object.

Ignore the extract_link, field that is irrelevant and not needed to worry about, its purely a dummy field for the javascript.

Make sure you have no get/set mutators on the field. I've just tested on 2 different installs and its working as expected, so there must be a configuration issue your end thats conflicting.

Also make sure you don't have anything like "extract_link" in your $fillable, basically remove any of your code that even acknowledges the existence of _link, you do not need to worry about that.

Additionally try a composer update, just to make sure your on the latest, and make sure you have no customly published views overwriting the core one

**Comment by MarcBrillault** [comment] 2016-11-02 17:11
I still have the problem (And yes, I have made a composer update).

I'll try to test it on a fresh install this evening, I'll let you know.

**Comment by MarcBrillault** [comment] 2016-11-03 06:55
I made a fresh install (base, crud and generators).

I made the simplest possible migration:
```
    public function up()
    {
        Schema::create('discs', function (Blueprint $table) {
            $table->increments('id');
            $table->text('video')->nullable();
            $table->timestamps();
        });
    }
```

I generated all the files with `php artisan backpack:crud disc`

And I added this to Http/Controllers/Admin/DiscCrudController.php:
```

        $this->crud->addField(
            [
                'name'  => 'video',
                'label' => 'Vidéo',
                'type'  => 'video',
            ]
        );
```

And I still have the issue.

I uploaded my Laravel installation (minus the vendor dir) here : http://files.brillault.fr/dev/testBackpack.zip

**Comment by tabacitu** [comment] 2016-11-03 07:45
Hi guys,

Found it! The zip helped, thank you. I think the problem is that there is a video_link input that reaches the create() and store() methods. If $fillable isn't specified, the CRUD will try to store all inputs. And it can't store video_link, because there is no such column.

@MarcBrillault , you can fix this by specifying in ```$fillable``` on the model what db columns are ok to be edited. It's good practice to use $fillable instead of $guarded because it's more restrictive. Otherwise a hacker could potentially insert a "created_at" or "updated_at" or other valid inputs that are more important in the front-end, click Save and overwrite the db entry.

@OwenMelbz , I think to prevent this problem ever happening again we could remove the video_link input from the "video" field type. Or just remove its name? I think that should work. What do you think?

Cheers!

**Comment by OwenMelbz** [comment] 2016-11-03 09:12
@tabacitu there is a PR here -> https://github.com/Laravel-Backpack/CRUD/pull/214 which contains 2 fixes, one of them is the removal of the name attribute!

**Comment by MarcBrillault** [comment] 2016-11-03 09:30
Thanks to both of you ;)

**Comment by tabacitu** [comment] 2016-11-06 18:22
Merged @OwenMelbz 's PR, so it's now fixed. Thanks guys. Cheers!

**Closed by tabacitu** 2016-11-06 18:22 UTC
Labels: bug, help wanted, ready
