### ISSUE TITLE
[Bug] Field Tinymce didn´t inizialize in repeatable if there is another one somewhere in the form

### ISSUE THREAD

**Issue by SebastianCordiano** [Laravel-Backpack/CRUD#4318] opened 2022-04-12 09:42 UTC
# Bug report

### What I did
Insert 2 field in my create/update operation, the first one a simple tinymce and the second one a repeatble with a tinymce inside

### What I expected to happen
All the tinymce works

### What happened
Only the first field initialize correctly and in console the error is: "Uncaught TypeError: o is undefined"
It s seems to be the function "initializeFieldsWithJavascript" that launch only once "bpFieldInitTinyMceElement" (that initialize the tinymce js)
![TinymceError](https://user-images.githubusercontent.com/81357937/162930954-32e1e89d-f41c-445a-a9bf-e5e6bfadebff.png)

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.4 (cli) (built: Apr  4 2022 13:30:33) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.4, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.5.1@35be2599c9ac3d58bf1578895c2e85ea4848a0d7

### BACKPACK VERSION:
5.0.11@337163b7e9a0e63413474bd3ee800a198f83c8e9

**Comment by pxpm** [comment] 2022-04-13 16:10
Hello @SebastianCordiano !

Thanks for the report. I was indeed able to reproduce your issue and already submitted a PR to fix it. 

I will let you know as soon as it gets merged, it should not take much. 

Cheers

**Comment by tabacitu** [comment] 2022-04-13 18:18
Merged and tagged. A `composer update backpack/pro` should do it for you @SebastianCordiano . Thank you!

**Closed by tabacitu** 2022-04-13 18:18 UTC
Labels: Bug

**Comment by vkudrych** [comment] 2024-11-27 11:03
The problem is still here. I'm using backpack/pro:2.2.17
