### ISSUE TITLE
MorphOne relation

### ISSUE THREAD

**Issue by nikolaynesov** [Laravel-Backpack/CRUD#343] opened 2017-01-07 14:36 UTC
Hi,

I am trying to  use a MorphOne relation with Backpack but without any success. I am adding Backback after the functionality already developed so all relations work fine and tested but I am not able to make them work with Backpack. There is only select_multiple for columns and fields but I think something like select_morph_one is needed? Code I use:

```
$this->crud->addColumn([

            'label' => 'City',
            'type'  => 'select_multiple',
            'name'  => 'address',
            'entity'=> 'address',
            'attribute' => 'city',
            'model' => "App\\Address"

]);
```
```
$this->crud->addField([
            'label' => "Address",
            'type' => 'select2_multiple',
            'name' => 'address', 
            'entity' => 'address', 
            'attribute' => 'city',
            'model' => "App\\Address"
        ]);
```
At the moment it just gets all the addresses I have in my table not depending on if it's connected with the model or not. 
Polymorphic structure of Address table:

```
id
addressable_id
addressable_type
city
...
```
How can I make it work?

**Comment by mariavilaro** [comment] 2017-03-19 21:59
I need this too.

**Comment by victorlap** [comment] 2017-04-23 09:43
This is a duplicate of #250

**Comment by lloy0076** [comment] 2017-08-12 10:07
Closed as duplicate.

**Closed by lloy0076** 2017-08-12 10:07 UTC
