### ISSUE TITLE
Backpack\CRUD\app\Models\Traits\SpatieTranslatable\SlugService assumes slugs are always 'translatable'

### ISSUE THREAD

**Issue by tibbsa** [Laravel-Backpack/CRUD#2666] opened 2020-04-11 16:56 UTC
# Bug report

The SlugService implementation provided by Backpack assumes that slugs on all models will be translatable, which isn't necessarily the case.  

### What I did

I created a new custom CRUD type for a site where the contents, but not the slugs, will be translatable.  "Slug" was not included in my model's **translatable** array accordingly.

### What I expected to happen

Slugs would not be translated or require translation.

### What happened

The slug field was shown in the CRUD create/update form as not being translatable.  However, every time I saved the entity, the slug was converted to JSON (in the form that Spatie's laravel-translatasble package would expect), despite 'slug' not being among the translatable fields. 

### What I've already tried to fix it

The **SlugService** implementation provided by Backpack assumes that the slug will be subject to translation.

**/vendor/backpack/crud/src/app/Models/Traits/SpatieTranslatable**:

```
    public function slug(Model $model, bool $force = false): bool
    {
        /* ... */ 
        foreach ($this->model->sluggable() as $attribute => $config) {
            /* ... */
            $slug = $this->buildSlug($attribute, $config, $force);

            // customized for Backpack using SpatieTranslatable
            // save the attribute as a JSON
           $this->model->setAttribute($attribute.'->'.$model->getLocale(), $slug);
           $attributes[] = $attribute;
        }

        return $this->model->isDirty($attributes);
    }
```

I have corrected this locally by checking to see whether 'slug' is in fact translatable:

```
            // customized for Backpack using SpatieTranslatable
            // save the attribute as a JSON
            if ($this->model->isTranslatableAttribute($attribute)) {
                $this->model->setAttribute($attribute.'->'.$model->getLocale(), $slug);
            } else {
                $this->model->setAttribute($attribute, $slug);
            }
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
    with Xdebug v2.9.3, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v7.5.2@3a3b3f7fea69813f5a03449c6314bfb42c3ccf78

### BACKPACK VERSION:
4.0.59@404ece5e7d164d30de6a715fe31aa3a373f4269b

**Comment by pxpm** [comment] 2020-04-14 11:15
Hello @tibbsa 

I get your point, from code I would also assume that, but while testing I could not reproduce your issue. 

If slug is not in translatable array it does NOT get saved as json.

I have attached a screen recording so you can see if I am doing something different from you. 

http://g.recordit.co/jpCycP9Kf2.gif

Could this have something to do with environments? Hum.. 
Let me know @tibbsa so we can dig in if needed.

Best,
Pedro

**Comment by tibbsa** [comment] 2020-04-20 15:50
Sometimes a bit of time "away" from a problem gives you a whole new perspective.  Perhaps I'm still missing something, but I _think_ this can be safely closed and put down to a non-issue.

If slugs are not to be translated, then one should not be using the ``Backpack\CRUD\app\Models\Traits\SpatieTranslatable\Sluggable`` and ``Backpack\CRUD\app\Models\Traits\SpatieTranslatable\SluggableScopeHelpers`` traits that come supplied with Backpack.  They are inherently intended for translatable slugs.

Instead, one should just use the original ``Cviebrock\EloquentSluggable\Sluggable`` and ``Cviebrock\EloquentSluggable\SluggableScopeHelpers`` traits.

I haven't extensively tested this yet but I don't believe that breaks anything in Backpack.  Is there some other Backpack-specific magic happening in those provided traits that must b e maintained?

**Comment by tabacitu** [comment] 2020-04-21 05:56
> Sometimes a bit of time "away" from a problem gives you a whole new perspective.

Ain't that the truth @tibbsa ? I regularly task "_future me_" to solve my problems, because I know he's smarter than me 😆 

I agree: 
- if the slug is NOT translatable, use ```Cviebrock\EloquentSluggable\Sluggable```
- only if the slug is translatable, use ```Backpack\CRUD\app\Models\Traits\SpatieTranslatable\Sluggable```

Closing this as a non-issue. Thanks for reporting it anyway @tibbsa - I'm sure someone, someday, will go through the same problem as you, and they'll be grateful you documented it 😉 

Cheers!

**Closed by tabacitu** 2020-04-21 05:56 UTC
Labels: Bug
