### ISSUE TITLE
[Bug] blue bundle do not include styles for Noty

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#4638] opened 2022-09-01 15:13 UTC
# Bug report

### What I did

I changeg to blu theme using your blu bundle

//        'packages/backpack/base/css/bundle.css', 
        'packages/backpack/base/css/blue-bundle.css',

### What I expected to happen

Nohing

### What happened

The notification alerts are not styled

### What I've already tried to fix it

in the blu bundle is missing the scss of noty.
I can fix adding  'packages/@digitallyhappy/backstrap/css/blue.min.css', into the configs

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:13:52) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.27.0@27572f45120fd3977d92651a71d8c711a9aaa790

### BACKPACK VERSION:
5.3.8@48b971b6073ac8fde3b021466b08d6a78283b15c


```

**Comment by pxpm** [comment] 2022-09-02 09:54
Hello @realtebo 

There was an issue with that that was fixed in https://github.com/Laravel-Backpack/CRUD/pull/4465

I've been trying to reproduce your issue but without success, so I guess you need to republish backpack public assets ? 

![image](https://user-images.githubusercontent.com/7188159/188114216-c4ad5865-1517-4c78-baa4-78c0174e6c22.png)


`php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force`

Make sure you do a backup of your `public/packages` folder before running that command in case something goes south 🙃 

Let me know how it goes.
Cheers

**Comment by pxpm** [comment] 2022-09-10 08:38
closed due inactivity! @realtebo is on vacations (now everybody knows!!!! 🙃 ) but it's probable that he didn't republished the assets as I was unable to reproduce this issue.

You know the drill already @realtebo , if that's not the case, please re-open and we can have a look at it!

Cheers

**Closed by pxpm** 2022-09-10 08:38 UTC
Labels: Wait Response
