### ISSUE TITLE
[4.0][Bug] "The command "elfinder:publish" does not exist"

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2517] opened 2020-03-08 10:42 UTC
# Bug report

### What I did

`php artisan backpack:install --elfinder yes`

### What I expected to happen

Backpack to be installed.

### What happened

"The command "elfinder:publish" does not exist."
![image](https://user-images.githubusercontent.com/734475/76161229-50d39200-6142-11ea-83d3-93a6c5454a7a.png)

### What I've already tried to fix it

Re-run the command fixed the issue.

### Backpack, Laravel, PHP, DB version

Windows, Wamp, Backpack 4.0, Laravel 6.0, PHP 7.4

**Comment by tabacitu** [comment] 2020-03-08 11:47
Thank you for raising this @mamprogr ! We need the exact version of Laravel and Backpack you are using to debug this. I know you haven't been able to get them because ```php artisan backpack:version``` was broken (thanks for that too). But a ```composer update``` should get you [4.0.49](https://github.com/Laravel-Backpack/CRUD/releases/tag/4.0.49) now, that has that fixed.

Let me know the output of ```php artisan backpack:version``` after a ```composer update``` please. Cheers!

**Comment by mamprogr** [comment] 2020-03-08 12:08
Laravel: 7.0.7 (sorry, it was wrong in my first comment)
Backpack version is 4.0.48

After `composer update`:
### PHP VERSION:
PHP 7.4.0 (cli) (built: Nov 27 2019 10:14:18) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.0.7@5c3b3d9c77560b249305cbc42d0aa0a16f9e80f9

### BACKPACK VERSION:
4.0.49@986f5e69593eab33e567787e0c28efb6747cd7b5

**Comment by tabacitu** [comment] 2020-03-08 12:16
Hmm and ```php artisan backpack:install``` still fails, after the update to 4.0.49? I was expecting 4.0.49 to fix that too...

**Comment by mamprogr** [comment] 2020-03-08 12:29
`php artisan backpack:install` still fails, check this: [https://github.com/Laravel-Backpack/CRUD/issues/2416](url)

`php artisan backpack:install --elfinder yes` also still fails, please check:

![image](https://user-images.githubusercontent.com/734475/76162766-a8c5c500-6151-11ea-8483-ad106a505331.png)

**Comment by nickyskills** [comment] 2020-03-08 13:25
I checked with Laravel 7.0 and i encounter the same issue
That ->  The command "elfinder:publish" does not exist.

Solution measure i took

- Open elFinder Package for Laravel 5.


- Require this package with Composer

` composer require barryvdh/laravel-elfinder`

- Add the ServiceProvider to the providers array in app/config/app.php

 Barryvdh\Elfinder\ElfinderServiceProvider::class

 - You need to copy the assets to the public folder, using the following artisan command:

 `php artisan elfinder:publish`


- After installing this  you may now re-run 

 `php artisan backpack:install --elfinder yes`

I wonder which Laravel package you are using

**Comment by tabacitu** [comment] 2020-03-08 13:37
Hmmm that's so weird. I've just tried it using the same version as you: Laravel 7, PHP 7.4, Backpack 4.0.49, and it worked fine:

![Screenshot 2020-03-08 at 15 33 44](https://user-images.githubusercontent.com/1032474/76163835-5507ab80-6152-11ea-9f45-b3803dab39d0.png)


I'm wondering if it's not a OS difference. I see you're running Windows, I can only try on Mac OS.

**@pxpm can you please run ```php artisan backpack:install``` on 4.0.49, PHP 7, Laravel 7, and share how that goes for you?**

**Comment by danielbriffa** [comment] 2020-03-08 17:10
Have the same issue, on a windows machine. Running laravel 7 & PHP 7

![image](https://user-images.githubusercontent.com/3406618/76167588-f816f000-6167-11ea-8413-5bede21137bc.png)

Executing the command again fixed the issue.

**Comment by pxpm** [comment] 2020-03-09 10:39
I can confirm that some weird error is occuring.

![error](https://user-images.githubusercontent.com/7188159/76205444-26d9a880-61f2-11ea-92bb-aae1dd8b6f0e.png)

From my understanding when we call `elfinder:publish` in install script I think the package is not loaded yet. Because after the script fails, you run `php artisan elfinder:publish` and it works normal. 


What you think @tabacitu

**Comment by tabacitu** [comment] 2020-03-09 11:25
Until we get to the bottom of this, if anybody gets this error, please complete the installation manually by running:
```shell
php artisan elfinder:publish
php artisan vendor:publish --provider=Backpack\CRUD\BackpackServiceProvider --tag=elfinder
php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('elfinder') }}'><i class='nav-icon fa fa-files-o'></i> {{ trans('backpack::crud.file_manager') }}</a></li>"
```

---

@pxpm - pff... no idea why this might be happening... And it's especially difficult to debug because it works for me... Maybe the ```elfinder:publish``` command gets run before the ```composer install barryvdh/laravel-elfinder``` command gets completed, and Laravel doesn't have the chance to run its autodiscovery feature? We could test for this by delaying it a little bit:

```diff
            if (isset($createUploadDirectoryCommand)) {
                $this->executeProcess($createUploadDirectoryCommand);
            }

+           sleep(10); // wait 10s before running the next command
            $this->line(' Publishing elFinder assets');
            $this->executeArtisanProcess('elfinder:publish');
```
Does this work @pxpm or @mamprogr ?

**Comment by tabacitu** [comment] 2020-03-09 11:47
Also, after a ```composer update``` you should be able to do ```php artisan backpack:install --debug``` and copy-paste the output here - it could provide some valuable info to debug this...

**Comment by pxpm** [comment] 2020-03-09 11:52
On it!

**Comment by tabacitu** [comment] 2020-03-09 16:42
Done! **I've just merged Pedro's PR #2528 which should fix this issue**. Thanks again for reporting this @mamprogr, and for pitching with screenshots and solutions @nickyskills & @danielbriffa . They really did help a lot.

**Anybody getting "_The command "elfinder:publish" does not exist_" when installing Backpack 4.0.50 or lower, please do a ```composer update``` to get 4.0.51, then run ```php artisan backpack:install``` again - it should work just fine.**

If anybody's still getting this error on 4.0.51 or higher, please post here and let us know. I'll leave this issue open for a few days, just in case.

**Comment by nickyskills** [comment] 2020-03-10 08:02
Thank you for feedback. I am thrilled it worked.

**Comment by nickyskills** [comment] 2020-04-22 18:19
.....................................

Nicky would like to stay in touch on LinkedIn.

Nicky Skills
Software Engineer at Web Technologies Tanzania Limited
Tanzania

View profile https://www.linkedin.com/comm/in/nicky-skills-b5b3441a7?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-%7E991o5z%7Ek9bnvwaz%7Ekc-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BKC8m8ZC7TvGLvFvlXIbuXg%3D%3D

Confirm that you know Nicky https://www.linkedin.com/e/v2?e=-991o5z-k9bnvwaz-kc&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BKC8m8ZC7TvGLvFvlXIbuXg%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=wnpWUudZ&invitationId=6658791106823757824


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-991o5z-k9bnvwaz-kc&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQH75tJ4CWM1bAAAAXGjHd5rV548-z9fWIw5cvTbYDGTwGLJPXsnK13NI3wVzmCy0o9Y6uf5Cqyi16vYXc2uiDhnLOhsFYT2bIDPhprVy4HKipR6WS7BIdyw8RulRoQbeR3LpI1S5GwL-YOn9f6P-oqp9ua-vDUWNA&eid=-991o5z-k9bnvwaz-kc

Help: https://www.linkedin.com/e/v2?e=-991o5z-k9bnvwaz-kc&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BKC8m8ZC7TvGLvFvlXIbuXg%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2020 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Closed** 2020-04-23 09:06 UTC
Labels: Bug, urgent

**Comment by nickyskills** [comment] 2020-04-30 06:16
Hi ,

Nicky would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-991o5z-k9mdl4ex-y2&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3Bn5IoD4TmQr21odg4Qrmeqg%3D%3D&t=suwj&ek=email_first_guest_reminder_03&li=20&m=hero&ts=accept_text

View Nicky’s profile: https://www.linkedin.com/comm/in/nicky-skills-b5b3441a7?trk=eml-email_first_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_first_guest_reminder_03-hero-2-prof%7Ename-null-%7E991o5z%7Ek9mdl4ex%7Ey2-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3Bn5IoD4TmQr21odg4Qrmeqg%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-991o5z-k9mdl4ex-y2&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_first_guest_reminder_03&li=17&m=unsub&ts=unsub&loid=AQFBDYPxy14zpQAAAXHJuuzjxsUJLA4aYTkyybfGvAzAXO1uMCQAoOLqfoSnmi80hNX4URqREliqaaITaZMSeXSbRSqId7LQZS_UIol5ETdIWm-zRCesVPgv15IwCtpCdu5WYxOMN54LJfTsmt1MI3eYjQnf0WbvPF7Q5Q&eid=-991o5z-k9mdl4ex-y2

Help: https://www.linkedin.com/e/v2?e=-991o5z-k9mdl4ex-y2&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3Bn5IoD4TmQr21odg4Qrmeqg%3D%3D&a=customerServiceUrl&ek=email_first_guest_reminder_03&li=16&m=footer&ts=help&articleId=67


 LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2020 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by nickyskills** [comment] 2020-05-07 06:45
https://www.linkedin.com/e/v2?e=-991o5z-k9wepgd0-vf&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BN5tT4D%2B%2BSRWtit%2BcOWdugw%3D%3D&t=suwj&ek=email_second_guest_reminder_03&li=11&m=hero&ts=accept_text

 https://www.linkedin.com/comm/in/nicky-skills-b5b3441a7?trk=eml-email_second_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_second_guest_reminder_03-hero-2-prof%7Ename-null-%7E991o5z%7Ek9wepgd0%7Evf-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BN5tT4D%2B%2BSRWtit%2BcOWdugw%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-991o5z-k9wepgd0-vf&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_second_guest_reminder_03&li=8&m=unsub&ts=unsub&loid=AQEWjSBOu4sxIAAAAXHt4f54AV78IyJo9BR43Y_h7LgZF56fkibipkG1Esn_PWXLnzblAZ7nnh3iscVaRCSNXsSUD0gyJRxUWmiaWiFU-6NG5fMNmn3Hf4LZ54NNbQiVOR7C1bHyo53qaZI1wB2vboucyZLwSuoVgyqx3w&eid=-991o5z-k9wepgd0-vf

Help: https://www.linkedin.com/e/v2?e=-991o5z-k9wepgd0-vf&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BN5tT4D%2B%2BSRWtit%2BcOWdugw%3D%3D&a=customerServiceUrl&ek=email_second_guest_reminder_03&li=7&m=footer&ts=help&articleId=67


You are receiving Invitation reminder email emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2020 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jerveyjervey** [comment] 2021-05-26 10:38
can someone help me with this issue?
![image](https://user-images.githubusercontent.com/84775529/119646215-7b962d00-be51-11eb-8af9-40ef5525b432.png)

**Comment by pxpm** [comment] 2021-05-26 16:07
@jerveyjervey I don't think your error is the same described in the issue.

From what seems from stacktrace you don't have `php` registered in your environment variables.

If on win 10 follow: https://www.forevolve.com/en/articles/2016/10/27/how-to-add-your-php-runtime-directory-to-your-windows-10-path-environment-variable/ 

Best,
Pedro

**Comment by jerveyjervey** [comment] 2021-05-27 02:04
hi @pxpm 

my php is registered in my env variables. I will check the link you sent to make sure I am doing the right one.

thank you very much

**Comment by jerveyjervey** [comment] 2021-05-27 02:30
@pxpm my php is registered in env variables. then i check it using "php -?", the help showed. it means the php is added correctly to my env variables.
