### ISSUE TITLE
The GET method is not supported for this route

### ISSUE THREAD

**Issue by tifaahmed** [Laravel-Backpack/CRUD#2718] opened 2020-04-27 14:44 UTC
# Bug report
{
    "message": "The GET method is not supported for this route. Supported methods: PUT, DELETE."
}
### What I did
delete row but with using the demo project
### What happened
delete is working in local host but when i upload it to the online server  it stop working 
![bandicam 2020-04-27 16-43-28-598](https://user-images.githubusercontent.com/35181458/80385398-4ca43500-88a6-11ea-9345-6931a01a1d00.jpg)

### Backpack, Laravel, PHP, DB version
latest  version

**Comment by senthu1994** [comment] 2020-04-29 06:58
I also affect by same bug in local when i click the preview icon. After upgrade Backpack 4.0. Actually my error is like below screenshot. Why it comes?
![Screenshot from 2020-04-29 12-27-01](https://user-images.githubusercontent.com/25341255/80568574-e689f000-8a14-11ea-8c2f-a5e893766948.png)

**Comment by pxpm** [comment] 2020-04-29 09:07
Hello @tifaahmed 

just clarify me, latest version is 4.0 or you are using 4.1 beta ?

I could not reproduce your issue in 4.1.

Best,
Pedro

**Comment by pxpm** [comment] 2020-05-06 10:32
Going to close this. If needed please re-open.

**Closed by pxpm** 2020-05-06 10:32 UTC
Labels: triage

**Comment by tifaahmed** [comment] 2020-05-06 12:41
the problem solved when i turned  the security off in the control panel.
i'm using the demo of  version  4.0.
i think everything will be fine when i buy the licence
