### ISSUE TITLE
(column: select_multiple) Relationship Values Column Formatting in Export is Not Properly Aligned

### ISSUE THREAD

**Issue by sandeepchowdary7** [Laravel-Backpack/CRUD#4270] opened 2022-03-16 17:50 UTC
# Bug report
(column: select_multiple) Relationship Values Column Formatting in Export is Not Properly Aligned

### What I did
I'm using Laravel Backpack 4.1.66V and Exporting data by calling `$this->crud->enableExportButtons();` in `CrudController@setup()` function. Where in this CRUD Controller I have used the `select_multiple` column type to display the relationship values (comma separated). Everything working fine except for Export Formatting for relationship values. In Export Files relationship values column format is weird. I guess because of commas they're not displaying in the right format.

### Is it a bug in the latest version of Backpack?
I guess it still persists in the latest version too.

### Backpack, Laravel, PHP version
Backpack: V4.1.66
Laravel: v8.83.5

When I run ```php artisan backpack:version``` the output is:
Backpack: 4.1.66

Any help would be great. Thanks in advance

**Comment by pxpm** [comment] 2022-03-22 10:47
Hello @sandeepchowdary7 thanks for the report. 

At the moment the separator comma (`,`) is hardcoded, but if you publish your column and override the blade file to use something else like `;` or `.` as a separator does it work ? https://github.com/Laravel-Backpack/CRUD/blob/337163b7e9a0e63413474bd3ee800a198f83c8e9/src/resources/views/crud/columns/select_multiple.blade.php#L43

Let me know. 🙏

**Comment by pxpm** [comment] 2022-07-22 12:32
Hello @sandeepchowdary7 

I can confirm the export for `select_multiple` column is kind of broken.

After some hours of debugging I found out the issue to be related on the fact that datatables export uses the generated html for export, and blade leaves out some artifacts in html that are not correctly interpreted. 

I found out that if we have the column "render" in one line, it will export **almost** fine:
```php
// select_multiple.blade.php column
{{-- relationships with pivot table (n-n) --}}
@php
    $column['value'] = $column['value'] ?? data_get($entry, $column['name'], []);
    $column['escaped'] = $column['escaped'] ?? true;
    $column['prefix'] = $column['prefix'] ?? '';
    $column['suffix'] = $column['suffix'] ?? '';
    $column['limit'] = $column['limit'] ?? 32;
    $column['attribute'] = $column['attribute'] ?? (new $column['model'])->identifiableAttribute();

    if($column['value'] instanceof \Closure) {
        $column['value'] = $column['value']($entry);
    }

    if($column['value'] !== null && !$column['value']->isEmpty()) {
        $related_key = $column['value']->first()->getKeyName();
        $column['value'] = $column['value']->pluck($column['attribute'], $related_key);
    }

    $column['value'] = $column['value']
        ->each(function($value) use ($column) {
            $value = Str::limit($value, $column['limit'], '…');
        })
        ->toArray();
@endphp

<span>@if(!empty($column['value'])){{ $column['prefix'] }} @foreach($column['value'] as $key => $text)<span class="d-inline-flex">@includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_start')@if($column['escaped']){{ $text }}@else{!! $text !!}@endif @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_end', ['related_key' => $key])@if(!$loop->last), @endif</span>@endforeach{{ $column['suffix'] }}@else{{ $column['default'] ?? '-' }}@endif</span>
```
The problem is that the html we give to the datatable column to render is from a view, that by default will render the exactly contents of your blade file (divs, spans, etc) in multiple lines like you defined in your blade file.
That is not needed in this case, as long as everything is displayed we don't need it to be rendered in multiple lines etc. 

I found a "quick" solution, since `render()` accepts a closure as parameter to format contents, I get the contents without line breaks and no more than 1 space allowed. 
Also did some modifications to the blade file to remove some extra white space from elements. Check PR here: https://github.com/Laravel-Backpack/CRUD/pull/4546

All of this findings came when debugging the colum and writting the output as a plain string, I've create a branch with it, but didn't submit pr for it, you can check the changes here: https://github.com/Laravel-Backpack/CRUD/compare/v5...select-multiple-column-string

@tabacitu I think $column['render'] would be usefull here ... 👍 If not any of this two solutions I talked about, only having CrudColumns as objects and implementing their render function could solve this. Using "rendered" views for this situation it's not ideal. 

What do you think ?

**Comment by tabacitu** [comment] 2022-08-05 09:33
Thanks for letting us know @sandeepchowdary7 . I tried it too, and I think I understand the problem. Let me post some screenshot here too, so it's easier to understand what we're talking about. Here's how the `select_multiple` column gets exported to PDF:
![CleanShot 2022-08-05 at 12 25 53](https://user-images.githubusercontent.com/1032474/183047507-a16abea2-5c22-459d-8666-4a3bb9a9543c.png)

and to Excel:

![CleanShot 2022-08-05 at 12 26 26](https://user-images.githubusercontent.com/1032474/183047640-000f560c-7404-4c81-a3a3-7519edffec73.png)

In short, the `Tags` column has a lot of space after each item (before the comma).

---

> All of this findings came when debugging the colum and writting the output as a plain string, I've create a branch with it, but didn't submit pr for it, you can check the changes here: https://github.com/Laravel-Backpack/CRUD/compare/v5...select-multiple-column-string

I don't understand - should I be looking at that or not? I don't understand if there's anything here to discuss @pxpm or we should close this and move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/4546 Can you please give your recommendation on what to do here?

Thanks!

**Comment by pxpm** [comment] 2022-08-09 10:39
Closing and moving the conversation to #4546

**Closed by pxpm** 2022-08-09 10:39 UTC
Labels: Minor Bug
