### ISSUE TITLE
Datatables Responsive

### ISSUE THREAD

**Issue by elraghifary** [Laravel-Backpack/CRUD#152] opened 2016-10-01 09:55 UTC
I have been struggling with many columns that I want to show in mobile view. I try to use datatables responsive to fix that.

Example:
![Example1](http://image.prntscr.com/image/b2fd7ec2545c406c8ec9722c39fd8877.png)

If I click that green + button, it will show the rest of the columns.
![Example2](http://image.prntscr.com/image/2e5b0818637348d48db3a0ac107a4809.png)

If I add enableDetailsRow(), it will show like this.
![Example2](http://image.prntscr.com/image/02babb4859d64213a765013566ee0e34.png)

To make that work, edit list.blade.php in backpack/crud packages:

```
{{-- <link href="{{ asset('vendor/adminlte/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" /> --}}
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.dataTables.min.css" rel="stylesheet" type="text/css" />
```

```
<table id="crudTable" class="table table-bordered table-striped display dt-responsive" cellspacing="0" width="100%">
```

```
{{-- <script src="{{ asset('vendor/adminlte/plugins/datatables/jquery.dataTables.js') }}" type="text/javascript"></script> --}}
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/responsive/2.1.0/js/responsive.bootstrap.min.js" type="text/javascript"></script>
```

```
var table = $("#crudTable").DataTable({
        "pageLength": {{ $crud->getDefaultPageLength() }},
        responsive: true,
        autoWidth: false,
        ...................
```

It seems good, but it will override details_row.blade.php. I want to keep details row, but the position is below the rest of the column. How?

**Comment by seedgabo** [comment] 2016-10-01 19:52
i don't know how to resolve your issue but your code is a good improvement for the crud...
Thanks 💃 .

maybe @tabacitu can use to the master branch
an option be like:
$this->crud->allowResponsive();

**Comment by tabacitu** [comment] 2016-10-02 12:21
Wooow. I think you're right, @seedgabo, this would be a great addition. Thank you, @elraghifary . 

@elraghifary - I don't understand the issue you're facing. Does the details_row "jump" one row below, so it seems like it's the details of a wrong row?

Cheers!

**Comment by elraghifary** [comment] 2016-10-02 12:49
The details_row information is right. But the position is not right. It would be like this:

![Example](http://image.prntscr.com/image/c645eed83d31492b83a0bfa46548078e.png)

Red box is the column that didn't covered because of responsive datatables.

Green box is the information in details_row.blade.php.

If I click the (+) button (green/red) from the responsive, it shows the rest of the columns.

If I click the [+] button from the enableDetailsRow(), it shows the details, but the + button change into red (-) like the third picture above. It means green box overwrite the red box. I need to split red box and green box like the picture above.

So if I click [+] button it will shows the red box and green box in right position. If I click (+) button only show the red box.

I'm sorry if this possible or not but I gonna try a bit more. Thank you.

**Comment by elraghifary** [comment] 2016-11-11 07:23
I just took another solution about this one, I use custom datatables with Fixed Columns extension and remove responsive extension.

It is cover my 16 columns in my table.

Thanks everyone.

**Comment by tabacitu** [comment] 2016-11-11 08:12
Hi @elraghifary ,

I wouldn't close this issue just yet. It is a real problem that the datatables aren't responsive, so I'd keep it open until we fix that.

Could you tell us more about your solution? Just by using the [Fixed Columns extension](https://datatables.net/extensions/fixedcolumns/) the problem is fixed? Do you think we can implement this in Backpack for all CRUDs, by default?

Thanks, cheers!

**Comment by elraghifary** [comment] 2016-11-11 14:40
@tabacitu 

For my case, yes it is.

I have one table that has 16 columns, and I want to show all of them. I did something like this:

![Image](http://image.prntscr.com/image/9f07156a127f490d8a635745a7d05feb.png)

![Image](http://image.prntscr.com/image/d268a86de400438d8a18c245fc1460e2.png)

The view looks good from mobile.

I think implement this list view by default is depend what user need. Since table view is normal if you show less columns, using [Fixed Columns](https://datatables.net/extensions/fixedcolumns/) extension it automatically expand the table view if you show more columns.

I modified list.blade.php:
```
<table id="crudTable" class="table table-bordered table-striped display nowrap" cellspacing="0" width="100%">
```
```
<link href="https://cdn.datatables.net/fixedcolumns/3.2.2/css/fixedColumns.dataTables.min.css" rel="stylesheet" type="text/css" />
```
```
<script src="https://cdn.datatables.net/fixedcolumns/3.2.2/js/dataTables.fixedColumns.min.js" type="text/javascript"></script>

var table = $("#crudTable").DataTable({
    "scrollY": "400px",
    "scrollX": true,
    "scrollCollapse": true,
    "fixedColumns": {
        "leftColumns": 2
    },
});
```

**Comment by OwenMelbz** [comment] 2016-12-04 18:27
Hi guys, I'm just going to close this to keep the place tidy, its been referenced in a consolidated list which can be monitored here https://github.com/Laravel-Backpack/CRUD/issues/285

**Comment by dberry37388** [comment] 2016-12-31 06:47
I realize this has been closed, but I'm not sure where else to put this.

An easy fix is to just add:
```
table-responsive
```

to the line ```<div class="box-body">```

No need to add any additional scripts or styles. This is a feature in AdminLTE.

See the Simple Hover Table Code here https://almsaeedstudio.com/themes/AdminLTE/pages/tables/simple.html

**Comment by tabacitu** [comment] 2017-01-08 10:59
@dberry37388 , you're right. It makes total sense to me for the table to be scrollable horizontally by default, on smaller viewports. 

Thank you, just pushed it into master. 

Cheers!

**Comment by abradabra** [comment] 2017-05-12 17:57
why do not push yet?

**Comment by tabacitu** [comment] 2018-01-11 13:57
Guys, I've reopened this issue because I think our datatables UX is sub par on mobile, and needs fixing ASAP.

@elraghifary 's [solution (using the responsive plugin for datatables)](https://datatables.net/extensions/responsive/) sounds like a good long-term solution to me, but with a twist - [opening the row in a bootstrap modal](https://datatables.net/extensions/responsive/examples/display-types/bootstrap-modal.html). This should allow us to use both datatables-responsive and our own details_row in the same list view and, in my opinion, give the best UX on mobile (click row, see all columns that you couldn't see, then click edit or delete or whatever). Simple. Intuitive.

Problem is: I couldn't get datatables-responsive plugin to work with AdminLTE/Backpack. At all. It gives no errors, just doesn't freaking work. I've spend an embarrassing number of hours on this already, so I must be missing something obvious. I'll post a screenshot here of the diff from ```list.blade.php``` (for me, mostly) and come back to it after I cool down a bit, hopefully I'll spot my error then. If anybody notices my mistake in the meantime, please oh please let me know :-)

But wanted to leave the issue open with my progress, so that we pick it up from here.

Cheers!

![screen shot 2018-01-11 at 15 53 08](https://user-images.githubusercontent.com/1032474/34828887-abf4d166-f6e7-11e7-95e6-bdd4720e6191.png)
![screen shot 2018-01-11 at 15 53 32](https://user-images.githubusercontent.com/1032474/34828888-ac1200ba-f6e7-11e7-99d6-6c2dd75078cd.png)

**Comment by lloy0076** [comment] 2018-01-11 14:40
@tabacitu Can we not push the simpler solution to make it better than it is now and then get excited about Modal popups etc?

**Comment by tabacitu** [comment] 2018-01-11 15:47
@lloy0076 the simpler solution is already pushed - has been for a year now :-) But it just allows you to scroll the table horizontally on mobile, which is... not mobile-friendly at all. It's a hack, imho.

In the meantime I found the problem (just needed to use the latest datatables) and have come up with a working prototype: https://github.com/Laravel-Backpack/CRUD/pull/1180 But yeah, you're right, better to move the conversation to the PR and close this issue. We have _a solution_, let's talk in the PR about _the better_ solution.

**Closed by tabacitu** 2018-01-11 15:47 UTC
