### ISSUE TITLE
[Bug] The file field that was used within the relationship's subfields, was not sent with the request

### ISSUE THREAD

**Issue by RoliJ** [Laravel-Backpack/CRUD#4676] opened 2022-09-20 11:09 UTC
# Bug report

### What I did

I added a `File` field to my relationship field's subfields, using the [website's instructions](https://backpackforlaravel.com/docs/5.x/crud-fields#upload-1).

### What I expected to happen

I expected the file's name be inserted to the database and I have the file on my disk.

### What happened

None of the aforementioned expectations were satisfied, because backpack didn't added `enctype="multipart/form-data"` to the main form tag.

### What I've already tried to fix it

I did nothing to fix that. But, when the user clicks on the "+ New Item" button, this propert should be added to the main form tag (in case there isn't a file field available inside the non-subfields).

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? YES.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

#### PHP VERSION:
`PHP 7.4.9`

#### LARAVEL VERSION:
`v8.83.23`

#### BACKPACK VERSION:
`5.3.12`

**Comment by pxpm** [comment] 2022-09-20 11:27
Hello @RoliJ 

Thanks for the report. 

Unfortunatelly the problem is a abit more extensive than adding the `encoding` in the form and we are aware of it, and plan to fix it by developing a new upload field ajax based. 🙏 

https://github.com/Laravel-Backpack/CRUD/issues/4141

There is also the mutator issue, the re-rendering etc. 

I will be closing this issue, if you test around and found something that we might be missing, please write on that issue I mentioned, so we keep the conversation regarding this issue in a single place. 

Thanks again

**Closed by pxpm** 2022-09-20 11:27 UTC
Labels: triage

**Comment by RoliJ** [comment] 2022-09-20 11:51
@pxpm Thanks for the response. Hope to see this MUST feature very soon.

**Comment by CamusMX7** [comment] 2023-07-26 05:01
@pxpm 
Sorry if it's not the right place.
I have followed this topic in different posts and it is not clear to me: Is this solved in backpack v6 with:
https://backpackforlaravel.com/docs/6.x/crud-uploaders#subfields-in-uploaders-1 ?

Because in the documentation they recommend as correct the option to make it suggested as in backpack v5:
https://backpackforlaravel.com/docs/6.x/crud-fields#upload-1

Is there no longer a problem with the upload field when using it in repeatable subfields?

Is there an up-to-date list of fields that are 100% compatible with the repeatable field?
something like what they commented on:
https://github.com/Laravel-Backpack/CRUD/pull/3905
