### ISSUE TITLE
Problem with Modal on theme-coreuiv2

### ISSUE THREAD

**Issue by helesjunior** [Laravel-Backpack/CRUD#5665] opened 2024-09-17 11:59 UTC
Hey guys, 

I'm having a problem using a modal button in coreuiv2. I created the button and when I click it shows the modal, but it blocks the screen and I can't use it.

```
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
    Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
```

![image](https://github.com/user-attachments/assets/9d582156-5451-4a24-811b-ff90055267fc)

### PHP VERSION:
8.3.10

### PHP EXTENSIONS:
Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, random, readline, Reflection, session, standard, mysqlnd, tokenizer, zlib, libxml, dom, PDO, openssl, 
SimpleXML, xml, xmlreader, xmlwriter, ldap, curl, fileinfo, gd, gettext, gmp, intl, imap, mbstring, mysqli, odbc, Phar, pdo_mysql, PDO_ODBC, pdo_pgsql, pgsql, shmop, sqlsrv, pdo_sqlsrv, soap, sqlite3, xsl, zip, Zend OPcache

### LARAVEL VERSION:
11.20.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.4
backpack/basset: 1.3.5
backpack/crud: 6.7.26
backpack/generators: v4.0.5
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.13
backpack/theme-coreuiv2: 1.2.5

**Comment by karandatwani92** [comment] 2024-09-17 15:29
Duplicate of https://github.com/Laravel-Backpack/community-forum/issues/1158 - Closing this one

**Closed by karandatwani92** 2024-09-17 15:29 UTC
Labels: triage
