### ISSUE TITLE
[Bug] model_function works for SHOW but not for LIST

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#2999] opened 2020-07-06 09:20 UTC
# Bug report
I would like to display a field using 'model_function' and it works only for 'SHOW' operation.

### What I did
I have below code inside both LIST and SHOW operations method of my CRUD Controller.
`CRUD::column('filepath')->label('Label File')->type('model_function')->function_name('getFileLink');`

### What I expected to happen
Both LIST and SHOW should display the column values.

### What happened
This works only for SHOW and LIST has empty column.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.18.0@116b508bafd81de97b1c09744445d32a91076b60

### BACKPACK VERSION:
4.1.12@e5e3efc89775574fff03ef0000677e9a85903c9b

**Comment by tabacitu** [comment] 2020-07-08 06:10
@srigurubyo I'm afraid I can't confirm this bug exists - it works well from my tests, this model_function 

![Screenshot 2020-07-08 at 09 07 24](https://user-images.githubusercontent.com/1032474/86883339-77a6d280-c0fa-11ea-9af1-d3d406129070.png)

shows both inside the Show operation: 
![Screenshot 2020-07-08 at 09 08 27](https://user-images.githubusercontent.com/1032474/86883409-9c02af00-c0fa-11ea-8ef9-c030a38ed338.png)


and inside the List operation:

![Screenshot 2020-07-08 at 09 08 47](https://user-images.githubusercontent.com/1032474/86883449-aae96180-c0fa-11ea-8ce1-b908d7d6bbea.png)

I'm going to close this as I'm pretty sure it's not a bug. You can even see it working on [demo.backpackforlaravel.com](https://demo.backpackforlaravel.com). Let us know if I'm wrong and there truly is a bug, I'm wrong sometimes too.

Cheers!

**Closed by tabacitu** 2020-07-08 06:10 UTC
Labels: Bug

**Comment by srigurubyo** [comment] 2020-07-08 09:18
@tabacitu Did you try with function returning a hyperlink instead of just a string?  I am using a helper method to construct the 'link' and am getting link only in SHOW.  In LIST content is getting displayed without link
