### ISSUE TITLE
[Bug] Serious problem after 5.2.0 update with middlewares using octane

### ISSUE THREAD

**Issue by dilneiss** [Laravel-Backpack/CRUD#4536] opened 2022-07-20 22:23 UTC
# Bug report

### What I did
I've gone back to the previous version (5.1.4) and now it's working normally.

### What I expected to happen
Load the page normal

### What happened

When I load a page that is using a certain middleware for the first time, it works and uses that middleware normally, when I load another page that uses another middleware, the system is thinking it should use the old middleware, not the other one.
If I run the command: artisan octane:reload, the page that was giving an error works again, but the previous one stops working, because it's trying to use middleware that it's not supposed to use.
Ps. I am using octane with swoole

### What I've already tried to fix it
I am looking at the differences in those versions: https://github.com/Laravel-Backpack/CRUD/compare/5.1.4...5.2.0
I think the problem can be here: src/app/Library/CrudPanel/Traits/HasViewNamespaces.php, i am trying to change codes to check.
Tried to rollback changes in those files according to compare:
src/app/Library/CrudPanel/CrudFilter.php
src/app/Library/CrudPanel/CrudButton.php (this break all)
src/app/Http/Controllers/Operations/ListOperation.php
Tried to comment: src/app/Library/CrudPanel/Traits/Columns.php
src/app/Library/CrudPanel/Traits/Read.php
src/app/Library/CrudPanel/Traits/Views.php

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 24 2022 10:42:33) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.21.3@66bfa61e61ffceddb6370b57306c76ead7667622

### BACKPACK VERSION:
5.2.1@0dc8eb9073cede13dc2afc0cebb41f067fc58271

**Comment by pxpm** [comment] 2022-07-21 15:49
Hello @dilneiss 

Thanks for the report, I had never used Backpack with Octane myself, today was my first 🙃 🍾 

I've submitted a PR that fixes the issue: https://github.com/Laravel-Backpack/CRUD/pull/4542

Can you give it a try and let me know if it solved for you too ? 

Also can you let me know if you found any other corner cases while using Backpack with Octane ?

Cheers

**Comment by dilneiss** [comment] 2022-07-21 21:44
Thankyou @pxpm, i believe you understand my problem :)
I think now it gonna work, is there a way to test just this branch? because it was not merged yet

**Comment by tabacitu** [comment] 2022-07-22 11:13
@dilneiss yes, you should be able to do `composer require backpack/crud:"dev-singleton-view-namespaces as 5.2.99"` and get that particular branch.

**Comment by pxpm** [comment] 2022-07-22 14:34
@tabacitu @dilneiss note that probably you would need to do the same if using PRO:
`composer require backpack/pro:"dev-use-CrudPanelViewNamespaces-class as 1.2.99"` since PRO service provider needs changes with this branch. 

Cheers

**Comment by dilneiss** [comment] 2022-07-22 23:01
@tabacitu @pxpm tested and everything is working now, thankyou! please merge that branch :)

**Comment by tabacitu** [comment] 2022-07-23 11:12
Awesome. Thanks for the confirmation @dilneiss . Let's close this in order to move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/4542 - there are still a few minor details to work out there, before merging.

**Closed by tabacitu** 2022-07-23 11:12 UTC
Labels: triage, Possible Bug

**Comment by busaku** [comment] 2022-08-13 19:47
I can confirm:
In dev-branch everything works fine.

I got other (more errors) before. Some fields are shown under different names.
e.g. "locations" table with "city" and "country". the country was shown under the city and the other way around.

But in dev branch everything works fine with octane :)
