### ISSUE TITLE
Multiple DB getting table schema

### ISSUE THREAD

**Issue by mohsensaeedi** [Laravel-Backpack/CRUD#354] opened 2017-01-12 17:42 UTC
I checked multiple database with Backpack CRUD and i have a problem when crud tries to get DB columns name from information_schema database. As you know i want to use another database in my Model with defined $connection property but CRUD tries first database to get columns with where table_schema = 'backpack' statement.

Note: I am know how to use multiple database in laravel without backpack and how to define second database connection on backpack as we discussed.

And for your recommendation about to use Accessors & Mutators in Model, I can't implement on my Model. Can you give me a brief example to do that? I want to define another database and table on my Model.

Best regards,

**Comment by mohsensaeedi** [comment] 2017-01-15 20:27
@tabacitu 
After some working hard, now i found a real bug on PanelTraits/AutoSet.php file.

You said me everything works like eloquent on model. on this issue #342 

but it's wrong! when i use two mysql database and i change my connection parameter on specific model, CRUD unable to get column list and type! you have method on trait AutoSet such as getDbColumnTypes and getDbColumnsNames.

When you need to get some information from table you should use correct eloquent form. for example:

` public function getTableColumns() {
        return $this->getConnection()->getSchemaBuilder()->getColumnListing($this->getTable());
    }`

but you use this in wrong way and now it try to get information from backpack main mysql connection that defined on .evn file. for example in getDbColumnTypes() the below

`$table_columns = \Schema::getColumnListing($this->model->getTable());`

must be changed to below:

`$table_columns = $this->model->getConnection()->getSchemaBuilder()->getColumnListing($this->model->getTable());`

and this line:
`$column_type = \Schema::getColumnType($this->model->getTable(), $column);`
must be changed to:
`$column_type = $this->model->getConnection()->getSchemaBuilder()->getColumnType($this->model->getTable(), $column);
`
and in getDbColumnsNames() this line:
`$columns = \Schema::getColumnListing($this->model->getTable());`
should be changed to:
`$columns = $this->model->getConnection()->getSchemaBuilder()->getColumnListing($this->model->getTable());`

Some problems exist after these change and i try to solve all of them. but after these changes CRUD get columns name and type correctly when you use more than one DB connection. The old code bypass $connection parameter defined on specified model. 

best regards,

**Comment by OwenMelbz** [comment] 2017-01-15 20:36
Is this what https://github.com/Laravel-Backpack/CRUD/pull/338/files tries to solve?

**Comment by mohsensaeedi** [comment] 2017-01-15 20:48
Yes! Right now i find this line and i see no connection named is defined as connection function input parameter. why these change is not in the last version of release 3.1?

**Comment by mohsensaeedi** [comment] 2017-01-15 21:19
@OwenMelbz 
After run composer update i got new changes. now everything works well. but some another problem. when i use specified model with second database i see this wrong query again
`select column_name from information_schema.columns where table_schema = 'backpack' and table_name = 'relay_users'`
backpack DB is used as first db connection and relay_users is on second db connection!! 
we defined mtpolicyd connection name on config/database.php and then use these setting on our .env file for second DB connection:

mtpolicyd_DB_CONNECTION=mysql
mtpolicyd_DB_HOST=127.0.0.1
mtpolicyd_DB_PORT=3306
mtpolicyd_DB_DATABASE=db_name
mtpolicyd_DB_USERNAME=user_name
mtpolicyd_DB_PASSWORD=user_password

I think problem is exist on AutoSet.php trait AutoSet in these methods:
getDbColumnTypes()
getDbCollumnsNames()

Do you agree with me?

**Comment by tabacitu** [comment] 2017-01-18 07:26
Hmm... If the problem is in AutoSet.php, a quick way around it would be to disable the ```autoSetFromDb()``` method in your EntityCrudController that doesn't use the same table, then define all the fields and columns manually. 

I usually do that anyway, because it provides more flexibility to edit. Plus, as it is right now, autoSetFromDb() doesn't guess my needs 100% of the time.

Hope it helps. Cheers!

**Comment by mohsensaeedi** [comment] 2017-01-18 12:17
I think,it's better to get db columns name and db columns type with autoSetFromDb() with any model. i our case we are force to use two database. autoSetFromDb() connect to first db and get schema information from mysql (in our case). 

I fixed this condition and just change two line code. 
define all fields and columns manually is not very good. 
If you add getConnection() on query line the problems will be solved. 

Thanks,

**Comment by christopher-wilson** [comment] 2017-02-03 18:31
@mohsensaeedi Or anyone else, do we still have to change `AutoSet.php`? These changes will be lost if we do a `composer update` right? Where do we put new functions so it will be overridden?

**Comment by OwenMelbz** [comment] 2017-02-03 18:34
If you changes files in the vendor folder they will get over written, if you want to change the functionality then create your custom autoFromDB function then you can keep it forever

**Comment by mohsensaeedi** [comment] 2017-02-03 18:35
@christopher-wilson I think the best way is to add our change by @tabacitu to mainstream. I can create pull request for them. I am not aware about all Laravel ability but i think you can inherit autoFromDB function and change it based on your requirement.

**Comment by lloy0076** [comment] 2017-08-12 10:10
@mohsensaeedi @halaei - is there a PR here?

**Comment by lloy0076** [comment] 2017-08-14 02:46
I think the merged PR fixes this issue - if not (and it's possible I'm muddling things here), please reopen.

**Closed by lloy0076** 2017-08-14 02:46 UTC

**Comment by SolarZi** [comment] 2018-03-21 09:55
非常感谢。

**Comment by kiddtang** [comment] 2018-10-31 03:55
the 'Search' trait using the current CRUD connection instead of the other connection which cause the ajax search fail. Anyone could fix the search issue for multiple DB connection?
