### ISSUE TITLE
[Bug] Permission manager roles and permissions cant assing to user

### ISSUE THREAD

**Issue by arminkardovic** [Laravel-Backpack/CRUD#4799] opened 2022-12-01 16:52 UTC
# Bug report

### What I did
I install permission manager and I can't save role or permission to the user from the panel, no error just nothing happened

### What I expected to happen

Assign role and permission to the user

### What happened

MorphToMany in creating function  is set but in this code relation type is MorphToManyCustom 
vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Create.php line 120

### What I've already tried to fix it

Yes but it's in the core package

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes, then the Roles list does not work

### Backpack, Laravel, PHP, DB version

PHP 8.0.13 (cli) (built: Nov 16 2021 21:58:37) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.40.1@9611fdaf2db5759b8299802d7185bcdbee0340bb

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8

**Comment by pxpm** [comment] 2022-12-02 10:48
Helllo @arminkardovic 

I've just tested this, and was not able to reproduce it. 

Can you reproduce your issue in https://demo.backpackforlaravel.com ?

**Comment by arminkardovic** [comment] 2022-12-02 10:54
https://demo.backpackforlaravel.com/admin/role  try to open this link

 it's also not working on my side and on the demo, and my bug on this demo is fine I can't reproduce it also. Let me check again and I will let you know

**Comment by pxpm** [comment] 2022-12-04 09:09
@arminkardovic no that link is broken 😞, it's related to this issue: https://github.com/Laravel-Backpack/CRUD/pull/4796

In tomorrow Monday Release we are going to get rid of that bug 👍 After you can let me know if your issue still persist and I can try to help you the best I can if it does.

Going to close this for now since you could not reproduce your issue in demo repository, but feel free to keep the discussion going and eventually if we find a bug we can re-open! 👍 

Wish you all the best 🎅

**Closed by pxpm** 2022-12-04 09:09 UTC
Labels: triage
