### ISSUE TITLE
[Help] Relationship

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#2975] opened 2020-06-29 14:25 UTC
# Report
I have a parent - child relationship where I am able to successfully pull data and display it on the LIST as well SHOW operations.  However I would like to display two fields from the dependent table where I have defined relationship.  Please refer the code below:

`
CRUD::column('material')->label('Material')->type('relationship')->attribute('shortname');
CRUD::column('material')->label('Category')->type('relationship')->attribute('category');`

The above code overwrites the 'shortname' attribute and displays only 'category' - as FORM can not have duplicate field names.  

I have read somewhere using 'field id' kind of a mechanism to overcome this problem wherein we can display multiple fields from the dependent table without modifying the model.

# Workaround
I have defined method in my Model class getCategoryAttribute() which returns the category.  However I am looking for a cleaner solution, if available. 

# Disadvantage in the workaround
Because it is a method defined in model, the default search option doesn't work and the developer has to write 'search' logic part of the filed definition.  

Thanks in advance for your help here.

**Comment by tabacitu** [comment] 2020-06-30 16:40
@srigurubyo I'm not sure I understand your use case, but yes, your second `CRUD::column()` call will refer to the same column and edit it, if it has the same name. 

Can you try `material.shortname` and `material.category` as the names of your columns? You can then lose the `type` and `attribute`, Backpack will deduct them from the dot notation.

```php
CRUD::column('material.shortname')->label('Material'); 
CRUD::column('material.category')->label('Category');
```

I'm going to close this as it's not a bug. Feel free to answer here if the above doesn't solve your problem though.
Cheers!

**Closed** 2020-06-30 16:40 UTC
Labels: Ask-It-On-Stack-Overflow

**Comment by srigurubyo** [comment] 2020-06-30 19:21
This is super cool @tabacitu.  I was not aware of such feature and thanks a lot for providing that piece of information.

**Comment by srigurubyo** [comment] 2020-06-30 19:31
I am wondering can the below statement be simplified using fluent syntax?
```

        CRUD::column('material.category')->label('Category')
        ->wrapper(['element' => 'span',
                   'class'   => function ($crud, $column, $entry, $related_key) {
                                    return CommonHelper::getMEStatusColor($column);
                                }
                  ]);
```

**Comment by srigurubyo** [comment] 2020-07-01 15:40
I figured this out. Thanks!

**Comment by srigurubyo** [comment] 2020-07-01 15:41
> @srigurubyo I'm not sure I understand your use case, but yes, your second `CRUD::column()` call will refer to the same column and edit it, if it has the same name.
> 
> Can you try `material.shortname` and `material.category` as the names of your columns? You can then lose the `type` and `attribute`, Backpack will deduct them from the dot notation.
> 
> ```
> CRUD::column('material.shortname')->label('Material'); 
> CRUD::column('material.category')->label('Category');
> ```
> 
> I'm going to close this as it's not a bug. Feel free to answer here if the above doesn't solve your problem though.
> Cheers!

Is there any such shortcuts available for 'field' as well or is this applicable only to 'column'?

**Comment by tabacitu** [comment] 2020-07-08 06:16
Same thing. ```CRUD::field()``` will create a new field, or modify an existing field. Otherwise if you want only one you can use `CRUD::addField()` or `CRUD::modifyField()`. More info about this in the docs:
- https://backpackforlaravel.com/docs/4.1/crud-cheat-sheet
- https://backpackforlaravel.com/docs/4.1/crud-api
- https://backpackforlaravel.com/docs/4.1/crud-fluent-syntax
