### ISSUE TITLE
Save function not working on iOS

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/CRUD#4889] opened 2023-01-08 21:42 UTC
# Bug report

### What I did

Run an app built with the latest version of Backpack and accessed the save function through Mobile Safari and Chrome on iOS 15.6.1.

### What I expected to happen

That the entity changes would be saved.

### What happened

Nothing. No error appeared, the changes were not saved, the page did not change.

### What I've already tried to fix it

Nothing.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug is still there.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.2-1ubuntu2.9 (cli) (built: Oct 19 2022 14:58:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.46.0@62b05b6de5733d89378a279e40230a71e5ab5d92

### BACKPACK VERSION:
5.4.14@f77c74c1d6ae8b0dedf825f74c6c1aea84ba1992

**Comment by pxpm** [comment] 2023-01-09 00:28
Hey @malle-pietje thanks for the report.

You say that when you click to save, nothing happens? Page don't refresh, nothing? 

Does it happen with every save action, or only the actions that are inside the dropdown?

Cheers

**Comment by malle-pietje** [comment] 2023-01-09 10:30
Hi @pxpm , yes, nothing happens whichever save function from the dropdown is used. Not even an error message. This is what the page looks like:
![IMG_0687](https://user-images.githubusercontent.com/12016131/211287789-6a9fe941-cc93-46e3-9682-c354b978da6e.jpg)

Unfortunately I don't have access to the browser console on the iPad (don't use MacOS) so can't check any output there.

**Comment by malle-pietje** [comment] 2023-01-09 10:37
Updated the version details.

**Comment by malle-pietje** [comment] 2023-01-09 10:39
By the way, the issue also occurs when accessing the demo, for example here:
https://demo.backpackforlaravel.com/admin/cave/create

**Comment by pekka** [comment] 2023-01-16 15:42
This is because Safari appears to have a problem with `.requestSubmit()`

Getting the same problem on Safari 15 on MacOS.

It is [supposedly fixed in Safari 16](https://caniuse.com/?search=requestSubmit), but I can't try because that seems to necessitate a MacOS update that I don't want at this point. 

This renders Backpack unusable on some Safaris.

![image](https://user-images.githubusercontent.com/262464/212716405-51f1c58e-6e86-4f66-8bda-390e8137da0c.jpeg)

**Comment by malle-pietje** [comment] 2023-01-16 16:17
@pekka Thanks for confirming. I just tested this with Mobile Safari 16 (iOS update on my iPad from last night) and the save function now works again! 😄

**Comment by pxpm** [comment] 2023-01-16 23:02
Thanks for confirmation guys 🙏 

@pekka from my research, we can replace `requestSubmit` by `form[0].dispatchEvent(new SubmitEvent('submit'))` in https://github.com/Laravel-Backpack/CRUD/blob/050b288caf2f60c79313f2b0b7d4fefd25177f3f/src/resources/views/crud/inc/form_save_buttons.blade.php#L88 and https://github.com/Laravel-Backpack/CRUD/blob/050b288caf2f60c79313f2b0b7d4fefd25177f3f/src/resources/views/crud/inc/form_save_buttons.blade.php#L103

I don't have an Apple product to test, would you mind manually testing yourself the change ? If it works feel free to submit the PR.

@tabacitu @maurohmartinez any of you guys has a way to test this ? 

Cheers

**Comment by pekka** [comment] 2023-01-17 00:10
> @pekka from my research, we can replace `requestSubmit` by `form[0].dispatchEvent(new SubmitEvent('submit'))` in

This does not seem to be working yet - there are no errors anymore, but the form is not submitted either and the button remains forever in its clicked state (with the bright background colour):

<img src="https://user-images.githubusercontent.com/262464/212783052-2ddd9522-31aa-48e6-b50e-fe05f8817bab.jpeg" width=400>

Hmm. Trying to wrap my head around what `requestSubmit()` does in the first place, if I work it out I'll see if I can find a fix...

**Comment by pekka** [comment] 2023-01-17 00:30
Nope. Can't get any version of 

```
form[0].dispatchEvent(new SubmitEvent('submit'))
```

to work on Safari 15. Tried different ways to create the event (`new Event()...` with `bubbles` set to `false` and `true`), different ways to address the form... the event just doesn't seem to fire, regardless whether the form is filled correctly or not, or (this is what I suspect) the event gets cancelled at some point with no error message. 

[This SO question](https://stackoverflow.com/questions/70698969/javascript-alternative-for-requestsubmit-since-safari-does-not-support-it) mentions a "fix" - firing a `.submit()` right after dispatching the event. But that just submits the form regardless of any validation errors, which seems to be the reason why `.requestSubmit()` is used in the first place.

I'm baffled!

**Comment by emogeekface** [comment] 2023-01-18 08:53
Not sure if this is related or I should open a new issue, but save actions within the dropdown list do nothing. I am not using iOS (I am on Windows 11 using Chrome).

**Comment by o15a3d4l11s2** [comment] 2023-02-23 09:43
@pxpm, not sure what is the current status on this, but we might use something like this polyfill: https://github.com/javan/form-request-submit-polyfill/blob/main/form-request-submit-polyfill.js which should handle the case with Safari versions before 16.

**Comment by maurohmartinez** [comment] 2023-02-25 07:47
@pxpm 
> @tabacitu @maurohmartinez any of you guys has a way to test this ?

I cannot reproduce this... it works without issues on my end. @tabacitu Have you been able to try this on your end?

**Comment by malle-pietje** [comment] 2023-02-25 08:52
> @pxpm
> 
> > @tabacitu @maurohmartinez any of you guys has a way to test this ?
> 
> I cannot reproduce this... it works without issues on my end. @tabacitu Have you been able to try this on your end?

As reported by me, it is now fixed with iOS 16.

**Comment by malle-pietje** [comment] 2023-02-25 08:54
I left the issue open because others were still seeing it.

**Closed** 2023-02-26 15:03 UTC
Labels: Minor Bug
