### ISSUE TITLE
[Bug] Select2_multiple does not send all values with include_all_form_fields

### ISSUE THREAD

**Issue by emogeekface** [Laravel-Backpack/CRUD#4960] opened 2023-03-03 15:33 UTC
# Bug report

### What I did

I have 2 fields, one is a `select2_multiple` field (languages) and one is `select_from_ajax` (preferred language). 

I want to use `include_all_form_fields` on my select_from_ajax to use in my fetch so that a user can only select a preferred language from the languages assigned to the record.

Code:

```php
//languages field
$this->crud->addField([ 
            'name'  => 'languages',
            'type'  => 'select2_multiple',
            'model'     => "App\Models\Language", 
            'attribute' => 'language_name',
            'pivot'     => true
]);

//preferred language field
$this->crud->addField([
            'label'                   => "Preferred Language",
            'type'                    => 'select2_from_ajax',
            'name'                    => 'preferred_language', 
            'model'                   => "App\Models\Language",
            'attribute'               => 'language_name', 
            'data_source'             => backpack_url('organisation/fetch/languages'), 
            'ajax'                    => true,
            'include_all_form_fields' => true,
            'minimum_input_length'    => 0,
            'dependencies'            => ['languages'], 
            'method'                  => 'POST',
 ]);

//fetch function
protected function fetchLanguages(Request $request)
    {
        $search_term = $request->input('q');
        $triggeredBy = $request->input('triggeredBy');
        $form = backpack_form_input();

        $options = \App\Models\Language::query();
        dd($form['languages']);

        //more stuff here but irrelevant to the issue

    }

```

### What I expected to happen

When I select multiple languages in my `languages` field, then click to use the `preferred_language` dropdown then I see an array of multiple values from my dd line.

### What happened

I see an array with only the last value I selected:

```
array:1 [ 
  "" => "10"
]
```

### What I've already tried to fix it

--

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? 

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
backpack/crud: 5.5.1
backpack/filemanager: 2.0.0
backpack/generators: v3.3.10
backpack/pagemanager: 3.0.12
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.0
backpack/settings: 3.0.16
```

**Comment by tabacitu** [comment] 2023-03-05 18:09
Hey @emogeekface ,

Interesting. I've dug into this and I can confirm this is happening. Looks like we have a bug inside `backpack_form_input()`. We'll fix ASAP and get back to you. 

Thanks for opening the issue!

---

@pxpm could you please take a look at this? I suspect was introduced [in this refactor](https://github.com/Laravel-Backpack/CRUD/commit/49ab723db56cebbe88e4c355a8b451709e1dd2e9) so it'll probably be fastest for you. From what I can tell from the code, we are treating `[]` now as relationships (because they have `[`), so... we might have forgotten all about select multiples 🤦‍♂️

How to reproduce in our Demo:
- I've added `'include_all_form_fields' => true,` to the `select2_from_ajax` field on Monsters;
- went to `ArticleController::index()` and done `dd(backpack_form_input())`;
- on Monsters, on the Select tab, I filled all fields, making sure the multiple fields were already filled before triggering the `select2_from_ajax` search;

The output of `backpack_form_input()` indeed include only the last selected item (see `tags` and `categories`), NOT all of the items selected:
<img width="1278" alt="CleanShot 2023-03-05 at 20 04 26@2x" src="https://user-images.githubusercontent.com/1032474/222977762-a552d805-e553-4a6d-a439-40351658f211.png">

So we're doing something wrong in `backpack_from_input()` now 🤦‍♂️

**Comment by pxpm** [comment] 2023-03-16 13:10
Thanks @emogeekface for the report, and @tabacitu for confirming the issue 🙏 

Indeed, one of my rookie mistakes, not handling inputs that name ends with `[]`, AKA multiple inputs. 

I've tried to redeem myself in https://github.com/Laravel-Backpack/CRUD/pull/4983 PR.

Someone in the team will review it, but if you happen to give it a try @emogeekface let me know if it's working in your use case too. You can do that by requiring in composer `"backpack/crud": "dev-fix-form-input-parsing-for-multiple-fields as 5.5.99"`

Going to close this, let's keep any discussion needed about this subject in the PR thread!

Cheers 🙏

**Closed by pxpm** 2023-03-16 13:10 UTC
Labels: Bug, triage
