### ISSUE TITLE
Add (fake) column with relationship count

### ISSUE THREAD

**Issue by Chrysanthos** [Laravel-Backpack/CRUD#1037] opened 2017-10-01 08:02 UTC
Hi, I want to add a column in my crud tables where the count of a relationship will be shown (just an integer).
I have a crud table of categories and I want to be able to see how many products there are in each category.
Is there any way to do it or is it something I need to implement on my own?

**Comment by tabacitu** [comment] 2017-10-02 06:17
Hi @Chrysanthos ,

I think the easiest way to do that would be to [have an accessor](https://laravel.com/docs/5.5/eloquent-mutators#defining-an-accessor) on your Category model that returns that, say... ```getNameWithCountAttribute()```. You'll then be able to use that attribute instead of the usual "name" when you define your column. Something like:

```php
[
   // 1-n relationship
   'label' => "Category", // Table column heading
   'type' => "select",
   'name' => 'category_id', // the column that contains the ID of that connected entity;
   'entity' => 'category', // the method that defines the relationship in your Model
   'attribute' => "name_with_count", // foreign key attribute that is shown to user
   'model' => "App\Models\Category", // foreign key model
]
```

Hope it helps. I'll close this issue as it's not a bug - more of a StackOverflow question.

Cheers!

**Closed by tabacitu** 2017-10-02 06:17 UTC
Labels: Ask-It-On-Stack-Overflow
