### ISSUE TITLE
4.0 searchLogic not working on whereHas clause.

### ISSUE THREAD

**Issue by rUriarteDev** [Laravel-Backpack/CRUD#2483] opened 2020-02-26 18:06 UTC
Good morning, I am having problems with the definition of search logic in a column of type select. This is the code ...
```
$this->crud->setColumnDetails('fecha_inscripcion', [
            'label' => 'Fecha Inscripcion',
            'type' => 'select',
            'name' => 'inscripcion_id', // the db column for the foreign key
            'entity' => 'inscripcion', // the method that defines the relationship in your Model
            'attribute' => 'fecha_inscripcion_formato', // foreign key attribute that is shown to user
            'model' => "App\Models\Inscripcion", // foreign key model
             'searchLogic' => function ($query, $column, $searchTerm) {
                 $query->orWhereHas('inscripcion', function ($q) use ($column, $searchTerm) {
                     $q->where('fecha_inscripcion_formato', 'like', '%' . $searchTerm . '%');
                 });
             },
        ]);
```
Inscripcion Model...
```
<?php

namespace App\Models;

use App\Support\FormatDate\FormatsDates;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Date;

class Inscripcion extends Model
{
    use CrudTrait;
    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'inscripciones';
    protected $primaryKey = 'id';
    public $timestamps = true;
    // protected $guarded = ['id'];
    protected $fillable = ['fecha_inscripcion', 'retira', 'user_id', 'banda_horaria_id', 'menu_asignado_id', 'comedor_id'];

    // protected $hidden = [];
    // protected $dates = [];
    protected $appends = ['nombre','fecha_inscripcion_formato'];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */
    public function user()
    {
        return $this->belongsTo('App\Models\BackpackUser');
    }
    public function bandaHoraria()
    {
        return $this->belongsTo('App\Models\BandaHoraria');
    }
    public function menuAsignado()
    {
        return $this->belongsTo('App\Models\MenuAsignado');
    }
    public function comedor()
    {
        return $this->belongsTo('App\Models\Comedor');
    }
    public function asistencia()
    {
        return $this->hasOne('App\Models\Asistencia');
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */
    public function getFechaInscripcionFormatoAttribute()
    {
        $myDate = Date::createFromFormat('Y-m-d', $this->fecha_inscripcion);
        return date_format($myDate,'d-m-Y');
    }
    public function getNombreAttribute(){
        return $this->user->name; 
    }

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */

}
```
on debug I get the following exception...

`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fecha_inscripcion_formato' in 'where clause'`

I know fecha_inscripcion_formato is not a column on Inscripcion, but there is an accessor on that name that should return the value required.

php artisan backpack:version returns
```
### LARAVEL VERSION:
laravel/framework                     v6.16.0          The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         v4.x-dev f84faa4 Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.6            Generate files for laravel projects
backpack/permissionmanager            5.0.6            Users and permissions management interface for Laravel 5 using Backpack CRUD.
```

**Comment by tabacitu** [comment] 2020-03-01 08:23
@rUriarteDev it should work fine with ```orWhereHas()```. I bet it's a query issue, rather than a Backpack issue, so I'll close this.

I suggest you move the ```$query->orWhereHas()``` logic outside your ```addColumn()``` statement while working on it, so it's easier to debug. You could do something like ```$this->crud->query = $this->crud->query->orWhereHas()``` to test it. I see that column is appended - that's probably the issue for you. Afaik you're trying to ask MySQL to do add a WHERE depending on a column that doesn't exist in MySQL. It's only appended in PHP, after the MySQL results are already out. You'll probably need to add a [Laravel subquery](https://laravel-news.com/eloquent-subquery-enhancements) for that column to be calculated in MySQL rather than PHP.

Sorry I can't be of more help, but this is definitely not a bug - it's an Eloquent query issue.

**Closed by tabacitu** 2020-03-01 08:23 UTC
Labels: triage
