### ISSUE TITLE
Sidebar doesn't open 

### ISSUE THREAD

**Issue by AlexandreCarvalhoDeMelo** [Laravel-Backpack/CRUD#3078] opened 2020-07-29 12:01 UTC
![Issue reported](https://i.imgur.com/SQTwJzB.gif "Title")

Hi everybody
So i've just managed to get backpack working with the admin flow running
Now for some reason after logging in the dashboard seems stuck
The logout but doesn't work, the sidebar doesn't open 
Trying to track any JS or CSS errors but nothing on console 
I've run the following commands to publish the assets

```
php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force
npm -i
npm run dev

```

Here's what my version output looks like

`### PHP VERSION:
PHP 7.3.19 (cli) (built: Jul  4 2020 20:25:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.22.4@30e851a2b3a2af73fba0b7f4fa22b04260db98e7

### BACKPACK VERSION:
4.1.15@6c751de946a9c8511dd32eb7bfa3ca6a568849f5
`

**Comment by AlexandreCarvalhoDeMelo** [comment] 2020-07-29 16:46
##Update

So looking at my checkIfAdmin even after login 
`backpack_auth()->guest()` resolves to true
What could be the problem?

**Comment by tabacitu** [comment] 2020-08-07 18:16
@AlexandreCarvalhoDeMelo - from your video I think your problem is with the login itself, rather than the sidebar. I noticed even after reaching the dashboard page, your top-right corner says "Login", not "Logout". That means you're not actually logged in. Which is _very_ weird, because you normally shouldn't even be able to see the dashboard without being logged in (obviously).

I'm 99.9% sure this is not a bug in Backpack, but an error in implementation, so I'm going to close this. We're trying to get the issue count down.

But feel free to reply below and I'll try to help out, time permitting.

First thing I'd check would be the parts of the authentication you customized. Have you changed `config/backpack/base.php` in any way? Middleware, guard, etc? Have you changed the backpack auth routes? Something in those changes must have triggered this weird behaviour.

Cheers!

**Closed** 2020-08-07 18:16 UTC
Labels: Ask-It-On-Stack-Overflow
