### ISSUE TITLE
[Bug] Summernote error in Chrome (due to jQuery version)

### ISSUE THREAD

**Issue by nbolender** [Laravel-Backpack/CRUD#3652] opened 2021-04-06 22:16 UTC
# Bug report

### What I did

Added a field with type `summernote`, then tried to submit a form from Chrome using the default save button.

### What I expected to happen

The form will submit

### What happened

Form does not submit, and Chrome shows this error in the console:

`Form submission failed, as the <TEXTAREA> element named '' was implicitly closed by reaching the end of the file. Please add an explicit end tag ('</TEXTAREA>')`

This is apparently due to the bundled jQuery version, according to the discussion here: https://github.com/summernote/summernote/issues/3820

Is there a way to upgrade/downgrade jQuery in the bundle, or generate the bundle on my end?

### PHP VERSION:
PHP 7.3.27 (cli) (built: Feb 27 2021 18:04:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.41@44770347b918e42c052d0a138c24535b43e32472

**Comment by pxpm** [comment] 2021-04-07 10:03
Hello @nbolender 

Thanks for the report, I was unaware of such bug. 

It seems that we are using the exact same version that broke the compatibility: https://github.com/DigitallyHappy/BackStrap/blob/139d5da11d791fd70b4d57142cfedc2cb8bdd0c9/package.json#L80

The bundle is generated from https://github.com/DigitallyHappy/BackStrap I will ask @tabacitu to run the update process.

Wish you the best,
Pedro

**Comment by tabacitu** [comment] 2021-04-16 07:38
Thanks for the bump @pxpm - indeed it's about time we bump the versions of the CSS and JS we use. I've done that in Backstrap (v0.3.4 is the latest now) and done so in Backpack too (https://github.com/Laravel-Backpack/CRUD/pull/3668). But take note that in fact we were _not_ using jQuery 3.5.1 - yes Backstrap was using it, but then Backpack in its `package.json` was pulling and bundling jQuery 3.6.0 - so we were using 3.6.0. Soo... no idea why the above was happening. Also, I could NOT reproduce the bug above in Chrome - summernote works as expected for me, no console error.

@nbolender I've already merged PR #3668 , will most likely tag it on Monday. Afterwards please run the code below and let us know if it fixes it for you:

```php
# update backpack to the version with the updated assets
composer update backpack/crud

# publish those updated assets (will overwrite existing ones)
php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force
```

Also, can you please check if you're not referencing the jQuery version manually? See in your `config/backpack/base.php` under `scripts` if you're loading the `bundle.js` file or individually each requirement from CDN.

I have a feeling this is going to be a weird one... 🤷‍♂️

**Comment by nbolender** [comment] 2021-04-23 23:43
@tabacitu Indeed updating the scripts did not help, but I did figure out what the issue was. It's a combination of a breaking change in jQuery, and summernote not making the required changes.

I submitted a PR to summernote: https://github.com/summernote/summernote/pull/4034

**Comment by tabacitu** [comment] 2021-09-20 07:36
Update - we've bumped the versions a long time ago, and I'm still not able to reproduce it, so... I'm going to close this. 

@nbolender if you're still getting this problem please let us know and we'll reopen.

Anybody else - if you're having this same problem please let us know and we'll reopen.

Cheers!

**Closed by tabacitu** 2021-09-20 07:36 UTC
Labels: Bug, triage
