### ISSUE TITLE
[Bug] Unable to activate the purchased product on an azure web app.

### ISSUE THREAD

**Issue by hakkahio** [Laravel-Backpack/CRUD#3344] opened 2020-11-20 17:55 UTC
# Bug report

### What I did

Purchased a license key, it isn't working.

### What I expected to happen

I expected the yellow 'ask your developer to pay' message to dissappear.

### What happened

Despite paying for the product, I am still seeing the message 'you're using unlicensed software. Please as your web developer to purchase a license code to hide this message.'. 

### What I've already tried to fix it

I have put the license key in both the ENV file, and the base.php config file.
I've ran `php artisan config:clear`
I've restarted the web app.

I've added the license code to the environment file on my production application. I've also tried testing it by adding the license code to the base.php file. The website is hosted on azure, and has an [mywebsite].azurewebsites.net domain structure. We go live very soon, and I can't get in touch with the team to get a steer on what the issue could be.  There is nothing peculiar about the hosting, it is a typical PHP environment, we have had no issues with any other packages.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP: 7.4.10
Laravel: 7.12
Backpack: 4.1.6

**Comment by tabacitu** [comment] 2020-11-20 18:11
Hi @hakkahio ,

We’ve had people reporting this kind of problem before, but it’s always _always_ been some sort of app/server configuration issue. Not a Backpack bug. I'm pretty sure this is the case too, but let's see how we can get to the bottom of it, and help you get on with your product launch.

1) Is your staging server configured exactly the same as the production server? Are they both on Azure? If not, what are the differences?

2) If you run a `dd(config(‘backpack.base.license_code’))` in production are you getting the license code? Or are you getting `false`? You should be able to do that using SSH and `php artisan tinker`... or just by adding that to a controller for a second.

3) [long shot] Can you also try clearing all other cache, not just the config?
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan view:clear

Eager to hear your answers to no 1 and no 2. Sorry you're having a frustrating launch - I know those aren't pleasant even without this kind of problems...
 
Cheers!

**Comment by hakkahio** [comment] 2020-11-20 19:20
Hi @tabacitu 

On point 1 - The staging server is a typical forge linux deployment - the azure web app technically has a windows windows back end, though I haven't faced any other issues with external dependencies before. The key difference is that a virtual path is created, that maps / to 'site\wwwroot\public'. It sounds like a dramatic difference, though honestly it 'just works' - until now. Its a production ready app - I have a license for another package, which works fine.

On point 2, I do see the license key when put into the dd();.

On point 3, unfortunately no success.

**Comment by tabacitu** [comment] 2020-11-20 20:12
@hakkahio I've emailed you with a GIF showing your license code does indeed work for me. So it's not that. I do have some other ideas though. Wrote them on email.

Let's move the conversation to email for now, and I'll come back here with the resolution for posterity.

**Comment by tabacitu** [comment] 2020-11-20 21:09
Update: just now did I notice you're using Backpack 4.1.6.

There was a known issue in the past, where the yellow notification bubble showed up, even though the license code was valid. And that only happened on 32-bit machines. We've fixed the issue in August 2020 - https://github.com/Laravel-Backpack/CRUD/pull/3101

So @hakkahio and anybody else seeing this in the future - I'm pretty sure a `composer update` will fix this for you, if you're using Backpack on a 32-bit machine. There are only upsides to doing this - we've done A LOT of bug fixing since then, with zero breaking changes.

Let me know 🤞
Cheers!

**Comment by tabacitu** [comment] 2020-11-20 21:48
Confirmed, `composer update` fixes it 😀 
Closing 🎉

**Closed by tabacitu** 2020-11-20 21:48 UTC
Labels: triage
