### ISSUE TITLE
Ajax data tables > model_function issue when the function uses an accessor / has no name

### ISSUE THREAD

**Issue by indra1** [Laravel-Backpack/CRUD#190] opened 2016-10-19 13:34 UTC
I have this crud controller where one of the columns I need uses a model function that returns a link.
This is the column from the controller:
`$this->crud->addColumn(
            [
                'type'          => 'model_function',
                'label'         => trans('drivers.name'),
                'function_name' => 'getDriverNameId',
            ]);`
and this is the function from the model:
`public function getDriverNameId()
    {
        return '<a href="'.url('drivers/'.$this->id).'">'.$this->name .'</a>';
    }`

where $this->name is actually an accessor
`public function getNameAttribute()
    {
        return trim($this->first_name). ($this->last_name ? " ".trim($this->last_name) : '');
    }`

From what I figure the issue is in the search method from the AjaxTable.php trait because there the function extracts the name from the list of columns witch is non-existent when using model_function. 
So I found out that I can fixe the issue (present in all the other crud controllers in the project) by:
**---- Method 1 ----**
changing the search method like this:
`$columns = collect($this->crud->columns)
            ->reject(function ($column, $key) {
                // the select_multiple columns are not searchable
                return isset($column['type']) && $column['type'] == 'select_multiple');
            })
            ->pluck('name')
            ->merge($this->crud->model->getKeyName())
            ->toArray();` 
now looks like this 
`$columns = collect($this->crud->columns)
            ->reject(function ($column, $key) {
                // the select_multiple columns are not searchable
                return isset($column['type']) && ($column['type'] == 'select_multiple' || $column['type']=='model_function');
            })
            ->pluck('name')
            ->merge($this->crud->model->getKeyName())
            ->toArray();`

**--- Method 2 ---**
change the way we define the column in the controller like this
`$this->crud->addColumn(
            [
                'type'          => 'model_function',
                'label'         => trans('drivers.name'),
                'function_name' => 'getDriverNameId',
                'name'          => 'first_name',
            ]);`

The only issue with the second solution it's that it will get the first_name column, but ignore the accessor and therefore I won't have the complete name of the driver. For now I am using the first solution and looking forward to any ideas that might help.

**Comment by tabacitu** [comment] 2016-10-20 13:19
So basically the issue is that CrudController::search() returns an ```\LiveControl\EloquentDataTable\DataTable``` instead of an ```Eloquent``` object.

I think migrating away from EloquentDataTable is now necessary, and rewriting this could bring two main benefits:
- model_function would work as expected;
- we could also include a 1-n and n-n relationship search; 

I think this is the future-proof solution. It is, however, time-consuming, of course...

**Comment by indra1** [comment] 2016-11-11 11:28
Also on this note: turn out you can actually order by date if the field type is text not date. There is still an  issue though. In  LiveControl\EloquentDataTable\DataTable in the addOrderBy method. When you have n-n relations the index is shifted and it actually orders by the next column.

**Comment by OwenMelbz** [comment] 2016-12-04 18:36
Hi guys, I'm just gonna close this up and add to https://github.com/Laravel-Backpack/CRUD/issues/285 to be followed up

**Closed by OwenMelbz** 2016-12-04 18:36 UTC
Labels: urgent
