### ISSUE TITLE
removeField doesnt seem to work

### ISSUE THREAD

**Issue by afdzal3** [Laravel-Backpack/CRUD#3832] opened 2021-09-14 04:09 UTC
# Bug report

### What I did
create  protected function setupShowOperation()

add this 
          $this->crud->removeField('deleted_by');
          CRUD::removeField('deleted_by');

### What I expected to happen

column deleted_by shouldn't appear in show page

### What happened

column deleted_by still appear
### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes
### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.28-1+ubuntu20.04.1+deb.sury.org+1 (cli) (built: May  1 2021 11:54:39) (
NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.28-1+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999
-2018, by Zend Technologies

### LARAVEL VERSION:
v8.60.0@44f16a31a1d4ac8a51605550d7796e2273984a48

### BACKPACK VERSION:
4.1.52@239e60df0436f8a817facce20a2dffcb2b6e7250

**Comment by tabacitu** [comment] 2021-09-14 08:16
Hey @afdzal3 ,

This might be connected to a known bug in the Show Operation. One that unfortunately we cannot fix without a breaking change, and plan to fix in Backpack 4.2. Basically the problem is that you cannot remove the columns that have been added by the ShowOperation using `setFromDb()`, because that's called _after_ your definition.

I have two possible solutions for you:

### Solution 1

There's a workaround to hiding columns in the Show operation that should work, when this doesn't. You can specify `'visibleInShow' => false` (or `->visibleInShow(false)` if you use the fluent syntax) in your `setupListOperation()` definition for that column, and it should hide it in Show.

### Solution 2

See my comment here please - https://github.com/Laravel-Backpack/CRUD/issues/3108#issuecomment-676425042 - you can disable the `setFromDb()` in the Show operation and manually specify all the columns (or call `setFromDb()` yourself but where it's ok to do so).

---

Sorry for the bad experience, I know this bug sucks, but unfortunately we can't fix it until we launch a new version. Otherwise we'd be breaking everybody's admin panels, and that would suck even more...

I'm going to close this, as I'm pretty sure https://github.com/Laravel-Backpack/CRUD/pull/3132 fixes it, but if I'm mistaken and the solutions above don't work for you, or the PR doesn't fix the problem or something, please let us know and we'll reopen the issue no problem.

Cheers!

Other notes:
- this issue seems to be the same as https://github.com/Laravel-Backpack/CRUD/issues/3108
- the PR that fixes this known bug is https://github.com/Laravel-Backpack/CRUD/pull/3132
- there's [a PR here](https://github.com/Laravel-Backpack/CRUD/pull/3624) to also be able to give a closure to `visibleInShow()` - will also be merged in 4.2; but for now it only supports `true`/`false`;

**Closed by tabacitu** 2021-09-14 08:16 UTC
Labels: Bug, triage

**Comment by tabacitu** [comment] 2021-09-14 11:55
Oh yeah... also... that... 😅

![stupid_me](https://user-images.githubusercontent.com/1032474/133253115-1e8bf769-2433-44d4-8182-09a5a5796bfe.gif)
