### ISSUE TITLE
[Bug] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my_db.password_resets' doesn't exist (Connection: mysql, SQL: select * from `password_resets` where `email` = myemail limit 1)

### ISSUE THREAD

**Issue by TheClaud99** [Laravel-Backpack/CRUD#4979] opened 2023-03-15 11:47 UTC
# Bug report

### What I did

I tried to use the forgot password on the admin panel login and i got this error becouse the password_resets table doesn't exists anymore on laravel 10

### What I expected to happen

Send reset password email

### What happened

Got this error

![image](https://user-images.githubusercontent.com/39127925/225300353-be9f06fa-23b0-4946-9dcf-79c492c78d79.png)

### What I've already tried to fix it

I think the bug is in BackpackServiceProvider.php in this line with wrong table name. 'password_resets' shuold be changed in 'password_reset_tokens'

````
```
        app()->config['auth.passwords'] = app()->config['auth.passwords'] +
        [
            'backpack' => [
                'provider'  => 'backpack',
                'table'     => 'password_resets',
                'expire'    => config('backpack.base.password_recovery_token_expiration', 60),
                'throttle'  => config('backpack.base.password_recovery_throttle_notifications'),
            ],
        ];

```
````

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

````
```
### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v10.3.3@90f24d9e2860ecf6b5492e966956270ceb98c03d

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.5.2
backpack/generators: 3.3.16

```
````

**Comment by promatik** [comment] 2023-03-16 16:20
Hi @TheClaud99, I can confirm this is an issue in new Laravel 10 installations 👌

I'm working on a fix for this one 🙌

**Comment by promatik** [comment] 2023-03-16 16:41
@TheClaud99 thank you for your report, we have a fix now 🎉

I've just opened a new PR to fix this issue; https://github.com/Laravel-Backpack/CRUD/pull/4986

We may move the conversation about this issue to the PR thread, if you test it please let us know if it fixes your issue 🙌

**Closed by promatik** 2023-03-16 16:41 UTC
Labels: Bug

**Comment by cubilog** [comment] 2023-05-23 16:03
This bug has been "closed" in March, since then, you've published seven new Backpack 5.x versions, yet the password reset feature on Laravel 10 is still unsupported.
The related pull request merge was blocked and still waiting for a fix and merge.

This bug was marked as DONE on the project board too. Please move it back to the IN PROGRESS state.
https://github.com/orgs/Laravel-Backpack/projects/13/views/13?filterQuery=%234979

**Comment by pxpm** [comment] 2023-05-23 17:40
> This bug has been "closed" in March, since then, you've published seven new Backpack 5.x versions, yet the password reset feature on Laravel 10 is still unsupported. The related pull request merge was blocked and still waiting for a fix and merge.
> 
> This bug was marked as DONE on the project board too. Please move it back to the IN PROGRESS state. https://github.com/orgs/Laravel-Backpack/projects/13/views/13?filterQuery=%234979
> 
> (Update: I've checked and I see that the pull request itself is in the IN PROGRESS tab.)

Indeed @cubilog it's in progress and we are discussing a possible breaking change and or a documentation solution to fix the issue. 

The current proposed solution is a workaround only. It introduces other possible problems and I am not totally comfortable with it. 

I am on support this week, I am going to have another look at it. 

Thanks for the heads up. 🙏 

Cheers

**Comment by hsh555** [comment] 2023-09-09 06:32
rename 'password_resets' to 'password_reset_tokens'
