### ISSUE TITLE
[Bug] Field with name "Deleted" gets entity "Deleted" an throws an error

### ISSUE THREAD

**Issue by WrdVdb** [Laravel-Backpack/CRUD#3442] opened 2021-01-06 12:11 UTC
# Bug report

### What I did

We have a field with the name "Deleted" in our database. It's a legacy soft-delete column, type bit.
I want to show this boolean as a checkbox in de crud. This throws this error:

`Too few arguments to function Illuminate\Database\Eloquent\Model::deleted(), 0 passed in /vendor/backpack/crud/src/app/Library/CrudPanel/CrudPanel.php on line 355 and exactly 1 expected
`

Because of the name "Deleted" this functions is called:

`
public static function deleted($callback)
    {
        static::registerModelEvent('deleted', $callback);
    }`

Crud file:

`$this->crud->addField([
            'name' => 'Deleted',
            'type' => 'checkbox',
            'label' => 'Deleted',
        ]);`

Also showing the column gives the same error:

Before version 4.1 (or the one before, not sure) this was not a problem.

### What I expected to happen

Show the checkbox

### What I've already tried to fix it

`'entity' => false`

Gives an other error in update.php trait.

### PHP VERSION:
PHP 7.4.6 (cli) (built: May 14 2020 10:02:31) ( NTS )

### LARAVEL VERSION:
v6.20.8@3d95575f4688e53e46d8d9a10f748a87698709f4

### BACKPACK VERSION:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

**Comment by pxpm** [comment] 2021-01-06 13:06
Hello @WrdVdb thanks for the report. 

Indeed that was a behavioral change in 4.1, we inteend to perfect it to the most when we upgrade our dependencies to php 8.0 and work with return types, for the moment we have the `entity => false` that should allow developers to stop this functionality in edge cases like yours. 

I'v submited PR #3445 to address this issue in columns (we were only checking if model has a function with that name). I was not able to reproduce your issue in fields (where we already account for `entity => false`)

In the meanwhile you could add an accessor/mutator to your column and use another name with backpack, or you could pull the code from that PR, if it solves the problem for you, could you please write it down in the PR #3445 thread ?


Let me know,
Pedro

**Comment by promatik** [comment] 2021-01-07 23:58
@WrdVdb thank you for your report 👌
I've just tested @pxpm PR and it solves this issue, I'll close this one for now, let's move the conversation there.

**Closed by promatik** 2021-01-07 23:58 UTC
Labels: Bug, triage
