### ISSUE TITLE
Elfinder route issue

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/CRUD#233] opened 2016-11-14 10:24 UTC
I just made a fresh install to test some ideas and i discovered that there is a problem with elfinder routes: they all miss the "/admin" prefix. Did you change that? Or it needs a fix?

**Comment by unbolt** [comment] 2016-11-16 15:11
Having the same issue, there appears to be a config file generated for elfinder, and in it this:

`    'route' => [
        'prefix'     => config('backpack.base.route_prefix').'/elfinder',
        'middleware' => ['web', 'auth'], //Set to null to disable middleware filter
    ],`

But it doesn't seem to do anything with the config, or the name isn't right. Going to continue installing other modules and see if they have the same issue so I can work out what the config should be.

Work around for now would be to hardcode in admin before it.

`
'prefix'     => 'admin/elfinder',
`

**Comment by AurelDragut** [comment] 2016-11-16 15:29
Modify the route section in the config/elfinder.php file like this:

``` 'route' => [
        'prefix'     => config('backpack.base.route_prefix','/admin').'/elfinder',
        'middleware' => ['web', 'auth'], //Set to null to disable middleware filter
    ], ```

**Comment by unbolt** [comment] 2016-11-16 15:38
That just means if the config entry doesn't exist then it falls back to /admin, but the config entry does exist in config/backpack/base.php - the issue is why it isn't being picked up in the elfinder config?

To be accessible it would need to be registered in the ConfigServiceProvider somewhere? Don't know enough about how configs are loaded in Laravel 5 to know if that's been done and just doesn't matter / can't cross-config, or if it's not being done. Presume it must be done as you can access the config variables in blade templates.

**Comment by AurelDragut** [comment] 2016-11-16 15:43
Yes, that is right. They know about it and they will fix it. Till then you can do the same as i did.

**Comment by tabacitu** [comment] 2016-11-17 06:11
Hi guys, I can't replicate the problem. Tried it on a bunch of projects and it worked for me. [Also works out of the box if I change the admin prefix from 'admin' to 'administration'](https://infinit.io/_/3c3rzKF).

@AurelDragut , if you didn't get this in your config/elfinder.php file when you published it 
```php
    'route' => [
        'prefix'     => config('backpack.base.route_prefix').'/elfinder',
        'middleware' => ['web', 'auth'], //Set to null to disable middleware filter
    ],
```
it probably means:
A) you published the stock elfinder file, instead of the one in Backpack\Base;
B) you were using an old version of Backpack\Base;


@unbolt , might be a service provider order issue? In you ```config/app.php```, the Backpack service providers should be loaded after the application service providers. Here's mine:

```php
    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */

        //

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,


        /*
         * Backpack Service Providers...
         */
        Backpack\Base\BaseServiceProvider::class,
        Backpack\CRUD\CrudServiceProvider::class,
        Backpack\NewsCRUD\NewsCRUDServiceProvider::class,
        Backpack\LangFileManager\LangFileManagerServiceProvider::class,
        Spatie\Backup\BackupServiceProvider::class,
        Backpack\BackupManager\BackupManagerServiceProvider::class,
        Backpack\LogManager\LogManagerServiceProvider::class,
        Backpack\Settings\SettingsServiceProvider::class,
        Backpack\PageManager\PageManagerServiceProvider::class,
        Backpack\PermissionManager\PermissionManagerServiceProvider::class,
        Backpack\MenuCRUD\MenuCRUDServiceProvider::class,
        Backpack\LangFileManager\LangFileManagerServiceProvider::class,

        Barryvdh\Debugbar\ServiceProvider::class,
    ],
``` 
Notice the first one is Base, then CRUD.

Does this fix it for you?

Cheers!

**Comment by AurelDragut** [comment] 2016-11-17 08:11
@tabacitu, 

i got that in the config file, but i had to add the "backup" value (you know, the one we setup in case we don't have a config/env value at that moment) in order to make it work, just like i wrote to @unbolt. It might be just a matter of "/" considering i added "/admin" and in the config file we have "admin".

**Comment by jaytheking** [comment] 2016-11-26 02:05
Has this issue been solved? i seem to be getting the same problem of not being able to access the elfinder from admin/elfinder but i can access it from /elfinder. I've done the installation process twice now and still same problem. adding 'admin' to the prefix in the elfinder config file seems to fix the problem but will only works for the default value in base.php.

**Comment by AurelDragut** [comment] 2016-11-26 08:11
Did you try this? 
https://github.com/Laravel-Backpack/CRUD/issues/233#issuecomment-260975217

**Comment by OwenMelbz** [comment] 2016-12-04 18:39
Hopefuly you guys have got this sorted now, I'm just closing it to keep it tidy, feel free to carry on if need be! :)

**Closed by OwenMelbz** 2016-12-04 18:39 UTC
