### ISSUE TITLE
Route Model Binding cause error

### ISSUE THREAD

**Issue by mgralikowski** [Laravel-Backpack/CRUD#1166] opened 2017-12-25 17:19 UTC
For example we use Model Binding for {user}
https://laravel.com/docs/5.5/routing#route-model-binding
then in route user/1/edit we have User model already injected by binding.
This cause an error:

> Method withFakes does not exist.

The problem is here:

`        $this->data['entry'] = $this->crud->getEntry($id);`

because in $id we have object, not numeric id. My fast fix proposition:

`$this->data['entry'] = is_object($id) ? $id : $this->crud->getEntry($id);`

**Comment by OliverZiegler** [comment] 2018-01-11 19:31
Not quite sure if this really is a bug @lloy0076 🤔 

Current backpack behaviour addresses `$id` and also the `CRUD::resource` route generation uses `$id` and no model binding.

Also as `$this->crud->getEntry($id)` is implemented like this:

```php
    public function getEntry($id)
    {
        if (! $this->entry) {
            $this->entry = $this->model->findOrFail($id);
            $this->entry = $this->entry->withFakes();
        }

        return $this->entry;
    }
```

you could mimic the inteded behaviour by just overriding the functions and set the bound entry.

Example for `edit` in a `CrudController` subclass

```php
function edit($id)
{
     // with model binding $id is already a model instance
    $instance = $id;

    $this->crud->entry = $instance;
    
    // as they will otherwise not be loaded call withFakes()
    $instance->withFakes();
    
    return parent::edit($instance->id);
}
```

another way would just be (but this would load the instance again)

```php
function edit($id)
{
     // with model binding $id is already a model instance
    $instance = $id;

    return parent::edit($instance->id);
}
```

**Comment by mgralikowski** [comment] 2018-01-11 23:07
> route generation uses $id and no model binding.
Binding is totally global - once set in web.php, it works everywhere also in an admin.php, separate routes (strange for me but it is how Laravel works).

I will try your proposed code soon.

**Comment by mgralikowski** [comment] 2018-01-23 10:39
Solutions confirmed (i have choose last one as the most minimalistic);) thx

**Comment by OliverZiegler** [comment] 2018-01-23 17:37
As this seems to be no bug and issuer has confirmed he resolved, I‘ll close this one.

**Closed by OliverZiegler** 2018-01-23 17:37 UTC
Labels: Ask-It-On-Stack-Overflow, bug
