### ISSUE TITLE
[Bug] hide actions buttons for specific row in backpack list operations

### ISSUE THREAD

**Issue by deepaksoftonicsolution** [Laravel-Backpack/CRUD#3721] opened 2021-05-20 07:50 UTC
# Bug report

### What I did
I have used the role permission of the backpack.
In which there is a user's module in which all the admin users are appearing. 
I am using actions here to edit and delete the user.
??
### What I expected to happen
I want to hide the actions button for that profile admin that means admin can't delete their own profile
??

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:4.1``` the output is:

**Comment by pxpm** [comment] 2021-06-07 13:46
Hello @deepaksoftonicsolution thanks for raising this subject.

I think this is an excelent `Feature` not a bug per se. 

You can already achieve that using your own buttons:

- create a model function let's say `function availableActionButtons() {}` that return your `html buttons`.
- then in crud add a button from model function `availableActionButtons` that returns the buttons you want based on your validations `backpack_user()->hasRole('admin')` etc. https://backpackforlaravel.com/docs/4.1/crud-buttons#buttons-api-1

 Tip: If you need JS in those buttons, use `Widgets` to pass JS into crud to use in the buttons. https://backpackforlaravel.com/docs/4.1/base-widgets#documentation-box

I 100% agree that it's a little messy, both the `callback for button display` and the insertion of JS in page using widgets, but I am sure both are going to be worked out in next version.  Still, they work for now as I explained.

I am going to close this one as there is already some ideas open that will lead to fix this like: https://github.com/Laravel-Backpack/ideas/issues/102

Best,
Pedro

**Closed by pxpm** 2021-06-07 13:46 UTC
Labels: triage

**Comment by tabacitu** [comment] 2021-06-11 08:15
@deepaksoftonicsolution hiding the button is nice, but personally what I would focus on is _not letting him do it_. I would first of all overwrite the `delete()` method in DeleteOperation (by adding it to my UserCrudController) so that the admin cannot do that. Or better yet, I'd do that in the User model using Eloquent events, to be super-sure they can't do that.

Then yeah I'd probably hide the `delete` button, but lazy as I am, I would probably just:
- remove the standard `delete` button
- add a custom `delete_user` button that not only check if `$user->hasAccess('delete')` but also that the deleted user is not the same as the logged in user; so something like this:

```diff
-@if ($crud->hasAccess('delete'))
+@if ($crud->hasAccess('delete') && backpack_user()->getKey() != $entry->getKey())
	<a href="javascript:void(0)" onclick="deleteEntry(this)" data-route="{{ url($crud->route.'/'.$entry->getKey()) }}" class="btn btn-sm btn-link" data-button-type="delete"><i class="la la-trash"></i> {{ trans('backpack::crud.delete') }}</a>
@endif

{{-- Button Javascript --}}
{{-- - used right away in AJAX operations (ex: List) --}}
{{-- - pushed to the end of the page, after jQuery is loaded, for non-AJAX operations (ex: Show) --}}
@push('after_scripts') @if (request()->ajax()) @endpush @endif
<script>

	if (typeof deleteEntry != 'function') {
	  $("[data-button-type=delete]").unbind('click');

	  function deleteEntry(button) {
		// ask for confirmation before deleting an item
		// e.preventDefault();
		var route = $(button).attr('data-route');

		swal({
		  title: "{!! trans('backpack::base.warning') !!}",
		  text: "{!! trans('backpack::crud.delete_confirm') !!}",
		  icon: "warning",
		  buttons: ["{!! trans('backpack::crud.cancel') !!}", "{!! trans('backpack::crud.delete') !!}"],
		  dangerMode: true,
		}).then((value) => {
			if (value) {
				$.ajax({
			      url: route,
			      type: 'DELETE',
			      success: function(result) {
			          if (result == 1) {
						  // Redraw the table
						  if (typeof crud != 'undefined' && typeof crud.table != 'undefined') {
							  // Move to previous page in case of deleting the only item in table
							  if(crud.table.rows().count() === 1) {
							    crud.table.page("previous");
							  }

							  crud.table.draw(false);
						  }

			          	  // Show a success notification bubble
			              new Noty({
		                    type: "success",
		                    text: "{!! '<strong>'.trans('backpack::crud.delete_confirmation_title').'</strong><br>'.trans('backpack::crud.delete_confirmation_message') !!}"
		                  }).show();

			              // Hide the modal, if any
			              $('.modal').modal('hide');
			          } else {
			              // if the result is an array, it means 
			              // we have notification bubbles to show
			          	  if (result instanceof Object) {
			          	  	// trigger one or more bubble notifications 
			          	  	Object.entries(result).forEach(function(entry, index) {
			          	  	  var type = entry[0];
			          	  	  entry[1].forEach(function(message, i) {
					          	  new Noty({
				                    type: type,
				                    text: message
				                  }).show();
			          	  	  });
			          	  	});
			          	  } else {// Show an error alert
				              swal({
				              	title: "{!! trans('backpack::crud.delete_confirmation_not_title') !!}",
	                            text: "{!! trans('backpack::crud.delete_confirmation_not_message') !!}",
				              	icon: "error",
				              	timer: 4000,
				              	buttons: false,
				              });
			          	  }			          	  
			          }
			      },
			      error: function(result) {
			          // Show an alert with the result
			          swal({
		              	title: "{!! trans('backpack::crud.delete_confirmation_not_title') !!}",
                        text: "{!! trans('backpack::crud.delete_confirmation_not_message') !!}",
		              	icon: "error",
		              	timer: 4000,
		              	buttons: false,
		              });
			      }
			  });
			}
		});

      }
	}

	// make it so that the function above is run after each DataTable draw event
	// crud.addFunctionToDataTablesDrawEventQueue('deleteEntry');
</script>
@if (!request()->ajax()) @endpush @endif
```

Hope it helps!
