### ISSUE TITLE
[Bug] HasMany relation key infering is broken, can't use HasMany with models with different key names

### ISSUE THREAD

**Issue by singeryo** [Laravel-Backpack/CRUD#4384] opened 2022-05-18 16:43 UTC
# Bug report

### What I did
For a more detailed explanation I made this Stackoverflow post: https://stackoverflow.com/questions/72272377/column-not-found-1054-unknown-column-when-submitting-form-with-subfield-relatio

To be short, my issue happens when I attempt to implement this setup: https://backpackforlaravel.com/docs/5.x/crud-fields#manage-related-entries-in-the-same-form-create-update-delete with 2 models that override their primary key attribute (as their primary key is not "id").
Now unless there is something I REALLY don't understand, i'm pretty sure that my relations are correctly defined.

I managed to reproduce the issue with the Backpack Demo project. Here is how you can you that:
- Install demo project following instructions
- Rename monsters primary key in table to id_monster and stories primary key to id_story
- Add the $primaryKey overrides on corresponding models like so:

     protected $primaryKey = 'id_monster'; // In Monster.php
     protected $primaryKey = 'id_story'; // In Story.php

- Add correct "foreignKey" parameters to relation method like so:

      // In Story.php
      public function monsters()
      {
         return $this->hasMany(\App\Models\Monster::class, 'story_id');
      }

      // In Monster.php
      public function story()
      {
         return $this->belongsTo(\App\Models\Story::class, 'story_id');
      }

- Now add a story with a monster through the Crud panel and you should reproduce the error.

### What I expected to happen

The form would submit without errors and my relations would be correctly inserted in database.

### What happened

I get this error: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_story' in 'where clause'`. 

### What I've already tried to fix it

I triple checked my relations and read the corresponding Laravel documentation to make sure i'm not missing something. I followed the stack trace which lead me to this file: `vendor\backpack\crud\src\app\Library\CrudPanel\Traits\Create.php:310` I ticked on this step because i don't quite understand why the relations `localKey` is used for this `updateOrCreate` call, and i'm thinking the issue i'm having could come from this (although I tried playing around with it with no real success).

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.27 (cli) (built: Dec 14 2021 19:52:13) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group                                               
Zend Engine v3.4.0, Copyright (c) Zend Technologies                       
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans        

### LARAVEL VERSION:                            
v9.10.1@93414b1c7c0a56081d96c060bb850ac192d3d323

### BACKPACK VERSION:
5.0.14@1e355c4c046a34423a1a3e3150120245a4bfd8e9

**Comment by pxpm** [comment] 2022-05-18 17:48
Hello @singeryo 

Thanks for the report. 

Around the lines you mentioned (:310 in Create.php), can you `dd($relation)` and post the results? 

Cheers

**Comment by singeryo** [comment] 2022-05-18 18:02
Hi !

Sure, here it is

^ Illuminate\Database\Eloquent\Relations\HasMany {#1798 ▼
  #query: Illuminate\Database\Eloquent\Builder {#1796 ▶}
  #parent: App\Models\Story {#1792 ▶}
  #related: App\Models\Monster {[#1793 ▶](http://backpack-demo.test/admin/story#sf-dump-386756513-ref21793)}
  #foreignKey: "monsters.story_id"
  #localKey: "id_story"
}

Let me know if you would like me to unwrap any of those

**Comment by pxpm** [comment] 2022-05-18 20:23
So ... localKey is correctly set, but somehow it's querying `story_`+localKey that ends up as `story_id_story`, it should be querying only `id_story`, so probably the problem is not around those lines. 

Can you provide me the full error stacktrace ? 

Cheers

**Comment by singeryo** [comment] 2022-05-19 07:11
Hey @pxpm , sorry there has been a copy/paste mistake as I was trying to play around with the relationships while testing this error, the error that i get initially and that i was supposed to paste here is this one :

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_story' in 'where clause'`

Sorry again, i'll edit the poste

**Comment by singeryo** [comment] 2022-05-19 07:26
For the stack trace I guess I can copy it here ?
Just to be clear, i've mentioned the steps above to reproduce the error on the backpack demo project so anyone can reprduce it

    Illuminate \ Database \ Connection : 742
    runQueryCallback
    Illuminate \ Database \ Connection : 702
    run
    Illuminate \ Database \ Connection : 404
    select
    Illuminate \ Database \ Query \ Builder : 2607
    runSelect
    Illuminate \ Database \ Query \ Builder : 2595
    Illuminate\Database\Query\{closure}
    Illuminate \ Database \ Query \ Builder : 3129
    onceWithColumns
    Illuminate \ Database \ Query \ Builder : 2596
    get
    Illuminate \ Database \ Eloquent \ Builder : 698
    getModels
    Illuminate \ Database \ Eloquent \ Builder : 682
    get
    Illuminate \ Database \ Eloquent \ Builder : 296
    first
    Illuminate \ Database \ Eloquent \ Relations \ Relation : 23
    forwardCallTo
    Illuminate \ Database \ Eloquent \ Relations \ Relation : 52
    forwardDecoratedCallTo
    Illuminate \ Database \ Eloquent \ Relations \ Relation : 491
    __call
    Illuminate \ Database \ Eloquent \ Relations \ HasOneOrMany : 216
    firstOrNew
    Illuminate \ Database \ Eloquent \ Relations \ HasOneOrMany : 250
    updateOrCreate
    Backpack \ CRUD \ app \ Library \ CrudPanel \ CrudPanel : 310
    createManyEntries
    Backpack \ CRUD \ app \ Library \ CrudPanel \ CrudPanel : 117
    createRelationsForItem
    Backpack \ CRUD \ app \ Library \ CrudPanel \ CrudPanel : 25
    create
    App \ Http \ Controllers \ Admin \ StoryCrudController : 82
    store
    Illuminate \ Routing \ Controller : 54
    callAction
    Illuminate \ Routing \ ControllerDispatcher : 45
    dispatch
    Illuminate \ Routing \ Route : 261
    runController
    Illuminate \ Routing \ Route : 204
    run
    Illuminate \ Routing \ Router : 725
    Illuminate\Routing\{closure}
    Illuminate \ Pipeline \ Pipeline : 141
    Illuminate\Pipeline\{closure}
    Backpack \ CRUD \ app \ Http \ Controllers \ CrudController : 44
    Backpack\CRUD\app\Http\Controllers\{closure}
    Illuminate \ Pipeline \ Pipeline : 162
    Illuminate\Pipeline\{closure}
    Illuminate \ Foundation \ Http \ Middleware \ TransformsRequest : 21
    handle
    Illuminate \ Foundation \ Http \ Middleware \ ConvertEmptyStringsToNull : 31
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    App \ Http \ Middleware \ CheckIfAdmin : 63
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ Foundation \ Http \ Middleware \ VerifyCsrfToken : 78
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ View \ Middleware \ ShareErrorsFromSession : 49
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ Session \ Middleware \ StartSession : 121
    handleStatefulRequest
    Illuminate \ Session \ Middleware \ StartSession : 64
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ Cookie \ Middleware \ AddQueuedCookiesToResponse : 37
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ Cookie \ Middleware \ EncryptCookies : 67
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ Pipeline \ Pipeline : 116
    then
    Illuminate \ Routing \ Router : 726
    runRouteWithinStack
    Illuminate \ Routing \ Router : 703
    runRoute
    Illuminate \ Routing \ Router : 667
    dispatchToRoute
    Illuminate \ Routing \ Router : 656
    dispatch
    Illuminate \ Foundation \ Http \ Kernel : 167
    Illuminate\Foundation\Http\{closure}
    Illuminate \ Pipeline \ Pipeline : 141
    Illuminate\Pipeline\{closure}
    Barryvdh \ Debugbar \ Middleware \ InjectDebugbar : 67
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ Foundation \ Http \ Middleware \ TransformsRequest : 21
    handle
    Illuminate \ Foundation \ Http \ Middleware \ ConvertEmptyStringsToNull : 31
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ Foundation \ Http \ Middleware \ PreventRequestsDuringMaintenance : 86
    handle
    Illuminate \ Pipeline \ Pipeline : 180
    Illuminate\Pipeline\{closure}
    Illuminate \ Pipeline \ Pipeline : 116
    then
    Illuminate \ Foundation \ Http \ Kernel : 142
    sendRequestThroughRouter
    Illuminate \ Foundation \ Http \ Kernel : 111
    handle
    C:\laragon\www\backpack-demo\public\index.php : 52
    [top]

**Comment by singeryo** [comment] 2022-05-24 15:45
Hi,
Is it possible that someone confirms this is in fact a bug ?
I guess there is always a workaround which is using a repeatable field and overriding the "on save" function, like in Backpack 4. But it would sure be nice to not have to do that !

**Comment by pxpm** [comment] 2022-05-26 15:12
Hello @singeryo 
I've been debugging this in the last few days, I needed to setup a testable scenario first so I could be sure if it was indeed a bug, or something you were missing in your definition.
I **can confirm we have an issue** on how we get the related key in `HasMany` relation that would prevent people from using the functionality if they used different names for the keys. 

I've submitted https://github.com/Laravel-Backpack/CRUD/pull/4402 to address this issue, I've tested your specific scenario and everything is working fine after the PR. 

It should be merged and tagged probably in the next monday. 

Thanks again for the report and sticking with us finding the solution. 

Wish you the best,
Pedro

**Comment by tabacitu** [comment] 2022-05-30 14:58
Merged! Will be available later today after I tag a new version. Thanks guys!

**Closed** 2022-05-30 14:57 UTC
Labels: Bug
