### ISSUE TITLE
Translatable fake field not working in CRUD 3.4.23

### ISSUE THREAD

**Issue by axelzuzek** [Laravel-Backpack/CRUD#1546] opened 2018-07-16 10:25 UTC
# Bug report
Translateable fake fields store values in database but don't display the values in crud/edit after updating form backpack/crud (3.4.5 => 3.4.23)

### What I did:
Migration:
```
  Schema::create('tests', function (Blueprint $table) {
            $table->increments('id');
            $table->text('i18ndatafake')->nullable();
        });
```

Created new Testmodel/CRUD:
```
protected $fillable = ['i18ndatafake'];
protected $translatable = [ 'i18ndatafake' ];
protected $fakeColumns = ['i18ndatafake'];
protected $casts = ['i18ndatafake' => 'array'];

```
Crud Controller:
```
        $this->crud->addField([
            'name' => 'title',
            'label' => 'title',
            'fake' => true,
            'store_in' => 'i18ndatafake'
        ]);

        $this->crud->addField( [
            'name' => 'description',
            'label' => 'description',
            'fake' => true,
            'store_in' => 'i18ndatafake',
        ]);
```
Database after insert: 
 i18ndatafake {"de":{"title":"title german","description":"description german"},"en":{"title":"title englisch","description":"description english"}} 

### Problem ###
Crud/Edit Fields are empty after saving. 

This worked fine in CRUD 3.4.5

### Backpack, Laravel, PHP, DB version:
Laravel: 5.6.27
PHP: 7.1.11
MySQL: 5.7.11
backpack/crud: 3.4.23

**Comment by tswonke** [comment] 2018-07-16 10:34
Does it work for you if you remove `$casts`?

**Comment by axelzuzek** [comment] 2018-07-16 10:43
No there is no difference.

**Comment by axelzuzek** [comment] 2018-07-16 11:01
No there is no difference.

**Comment by OliverZiegler** [comment] 2018-07-16 11:18
@axelzuzek Do you use the correct traits in your model (the ones provided by backpack)?

Could you provide a var_dump of your model data before your CrudControllers edit function returns?

Should look something like:

```php
public function edit($id) {
    $response = parent::edit($id);
    dd(var_dump($this->crud->entry);
}
```

**Comment by OliverZiegler** [comment] 2018-07-16 11:48
Ok so this seems to be an issue. Need to dive into and check if I find something.

Just for me, could you print the following output (in the edit function) so I can later check my own dummy application for reference:

* `$this->crud->entry-> i18ndatafake`
* `$this->crud->entry->getTranslation('i18ndatafake', 'de')`
* `$this->crud->entry->getTranslation('i18ndatafake', 'en')`

And could you revert [this](https://github.com/Laravel-Backpack/CRUD/commit/f906a6baa040a425ceff06a6341a83cb42409e5d#diff-e105427d8e6d81cc9511bcf4ebf81e8d) change locally and see if it works without?

**Comment by tswonke** [comment] 2018-07-16 11:51
reverting your change doesn't seem to have an effect, @OliverZiegler

**Comment by OliverZiegler** [comment] 2018-07-16 11:54
ok so... then I need to dive in to check what exactly is happening. 
Give me some time people 😊 
will start digging 👷⚒

**Comment by OliverZiegler** [comment] 2018-07-16 12:19
So we identified the issue (introduced in 3.4.23) so in the meantime please "downgrade" to 3.4.22 so this will work.

Issue introduced with #1488 in PR #1533

**Comment by axelzuzek** [comment] 2018-07-16 12:37
thx a lot!

**Comment by tabacitu** [comment] 2018-07-16 16:01
@axelzuzek , thanks for reporting this.
@OliverZiegler and @tswonke , thank you for being first-responders. Let's put this fire out :-)

@axelzuzek - we have a solution you can implement _right now_, so you don't downgrade to 3.4.22. Please add the code below on you model. **Can you please confirm it fixes it?** It did in my tests. 

```php
/**
  * Add fake fields as regular attributes, even though they are stored as JSON.
  *
  * @param array $columns - the database columns that contain the JSONs
  */
public function addFakes($columns = ['extras'])
    {
        foreach ($columns as $key => $column) {
            if (! isset($this->attributes[$column])) {
                continue;
            }

            if ($this->translationEnabled() && $this->isTranslatableAttribute($column)) {
                $column_contents = $this->{$column};
            } else {
                $column_contents = $this->attributes[$column];
            }

            if (! is_object($column_contents)) {
                $column_contents = json_decode($column_contents);
            }

            if ((is_array($column_contents) || is_object($column_contents) || $column_contents instanceof Traversable)) {
                foreach ($column_contents as $fake_field_name => $fake_field_value) {
                    $this->setAttribute($fake_field_name, $fake_field_value);
                }
            }
        }
    }
```

If this fixes it for you too, I'll merge PR #1549 to fix it for everyone. 

Cheers!

**Comment by OliverZiegler** [comment] 2018-07-16 16:05
@tabacitu see my PR #1548 your solution did lead to another issue in our tests. 
@tswonke can you remember which situation will fail with the provided solution?

**Comment by OliverZiegler** [comment] 2018-07-16 16:54
@axelzuzek please check out #1548.

If this closes your issue (and I'm sure it will) you may close this issue as it can be seen **fixed** 😉

**Comment by tabacitu** [comment] 2018-07-16 17:17
:-)) Confirmed! Thank you @OliverZiegler , merged https://github.com/Laravel-Backpack/CRUD/pull/1548. 

So @axelzuzek a ```composer update``` should do it for you. You'll get ```3.4.25``` where this is fixed. You can thank @OliverZiegler for his fix - much more elegant than mine. Please ignore my addFakes() suggestion above - you no longer need to test that.

Cheers!

**Closed by tabacitu** 2018-07-16 17:17 UTC

**Comment by axelzuzek** [comment] 2018-07-16 20:10
3.4.25 works for me too, thank you guys!

**Comment by tswonke** [comment] 2018-07-17 08:45
@OliverZiegler do you mean what we tested yesterday during our phone session? I suppose your question was answered by yourself or is it still open? 😅

**Comment by OliverZiegler** [comment] 2018-07-17 08:50
@tswonke as @tabacitu merged our solution (which now is also unit tested) the question is obsolete.

just wanted to tell why @tabacitu s code won't work... but can't remember what exact situation would be a problem... 🙈 too much try and error and situations to test... 😅

**Comment by tswonke** [comment] 2018-07-17 08:53
😆

**Comment by diakosavvasn** [comment] 2019-12-07 19:30
Hello guys, 

I think there is bug report also backpack/crud 4.0. I'm not so sure but translatable fake fields store values in database but don't display the values in crud/edit. Using

What I did:

**Migration:**

```
 Schema::create('pages', function (Blueprint $table) {
            $table->increments('id');
            $table->string('template');
            $table->string('name');
            $table->text('title');
            $table->string('slug');
            $table->text('content')->nullable();
            $table->text('extras')->nullable();
            $table->text('extras_translatable')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
```

**in Models/Pages.php**

```
    protected $fillable = ['template', 'name', 'title', 'slug', 'content', 'extras', 'extras_translatable'];
    protected $fakeColumns = ['extras', 'extras_translatable'];	
    protected $translatable = ['title', 'content','extras_translatable'];
    protected $casts = [
        'extras' => 'array', 
        'extras_translatable' => 'array'
    ];
```

**in PageTemplate.php :**

```
$this->crud->addField([
        'name' => 'main_title',
        'label' => 'Main Title',
        'type' => 'text',
        'store_in' => 'extras_translatable',
        'fake' => true,
]);
```

**Database after insert:**

`extras_translatable {"el":{"main_title":"Η εταιρία μας"},"en":{"main_title":"Our Company"}}`

**Problem**

`extras_translatable` fields are empty after saving

**Backpack, Laravel, PHP Version:**

Laravel: 6.6.0
PHP: 7.2
backpack/crud: 4.0.23
