### ISSUE TITLE
[Bug] On Relationship Field, the attribute 'attribute' doesn't work in Show View

### ISSUE THREAD

**Issue by MDW-Chris** [Laravel-Backpack/CRUD#4545] opened 2022-07-22 08:06 UTC
This is a regression between a previous version of Backpack and version 5.2.1

With an identical configuration, the relationship type field has a different behavior between the ListView and the ShowView

In the ListView, the attribute works and displays my user's 'name'
In the ShowView, the attribute does not work and displays the identifier and/or the JSON object of my user

**Comment by pxpm** [comment] 2022-07-22 14:37
Hello @MDW-Chris thanks for the report.

List and Show uses `Columns`, not `Fields`, it might be a typo no worries.

Can you provide me more detailed information ? Your column definition, your relation definition ?

Cheers

**Comment by MDW-Chris** [comment] 2022-07-26 09:35
Hello, that's right, it's Columns

```
class Project extends Model
{
   public function lead_user()
   {
      return $this->belongsTo(User::class);
   }
}
```

```
class ProjectCrudController extends CrudController
{
   protected function setupListOperation()
   {
      /* 'lead_user_id' display now the ID -- 'lead_user' display the JSON object of the relation */
      CRUD::addColumn([
         'name'      => 'lead_user_id', 
         'type'      => 'relationship',
         'label'     => 'Leader',
         'attribute' => 'name',
      ]);
   }
}
```


In the ListView, the attribute works and displays my user's 'name'
In the ShowView, the attribute does not work and displays the identifier and/or the JSON object of my user

**Comment by pxpm** [comment] 2022-07-26 09:48
Thanks for clarification 🙏 

I will make my tests and come back to you with my findings.

Cheers

**Comment by pxpm** [comment] 2022-07-26 10:10
Hello @MDW-Chris 

I am sorry, but still unable to reproduce your issue:

my column:
```php
[
    'name'      => 'category_select2', 
    'type'      => 'relationship',
    'label'     => 'My test column',
    'attribute' => 'name',
    
],
```
my relation:
```php
public function category_select2()
{
    return $this->belongsTo(\Backpack\NewsCRUD\app\Models\Category::class, 'select2');
}
```php

The results in List:
![image](https://user-images.githubusercontent.com/7188159/180981483-6e28e12c-cc69-4fd8-95c2-cd741c5f76b4.png)
The results in Show:
![image](https://user-images.githubusercontent.com/7188159/180981605-4b379566-13af-4829-8c9b-381330ba3350.png)

What am I doing different than you ?

Sorry I was not able to reproduce it yet :| we will get there eventually. 

Cheers

**Comment by pxpm** [comment] 2022-07-26 15:54
Hey @MDW-Chris nice catch! 👍 Glad you figured it out. 
Please be advised that it will change again in future as per this PR: https://github.com/Laravel-Backpack/CRUD/pull/4542 
Maybe subscribe to it so you get notified when it gets merged 👍 

Going to close this, cheers.

**Closed by pxpm** 2022-07-26 15:54 UTC
Labels: needs-more-info
