### ISSUE TITLE
Join a relationship not working with enableAjaxTable

### ISSUE THREAD

**Issue by giorgoskorakas** [Laravel-Backpack/CRUD#273] opened 2016-12-01 17:05 UTC
Hi,

in my controller i have added 3 joins to get some values like below:

1. From current model i join model1 with id. 
2. Then i join model2 with model1's id that is key to model2.
3. Then i join model2 again with another model1's column that is key to model2 too.

I did it by adding $this->crud->addClause() to my controller. I use eAjax Table because of the amount of data.

I get ajax error popup (DataTables warning: table id=crudTable - Ajax error) when i add a new column to crud with the value i got from query 2 and 3. 

The joins are working fine.

Any suggestion?

**Comment by tabacitu** [comment] 2016-12-02 09:11
Hi @giorgoskorakas ,

You should check out the AJAX request in your browser's developer tools (Network tab, maybe?). The output of the AJAX request should be a specific db error you need to fix. My first thought - it could be a double-naming issue and you should rename a column to smth else, for Eloquent to make sense of it all. That's the most common JOIN error, anyway.

Cheers!

**Comment by giorgoskorakas** [comment] 2016-12-02 09:37
Hi @tabacitu ,

thank you for the fast reply. It is such a great package. I love it! 

The error i get is a search 500 internal server error. I tried to rename the columns with no luck.

**Comment by AurelDragut** [comment] 2016-12-02 10:07
@giorgoskorakas if you are on shared hosting, you might need to check the PHP version that is set in the cpanel, if it's a native version it might be the reason for the 500.

**Comment by giorgoskorakas** [comment] 2016-12-02 10:10
@AurelDragut i am in local environment with mamp and PHP 7.0.8

**Comment by tabacitu** [comment] 2016-12-02 10:39
@giorgoskorakas , 

1) What Laravel & Backpack/CRUD versions are you using?
2) Are you doing the CRUD setup in __construct() or setup()?
3) Have you overwritten the search() method in your EntityCrudController?
4) Does a ```composer update``` fix it?

Cheers!

**Comment by giorgoskorakas** [comment] 2016-12-02 10:48
@tabacitu ,

1. I use Laravel 5.3 and Backpack/CRUD 3.1.42
2. I am doing the CRUD setup in __construct(). I tried to put all my clauses in setup() and enable Ajax there but couldn't get it.
3. No. I thought it is not necessary.
4. I did `composer update backpack/crud` to update crud and be able to use new features.

Thank you

**Comment by tabacitu** [comment] 2016-12-02 10:57
Hmm.. Can you paste your __construct() code and the error you're getting?

**Comment by giorgoskorakas** [comment] 2016-12-02 11:18
```
public function __construct() {
        parent::__construct();

        // Enable access only for given permission
        $this->middleware('routeNeedsPermission:backend-access');

        $this->crud->setModel("App\Models\Odd");
        $this->crud->setRoute("admin/odd");
        $this->crud->setEntityNameStrings(trans_choice('guru-tables.odds.admin', 1), trans_choice('guru-tables.odds.admin', 2));


        // ------ CRUD FIELDS
        $this->crud->addFields([
            // I add some fields here (not the team name)
        ], 'update/create/both');

        // ------ CRUD COLUMNS
        $this->crud->addColumns([
            [   // Team Name
                'name' => 'team_home_name',
                'label' => 'team name',
            ],
        ]);

        // ------ CRUD ACCESS
        $this->crud->denyAccess(['create', 'reorder', 'delete']);

        // ------ AJAX TABLE VIEW
        $this->crud->enableAjaxTable();

// here i get the error
        $this->crud->addClause('join', 'events', 'odds.event_id', 'events.id');
        $this->crud->addClause('select', ['odds.*', 'events.team_home_id AS team_home_id', 'events.team_away_id AS team_away_id']);
        
// even when i comment out the following and i set column to show team_home_id i get the same error

        $this->crud->addClause('join', 'teams', 'team_home_id', 'teams.id');
        $this->crud->addClause('select', ['events.*', 'teams.display_name AS team_home_name']);
        $this->crud->addClause('join', 'teams', 'team_away_id', 'teams.id');
        $this->crud->addClause('select', ['events.*', 'teams.display_name AS team_away_name']);

    }
```

**Comment by tabacitu** [comment] 2016-12-02 11:31
Hmm... pretty difficult to debug like this.

I think another way to achieve this would be to let Eloquent do the joins for you, if you [setup the relationships](https://laravel.com/docs/5.3/eloquent-relationships) on the Odd model. I just pushed an update where it automatically eager loads your relationships, so it wouldn't add any queries to the table view. An added benefit would be that you would also be able to use those relationships in your frontend, outside the CRUD.

Could you try that?

**Comment by giorgoskorakas** [comment] 2016-12-02 11:35
Yes sure. Is it possible to use the team name from model no2 because i join model2 with model1's id that is key to get the team name?

 The CRUD i'm working on has no direct relation to teams model to be able to get the team name. I have to get the event first and then from event to get the team.

**Comment by tabacitu** [comment] 2017-01-08 11:17
@giorgoskorakas did you figure this out in the end?

P.S. Since this is a support question, not a bug, I'll go ahead and close this issue so we don't clog the section. Feel free to comment if you have follow-ups.

**Closed by tabacitu** 2017-01-08 11:17 UTC
Labels: question
