### ISSUE TITLE
Pass parameters to crud controller

### ISSUE THREAD

**Issue by Moaz-e** [Laravel-Backpack/CRUD#2838] opened 2020-05-18 09:33 UTC
# Bug report

Hi ...
i have a problem when pass parameters to crud controller and i get the parameter in setup function :

     $passed_id = \Route::current()->parameter('id');
     error_log("test");
     error_log($passed_id);

the output show :

    test
    3
    .
    .
    .
    test
    "empty line"
    .
    .
    .
    test
    "empty line"
    .
    .
    .

i don't andurstand why print "test" three times and i can't access the passed_id ?!

Does anyone know the problem? and how can i reach "id" at any time? ..
Thanks for help..

my backpack version is 4.0.x

**Comment by tabacitu** [comment] 2020-05-19 04:19
Hi @Moaz-e ,

I recommend you take a look at the DeleteOperation for inspiration. There's not much different about parameters in Backpack - it's the same as in all Laravel apps. The only difference is that code that registered the route is inside the controller, not in a separate routes file.

The Delete operation for example uses the $id parameter by including it in the controller method:

```php
    public function destroy($id)
    {
        $this->crud->hasAccessOrFail('delete');

        // get entry ID from Request (makes sure its the last ID for nested resources)
        $id = $this->crud->getCurrentEntryId() ?? $id;

        return $this->crud->delete($id);
    }
```

You could do that if you want. Or with any other way that Laravel can do this, Backpack won't restrict you. I'm going to close this as it's not a bug, and it's not Backpack-related.

Cheers!

**Closed** 2020-05-19 04:19 UTC
Labels: Ask-It-On-Stack-Overflow
